apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  SMTP_PASSWORD: {{ .Values.email.smtpPassword | b64enc | quote }}