apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "common.names.fullname" . }}
      {{- if .Values.global.multiCluster.isMainCluster }}
      initContainers:
      - name: "postgres-listener"
        image: {{ include "cluster-manager.init.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ include "common.pgpool.defaultName" . }} 5432 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.init.resources | trim | indent 10 }}
      {{- end }}
      containers:
      - name: cluster-manager
        image: {{ include "clusterManager.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        {{- if .Values.global.multiCluster.isMainCluster }}
        - --cluster-name=default
        - --master-addr={{ include "common.console.defaultName" . }}:8889
        - --console-postgres={{ include "common.pgpool.DSN" . }}
        - --redis-endpoint={{ include "common.redis.sentinel.address" . }}
        {{- else if .Values.global.multiCluster.isMemberCluster }}
        - --master-addr={{ .Values.global.multiCluster.configs.consoleExternalAdd }}
        - --cluster-name={{ .Values.global.multiCluster.configs.clusterName }}
        - --api-server-address={{ .Values.global.multiCluster.configs.apiServerAddr }}
        {{- end }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.global.multiCluster.isMainCluster }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.redis-ha.defaultName" . }}
              key: auth
        {{- end }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        volumeMounts:
        - name: cluster-admin-secret
          readOnly: true
          mountPath: "/etc/secrets/cluster-admin"
      {{- if .Values.global.multiCluster.isMemberCluster }}
      - name: redis
        args:
        - /etc/redis.conf
        command:
        - redis-server
        image: {{ include "cluster-manager.redis.image" . }}
        imagePullPolicy: IfNotPresent
        name: redis
        resources:
{{ toYaml .Values.redis.resources | trim | indent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redis.conf
          name: redis-conf
          subPath: redis.conf
        - mountPath: /data
          name: redis-data
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      restartPolicy: Always
      volumes:
      - name: cluster-admin-secret
        secret:
          secretName: {{ include "common.names.fullname" . }}
      {{- if .Values.global.multiCluster.isMemberCluster }}
      - name: redis-conf
        configMap:
          defaultMode: 420
          items:
          - key: redis.conf
            path: redis.conf
          name: {{ include "common.names.fullname" . }}-redis
      - name: redis-data
        emptyDir: {}
      {{- end }}

