apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster-manager.fullname" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "cluster-manager.fullname" . }}
type: kubernetes.io/service-account-token