apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "common.names.fullname" . }}
type: kubernetes.io/service-account-token