global:
  image: 
    registry: ""
    repository: ""
  storageClass: ""


image:
  registry: localhost:32000
  repository: tensorsecurity
  name: tensorsec-console
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret


scap:
  tag: latest
  clusterAddr: "http://tensorsec-cluster-manager:9443"

persistence:
  enabled: true
  storageClass: "nfs-client-provisioner"
  claimName: audit-pvc
  accessModes:
    - ReadWriteOnce
  size: 50Gi
  tensorsecCleaner:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: tensorsec-cleaner
      tag: latest
      pullPolicy: Always
      pullSecret: harbor-admin-secret
    coldCronjob:
      cronString: "0 4 * * *"
      nameOverride: "cron-cold-cleaner"
      fullnameOverride: "tensorsec-cron-cold-cleaner"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi
    hotLogicCronjob:
      cronString: "0 2 * * *"
      nameOverride: "cron-hot-logic-cleaner"
      fullnameOverride: "tensorsec-cron-hot-logic-cleaner"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi
    hotOfflineCronjob:
      cronString: "0 3 * * *"
      nameOverride: "cron-hot-offline-cleaner"
      fullnameOverride: "tensorsec-cron-hot-offline-cleaner"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi

jobs:
  tensorsecCleaner:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: tensorsec-cleaner
      tag: latest
      pullPolicy: Always
      pullSecret: harbor-admin-secret
  tensorsecHunter:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: tensorsec-kube-hunter-report
      tag: latest
  tensorsecHunterOrigin:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: kube-hunter
      tag: 0.6.2
  tensorsecApiScan:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: tensorsec-apiscan-job
      tag: latest
  tensorsecPlatform:
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: tensorsec-platform-report
      tag: latest

## Deployment pod host aliases
####  hostAliases:
####  - ip: "192.168.x.x"
####    hostnames:
####    - "xxx.xxx.com"
hostAliases: []

## config user email check
emailCheck:
  smtpEnabled: false
  smtpHost: smtp.feishu.cn
  smtpPort: 465
  smtpUsername: console-robot@tensorsecurity.cn
  smtpPassword: password
  


nameOverride: "console"
fullnameOverride: "tensorsec-console"
debugServiceName: "tensorsec-console-debug"

# Custom service account override that the pod will use
serviceAccount: ""

restartPolicy: Always

service:
  type: ClusterIP
  port: 8889
  containerPort: 8080
  k8sAuditWebHookPort: 8081
  k8sAuditWebHookContainerPort: 8081

debugService:
  type:  NodePort
  port: 18889
  containerPort: 18080

replicaCount: 1

resources:
  requests:
    cpu: "200m"
    memory: "500Mi"
  limits:
    cpu: "200m"
    memory: "500Mi"

initResources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

init:
  image:
    registry:  localhost:32000
    repository: tensorsecurity
    name: alpine
    tag: latest
  

apiInstallLabel: "console.tensorsec/install"

consoleInternalAdd: "http://tensorsec-console:8889"
consoleExternalAdd: "http://tensorsec-console:8889"

eventcenter:
  eventGrpcUrl: tensorsec-eventcenter:9090
  eventGrpcCertServerName: tensorsec-eventcenter

elasticsearch:
  elasticSecretName: elastic-secret
  extraEnvs:
    - name: ELASTIC_PASSWORD
      value: Elastic12345
    - name: ELASTIC_USERNAME
      value: elasticsearch
elastic:
  host: tensorsec-elasticsearch-master
  port: 9200
  index: filebeat-*
  elasticDataPath: /usr/share/elasticsearch/data
postgresql:
  postgresqlDataDir: /bitnami/postgresql/data
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: postgres

imagePullSecret:
  imageRegistryURL: https://192.168.1.152:30003
  imageRegistryUsername: tensorsec
  imageRegistryPassword: Tensorsec123!
  
redis:
  redisSecretName: tensorsec-redis-ha

version:
  softName: Navigator
  softVersion: v1.11.0

k8sAudit:
  prefix: "audit_"

openapi:
  guideURL: "https://tensorsecurity.feishu.cn/docs/doccn14Oeay2PwoXy0gq3RvRj2f"
