global:
  image: 
    registry: ""
    repository: ""
  storageClass: ""


image:
  registry: localhost:32000
  repository: library
  name: console
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret


scap:
  tag: latest

persistence:
  enabled: true
  storageClass: "nfs-client-provisioner"
  claimName: audit-pvc
  accessModes:
    - ReadWriteOnce
  size: 50Gi
  Cleaner:
    image:
      registry: localhost:32000
      repository: library
      name: cleaner
      tag: latest
      pullPolicy: Always
      pullSecret: harbor-admin-secret
    coldCronjob:
      cronString: "0 4 * * *"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi
    hotLogicCronjob:
      cronString: "0 2 * * *"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi
    hotOfflineCronjob:
      cronString: "0 3 * * *"
      resources:
        limits:
          cpu: "0.1"
          memory: 200Mi
        requests:
          cpu: "0.1"
          memory: 200Mi

jobs:
  Cleaner:
    image:
      registry: localhost:32000
      repository: library
      name: cleaner
      tag: latest
      pullPolicy: Always
      pullSecret: harbor-admin-secret
  Hunter:
    image:
      registry: localhost:32000
      repository: library
      name: kube-scanner-report
      tag: latest
  HunterOrigin:
    image:
      registry: localhost:32000
      repository: library
      name: kube-scanner
      tag: 0.6.2
  ApiScan:
    image:
      registry: localhost:32000
      repository: library
      name: apiscan-job
      tag: latest
  Platform:
    image:
      registry: localhost:32000
      repository: library
      name: platform-report
      tag: latest

## Deployment pod host aliases
####  hostAliases:
####  - ip: "192.168.x.x"
####    hostnames:
####    - "xxx.xxx.com"
hostAliases: []

## config user email check
emailCheck:
  smtpEnabled: false
  smtpHost: smtp.feishu.cn
  smtpPort: 465
  smtpUsername: console-robot@example.com
  smtpPassword: password
  


nameOverride: "console"
fullnameOverride: "console"

# Custom service account override that the pod will use
serviceAccount: ""

restartPolicy: Always

service:
  type: ClusterIP
  port: 8889
  containerPort: 8080
  k8sAuditWebHookPort: 8081
  k8sAuditWebHookContainerPort: 8081

debugService:
  type:  NodePort
  port: 18889
  containerPort: 18080

replicaCount: 1

resources:
  requests:
    cpu: "200m"
    memory: "500Mi"
  limits:
    cpu: "200m"
    memory: "500Mi"

initResources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "50m"
    memory: "128Mi"

init:
  image:
    registry:  localhost:32000
    repository: library
    name: alpine
    tag: latest
  

apiInstallLabel: "console/install"

consoleExternalAdd: "http://console.example.com"

elasticsearch:
  extraEnvs:
    - name: ELASTIC_PASSWORD
      value: Elastic12345
    - name: ELASTIC_USERNAME
      value: elasticsearch
  port: 9200
  index: filebeat-*
  elasticDataPath: /usr/share/elasticsearch/data

postgresql:
  postgresqlDataDir: /bitnami/postgresql/data
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: postgres

imagePullSecret:
  imageRegistryURL: https://192.168.1.152:30003
  imageRegistryUsername: 
  imageRegistryPassword: 123!

version:
  softName: ManagerPlatform
  softVersion: v1.11.0

k8sAudit:
  prefix: "audit_"

openapi:
  guideURL: "https://shimo.im/docs/KyKK86Y6jhwDRCc8"