# imagePullSecrets:
#   - name: vegeta-gitlab

nameOverride: "tensorsec-console"
#fullnameOverride: "tensorsec-console"

restartPolicy: Always

service:
  type: ClusterIP
  port: 8889
  containerPort: 8080

replicaCount: 1

apiInstallLabel: "console.tensorsec/install"

image:
  name: tensorsec-console
  # repository: localhost:32000
  tag: latest
  pullPolicy: Always
