global:
  image: 
    registry: ""
    repository: ""

image:
  registry: localhost:32000
  repository: library
  name: cluster-manager
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret
  
init: 
  image:
    registry: localhost:32000
    repository: library
    name: alpine
    tag: latest
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

redis:
  image:
    registry: localhost:32000
    repository: library
    name: redis
    tag: "5.0"
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  password: Redis12345
  service:
    port: 6379
    targetPort: 6379

scanner:
  port: 8888

postgres:
  username: postgres
  port: "5432"
  dbName: postgres
  sslMode: disable

nameOverride: "cluster-manager"
fullnameOverride: "cluster-manager"

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

service:
  port: 9443
  targetPort: 9443

