global:
  image: 
    registry: ""
    repository: ""

image:
  registry: localhost:32000
  repository: library
  name: cluster-manager
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret
  
init: 
  image:
    registry: localhost:32000
    repository: library
    name: alpine
    tag: latest
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

nameOverride: "cluster-manager"
fullnameOverride: "cluster-manager"

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

service:
  port: 9443
  targetPort: 9443

