global:
  image: 
    registry: ""
    repository: ""


##  safenode image name
image:
  registry: localhost:32000
  repository: library
  name: safe-node-image
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

bufRegistry: 
  bufRegistryUser: admin
  bufRegistryPass: Registry@Passw0rd

pushConfigs:
  pushInterval: 10
  batchInterval: 60
  batchSize: 60

tolerations:
- effect: NoSchedule
  key: node-role.kubernetes.io/master
resources:
  limits:
    cpu: "100m"
    memory: "200Mi"
  requests:
    cpu: "100m"
    memory: "200Mi"

nameOverride: "safenode-image"
fullnameOverride: "safenode-image"

restartPolicy: Always
