apiVersion: v1
kind: Service
metadata:
  name: {{ include "seccompGenerator.fullname" . }}
  labels:
    helm.sh/chart: {{ include "seccompGenerator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ include "seccompGenerator.name" . }}
  selector:
    app.kubernetes.io/name: {{ include "seccompGenerator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
