apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tensorsec-image-certs
  namespace: tensorsec
spec:
  secretName: tensorsec-webhook-certs
  dnsNames:
    - tensorsec-image-validator.tensorsec.svc
  issuerRef:
    name: tensorsec-selfsigned
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tensorsec-selfsigned
  namespace: tensorsec
spec:
  selfSigned: {}
