# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: harbor.tensorsecurity.com/library/golang:1.21.3
variables:
  GOPROXY: https://goproxy.cn
  GO111MODULE: 'on'
  GOPRIVATE: gitlab.com,scm.tensorsecurity.cn
  CGO_LDFLAGS: "-no-pie"
  HARBORPASSWD: Hrbr12@Tensor.*#)
  VERSION: ci
  REPOPREFIX: harbor.tensorsecurity.com/tensorsecurity
  IMAGE_TAG: ci
  FETCHTAG: latest
  LICENSE_SECRET: sit
  MIRROR_SOURCE: mirrors.tuna.tsinghua.edu.cn
workflow:
  rules:
  - if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^master/"
    when: always
stages:
- build
all:
  stage: build
  resource_group: all
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  - mkdir ~/.kube/
  - cp ~/.docker/xray ./
  - cp ~/.docker/irene ./configs/node-image/
  - mkdir avira/
  - cp ~/.docker/savapi-sdk-linux64.tgz avira/
  - mkdir clamav/
  - cp ~/.docker/clamav.tgz clamav/
  - mkdir hm/
  - cp ~/.docker/hm-linux.tgz hm/
  - mkdir hmj/
  - cp ~/.docker/hmj hmj/
  script:
  - make all
  - make rm-local-images || true
  rules:
  - changes:
    - pkg/**/*
    - Makefile
    - go.mod
    - configs/**/*
cluster-manager:
  stage: build
  resource_group: cluster-manager
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  script:
  - make cluster-manager
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/cluster-manager:ci || true
  rules:
  - changes:
    - cmd/cluster-manager/**/*
    - build/cluster-manager/**/*
    - configs/cluster-manager/**/*
console:
  stage: build
  resource_group: console
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  script:
  - make console
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/console:ci || true
  rules:
  - changes:
    - cmd/console/**/*
    - build/console/**/*
    - configs/console/**/*
node-image:
  stage: build
  resource_group: node-image
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  - cp -a ~/.docker/irene ./configs/node-image/
  - mkdir avira/
  - cp ~/.docker/savapi-sdk-linux64.tgz avira/
  - mkdir clamav/
  - cp ~/.docker/clamav.tgz clamav/
  - mkdir hm/
  - cp ~/.docker/hm-linux.tgz hm/
  script:
  - make node-image
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/node-image:ci || true
  rules:
  - changes:
    - cmd/node-image/**/*
    - build/node-image/**/*
    - configs/node-image/**/*
holmes:
  stage: build
  resource_group: holmes
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  - mkdir avira/
  - cp ~/.docker/savapi-sdk-linux64.tgz avira/
  - mkdir hmj/
  - cp ~/.docker/hmj hmj/
  - mkdir hm/
  - cp ~/.docker/hm-linux.tgz hm/
  script:
  - make daemon holmes
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/daemon:ci || true
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/holmes:ci || true
  rules:
  - changes:
    - cmd/daemon/**/*
    - build/daemon/**/*
    - configs/daemon/**/*
    - cmd/holmes/**/*
    - build/holmes/**/*
    - configs/holmes/**/*
scanner:
  stage: build
  resource_group: scanner
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  - mkdir avira/
  - cp ~/.docker/savapi-sdk-linux64.tgz avira/
  - mkdir clamav/
  - cp ~/.docker/clamav.tgz clamav/
  - mkdir hm/
  - cp ~/.docker/hm-linux.tgz hm/
  script:
  - make scanner
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/scanner:ci || true
  rules:
  - changes:
    - cmd/scanner/**/*
    - build/scanner/**/*
    - configs/scanner/**/*
scan-report:
  stage: build
  resource_group: scan-report
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  script:
  - make scan_report
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/scan-report:ci || true
  rules:
  - changes:
    - cmd/scanner/bin/scan-report/**/*
    - build/scan_report/**/*
webhook:
  stage: build
  resource_group: webhook
  tags:
  - k8s
  before_script:
  - git merge origin/master
  - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
  - |
    for file in `ls build/*/Dockerfile`; do
        sed -i '/.*&& apt-get full-upgrade -y.*/ d' ${file}
        sed -i '/.*&& apk upgrade.*/d' ${file}
    done
  script:
  - make webhook
  - docker rmi harbor.tensorsecurity.com/tensorsecurity/webhook:ci || true
  rules:
  - changes:
    - cmd/webhook/**/*
    - build/webhook/**/*
    - configs/webhook/**/*
