image: harbor.tensorsecurity.com/library/reviewdog:v5

variables:
  GOPROXY: "https://goproxy.cn"
  GO111MODULE: "on"
  GOPRIVATE: "gitlab.com,scm.tensorsecurity.cn"
  CGO_LDFLAGS: "-no-pie"
  HARBORPASSWD: "Hrbr12@Tensor.*#)"

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^master/'
      when: always

stages:
  - reviewdog
  - build
  - test

## reviewdog
reviewdog:
  stage: reviewdog
  tags:
    - k8s
  before_script:
    - export REVIEWDOG_GITLAB_API_TOKEN=Ux_Ex4z5-payZMS_evgC
    - export GITLAB_API="http://gitlab.gitlab-ce.svc.cluster.local/api/v4"
    - export CI_REPO_OWNER=tensorsecurity-rd
    - export CI_REPO_NAME=tensornavigator
    - export CI_COMMIT=$(git rev-parse HEAD)
    - export REVIEWDOG_INSECURE_SKIP_VERIFY=true
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
  script:
    - reviewdog -reporter=gitlab-mr-discussion -debug -tee
  rules:
    - changes:
        - cmd/**/*

### build & deploy
all:
  stage: build
  resource_group: all
  tags:
    - k8s
  before_script:
    ## Configuration of Git
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - git clone ssh://git@10.99.201.85/tensorsecurity-rd/tensor-compliance-check.git
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    ## Configuration of Make
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - 'find ./ -name "Dockerfile"|xargs sed -i "s#registry.t-appagile.com#harbor.tensorsecurity.com#g"'
    ## Copy tools
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
    - cp ~/.docker/helm /bin/
  script:
    - USEMIRROR=true FETCHTAG=latest make all
    - make pushimages
    - kubectl get pod --no-headers -n tensorsec|grep -v "db\|mongodb\|redis\|elasticsearch\|stan\|frontend\|eventcenter\|microseg"|awk '{print $1}'|xargs -i kubectl delete pod {} -n tensorsec --force --grace-period=0

  rules:
    - changes:
        - pkg/**/*
        - Makefile
        - go.mod
        - configs/**/*

helm-upgrade:
  stage: build
  resource_group: helm-upgrade
  tags:
    - k8s
  before_script:
    ## Configuration of Git
    - git merge origin/master
    ## Configuration of Helm
    - 'sed -i "s#harbor.local.tensorsecurity.cn#harbor.tensorsecurity.com#g" deployments/helm/example-values.yaml'
    - 'sed -i "s#1.0.0#ci#g" deployments/helm/example-values.yaml'
    - 'sed -i "s#admin#devops#g" deployments/helm/example-values.yaml'
    - 'sed -i "s|Harbor12345|$HARBORPASSWD|g" deployments/helm/example-values.yaml'
    - 'sed -i "s#smtpEnabled: false#smtpEnabled: true#g" deployments/helm/example-values.yaml'
    - 'sed -i "s#smtpPassword: password#smtpPassword: r8UJgg7ejpSoDOAF#g" deployments/helm/example-values.yaml'
    - 'sed -i "s#console.localhost.com#172.21.3.226:31517#g" deployments/helm/example-values.yaml'
    - 'sed -i "s#https://console-external.localhost.com#https://console-ci.tensorsecurity.cn#g" deployments/helm/example-values.yaml'
    ## certgen image for k8s v1.22
    - 'sed -i "s#tensorsec-certgen#kube-webhook-certgen#g" deployments/helm/values.yaml'
    - 'sed -i "s#v1.5.1#v1.1.1#g" deployments/helm/values.yaml'
    ## Copy tools
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/helm /bin/
  script:
    - cd deployments/helm
    - helm dep up
    - helm upgrade --install tensorsec -f example-values.yaml ./ --namespace tensorsec
  rules:
    - changes:
        - deployments/helm/**/*

cluster-manager:
  stage: build
  retry: 2
  resource_group: cluster-manager
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make cluster-manager
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-cluster-manager:ci
  rules:
    - changes:
        - cmd/cluster-manager/**/*
        - build/cluster-manager/**/*
        - configs/cluster-manager/**/*

console:
  stage: build
  resource_group: console
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - git clone ssh://git@10.99.201.85/tensorsecurity-rd/tensor-compliance-check.git
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make console
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-console:ci
    - kubectl scale --replicas=0 deploy tensorsec-console -n tensorsec
    - kubectl scale --replicas=1 deploy tensorsec-console -n tensorsec
  rules:
    - changes:
        - cmd/cluster-manager/**/*
        - build/cluster-manager/**/*
        - configs/cluster-manager/**/*

event-processor:
  stage: build
  resource_group: event-processor
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make event-processor
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-event-processor:ci
    - kubectl scale --replicas=0 deploy tensorsec-sec-prof-man-processor -n tensorsec
    - kubectl scale --replicas=1 deploy tensorsec-sec-prof-man-processor -n tensorsec
  rules:
    - changes:
        - cmd/event-processor/**/*
        - build/event-processor/**/*
        - configs/event-processor/**/*

holmes:
  stage: build
  resource_group: holmes
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true FETCHTAG=latest make daemon holmes
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-daemon:ci
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-holmes:ci
    - kubectl delete pod -n tensorsec -l app=tensorsec-holmes
  rules:
    - changes:
        - cmd/daemon/**/*
        - build/daemon/**/*
        - configs/daemon/**/*
        - cmd/holmes/**/*
        - build/holmes/**/*
        - configs/holmes/**/*

prof-man-daemon:
  stage: build
  resource_group: prof-man-daemon
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make go-audit security-profiles-loader
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-go-audit:ci
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-security-profiles-loader:ci
    - kubectl delete pod -n tensorsec -l app=tensorsec-sec-prof-man-daemon
  rules:
    - changes:
        - cmd/go-audit/**/*
        - build/go-audit/**/*
        - configs/go-audit/**/*
        - cmd/security-profiles-loader/**/*
        - build/security-profiles-loader/**/*
        - configs/security-profiles-loader/**/*

safe-node-image:
  stage: build
  resource_group: safe-node-image
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make safe-node-image
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-safe-node-image:ci
    - kubectl delete pod -l app=tensorsec-safenode-image -n tensorsec
  rules:
    - changes:
        - cmd/safe-node-image/**/*
        - build/safe-node-image/**/*
        - configs/safe-node-image/**/*

scanner:
  stage: build
  resource_group: scanner
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - go test -v -cover ./cmd/scanner/...
    - USEMIRROR=true make scanner
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-scanner:ci
    - kubectl scale --replicas=0 deploy tensorsec-scanner -n tensorsec
    - kubectl scale --replicas=1 deploy tensorsec-scanner -n tensorsec
  rules:
    - changes:
        - cmd/scanner/**/*
        - build/scanner/**/*
        - configs/scanner/**/*

security-profiles-manager:
  stage: build
  resource_group: security-profiles-manage
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make security-profiles-manager
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-security-profiles-manager:ci
    - kubectl scale --replicas=0 deploy/tensorsec-sec-prof-man -n tensorsec
    - kubectl scale --replicas=1 deploy/tensorsec-sec-prof-man -n tensorsec
  rules:
    - changes:
        - cmd/security-profiles-manager/**/*
        - build/security-profiles-manager/**/*
        - configs/security-profiles-manager/**/*

webhook:
  stage: build
  resource_group: webhook
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make webhook
    - docker push harbor.tensorsecurity.com/tensorsecurity/tensorsec-webhook:ci
    - kubectl scale --replicas=0 deploy tensorsec-webhook -n tensorsec
    - kubectl scale --replicas=1 deploy tensorsec-webhook -n tensorsec
  rules:
    - changes:
        - cmd/webhook/**/*
        - build/webhook/**/*
        - configs/webhook/**/*

webshell-server:
  stage: build
  resource_group: webshell-server
  retry: 2
  tags:
    - k8s
  before_script:
    - git merge origin/master
    - git config --global --add url."git@gitlab.com:".insteadOf "https://gitlab.com/"
    - git config --global --add url."ssh://git@10.99.201.85/".insteadOf "http://scm.tensorsecurity.cn/"
    - sed -i 's#scm.tensorsecurity.cn:30022#10.99.201.85#g' .gitmodules
    - git submodule init
    - git submodule update
    - git submodule update --init --recursive
    - sed -i 's#RELEASEVERSION?=v0.0.1#RELEASEVERSION?=ci#g' Makefile
    - sed -i "s#latest#ci#g" Makefile
    - sed -i "s#DOCKER_REGISTRY=$(REPOPREFIX)#DOCKER_REGISTRY=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - sed -i "s#REPOPREFIX?=localhost:32000#REPOPREFIX?=harbor.tensorsecurity.com/tensorsecurity#g" Makefile
    - mkdir ~/.kube/
    - cp ~/.docker/config-ci ~/.kube/config
    - cp ~/.docker/kubectl /bin/
    - chmod +755 /bin/kubectl
  script:
    - USEMIRROR=true make webshell-server
    - docker push harbor.tensorsecurity.com/tensorsecurity/webshell-server:ci
    - kubectl scale --replicas=0 deploy tensorsec-scanner-webshell-server -n tensorsec
    - kubectl scale --replicas=2 deploy tensorsec-scanner-webshell-server -n tensorsec
  rules:
    - changes:
        - cmd/webshell-server/**/*
        - build/webshell-server/**/*
        - configs/webshell-server/**/*

## api test
api-test:
  stage: test
  resource_group: api-test
  retry: 2
  tags:
    - k8
  before_script:
    - apt-get update
    - apt-get install python3 python3-pip -y
    - git clone ssh://git@10.99.201.85/tensorsecurity-rd/tensor-api-test.git
    - pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r tensor-api-test/requirements.txt
    - cp ~/.docker/tensor-scanner-cicd /root/tensor-scanner-cicd
  script:
    - python3 tensor-api-test/run_suite.py
  artifacts:
    paths:
      - report/*.html
    when: always
    expire_in: 1 day
  when: delayed
  start_in: 2 minutes
