apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "driftPrevention.serviceAccount" . }}-role
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create