apiVersion: {{ include "tensorsec.common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "image-validator.fullname" . }}
  labels:
{{ include "image-validator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "image-validator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "image-validator.fullname" . }}
    namespace: {{ .Release.Namespace }}