package mozart

var falcoRules1 []string
var mozartRules []string

func init() {
	falcoRules1 = []string{
		"Gaining environment information",
		"Read sensitive file trusted after startup",
		"Search Private Keys or Passwords",
		"Clear Log Activities",
		"Delete Bash History",
		"Create Symlink Over Sensitive Files",
		//"Read sensitive file untrusted",
		"View network information in the container",
		"Read Shell Configuration File",
		"Read ssh information",
		"Contact K8S API Server From Container",
		"Launch Suspicious Network Tool on Host",
		"View process information in the container",
		"View disk information in the container",
		"Scanning web directories in the container",
		"Find files with suid privilege by non-root users",
		"View login information in the container",
		"View history command file in container",
		"Get ApiServer_token through kubectl",
		"Contact K8S DNS Server From Container",
		"DB program spawned process",
		"Run shell untrusted",
		"Terminal shell in container",
		"Running k8s malicious tools in the container",
		//"Connecting to a remote server through redis client in container",
		"Run the tool for scanning ports",
		"Run the tool for brute-force cracking",
		"Docker build vulnerability(CVE-2019-13139)",
		//"Reverse shell - Brute force hacking detected - Scanning ports detected - Reverse shell through socket and dup",
		"System procs network activity",
		"Interpreted procs inbound network activity",
		"Interpreted procs outbound network activity",
		"Unexpected outbound connection destination",
		"Contact EC2 Instance Metadata Service From Container",
		"Contact cloud metadata service from container",
		"Program run with disallowed http proxy env",
		"Unexpected K8s NodePort Connection",
		"Launch Remote File Copy Tools in Container",
		"Unexpected UDP Traffic",
		"Launch Suspicious Network Tool in Container",
		"Detect outbound connections to common miner pool ports",
		"Detect crypto miners using the Stratum protocol",
		"CVE-2020-14386(Packet socket created in container)",
		"Try ssh connection in container",
		"Try ssh connection in host",
		"Access k8s component ports detected",
		"Launch Sensitive Mount Container",
		"Change thread namespace - The k8s client is executed in a container",
		"Launch Disallowed Container",
		//"Contact remote server from container",
		//"Running vim in container - Using vim for linux privilege escalation",
		//"Running telnet in container",
		//"Created remote connection through ruby in container",
		//"Running visudo in container",
		//"Created remote connection through awk in container",
		//"Generated java child process shell after starting the container",
		//"Generated go child process shell after starting the container",
		//"Generated child process shell after starting the container",
		"Schedule Cron Jobs",
		"Run user mgmt binaries",
		"Package management process launched in container",
		"Update package repository",
		"Write below rpm database",
		"Remove Bulk Data from Disk",
		"Modify shell configuration file",
		"Create files below dev",
		"Create hidden files or directories",
		"Write below monitored dir",
		"Write below binary dir",
		"Modify binary dirs",
		"Mkdir binary dirs",
		"Write below etc",
		"Launch Privileged Container",
		"Non sudo setuid",
		"System user interactive",
		"Set Setuid or Setgid bit",
		"Delete or rename shell history",
		"Escape to access by chroot",
		"Escape to access rule by procfs",
		"Escape to access rule by debugfs",
		"Escape to access rule by cgroup",
		"CVE-2021-3156(Linux sudo Privilege_Escalation)",
		"CVE-2019-5736(Modify Container Entrypoint)",
		"CVE-2019-14287(Sudo Potential bypass of Run as user restrictions)",
		"CVE-2022-0185(in Linux Kernel Can Allow Container Escape in Kubernetes Linux)",
		"CVE-2021-4034(Polkit Local Privilege Escalation Vulnerability)",
		"Linux Privilege Escalation using nmap suid binaries",
		//"Linux Privilege Escalation using find suid binaries",
		"Linux Privilege Escalation using bash suid binaries",
		//"Linux Privilege Escalation by modifying sensitive files with suid binaries",
		"Detect release_agent File Container Escapes",
		"Connect to docker.sock in container",
		"Try to read the k8s token and bypass RBAC",
		"Execute commands through the docker api",
		"Docker copy vulnerability leads to container escape(CVE-2019-14271)",
		"Containerd vulnerability leads to container escape(CVE-2020-15257)",
		//"Using visudo to modify sensitive file for linux privilege escalation",
		//"Linux dirty cow vulnerability leads to container escape(CVE-2016-5195)",
		"Unauthorized access to Tomcat-Web in Redis",
		"Upload webshell through the Tomcat-Manager-App",
		//"Execute commands through webshell",
		"Unauthorized access to Redis-Server",
		"Unauthorized access to ElasticSearch",
		"Execute sensitive commands through ElasticSearch（CVE-2015-1427）",
		"Unauthorized access to Tomcat-Web",
		"Reading local files through Tomcat-AJP-Connector（CVE-2020-1938）",
		"Unauthorized access to Jenkins",
		"Execute sensitive commands through Jenkins",
		"Unauthorized access to Jupyter-Notebook",
		"Execute sensitive commands through Jupyter-Notebook",
		"The k8s client is executed in Watson",
		"Unauthorized access to Mysql",
		"The attacker successfully cracked the weak Mysql password",
		"Unauthorized access to SSH",
		"The attacker successfully cracked the weak SSH password",
		"Unauthorized access to vsftpd",
		"The attacker successfully cracked the weak ftp password",
	}

	mozartRules = []string{
		"Connecting to a remote server through redis client in container",
		"Execute commands through webshell",
		"Linux dirty cow vulnerability leads to container escape(CVE-2016-5195)",
		"Using visudo to modify sensitive file for linux privilege escalation",
		"Brute force hacking detected",
		"Scanning ports detected",
		"Linux Privilege Escalation using find suid binaries",
		"Using vim for linux privilege escalation",
		"Reverse shell",
	}

}
