nameOverride: "seccomp-generator"
fullnameOverride: "tensorsec-seccomp-generator"

managedServiceAccount: true

auditdLogging: false

audit:
  image:
    name: tensorsec-go-audit
    # repository: localhost:32000
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret

image:
  name: tensorsec-seccomp-generator
  # repository: localhost:32000
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

service:
  type: ClusterIP
  port: 8881
  containerPort: 6969

webhook:
  image:
    name: tensorsec-seccomp-generator-webhook
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
