apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: immune-test
        image: "{{ template "immune-test.image" . }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/immune-test"]
        env:
        - name: CLUSTER_MANAGER_URL
          value: "http://{{ include "common.cluster-manager.defaultName" . }}:9443"
        - name: EVENT_GRPC_URL
          value: "{{ include "common.eventcenter.defaultName" . }}:9090"
        - name: HTTP_ADDR
          value: ":{{ .Values.service.httpTargetPort}}"
        - name: RDB_USER
          value: {{ .Values.postgres.username }}
        - name: RDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.postgresql.defaultName" . }}
              key: postgresql-password
        - name: RDB_HOST
          value: {{ include "common.pgpool.defaultName" . }}
        - name: RDB_PORT
          value: {{ .Values.postgres.port | quote }}
        - name: RDB_DBNAME
          value: {{ .Values.postgres.dbName }}
        - name: RDB_SSLMODE
          value: {{ .Values.postgres.sslMode }}
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        ports:
        - name: http
          containerPort: {{ .Values.service.httpTargetPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
      dnsPolicy: ClusterFirst
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
