##attck_rule_type=Credential_Access
- rule: Gaining environment information
  hid: ca_01
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "Please confirm whether this behavior is caused by malicious tools. If it is a container, it may be invaded by hackers. You can use offset defense to limit the corresponding binary execution."
    zh:
      key: "处置建议"
      value: "请确认该行为产生是否为恶意工具所致，如果是容器则可能遭到黑客入侵，可使用偏移防御限制对应二进制执行。"
  desc: Gaining environment information
  condition: >
    open_read and container and ((proc.name in (show_information_binaries)) and
    (fd.filename in (sensitive_paths) or fd.name in (sensitive_paths) or fd.directory in (sensitive_paths)) or (proc.name in (show_env_binaries)))  and not tensorsec_namespace and shell_parent_procs
  output: container shell gaining environment info (zh_msg=容器内存在敏感信息收集行为,rule_type=Credential_Access,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,fd_name=%fd.name,container_id=%container.id,container_name=%container.name)
  priority: WARNING
  tags: [ATT&CK]

- rule: Read sensitive file trusted after startup
  hid: ca_02
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "Please confirm whether the reading behavior is as expected. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit mounting sensitive directories and files."
    zh:
      key: "处置建议"
      value: "请确认该读取行为是否符合预期，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
  desc: >
    an attempt to read any sensitive file (e.g. files containing user/password/authentication
    information) by a trusted program after startup. Trusted programs might read these files
    at startup to load initial state, but not afterwards.
  condition: sensitive_files and open_read and server_procs and not proc_is_new and proc.name!="sshd" and not user_known_read_sensitive_files_activities and not tensorsec_namespace
  output: >
    Sensitive file opened for reading by trusted program after startup (zh_msg=敏感文件在启动后被受信任的程序读取,rule_type=Credential_Access,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,original_info=user=%user.name user_loginuid=%user.loginuid
    parent=%proc.pname file=%fd.name parent=%proc.pname gparent=%proc.aname[2] container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: INFO
  tags: [ATT&CK, filesystem, mitre_credential_access]

- rule: Search Private Keys or Passwords
  hid: ca_03
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "This action is usually initiated by a hacker. Please confirm whether the container has been invaded, whether the key inside the container has been leaked, and whether other attacks are associated."
    zh:
      key: "处置建议"
      value: "该行为通常由黑客发起，请确认容器是否遭到入侵，容器内密钥是否泄漏，同时关联其他攻击行为。"
  desc: >
    Detect grep private keys or passwords activity.
  condition: >
    (spawned_process and
     ((grep_commands and private_key_or_password) or
      (proc.name = "find" and (proc.args contains "id_rsa" or proc.args contains "id_dsa")))
    )
  output: >
    Grep private keys or passwords activities found
    (zh_msg=存在查找私钥或密码行为,rule_type=Credential_Access,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,original_info=user=%user.name user_loginuid=%user.loginuid container_id=%container.id container_name=%container.name 
    image=%container.image.repository:%container.image.tag)
  priority: WARNING
  tags: [ATT&CK, process, mitre_credential_access]