apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: scanner-deployment
    spec:
      containers:
      - name: scanner-container
        image: scanner:1.0.0
        command: ["/vegeta-scanner"]
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_ADDR
          valueFrom:
            configMapKeyRef:
              name: scanner-map
              key: POSTGRES_ADDR
        - name: CLAIR_CONF
          valueFrom:
            configMapKeyRef:
              name: scanner-map
              key: CLAIR_CONF
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
      - name: scanner-clair
        image: arminc/clair-local-scan:v2.0.6
        ports:
          - containerPort: 6060
        volumeMounts:
          - name: configmap-volume
            mountPath: /config
      - name: scanner-progres
        image: arminc/clair-db:latest
        ports:
          - containerPort: 5432
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: configmap-volume
          configMap:
            name: clair-config
