global:
  image:
    registry: harbor.local.tensorsecurity.cn
    #persistence enabled config
    #storageClass: 
  verison: &tensorsecVerison 1.6.8
  persistence:
    enabled: &persistenceStorage true
  harbor:
    url: &harborURL https://harbor.local.tensorsecurity.cn
    username: &harborUsername admin
    password: &harborPassword Harbor12345
    type: &harborType harbor-v2.0





console:
  image:
    tag: *tensorsecVerison
  scap:
    tag: *tensorsecVerison
  persistence:
    #enabled: false
    enabled: *persistenceStorage
    tensorsecCleaner:
      image:
        tag: *tensorsecVerison
  harbor:
    harborURL: *harborURL
    harborUsername: *harborUsername
    harborPassword: *harborPassword
  email:
    enabled: false

scanner:
  image:
    tag: *tensorsecVerison
  harbor:
    harborURL: *harborURL
    harborUsername: *harborUsername
    harborPassword: *harborPassword
#  hostAliases:
#  - ip: "192.168.3.2"
#    hostnames:
#    - "harbor.local.tensorsecurity.cn"
  # scanner registry config
  # 
  config:
    registry:
      scanner:
      # -
      #   registry:
      #      type: harbor-v2.0
      #      options:
      #        url: https://my.harbor.com
      #        username: myusername
      #        password: mypassword
      #        skiptlsverify: true
      #        paginationkey:
      # -
      #   registry:
      #      type: registry-v2
      #      options:
      #        url: https://my.registry.com
      #        username: myusername
      #        password: mypassword
      #        skiptlsverify: true
      #        paginationkey:
        -
          registry:
            type: *harborType
            options:
              url: *harborURL
              username: *harborUsername
              password: *harborPassword
              skiptlsverify: true
              paginationkey:

drift-prevention:
  image:
    tag: *tensorsecVerison

holmes:
  image:
    tag: *tensorsecVerison
  tensorsecDaemon:
    image:
      tag: *tensorsecVerison

image-validator:
  image:
    #tag: 1.6.8
    tag: *tensorsecVerison
  args:
    # Specify which namespace will not be validated by image ValidatingWebhook.
    # E.g: IgnoredNameSpaces: tensorsec,tensorsec-test-cn,yournamespace
      IgnoredNameSpaces: tensorsec


redis:
  master:
    persistence:
      enabled: *persistenceStorage
  slave:
    persistence:
      enabled: *persistenceStorage
postgresql:
  persistence:
    enabled: *persistenceStorage
mongodb:
  persistence:
    enabled: *persistenceStorage
elasticsearch:
  persistence:
    enabled: *persistenceStorage

