global:
  image:
    registry: harbor.local.tensorsecurity.cn
    #persistence enabled config
    #storageClass: 
  verison: &tensorsecVerison 1.6.8
  persistence:
    enabled: &persistenceStorage true
  harbor:
    url: &harborURL https://harbor.local.tensorsecurity.cn
    username: &harborUsername admin
    password: &harborPassword Harbor12345
    type: &harborType harbor-v2.0
  multiCluster:
    ## Both 'isMasterCluster' and 'isMemberCluster' all need be modified 
    ## and the values of them must be opposite
    isMasterCluster: &isMasterCluster true
    isMemberCluster: &isMemberCluster false
    configs:
      ## console address, use short servicename for MainCluster and exposed address for MemberCluster
      masterAddr: &masterAddr http://tensorsec-console:8889
      ## Unique cluster name, use "default" for MainCluster and other name for MemberCluster
      clusterName: &clusterName default
      ## ApiServer address 
      apiServerAddr: &apiServerAddr 172.21.0.3:6443
      
      




clair:
  enabled: *isMasterCluster
  image:
    tag: *tensorsecVerison

console:
  enabled: *isMasterCluster
  image:
    tag: *tensorsecVerison
  scap:
    tag: *tensorsecVerison
  persistence:
    #enabled: false
    enabled: *persistenceStorage
    tensorsecCleaner:
      image:
        tag: *tensorsecVerison
  harbor:
    harborURL: *harborURL
    harborUsername: *harborUsername
    harborPassword: *harborPassword
  emailCheck:
    smtpEnabled: false
    smtpHost: smtp.feishu.cn
    smtpPort: 465
    smtpUsername: console-robot@tensorsecurity.cn
    smtpPassword: password
  version:
    softName: tensor
    softVersion: v1.9

scanner:
  enabled: *isMasterCluster
  image:
    tag: *tensorsecVerison
  harbor:
    harborURL: *harborURL
    harborUsername: *harborUsername
    harborPassword: *harborPassword
  dockerregistry:
    persistence:
      enabled: *persistenceStorage
      size: 10Gi
    secrets:
      # If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
      # e.g. "htpasswd -nbBC10 $username $password"
      # Default: tensorsec:TensorSec@Passw0rd
      htpasswd: "tensorsec:$2y$10$zYHR.AGhdeKnjpxIKU3.3.XH9MeEUdmSJZil9MUWlqB8b2Q3th7PK"
    service:
      type: ClusterIP
      # clusterIP:
      port: 5000
      # nodePort:
  webshell:
    replicas: 2
#  hostAliases:
#  - ip: "192.168.3.2"
#    hostnames:
#    - "harbor.local.tensorsecurity.cn"
  # scanner registry config
  # 
  config:
    registry:
      scanner:
      # -
      #   registry:
      #      type: harbor-v2.0
      #      options:
      #        url: https://my.harbor.com
      #        username: myusername
      #        password: mypassword
      #        skiptlsverify: true
      #        paginationkey:
      #        usetype: 1
      # -
      #   registry:
      #      type: registry-v2
      #      options:
      #        url: https://my.registry.com
      #        username: myusername
      #        password: mypassword
      #        skiptlsverify: true
      #        paginationkey:
      #        usetype: 1
      # This part used "usetype: 2" is the default configs for internel docker-registry
        -
          registry:
            type: registry-v2
            options:
              # Service FQDN of docker-registry service.
              url: http://tensorsec-scanner-dockerregistry:5000
              # Username & password must be consistent with ".Values.scanner.dockerregistry.secrets.htpasswd".
              username: tensorsec
              password: TensorSec@Passw0rd
              skiptlsverify: true
              paginationkey:
              # Value "1" is for internel docker-registry, and "2" is for customer's external harbor or registry.
              usetype: 2
        -
          registry:
            type: *harborType
            options:
              url: *harborURL
              username: *harborUsername
              password: *harborPassword
              skiptlsverify: true
              paginationkey:
              usetype: 1

holmes:
  enabled: true
  image:
    tag: *tensorsecVerison
  tensorsecDaemon:
    image:
      tag: *tensorsecVerison
    multicluster:
      consoleaddr: *masterAddr   

image-validator:
  enabled: false
  image:
    #tag: 1.6.8
    tag: *tensorsecVerison

webhook:
  enabled: true
  image:
    tag: *tensorsecVerison
  args:
    consoleUrl: *masterAddr
    

cluster-manager:
  enabled: true
  image:
    tag: *tensorsecVerison
  args:
    masterAddr: *masterAddr
    clusterName: *clusterName
    apiServerAddr: *apiServerAddr

eventcenterAuth:
  enabled: *isMasterCluster

security-profiles-manager:
  enabled: *isMasterCluster
  image:
    tag: *tensorsecVerison
  webhook:
    image:
      tag: *tensorsecVerison
  loader:
    image:
      tag: *tensorsecVerison
  audit:
    image:
      tag: *tensorsecVerison
  eventProcessor:
    image:
      tag: *tensorsecVerison
stan:
  enabled: *isMasterCluster
  store:
    volume:
      enabled: *persistenceStorage
holmessidekick:
  enabled: *isMasterCluster

redis-ha:
  enabled: *isMasterCluster
  persistentVolume:
    enabled: *persistenceStorage
postgresql-ha:
  enabled: *isMasterCluster
  persistence:
    enabled: *persistenceStorage
mongodb:
  enabled: *isMasterCluster
  persistence:
    enabled: *persistenceStorage
elasticsearch:
  enabled: *isMasterCluster
  persistence:
    enabled: *persistenceStorage
kibana:
  enabled: *isMasterCluster

