dependencies:
  - name: scanner
    version: 0.1.0
    repository: "file://./subcharts/scanner"
    condition: scanner.enabled

  - name: console
    version: 0.1.0
    repository: "file://./subcharts/console"
    condition: console.enabled

  - name: clair
    version: 0.1.2
    repository: "file://./subcharts/clair"
    condition: clair.enabled

  - name: postgresql
    version: "6.3.9"
    condition: postgresql.enabled
    repository: "alias:stable"

  - name: mongodb
    version: 7.2.10
    repository: "@stable"
    condition: mongodb.enabled
