global:
  # Not sure if it's good practice to pas our docker repo address to our subcharts like this.
  ourDockerRepo: 192.168.1.203:5000

clair:
  enabled: true
  config:
    postgresURI: "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"
  
scanner:
  enabled: true
  clair:
    postgresURI: "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"

console:
  enabled: true

redis:
  enabled: true
  usePassword: false
  cluster:
    slaveCount: 1
  master:
    disableCommands: []

postgresql:
  # Note for maintainers:
  # Some confusion may appear here because we use docker image created from "official" dockerhub base image postgresql 
  # but we use helm chart designed for bitnami/postgresql.
  enabled: true
  image:
    repository: arminc/clair-db # Custom image with prefilled vulnerabilities info
    tag: latest
  # Use the same PGDATA as the travis job that builds arminc/clair-db
  # (https://github.com/arminc/clair-local-scan/blob/master/.travis.yml)
  # TODO: this should be a persistent volume mount
  postgresqlDataDir: /var/lib/postgresql/clair
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: postgres
  # Based on https://github.com/timescale/timescaledb/issues/522#issuecomment-437162196
  # Otherwise we get CrashLoopBackoff: chmod: /var/lib/postgresql/clair: Operation not permitted
  securityContext:
    enabled: true
    fsGroup: 70
    runAsUser: 70

  replication:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    enabled: false

mongodb:
  enabled: true
  image:
    tag: 4.2.0-debian-9-r37
  mongodbUsername: redstone
  mongodbPassword: redstoneMongo123
  mongodbRootPassword: redstoneMongo123
  mongodbDatabase: vegeta
  # mongodbDatabase: elasticalert
  # NOTE: we need to create elasticalert database as well.
  volumePermissions:
    enabled: true
