global:
  # Not sure if it's good practice to pas our docker repo address to our subcharts like this.
  ourDockerRepo: localhost:32000

clair:
  enabled: true
  config:
    postgresURI: "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"

scanner:
  enabled: true
  # TODO: reference below variables from the original setting (maybe Helm enables it?)
  redis:
    password: Redis12345
    redisSecretName: redis-secret
  clair:
    postgresURI: "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"

console:
  # TODO: reference below variables from the original setting (maybe Helm enables it?)
  elasticsearch:
    elasticSecretName: elastic-secret
    extraEnvs:
      - name: ELASTIC_PASSWORD
        value: Elastic12345
      - name: ELASTIC_USERNAME
        value: elasticsearch
  enabled: true

  eventcenter:
    eventGrpcUrl: tensorsec-eventcenter:9090
    eventGrpcCertServerName: tensorsec-eventcenter
  postgresql:
    postgresqlDataDir: /bitnami/postgresql/data
    postgresqlUsername: postgres
    postgresqlPassword: password
    postgresqlDatabase: postgres

daemon:
  enabled: true
  eventcenter:
    eventGrpcUrl: tensorsec-eventcenter:9090
    eventGrpcCertServerName: tensorsec-eventcenter

eventcenterAuth:
  enabled: true

redis:
  enabled: true
  password: Redis12345
  usePassword: true
  cluster:
    slaveCount: 1
  master:
    disableCommands: []

elasticsearch:
  enabled: true
  minimumMasterNodes: 1
  replicas: 1
  extraEnvs:
    - name: ELASTIC_PASSWORD
      value: Elastic12345
    - name: ELASTIC_USERNAME
      value: elasticsearch
  # Below settings for local dev environment
  # sysctlInitContainer:
  #   enabled: false
  # esConfig:
  #   elasticsearch.yml: |
  #     node.store.allow_mmap: false
  # antiAffinity: "soft"
  # esJavaOpts: "-Xmx128m -Xms128m"
  # resources:
  #   requests:
  #     cpu: "100m"
  #     memory: "512M"
  #   limits:
  #     cpu: "1000m"
  #     memory: "512M"
  # volumeClaimTemplate:
  #   accessModes: [ "ReadWriteOnce" ]
  #   storageClassName: "microk8s-hostpath"
  #   resources:
  #     requests:
  #       storage: 100M

kibana:
  enabled: true

drift-prevention:
  enabled: true
  eventcenter:
    addr: tensorsec-eventcenter
    port: "8080"

postgresql:
  # Note for maintainers:
  # Some confusion may appear here because we use docker image created from "official" dockerhub base image postgresql
  # but we use helm chart designed for bitnami/postgresql.
  enabled: true
  image:
    pullSecret: harbor-admin-secret
    registry: registry.t-appagile.com
    repository: tensorsecurity/tensorsec-postgres # Our image with prefilled vulnerabilities info
    tag: "latest"
    pullPolicy: Always
  # Use the same PGDATA as the travis job that builds arminc/clair-db
  # (https://github.com/arminc/clair-local-scan/blob/master/.travis.yml)
  postgresqlDataDir: /bitnami/postgresql/data 
  postgresqlUsername: postgres
  postgresqlPassword: password
  postgresqlDatabase: postgres
  # Based on https://github.com/timescale/timescaledb/issues/522#issuecomment-437162196
  # Otherwise we get CrashLoopBackoff: chmod: /var/lib/postgresql/clair: Operation not permitted
  securityContext:
    enabled: true
    fsGroup: 70
    runAsUser: 70

  replication:
    enabled: false
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  persistence:
    enabled: true
    size: 10Gi
  metrics:
    enabled: false

mongodb:
  enabled: true
  image:
    tag: 4.4.2-debian-10-r12
  mongodbUsername: redstone
  mongodbPassword: redstoneMongo123
  mongodbRootPassword: redstoneMongo123
  mongodbDatabase: vegeta

  # https://github.com/helm/charts/issues/18588
  useStatefulSet: true
  replicaSet:
    enabled: true

  volumePermissions:
    enabled: true

seccompGenerator:
  auditdLogging: false
  enabled: false



holmes:
  enabled: true
  ebpf:
    enabled: false
  falco:
    rulesFile:
      - /etc/falco/falco_rules.local.yaml
    jsonOutput: true
    jsonIncludeOutputProperty: true
    httpOutput:
      enabled: false

    webserver:
      enabled: false
      
    programOutput:
      enabled: true
      keepAlive: false
      program: /bin/bash /holmes_export.sh

    syslogOutput:
      enabled: false

    stdoutOutput:
      enabled: true
  # Add extra volumes to Falco daemonset
  extraVolumes:
    - name: client-cert
      secret:
        secretName: eventcenter-tls-client-cert-secret
    - name: ca-cert
      secret:
        secretName: eventcenter-tls-ca-secret

  # Add extra volumeMounts to Falco container in Falco daemonset
  extraVolumeMounts:
    - mountPath: /auth/client
      name: client-cert
      readOnly: true
    - mountPath: /auth/ca
      name: ca-cert
      readOnly: true

