apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "image-validator.fullname" . }}
  labels:
{{ include "image-validator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "image-validator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "image-validator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "image-validator.fullname" . }}
        image: {{ include "tensorsec.imageValidator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9443
          protocol: TCP
        args:
        - --validateserver=tensorsec-scanner.{{ .Release.Namespace }}.svc:8888
        - --IgnoredNameSpaces={{ .Release.Namespace }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/tensorsec/certs
          readOnly: true
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ template "image-validator.fullname" . }}-certs     

