package constant

var SyscallIoStructMap = map[string]string{
	"time_args": "typedef struct {u64 __unused__; int __syscall_nr; time_t * tloc;} time_args;",
	"time_data": "typedef struct {event_info_t event_info; u64 tloc;} time_data;",
	"time_split": "tloc:pointer",
	"migrate_pages_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; unsigned long maxnode; unsigned long * old_nodes; unsigned long * new_nodes;} migrate_pages_args;",
	"migrate_pages_data": "typedef struct {event_info_t event_info; u64 pid; u64 maxnode; u64 old_nodes; u64 new_nodes;} migrate_pages_data;",
	"migrate_pages_split": "pid:integer maxnode:integer old_nodes:pointer new_nodes:pointer",
	"lsetxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name; void * value; size_t size; long flags;} lsetxattr_args;",
	"lsetxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64]; u64 value; u64 size; u64 flags;} lsetxattr_data;",
	"lsetxattr_split": "pathname:string name:string value:pointer size:integer flags:integer",
	"clock_getres_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; struct timespec * tp;} clock_getres_args;",
	"clock_getres_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 tp;} clock_getres_data;",
	"clock_getres_split": "which_clock:integer tp:pointer",
	"set_tid_address_args": "typedef struct {u64 __unused__; int __syscall_nr; long * tidptr;} set_tid_address_args;",
	"set_tid_address_data": "typedef struct {event_info_t event_info; u64 tidptr;} set_tid_address_data;",
	"set_tid_address_split": "tidptr:pointer",
	"pipe2_args": "typedef struct {u64 __unused__; int __syscall_nr; long * fildes; long flags;} pipe2_args;",
	"pipe2_data": "typedef struct {event_info_t event_info; u64 fildes; u64 flags; u64 readfd; u64 writefd;} pipe2_data;",
	"pipe2_split": "fildes:pointer flags:integer readfd:integer writefd:integer",
	"sethostname_args": "typedef struct {u64 __unused__; int __syscall_nr; char * name; long len;} sethostname_args;",
	"sethostname_data": "typedef struct {event_info_t event_info; char name[64]; u64 len;} sethostname_data;",
	"sethostname_split": "name:string len:integer",
	"dup3_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 oldfd; u64 newfd; long flags;} dup3_args;",
	"dup3_data": "typedef struct {event_info_t event_info; u64 oldfd; u64 newfd; u64 flags;} dup3_data;",
	"dup3_split": "oldfd:integer newfd:integer flags:integer",
	"umask_args": "typedef struct {u64 __unused__; int __syscall_nr; long mask;} umask_args;",
	"umask_data": "typedef struct {event_info_t event_info; u64 mask;} umask_data;",
	"umask_split": "mask:integer",
	"exit_group_args": "typedef struct {u64 __unused__; int __syscall_nr; long error_code;} exit_group_args;",
	"exit_group_data": "typedef struct {event_info_t event_info; u64 error_code;} exit_group_data;",
	"exit_group_split": "error_code:integer",
	"set_robust_list_args": "typedef struct {u64 __unused__; int __syscall_nr; struct robust_list_head * head; size_t len;} set_robust_list_args;",
	"set_robust_list_data": "typedef struct {event_info_t event_info; u64 head; u64 len;} set_robust_list_data;",
	"set_robust_list_split": "head:pointer len:integer",
	"iopl_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 level;} iopl_args;",
	"iopl_data": "typedef struct {event_info_t event_info; u64 level;} iopl_data;",
	"iopl_split": "level:integer",
	"lgetxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name; void * value; size_t size;} lgetxattr_args;",
	"lgetxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64]; u64 value; u64 size;} lgetxattr_data;",
	"lgetxattr_split": "pathname:string name:string value:pointer size:integer",
	"kill_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; long sig;} kill_args;",
	"kill_data": "typedef struct {event_info_t event_info; u64 pid; u64 sig;} kill_data;",
	"kill_split": "pid:integer sig:integer",
	"pread64_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; char * buf; size_t count; loff_t pos;} pread64_args;",
	"pread64_data": "typedef struct {event_info_t event_info; u64 fd; char buf[64]; u64 count; u64 pos;} pread64_data;",
	"pread64_split": "fd:integer buf:string count:integer pos:integer",
	"newfstatat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; struct stat * statbuf; long flag;} newfstatat_args;",
	"newfstatat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 statbuf; u64 flag;} newfstatat_data;",
	"newfstatat_split": "dfd:integer filename:string statbuf:pointer flag:integer",
	"newlstat_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; struct stat * statbuf;} newlstat_args;",
	"newlstat_data": "typedef struct {event_info_t event_info; char filename[64]; u64 statbuf;} newlstat_data;",
	"newlstat_split": "filename:string statbuf:pointer",
	"write_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; char * buf; size_t count;} write_args;",
	"write_data": "typedef struct {event_info_t event_info; u64 fd; char buf[64]; u64 count;} write_data;",
	"write_split": "fd:integer buf:string count:integer",
	"setregid_args": "typedef struct {u64 __unused__; int __syscall_nr; gid_t rgid; gid_t egid;} setregid_args;",
	"setregid_data": "typedef struct {event_info_t event_info; u64 rgid; u64 egid;} setregid_data;",
	"setregid_split": "rgid:integer egid:integer",
	"ustat_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned dev; struct ustat * ubuf;} ustat_args;",
	"ustat_data": "typedef struct {event_info_t event_info; u64 dev; u64 ubuf;} ustat_data;",
	"ustat_split": "dev:integer ubuf:pointer",
	"pause_args": "typedef struct {u64 __unused__; int __syscall_nr;} pause_args;",
	"pause_data": "typedef struct {event_info_t event_info;} pause_data;",
	"pause_split": "",
	"getrlimit_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 resource; struct rlimit * rlim;} getrlimit_args;",
	"getrlimit_data": "typedef struct {event_info_t event_info; u64 resource; u64 rlim;} getrlimit_data;",
	"getrlimit_split": "resource:integer rlim:pointer",
	"tkill_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; long sig;} tkill_args;",
	"tkill_data": "typedef struct {event_info_t event_info; u64 pid; u64 sig;} tkill_data;",
	"tkill_split": "pid:integer sig:integer",
	"dup2_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 oldfd; u64 newfd;} dup2_args;",
	"dup2_data": "typedef struct {event_info_t event_info; u64 oldfd; u64 newfd;} dup2_data;",
	"dup2_split": "oldfd:integer newfd:integer",
	"clock_adjtime_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; struct timex * utx;} clock_adjtime_args;",
	"clock_adjtime_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 utx;} clock_adjtime_data;",
	"clock_adjtime_split": "which_clock:integer utx:pointer",
	"rt_sigqueueinfo_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; long sig; siginfo_t * uinfo;} rt_sigqueueinfo_args;",
	"rt_sigqueueinfo_data": "typedef struct {event_info_t event_info; u64 pid; u64 sig; u64 uinfo;} rt_sigqueueinfo_data;",
	"rt_sigqueueinfo_split": "pid:integer sig:integer uinfo:pointer",
	"utime_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; struct utimbuf * times;} utime_args;",
	"utime_data": "typedef struct {event_info_t event_info; char filename[64]; u64 times;} utime_data;",
	"utime_split": "filename:string times:pointer",
	"setxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name; void * value; size_t size; long flags;} setxattr_args;",
	"setxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64]; u64 value; u64 size; u64 flags;} setxattr_data;",
	"setxattr_split": "pathname:string name:string value:pointer size:integer flags:integer",
	"membarrier_args": "typedef struct {u64 __unused__; int __syscall_nr; long cmd; long flags;} membarrier_args;",
	"membarrier_data": "typedef struct {event_info_t event_info; u64 cmd; u64 flags;} membarrier_data;",
	"membarrier_split": "cmd:integer flags:integer",
	"getegid_args": "typedef struct {u64 __unused__; int __syscall_nr;} getegid_args;",
	"getegid_data": "typedef struct {event_info_t event_info;} getegid_data;",
	"getegid_split": "",
	"mlock_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len;} mlock_args;",
	"mlock_data": "typedef struct {event_info_t event_info; u64 start; u64 len;} mlock_data;",
	"mlock_split": "start:integer len:integer",
	"tee_args": "typedef struct {u64 __unused__; int __syscall_nr; long fdin; long fdout; size_t len; u64 flags;} tee_args;",
	"tee_data": "typedef struct {event_info_t event_info; u64 fdin; u64 fdout; u64 len; u64 flags;} tee_data;",
	"tee_split": "fdin:integer fdout:integer len:integer flags:integer",
	"setpgid_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; pid_t pgid;} setpgid_args;",
	"setpgid_data": "typedef struct {event_info_t event_info; u64 pid; u64 pgid;} setpgid_data;",
	"setpgid_split": "pid:integer pgid:integer",
	"utimes_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; struct timeval * utimes;} utimes_args;",
	"utimes_data": "typedef struct {event_info_t event_info; char filename[64]; u64 utimes;} utimes_data;",
	"utimes_split": "filename:string utimes:pointer",
	"lremovexattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name;} lremovexattr_args;",
	"lremovexattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64];} lremovexattr_data;",
	"lremovexattr_split": "pathname:string name:string",
	"link_args": "typedef struct {u64 __unused__; int __syscall_nr; char * oldname; char * newname;} link_args;",
	"link_data": "typedef struct {event_info_t event_info; char oldname[64]; char newname[64];} link_data;",
	"link_split": "oldname:string newname:string",
	"readv_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen;} readv_args;",
	"readv_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen;} readv_data;",
	"readv_split": "fd:integer vec:pointer vlen:integer",
	"futex_args": "typedef struct {u64 __unused__; int __syscall_nr; u32 * uaddr; long op; u32 val; struct timespec * utime; u32 * uaddr2; u32 val3;} futex_args;",
	"futex_data": "typedef struct {event_info_t event_info; u64 uaddr; u64 op; u64 val; u64 utime; u64 uaddr2; u64 val3;} futex_data;",
	"futex_split": "uaddr:pointer op:integer val:integer utime:pointer uaddr2:pointer val3:integer",
	"getxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name; void * value; size_t size;} getxattr_args;",
	"getxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64]; u64 value; u64 size;} getxattr_data;",
	"getxattr_split": "pathname:string name:string value:pointer size:integer",
	"sched_get_priority_max_args": "typedef struct {u64 __unused__; int __syscall_nr; long policy;} sched_get_priority_max_args;",
	"sched_get_priority_max_data": "typedef struct {event_info_t event_info; u64 policy;} sched_get_priority_max_data;",
	"sched_get_priority_max_split": "policy:integer",
	"preadv2_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen; unsigned long pos_l; unsigned long pos_h; rwf_t flags;} preadv2_args;",
	"preadv2_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen; u64 pos_l; u64 pos_h; u64 flags;} preadv2_data;",
	"preadv2_split": "fd:integer vec:pointer vlen:integer pos_l:integer pos_h:integer flags:integer",
	"readlinkat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * pathname; char * buf; long bufsiz;} readlinkat_args;",
	"readlinkat_data": "typedef struct {event_info_t event_info; u64 dfd; char pathname[64]; char buf[64]; u64 bufsiz;} readlinkat_data;",
	"readlinkat_split": "dfd:integer pathname:string buf:string bufsiz:integer",
	"prctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long option; unsigned long arg2; unsigned long arg3; unsigned long arg4; unsigned long arg5;} prctl_args;",
	"prctl_data": "typedef struct {event_info_t event_info; u64 option; u64 arg2; u64 arg3; u64 arg4; u64 arg5;} prctl_data;",
	"prctl_split": "option:integer arg2:integer arg3:integer arg4:integer arg5:integer",
	"renameat_args": "typedef struct {u64 __unused__; int __syscall_nr; long olddfd; char * oldname; long newdfd; char * newname;} renameat_args;",
	"renameat_data": "typedef struct {event_info_t event_info; u64 olddfd; char oldname[64]; u64 newdfd; char newname[64];} renameat_data;",
	"renameat_split": "olddfd:integer oldname:string newdfd:integer newname:string",
	"renameat2_args": "typedef struct {u64 __unused__; int __syscall_nr; long olddfd; char * oldname; long newdfd; char * newname; u64 flags;} renameat2_args;",
	"renameat2_data": "typedef struct {event_info_t event_info; u64 olddfd; char oldname[64]; u64 newdfd; char newname[64]; u64 flags;} renameat2_data;",
	"renameat2_split": "olddfd:integer oldname:string newdfd:integer newname:string flags:integer",
	"sendmmsg_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct mmsghdr * mmsg; u64 vlen; u64 flags;} sendmmsg_args;",
	"sendmmsg_data": "typedef struct {event_info_t event_info; u64 fd; u64 mmsg; u64 vlen; u64 flags;} sendmmsg_data;",
	"sendmmsg_split": "fd:integer mmsg:pointer vlen:integer flags:integer",
	"modify_ldt_args": "typedef struct {u64 __unused__; int __syscall_nr; long func; void * ptr; unsigned long bytecount;} modify_ldt_args;",
	"modify_ldt_data": "typedef struct {event_info_t event_info; u64 func; u64 ptr; u64 bytecount;} modify_ldt_data;",
	"modify_ldt_split": "func:integer ptr:pointer bytecount:integer",
	"close_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd;} close_args;",
	"close_data": "typedef struct {event_info_t event_info; u64 fd;} close_data;",
	"close_split": "fd:integer",
	"ioprio_get_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; long who;} ioprio_get_args;",
	"ioprio_get_data": "typedef struct {event_info_t event_info; u64 which; u64 who;} ioprio_get_data;",
	"ioprio_get_split": "which:integer who:integer",
	"setreuid_args": "typedef struct {u64 __unused__; int __syscall_nr; uid_t ruid; uid_t euid;} setreuid_args;",
	"setreuid_data": "typedef struct {event_info_t event_info; u64 ruid; u64 euid;} setreuid_data;",
	"setreuid_split": "ruid:integer euid:integer",
	"sendfile64_args": "typedef struct {u64 __unused__; int __syscall_nr; long out_fd; long in_fd; loff_t * offset; size_t count;} sendfile64_args;",
	"sendfile64_data": "typedef struct {event_info_t event_info; u64 out_fd; u64 in_fd; u64 offset; u64 count;} sendfile64_data;",
	"sendfile64_split": "out_fd:integer in_fd:integer offset:pointer count:integer",
	"statfs_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; struct statfs * buf;} statfs_args;",
	"statfs_data": "typedef struct {event_info_t event_info; char pathname[64]; u64 buf;} statfs_data;",
	"statfs_split": "pathname:string buf:pointer",
	"getpriority_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; long who;} getpriority_args;",
	"getpriority_data": "typedef struct {event_info_t event_info; u64 which; u64 who;} getpriority_data;",
	"getpriority_split": "which:integer who:integer",
	"truncate_args": "typedef struct {u64 __unused__; int __syscall_nr; char * path; long length;} truncate_args;",
	"truncate_data": "typedef struct {event_info_t event_info; char path[64]; u64 length;} truncate_data;",
	"truncate_split": "path:string length:integer",
	"getcpu_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned * cpup; unsigned * nodep; struct getcpu_cache * unused;} getcpu_args;",
	"getcpu_data": "typedef struct {event_info_t event_info; u64 cpup; u64 nodep; u64 unused;} getcpu_data;",
	"getcpu_split": "cpup:pointer nodep:pointer unused:pointer",
	"shmat_args": "typedef struct {u64 __unused__; int __syscall_nr; long shmid; char * shmaddr; long shmflg;} shmat_args;",
	"shmat_data": "typedef struct {event_info_t event_info; u64 shmid; char shmaddr[64]; u64 shmflg;} shmat_data;",
	"shmat_split": "shmid:integer shmaddr:string shmflg:integer",
	"swapon_args": "typedef struct {u64 __unused__; int __syscall_nr; char * specialfile; long swap_flags;} swapon_args;",
	"swapon_data": "typedef struct {event_info_t event_info; char specialfile[64]; u64 swap_flags;} swapon_data;",
	"swapon_split": "specialfile:string swap_flags:integer",
	"waitid_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; pid_t upid; struct siginfo * infop; long options; struct rusage * ru;} waitid_args;",
	"waitid_data": "typedef struct {event_info_t event_info; u64 which; u64 upid; u64 infop; u64 options; u64 ru;} waitid_data;",
	"waitid_split": "which:integer upid:integer infop:pointer options:integer ru:pointer",
	"sync_file_range_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; loff_t offset; loff_t nbytes; u64 flags;} sync_file_range_args;",
	"sync_file_range_data": "typedef struct {event_info_t event_info; u64 fd; u64 offset; u64 nbytes; u64 flags;} sync_file_range_data;",
	"sync_file_range_split": "fd:integer offset:integer nbytes:integer flags:integer",
	"sched_rr_get_interval_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct timespec * interval;} sched_rr_get_interval_args;",
	"sched_rr_get_interval_data": "typedef struct {event_info_t event_info; u64 pid; u64 interval;} sched_rr_get_interval_data;",
	"sched_rr_get_interval_split": "pid:integer interval:pointer",
	"sched_getscheduler_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid;} sched_getscheduler_args;",
	"sched_getscheduler_data": "typedef struct {event_info_t event_info; u64 pid;} sched_getscheduler_data;",
	"sched_getscheduler_split": "pid:integer",
	"signalfd_args": "typedef struct {u64 __unused__; int __syscall_nr; long ufd; sigset_t * user_mask; size_t sizemask;} signalfd_args;",
	"signalfd_data": "typedef struct {event_info_t event_info; u64 ufd; u64 user_mask; u64 sizemask;} signalfd_data;",
	"signalfd_split": "ufd:integer user_mask:pointer sizemask:integer",
	"accept4_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * upeer_sockaddr; long * upeer_addrlen; long flags;} accept4_args;",
	"accept4_data": "typedef struct {event_info_t event_info; u64 fd; u64 upeer_sockaddr; u64 upeer_addrlen; u64 flags;} accept4_data;",
	"accept4_split": "fd:integer upeer_sockaddr:pointer upeer_addrlen:pointer flags:integer",
	"io_destroy_args": "typedef struct {u64 __unused__; int __syscall_nr; aio_context_t ctx;} io_destroy_args;",
	"io_destroy_data": "typedef struct {event_info_t event_info; u64 ctx;} io_destroy_data;",
	"io_destroy_split": "ctx:integer",
	"shutdown_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long how;} shutdown_args;",
	"shutdown_data": "typedef struct {event_info_t event_info; u64 fd; u64 how;} shutdown_data;",
	"shutdown_split": "fd:integer how:integer",
	"execveat_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * filename; char ** argv; char ** envp; long flags;} execveat_args;",
	"execveat_data": "typedef struct {event_info_t event_info; u64 fd; char filename[64]; char argv1[16]; char argv2[16]; char argv3[16]; u64 envp; u64 flags;} execveat_data;",
	"execveat_split": "fd:integer filename:string argv1:string argv2:string argv3:string envp:pointer flags:integer",
	"readahead_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; loff_t offset; size_t count;} readahead_args;",
	"readahead_data": "typedef struct {event_info_t event_info; u64 fd; u64 offset; u64 count;} readahead_data;",
	"readahead_split": "fd:integer offset:integer count:integer",
	"msgrcv_args": "typedef struct {u64 __unused__; int __syscall_nr; long msqid; struct msgbuf * msgp; size_t msgsz; long msgtyp; long msgflg;} msgrcv_args;",
	"msgrcv_data": "typedef struct {event_info_t event_info; u64 msqid; u64 msgp; u64 msgsz; u64 msgtyp; u64 msgflg;} msgrcv_data;",
	"msgrcv_split": "msqid:integer msgp:pointer msgsz:integer msgtyp:integer msgflg:integer",
	"removexattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * name;} removexattr_args;",
	"removexattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char name[64];} removexattr_data;",
	"removexattr_split": "pathname:string name:string",
	"shmctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long shmid; long cmd; struct shmid_ds * buf;} shmctl_args;",
	"shmctl_data": "typedef struct {event_info_t event_info; u64 shmid; u64 cmd; u64 buf;} shmctl_data;",
	"shmctl_split": "shmid:integer cmd:integer buf:pointer",
	"sendmsg_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct user_msghdr * msg; u64 flags;} sendmsg_args;",
	"sendmsg_data": "typedef struct {event_info_t event_info; u64 fd; u64 msg; u64 flags;} sendmsg_data;",
	"sendmsg_split": "fd:integer msg:pointer flags:integer",
	"setrlimit_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 resource; struct rlimit * rlim;} setrlimit_args;",
	"setrlimit_data": "typedef struct {event_info_t event_info; u64 resource; u64 rlim;} setrlimit_data;",
	"setrlimit_split": "resource:integer rlim:pointer",
	"munmap_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long addr; size_t len;} munmap_args;",
	"munmap_data": "typedef struct {event_info_t event_info; u64 addr; u64 len;} munmap_data;",
	"munmap_split": "addr:integer len:integer",
	"exit_args": "typedef struct {u64 __unused__; int __syscall_nr; long error_code;} exit_args;",
	"exit_data": "typedef struct {event_info_t event_info; u64 error_code;} exit_data;",
	"exit_split": "error_code:integer",
	"io_getevents_args": "typedef struct {u64 __unused__; int __syscall_nr; aio_context_t ctx_id; long min_nr; long nr; struct io_event * events; struct timespec * timeout;} io_getevents_args;",
	"io_getevents_data": "typedef struct {event_info_t event_info; u64 ctx_id; u64 min_nr; u64 nr; u64 events; u64 timeout;} io_getevents_data;",
	"io_getevents_split": "ctx_id:integer min_nr:integer nr:integer events:pointer timeout:pointer",
	"symlink_args": "typedef struct {u64 __unused__; int __syscall_nr; char * oldname; char * newname;} symlink_args;",
	"symlink_data": "typedef struct {event_info_t event_info; char oldname[64]; char newname[64];} symlink_data;",
	"symlink_split": "oldname:string newname:string",
	"rt_sigpending_args": "typedef struct {u64 __unused__; int __syscall_nr; sigset_t * uset; size_t sigsetsize;} rt_sigpending_args;",
	"rt_sigpending_data": "typedef struct {event_info_t event_info; u64 uset; u64 sigsetsize;} rt_sigpending_data;",
	"rt_sigpending_split": "uset:pointer sigsetsize:integer",
	"fanotify_init_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 flags; u64 event_f_flags;} fanotify_init_args;",
	"fanotify_init_data": "typedef struct {event_info_t event_info; u64 flags; u64 event_f_flags;} fanotify_init_data;",
	"fanotify_init_split": "flags:integer event_f_flags:integer",
	"geteuid_args": "typedef struct {u64 __unused__; int __syscall_nr;} geteuid_args;",
	"geteuid_data": "typedef struct {event_info_t event_info;} geteuid_data;",
	"geteuid_split": "",
	"getpeername_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * usockaddr; long * usockaddr_len;} getpeername_args;",
	"getpeername_data": "typedef struct {event_info_t event_info; u64 fd; u64 usockaddr; u64 usockaddr_len;} getpeername_data;",
	"getpeername_split": "fd:integer usockaddr:pointer usockaddr_len:pointer",
	"fsetxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * name; void * value; size_t size; long flags;} fsetxattr_args;",
	"fsetxattr_data": "typedef struct {event_info_t event_info; u64 fd; char name[64]; u64 value; u64 size; u64 flags;} fsetxattr_data;",
	"fsetxattr_split": "fd:integer name:string value:pointer size:integer flags:integer",
	"acct_args": "typedef struct {u64 __unused__; int __syscall_nr; char * name;} acct_args;",
	"acct_data": "typedef struct {event_info_t event_info; char name[64];} acct_data;",
	"acct_split": "name:string",
	"times_args": "typedef struct {u64 __unused__; int __syscall_nr; struct tms * tbuf;} times_args;",
	"times_data": "typedef struct {event_info_t event_info; u64 tbuf;} times_data;",
	"times_split": "tbuf:pointer",
	"msgget_args": "typedef struct {u64 __unused__; int __syscall_nr; key_t key; long msgflg;} msgget_args;",
	"msgget_data": "typedef struct {event_info_t event_info; u64 key; u64 msgflg;} msgget_data;",
	"msgget_split": "key:integer msgflg:integer",
	"inotify_add_watch_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * pathname; u32 mask;} inotify_add_watch_args;",
	"inotify_add_watch_data": "typedef struct {event_info_t event_info; u64 fd; char pathname[64]; u64 mask;} inotify_add_watch_data;",
	"inotify_add_watch_split": "fd:integer pathname:string mask:integer",
	"timerfd_gettime_args": "typedef struct {u64 __unused__; int __syscall_nr; long ufd; struct itimerspec * otmr;} timerfd_gettime_args;",
	"timerfd_gettime_data": "typedef struct {event_info_t event_info; u64 ufd; u64 otmr;} timerfd_gettime_data;",
	"timerfd_gettime_split": "ufd:integer otmr:pointer",
	"rt_tgsigqueueinfo_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t tgid; pid_t pid; long sig; siginfo_t * uinfo;} rt_tgsigqueueinfo_args;",
	"rt_tgsigqueueinfo_data": "typedef struct {event_info_t event_info; u64 tgid; u64 pid; u64 sig; u64 uinfo;} rt_tgsigqueueinfo_data;",
	"rt_tgsigqueueinfo_split": "tgid:integer pid:integer sig:integer uinfo:pointer",
	"timer_delete_args": "typedef struct {u64 __unused__; int __syscall_nr; timer_t timer_id;} timer_delete_args;",
	"timer_delete_data": "typedef struct {event_info_t event_info; u64 timer_id;} timer_delete_data;",
	"timer_delete_split": "timer_id:integer",
	"pkey_alloc_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long flags; unsigned long init_val;} pkey_alloc_args;",
	"pkey_alloc_data": "typedef struct {event_info_t event_info; u64 flags; u64 init_val;} pkey_alloc_data;",
	"pkey_alloc_split": "flags:integer init_val:integer",
	"setfsgid_args": "typedef struct {u64 __unused__; int __syscall_nr; gid_t gid;} setfsgid_args;",
	"setfsgid_data": "typedef struct {event_info_t event_info; u64 gid;} setfsgid_data;",
	"setfsgid_split": "gid:integer",
	"tgkill_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t tgid; pid_t pid; long sig;} tgkill_args;",
	"tgkill_data": "typedef struct {event_info_t event_info; u64 tgid; u64 pid; u64 sig;} tgkill_data;",
	"tgkill_split": "tgid:integer pid:integer sig:integer",
	"setgid_args": "typedef struct {u64 __unused__; int __syscall_nr; gid_t gid;} setgid_args;",
	"setgid_data": "typedef struct {event_info_t event_info; u64 gid;} setgid_data;",
	"setgid_split": "gid:integer",
	"adjtimex_args": "typedef struct {u64 __unused__; int __syscall_nr; struct timex * txc_p;} adjtimex_args;",
	"adjtimex_data": "typedef struct {event_info_t event_info; u64 txc_p;} adjtimex_data;",
	"adjtimex_split": "txc_p:pointer",
	"fgetxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * name; void * value; size_t size;} fgetxattr_args;",
	"fgetxattr_data": "typedef struct {event_info_t event_info; u64 fd; char name[64]; u64 value; u64 size;} fgetxattr_data;",
	"fgetxattr_split": "fd:integer name:string value:pointer size:integer",
	"pkey_mprotect_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len; unsigned long prot; long pkey;} pkey_mprotect_args;",
	"pkey_mprotect_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 prot; u64 pkey;} pkey_mprotect_data;",
	"pkey_mprotect_split": "start:integer len:integer prot:integer pkey:integer",
	"sched_setscheduler_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; long policy; struct sched_param * param;} sched_setscheduler_args;",
	"sched_setscheduler_data": "typedef struct {event_info_t event_info; u64 pid; u64 policy; u64 param;} sched_setscheduler_data;",
	"sched_setscheduler_split": "pid:integer policy:integer param:pointer",
	"mq_notify_args": "typedef struct {u64 __unused__; int __syscall_nr; mqd_t mqdes; struct sigevent * u_notification;} mq_notify_args;",
	"mq_notify_data": "typedef struct {event_info_t event_info; u64 mqdes; u64 u_notification;} mq_notify_data;",
	"mq_notify_split": "mqdes:integer u_notification:pointer",
	"epoll_pwait_args": "typedef struct {u64 __unused__; int __syscall_nr; long epfd; struct epoll_event * events; long maxevents; long timeout; sigset_t * sigmask; size_t sigsetsize;} epoll_pwait_args;",
	"epoll_pwait_data": "typedef struct {event_info_t event_info; u64 epfd; u64 events; u64 maxevents; u64 timeout; u64 sigmask; u64 sigsetsize;} epoll_pwait_data;",
	"epoll_pwait_split": "epfd:integer events:pointer maxevents:integer timeout:integer sigmask:pointer sigsetsize:integer",
	"syncfs_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd;} syncfs_args;",
	"syncfs_data": "typedef struct {event_info_t event_info; u64 fd;} syncfs_data;",
	"syncfs_split": "fd:integer",
	"getrandom_args": "typedef struct {u64 __unused__; int __syscall_nr; char * buf; size_t count; u64 flags;} getrandom_args;",
	"getrandom_data": "typedef struct {event_info_t event_info; char buf[64]; u64 count; u64 flags;} getrandom_data;",
	"getrandom_split": "buf:string count:integer flags:integer",
	"creat_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; umode_t mode;} creat_args;",
	"creat_data": "typedef struct {event_info_t event_info; char pathname[64]; u64 mode;} creat_data;",
	"creat_split": "pathname:string mode:integer",
	"ppoll_args": "typedef struct {u64 __unused__; int __syscall_nr; struct pollfd * ufds; u64 nfds; struct timespec * tsp; sigset_t * sigmask; size_t sigsetsize;} ppoll_args;",
	"ppoll_data": "typedef struct {event_info_t event_info; u64 ufds; u64 nfds; u64 tsp; u64 sigmask; u64 sigsetsize;} ppoll_data;",
	"ppoll_split": "ufds:pointer nfds:integer tsp:pointer sigmask:pointer sigsetsize:integer",
	"sync_args": "typedef struct {u64 __unused__; int __syscall_nr;} sync_args;",
	"sync_data": "typedef struct {event_info_t event_info;} sync_data;",
	"sync_split": "",
	"futimesat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; struct timeval * utimes;} futimesat_args;",
	"futimesat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 utimes;} futimesat_data;",
	"futimesat_split": "dfd:integer filename:string utimes:pointer",
	"getuid_args": "typedef struct {u64 __unused__; int __syscall_nr;} getuid_args;",
	"getuid_data": "typedef struct {event_info_t event_info;} getuid_data;",
	"getuid_split": "",
	"kexec_load_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long entry; unsigned long nr_segments; struct kexec_segment * segments; unsigned long flags;} kexec_load_args;",
	"kexec_load_data": "typedef struct {event_info_t event_info; u64 entry; u64 nr_segments; u64 segments; u64 flags;} kexec_load_data;",
	"kexec_load_split": "entry:integer nr_segments:integer segments:pointer flags:integer",
	"fanotify_mark_args": "typedef struct {u64 __unused__; int __syscall_nr; long fanotify_fd; u64 flags; __u64 mask; long dfd; char * pathname;} fanotify_mark_args;",
	"fanotify_mark_data": "typedef struct {event_info_t event_info; u64 fanotify_fd; u64 flags; u64 mask; u64 dfd; char pathname[64];} fanotify_mark_data;",
	"fanotify_mark_split": "fanotify_fd:integer flags:integer mask:integer dfd:integer pathname:string",
	"chroot_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename;} chroot_args;",
	"chroot_data": "typedef struct {event_info_t event_info; char filename[64];} chroot_data;",
	"chroot_split": "filename:string",
	"select_args": "typedef struct {u64 __unused__; int __syscall_nr; long n; fd_set * inp; fd_set * outp; fd_set * exp; struct timeval * tvp;} select_args;",
	"select_data": "typedef struct {event_info_t event_info; u64 n; u64 inp; u64 outp; u64 exp; u64 tvp;} select_data;",
	"select_split": "n:integer inp:pointer outp:pointer exp:pointer tvp:pointer",
	"getrusage_args": "typedef struct {u64 __unused__; int __syscall_nr; long who; struct rusage * ru;} getrusage_args;",
	"getrusage_data": "typedef struct {event_info_t event_info; u64 who; u64 ru;} getrusage_data;",
	"getrusage_split": "who:integer ru:pointer",
	"pwritev_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen; unsigned long pos_l; unsigned long pos_h;} pwritev_args;",
	"pwritev_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen; u64 pos_l; u64 pos_h;} pwritev_data;",
	"pwritev_split": "fd:integer vec:pointer vlen:integer pos_l:integer pos_h:integer",
	"getsockopt_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long level; long optname; char * optval; long * optlen;} getsockopt_args;",
	"getsockopt_data": "typedef struct {event_info_t event_info; u64 fd; u64 level; u64 optname; char optval[64]; u64 optlen;} getsockopt_data;",
	"getsockopt_split": "fd:integer level:integer optname:integer optval:string optlen:pointer",
	"rename_args": "typedef struct {u64 __unused__; int __syscall_nr; char * oldname; char * newname;} rename_args;",
	"rename_data": "typedef struct {event_info_t event_info; char oldname[64]; char newname[64];} rename_data;",
	"rename_split": "oldname:string newname:string",
	"fstatfs_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; struct statfs * buf;} fstatfs_args;",
	"fstatfs_data": "typedef struct {event_info_t event_info; u64 fd; u64 buf;} fstatfs_data;",
	"fstatfs_split": "fd:integer buf:pointer",
	"sysfs_args": "typedef struct {u64 __unused__; int __syscall_nr; long option; unsigned long arg1; unsigned long arg2;} sysfs_args;",
	"sysfs_data": "typedef struct {event_info_t event_info; u64 option; u64 arg1; u64 arg2;} sysfs_data;",
	"sysfs_split": "option:integer arg1:integer arg2:integer",
	"mincore_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len; unsigned char * vec;} mincore_args;",
	"mincore_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 vec;} mincore_data;",
	"mincore_split": "start:integer len:integer vec:pointer",
	"copy_file_range_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd_in; loff_t * off_in; long fd_out; loff_t * off_out; size_t len; u64 flags;} copy_file_range_args;",
	"copy_file_range_data": "typedef struct {event_info_t event_info; u64 fd_in; u64 off_in; u64 fd_out; u64 off_out; u64 len; u64 flags;} copy_file_range_data;",
	"copy_file_range_split": "fd_in:integer off_in:pointer fd_out:integer off_out:pointer len:integer flags:integer",
	"splice_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd_in; loff_t * off_in; long fd_out; loff_t * off_out; size_t len; u64 flags;} splice_args;",
	"splice_data": "typedef struct {event_info_t event_info; u64 fd_in; u64 off_in; u64 fd_out; u64 off_out; u64 len; u64 flags;} splice_data;",
	"splice_split": "fd_in:integer off_in:pointer fd_out:integer off_out:pointer len:integer flags:integer",
	"newstat_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; struct stat * statbuf;} newstat_args;",
	"newstat_data": "typedef struct {event_info_t event_info; char filename[64]; u64 statbuf;} newstat_data;",
	"newstat_split": "filename:string statbuf:pointer",
	"process_vm_writev_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct iovec * lvec; unsigned long liovcnt; struct iovec * rvec; unsigned long riovcnt; unsigned long flags;} process_vm_writev_args;",
	"process_vm_writev_data": "typedef struct {event_info_t event_info; u64 pid; u64 lvec; u64 liovcnt; u64 rvec; u64 riovcnt; u64 flags;} process_vm_writev_data;",
	"process_vm_writev_split": "pid:integer lvec:pointer liovcnt:integer rvec:pointer riovcnt:integer flags:integer",
	"timer_gettime_args": "typedef struct {u64 __unused__; int __syscall_nr; timer_t timer_id; struct itimerspec * setting;} timer_gettime_args;",
	"timer_gettime_data": "typedef struct {event_info_t event_info; u64 timer_id; u64 setting;} timer_gettime_data;",
	"timer_gettime_split": "timer_id:integer setting:pointer",
	"pivot_root_args": "typedef struct {u64 __unused__; int __syscall_nr; char * new_root; char * put_old;} pivot_root_args;",
	"pivot_root_data": "typedef struct {event_info_t event_info; char new_root[64]; char put_old[64];} pivot_root_data;",
	"pivot_root_split": "new_root:string put_old:string",
	"name_to_handle_at_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * name; struct file_handle * handle; long * mnt_id; long flag;} name_to_handle_at_args;",
	"name_to_handle_at_data": "typedef struct {event_info_t event_info; u64 dfd; char name[64]; u64 handle; u64 mnt_id; u64 flag;} name_to_handle_at_data;",
	"name_to_handle_at_split": "dfd:integer name:string handle:pointer mnt_id:pointer flag:integer",
	"bind_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * umyaddr; long addrlen;} bind_args;",
	"bind_data": "typedef struct {event_info_t event_info; u64 fd; u64 umyaddr; u64 addrlen;} bind_data;",
	"bind_split": "fd:integer umyaddr:pointer addrlen:integer",
	"readlink_args": "typedef struct {u64 __unused__; int __syscall_nr; char * path; char * buf; long bufsiz;} readlink_args;",
	"readlink_data": "typedef struct {event_info_t event_info; char path[64]; char buf[64]; u64 bufsiz;} readlink_data;",
	"readlink_split": "path:string buf:string bufsiz:integer",
	"getppid_args": "typedef struct {u64 __unused__; int __syscall_nr;} getppid_args;",
	"getppid_data": "typedef struct {event_info_t event_info;} getppid_data;",
	"getppid_split": "",
	"setuid_args": "typedef struct {u64 __unused__; int __syscall_nr; uid_t uid;} setuid_args;",
	"setuid_data": "typedef struct {event_info_t event_info; u64 uid;} setuid_data;",
	"setuid_split": "uid:integer",
	"mremap_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long addr; unsigned long old_len; unsigned long new_len; unsigned long flags; unsigned long new_addr;} mremap_args;",
	"mremap_data": "typedef struct {event_info_t event_info; u64 addr; u64 old_len; u64 new_len; u64 flags; u64 new_addr;} mremap_data;",
	"mremap_split": "addr:integer old_len:integer new_len:integer flags:integer new_addr:integer",
	"keyctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long option; unsigned long arg2; unsigned long arg3; unsigned long arg4; unsigned long arg5;} keyctl_args;",
	"keyctl_data": "typedef struct {event_info_t event_info; u64 option; u64 arg2; u64 arg3; u64 arg4; u64 arg5;} keyctl_data;",
	"keyctl_split": "option:integer arg2:integer arg3:integer arg4:integer arg5:integer",
	"pselect6_args": "typedef struct {u64 __unused__; int __syscall_nr; long n; fd_set * inp; fd_set * outp; fd_set * exp; struct timespec * tsp; void * sig;} pselect6_args;",
	"pselect6_data": "typedef struct {event_info_t event_info; u64 n; u64 inp; u64 outp; u64 exp; u64 tsp; u64 sig;} pselect6_data;",
	"pselect6_split": "n:integer inp:pointer outp:pointer exp:pointer tsp:pointer sig:pointer",
	"delete_module_args": "typedef struct {u64 __unused__; int __syscall_nr; char * name_user; u64 flags;} delete_module_args;",
	"delete_module_data": "typedef struct {event_info_t event_info; char name_user[64]; u64 flags;} delete_module_data;",
	"delete_module_split": "name_user:string flags:integer",
	"utimensat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; struct timespec * utimes; long flags;} utimensat_args;",
	"utimensat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 utimes; u64 flags;} utimensat_data;",
	"utimensat_split": "dfd:integer filename:string utimes:pointer flags:integer",
	"get_mempolicy_args": "typedef struct {u64 __unused__; int __syscall_nr; long * policy; unsigned long * nmask; unsigned long maxnode; unsigned long addr; unsigned long flags;} get_mempolicy_args;",
	"get_mempolicy_data": "typedef struct {event_info_t event_info; u64 policy; u64 nmask; u64 maxnode; u64 addr; u64 flags;} get_mempolicy_data;",
	"get_mempolicy_split": "policy:pointer nmask:pointer maxnode:integer addr:integer flags:integer",
	"dup_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fildes;} dup_args;",
	"dup_data": "typedef struct {event_info_t event_info; u64 fildes;} dup_data;",
	"dup_split": "fildes:integer",
	"eventfd_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 count;} eventfd_args;",
	"eventfd_data": "typedef struct {event_info_t event_info; u64 count;} eventfd_data;",
	"eventfd_split": "count:integer",
	"recvfrom_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; void * ubuf; size_t size; u64 flags; struct sockaddr * addr; long * addr_len;} recvfrom_args;",
	"recvfrom_data": "typedef struct {event_info_t event_info; u64 fd; u64 ubuf; u64 size; u64 flags; u64 addr; u64 addr_len;} recvfrom_data;",
	"recvfrom_split": "fd:integer ubuf:pointer size:integer flags:integer addr:pointer addr_len:pointer",
	"statx_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; unsigned flags; u64 mask; struct statx * buffer;} statx_args;",
	"statx_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 flags; u64 mask; u64 buffer;} statx_data;",
	"statx_split": "dfd:integer filename:string flags:integer mask:integer buffer:pointer",
	"rt_sigaction_args": "typedef struct {u64 __unused__; int __syscall_nr; long sig; struct sigaction * act; struct sigaction * oact; size_t sigsetsize;} rt_sigaction_args;",
	"rt_sigaction_data": "typedef struct {event_info_t event_info; u64 sig; u64 act; u64 oact; u64 sigsetsize;} rt_sigaction_data;",
	"rt_sigaction_split": "sig:integer act:pointer oact:pointer sigsetsize:integer",
	"munlockall_args": "typedef struct {u64 __unused__; int __syscall_nr;} munlockall_args;",
	"munlockall_data": "typedef struct {event_info_t event_info;} munlockall_data;",
	"munlockall_split": "",
	"getdents_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; struct linux_dirent * dirent; u64 count;} getdents_args;",
	"getdents_data": "typedef struct {event_info_t event_info; u64 fd; u64 dirent; u64 count;} getdents_data;",
	"getdents_split": "fd:integer dirent:pointer count:integer",
	"epoll_create1_args": "typedef struct {u64 __unused__; int __syscall_nr; long flags;} epoll_create1_args;",
	"epoll_create1_data": "typedef struct {event_info_t event_info; u64 flags;} epoll_create1_data;",
	"epoll_create1_split": "flags:integer",
	"wait4_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t upid; long * stat_addr; long options; struct rusage * ru;} wait4_args;",
	"wait4_data": "typedef struct {event_info_t event_info; u64 upid; u64 stat_addr; u64 options; u64 ru;} wait4_data;",
	"wait4_split": "upid:integer stat_addr:pointer options:integer ru:pointer",
	"sched_yield_args": "typedef struct {u64 __unused__; int __syscall_nr;} sched_yield_args;",
	"sched_yield_data": "typedef struct {event_info_t event_info;} sched_yield_data;",
	"sched_yield_split": "",
	"mlockall_args": "typedef struct {u64 __unused__; int __syscall_nr; long flags;} mlockall_args;",
	"mlockall_data": "typedef struct {event_info_t event_info; u64 flags;} mlockall_data;",
	"mlockall_split": "flags:integer",
	"sched_getattr_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct sched_attr * uattr; u64 size; u64 flags;} sched_getattr_args;",
	"sched_getattr_data": "typedef struct {event_info_t event_info; u64 pid; u64 uattr; u64 size; u64 flags;} sched_getattr_data;",
	"sched_getattr_split": "pid:integer uattr:pointer size:integer flags:integer",
	"setpriority_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; long who; long niceval;} setpriority_args;",
	"setpriority_data": "typedef struct {event_info_t event_info; u64 which; u64 who; u64 niceval;} setpriority_data;",
	"setpriority_split": "which:integer who:integer niceval:integer",
	"socket_args": "typedef struct {u64 __unused__; int __syscall_nr; long family; long type; long protocol;} socket_args;",
	"socket_data": "typedef struct {event_info_t event_info; u64 family; u64 type; u64 protocol;} socket_data;",
	"socket_split": "family:integer type:integer protocol:integer",
	"semtimedop_args": "typedef struct {u64 __unused__; int __syscall_nr; long semid; struct sembuf * tsops; u64 nsops; struct timespec * timeout;} semtimedop_args;",
	"semtimedop_data": "typedef struct {event_info_t event_info; u64 semid; u64 tsops; u64 nsops; u64 timeout;} semtimedop_data;",
	"semtimedop_split": "semid:integer tsops:pointer nsops:integer timeout:pointer",
	"setfsuid_args": "typedef struct {u64 __unused__; int __syscall_nr; uid_t uid;} setfsuid_args;",
	"setfsuid_data": "typedef struct {event_info_t event_info; u64 uid;} setfsuid_data;",
	"setfsuid_split": "uid:integer",
	"epoll_create_args": "typedef struct {u64 __unused__; int __syscall_nr; long size;} epoll_create_args;",
	"epoll_create_data": "typedef struct {event_info_t event_info; u64 size;} epoll_create_data;",
	"epoll_create_split": "size:integer",
	"semop_args": "typedef struct {u64 __unused__; int __syscall_nr; long semid; struct sembuf * tsops; unsigned nsops;} semop_args;",
	"semop_data": "typedef struct {event_info_t event_info; u64 semid; u64 tsops; u64 nsops;} semop_data;",
	"semop_split": "semid:integer tsops:pointer nsops:integer",
	"open_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; long flags; umode_t mode;} open_args;",
	"open_data": "typedef struct {event_info_t event_info; char filename[64]; u64 flags; u64 mode;} open_data;",
	"open_split": "filename:string flags:integer mode:integer",
	"openat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; long flags; umode_t mode;} openat_args;",
	"openat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 flags; u64 mode;} openat_data;",
	"openat_split": "dfd:integer filename:string flags:integer mode:integer",
	"fremovexattr_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * name;} fremovexattr_args;",
	"fremovexattr_data": "typedef struct {event_info_t event_info; u64 fd; char name[64];} fremovexattr_data;",
	"fremovexattr_split": "fd:integer name:string",
	"faccessat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; long mode;} faccessat_args;",
	"faccessat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 mode;} faccessat_data;",
	"faccessat_split": "dfd:integer filename:string mode:integer",
	"ftruncate_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; unsigned long length;} ftruncate_args;",
	"ftruncate_data": "typedef struct {event_info_t event_info; u64 fd; u64 length;} ftruncate_data;",
	"ftruncate_split": "fd:integer length:integer",
	"sched_get_priority_min_args": "typedef struct {u64 __unused__; int __syscall_nr; long policy;} sched_get_priority_min_args;",
	"sched_get_priority_min_data": "typedef struct {event_info_t event_info; u64 policy;} sched_get_priority_min_data;",
	"sched_get_priority_min_split": "policy:integer",
	"move_pages_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; unsigned long nr_pages; void * * pages; long * nodes; long * status; long flags;} move_pages_args;",
	"move_pages_data": "typedef struct {event_info_t event_info; u64 pid; u64 nr_pages; u64 pages; u64 nodes; u64 status; u64 flags;} move_pages_data;",
	"move_pages_split": "pid:integer nr_pages:integer pages:pointer nodes:pointer status:pointer flags:integer",
	"lseek_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; off_t offset; u64 whence;} lseek_args;",
	"lseek_data": "typedef struct {event_info_t event_info; u64 fd; u64 offset; u64 whence;} lseek_data;",
	"lseek_split": "fd:integer offset:integer whence:integer",
	"poll_args": "typedef struct {u64 __unused__; int __syscall_nr; struct pollfd * ufds; u64 nfds; long timeout_msecs;} poll_args;",
	"poll_data": "typedef struct {event_info_t event_info; u64 ufds; u64 nfds; u64 timeout_msecs;} poll_data;",
	"poll_split": "ufds:pointer nfds:integer timeout_msecs:integer",
	"fdatasync_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd;} fdatasync_args;",
	"fdatasync_data": "typedef struct {event_info_t event_info; u64 fd;} fdatasync_data;",
	"fdatasync_split": "fd:integer",
	"fsync_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd;} fsync_args;",
	"fsync_data": "typedef struct {event_info_t event_info; u64 fd;} fsync_data;",
	"fsync_split": "fd:integer",
	"setsockopt_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long level; long optname; char * optval; long optlen;} setsockopt_args;",
	"setsockopt_data": "typedef struct {event_info_t event_info; u64 fd; u64 level; u64 optname; char optval[64]; u64 optlen;} setsockopt_data;",
	"setsockopt_split": "fd:integer level:integer optname:integer optval:string optlen:integer",
	"timer_getoverrun_args": "typedef struct {u64 __unused__; int __syscall_nr; timer_t timer_id;} timer_getoverrun_args;",
	"timer_getoverrun_data": "typedef struct {event_info_t event_info; u64 timer_id;} timer_getoverrun_data;",
	"timer_getoverrun_split": "timer_id:integer",
	"getgid_args": "typedef struct {u64 __unused__; int __syscall_nr;} getgid_args;",
	"getgid_data": "typedef struct {event_info_t event_info;} getgid_data;",
	"getgid_split": "",
	"capset_args": "typedef struct {u64 __unused__; int __syscall_nr; cap_user_header_t header; cap_user_data_t data;} capset_args;",
	"capset_data": "typedef struct {event_info_t event_info; u64 header; u64 data;} capset_data;",
	"capset_split": "header:integer data:integer",
	"semget_args": "typedef struct {u64 __unused__; int __syscall_nr; key_t key; long nsems; long semflg;} semget_args;",
	"semget_data": "typedef struct {event_info_t event_info; u64 key; u64 nsems; u64 semflg;} semget_data;",
	"semget_split": "key:integer nsems:integer semflg:integer",
	"prlimit64_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; u64 resource; struct rlimit64 * new_rlim; struct rlimit64 * old_rlim;} prlimit64_args;",
	"prlimit64_data": "typedef struct {event_info_t event_info; u64 pid; u64 resource; u64 new_rlim; u64 old_rlim;} prlimit64_data;",
	"prlimit64_split": "pid:integer resource:integer new_rlim:pointer old_rlim:pointer",
	"mq_unlink_args": "typedef struct {u64 __unused__; int __syscall_nr; char * u_name;} mq_unlink_args;",
	"mq_unlink_data": "typedef struct {event_info_t event_info; char u_name[64];} mq_unlink_data;",
	"mq_unlink_split": "u_name:string",
	"clock_settime_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; struct timespec * tp;} clock_settime_args;",
	"clock_settime_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 tp;} clock_settime_data;",
	"clock_settime_split": "which_clock:integer tp:pointer",
	"rt_sigtimedwait_args": "typedef struct {u64 __unused__; int __syscall_nr; sigset_t * uthese; siginfo_t * uinfo; struct timespec * uts; size_t sigsetsize;} rt_sigtimedwait_args;",
	"rt_sigtimedwait_data": "typedef struct {event_info_t event_info; u64 uthese; u64 uinfo; u64 uts; u64 sigsetsize;} rt_sigtimedwait_data;",
	"rt_sigtimedwait_split": "uthese:pointer uinfo:pointer uts:pointer sigsetsize:integer",
	"sigaltstack_args": "typedef struct {u64 __unused__; int __syscall_nr; stack_t * uss; stack_t * uoss;} sigaltstack_args;",
	"sigaltstack_data": "typedef struct {event_info_t event_info; u64 uss; u64 uoss;} sigaltstack_data;",
	"sigaltstack_split": "uss:pointer uoss:pointer",
	"shmget_args": "typedef struct {u64 __unused__; int __syscall_nr; key_t key; size_t size; long shmflg;} shmget_args;",
	"shmget_data": "typedef struct {event_info_t event_info; u64 key; u64 size; u64 shmflg;} shmget_data;",
	"shmget_split": "key:integer size:integer shmflg:integer",
	"writev_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen;} writev_args;",
	"writev_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen;} writev_data;",
	"writev_split": "fd:integer vec:pointer vlen:integer",
	"mprotect_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len; unsigned long prot;} mprotect_args;",
	"mprotect_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 prot;} mprotect_data;",
	"mprotect_split": "start:integer len:integer prot:integer",
	"setitimer_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; struct itimerval * value; struct itimerval * ovalue;} setitimer_args;",
	"setitimer_data": "typedef struct {event_info_t event_info; u64 which; u64 value; u64 ovalue;} setitimer_data;",
	"setitimer_split": "which:integer value:pointer ovalue:pointer",
	"remap_file_pages_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; unsigned long size; unsigned long prot; unsigned long pgoff; unsigned long flags;} remap_file_pages_args;",
	"remap_file_pages_data": "typedef struct {event_info_t event_info; u64 start; u64 size; u64 prot; u64 pgoff; u64 flags;} remap_file_pages_data;",
	"remap_file_pages_split": "start:integer size:integer prot:integer pgoff:integer flags:integer",
	"getresgid_args": "typedef struct {u64 __unused__; int __syscall_nr; gid_t * rgidp; gid_t * egidp; gid_t * sgidp;} getresgid_args;",
	"getresgid_data": "typedef struct {event_info_t event_info; u64 rgidp; u64 egidp; u64 sgidp;} getresgid_data;",
	"getresgid_split": "rgidp:pointer egidp:pointer sgidp:pointer",
	"seccomp_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 op; u64 flags; char * uargs;} seccomp_args;",
	"seccomp_data": "typedef struct {event_info_t event_info; u64 op; u64 flags; char uargs[64];} seccomp_data;",
	"seccomp_split": "op:integer flags:integer uargs:string",
	"gettimeofday_args": "typedef struct {u64 __unused__; int __syscall_nr; struct timeval * tv; struct timezone * tz;} gettimeofday_args;",
	"gettimeofday_data": "typedef struct {event_info_t event_info; u64 tv; u64 tz;} gettimeofday_data;",
	"gettimeofday_split": "tv:pointer tz:pointer",
	"getsockname_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * usockaddr; long * usockaddr_len;} getsockname_args;",
	"getsockname_data": "typedef struct {event_info_t event_info; u64 fd; u64 usockaddr; u64 usockaddr_len;} getsockname_data;",
	"getsockname_split": "fd:integer usockaddr:pointer usockaddr_len:pointer",
	"symlinkat_args": "typedef struct {u64 __unused__; int __syscall_nr; char * oldname; long newdfd; char * newname;} symlinkat_args;",
	"symlinkat_data": "typedef struct {event_info_t event_info; char oldname[64]; u64 newdfd; char newname[64];} symlinkat_data;",
	"symlinkat_split": "oldname:string newdfd:integer newname:string",
	"getpid_args": "typedef struct {u64 __unused__; int __syscall_nr;} getpid_args;",
	"getpid_data": "typedef struct {event_info_t event_info;} getpid_data;",
	"getpid_split": "",
	"vfork_args": "typedef struct {u64 __unused__; int __syscall_nr;} vfork_args;",
	"vfork_data": "typedef struct {event_info_t event_info;} vfork_data;",
	"vfork_split": "",
	"fork_args": "typedef struct {u64 __unused__; int __syscall_nr;} fork_args;",
	"fork_data": "typedef struct {event_info_t event_info;} fork_data;",
	"fork_split": "",
	"getpgrp_args": "typedef struct {u64 __unused__; int __syscall_nr;} getpgrp_args;",
	"getpgrp_data": "typedef struct {event_info_t event_info;} getpgrp_data;",
	"getpgrp_split": "",
	"timer_create_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; struct sigevent * timer_event_spec; timer_t * created_timer_id;} timer_create_args;",
	"timer_create_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 timer_event_spec; u64 created_timer_id;} timer_create_data;",
	"timer_create_split": "which_clock:integer timer_event_spec:pointer created_timer_id:pointer",
	"listxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * list; size_t size;} listxattr_args;",
	"listxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char list[64]; u64 size;} listxattr_data;",
	"listxattr_split": "pathname:string list:string size:integer",
	"kexec_file_load_args": "typedef struct {u64 __unused__; int __syscall_nr; long kernel_fd; long initrd_fd; unsigned long cmdline_len; char * cmdline_ptr; unsigned long flags;} kexec_file_load_args;",
	"kexec_file_load_data": "typedef struct {event_info_t event_info; u64 kernel_fd; u64 initrd_fd; u64 cmdline_len; char cmdline_ptr[64]; u64 flags;} kexec_file_load_data;",
	"kexec_file_load_split": "kernel_fd:integer initrd_fd:integer cmdline_len:integer cmdline_ptr:string flags:integer",
	"msgsnd_args": "typedef struct {u64 __unused__; int __syscall_nr; long msqid; struct msgbuf * msgp; size_t msgsz; long msgflg;} msgsnd_args;",
	"msgsnd_data": "typedef struct {event_info_t event_info; u64 msqid; u64 msgp; u64 msgsz; u64 msgflg;} msgsnd_data;",
	"msgsnd_split": "msqid:integer msgp:pointer msgsz:integer msgflg:integer",
	"unlinkat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * pathname; long flag;} unlinkat_args;",
	"unlinkat_data": "typedef struct {event_info_t event_info; u64 dfd; char pathname[64]; u64 flag; u64 fd;} unlinkat_data;",
	"unlinkat_split": "dfd:integer pathname:string flag:integer",
	"gettid_args": "typedef struct {u64 __unused__; int __syscall_nr;} gettid_args;",
	"gettid_data": "typedef struct {event_info_t event_info;} gettid_data;",
	"gettid_split": "",
	"execve_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; char ** argv; char ** envp;} execve_args;",
	"execve_data": "typedef struct {event_info_t event_info; char filename[64]; char argv1[16]; char argv2[16]; char argv3[16]; u64 envp;} execve_data;",
	"execve_split": "filename:string argv1:string argv2:string argv3:string envp:pointer",
	"clone_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long clone_flags; unsigned long newsp; long * parent_tidptr; long * child_tidptr; unsigned long tls;} clone_args;",
	"clone_data": "typedef struct {event_info_t event_info; u64 clone_flags; u64 newsp; u64 parent_tidptr; u64 child_tidptr; u64 tls;} clone_data;",
	"clone_split": "clone_flags:integer newsp:integer parent_tidptr:pointer child_tidptr:pointer tls:integer",
	"rseq_args": "typedef struct {u64 __unused__; int __syscall_nr; struct rseq * rseq; u32 rseq_len; long flags; u32 sig;} rseq_args;",
	"rseq_data": "typedef struct {event_info_t event_info; u64 rseq; u64 rseq_len; u64 flags; u64 sig;} rseq_data;",
	"rseq_split": "rseq:pointer rseq_len:integer flags:integer sig:integer",
	"rt_sigreturn_args": "typedef struct {u64 __unused__; int __syscall_nr;} rt_sigreturn_args;",
	"rt_sigreturn_data": "typedef struct {event_info_t event_info;} rt_sigreturn_data;",
	"rt_sigreturn_split": "",
	"finit_module_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * uargs; long flags;} finit_module_args;",
	"finit_module_data": "typedef struct {event_info_t event_info; u64 fd; char uargs[64]; u64 flags;} finit_module_data;",
	"finit_module_split": "fd:integer uargs:string flags:integer",
	"pkey_free_args": "typedef struct {u64 __unused__; int __syscall_nr; long pkey;} pkey_free_args;",
	"pkey_free_data": "typedef struct {event_info_t event_info; u64 pkey;} pkey_free_data;",
	"pkey_free_split": "pkey:integer",
	"brk_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long brk;} brk_args;",
	"brk_data": "typedef struct {event_info_t event_info; u64 brk;} brk_data;",
	"brk_split": "brk:integer",
	"setresuid_args": "typedef struct {u64 __unused__; int __syscall_nr; uid_t ruid; uid_t euid; uid_t suid;} setresuid_args;",
	"setresuid_data": "typedef struct {event_info_t event_info; u64 ruid; u64 euid; u64 suid;} setresuid_data;",
	"setresuid_split": "ruid:integer euid:integer suid:integer",
	"rt_sigsuspend_args": "typedef struct {u64 __unused__; int __syscall_nr; sigset_t * unewset; size_t sigsetsize;} rt_sigsuspend_args;",
	"rt_sigsuspend_data": "typedef struct {event_info_t event_info; u64 unewset; u64 sigsetsize;} rt_sigsuspend_data;",
	"rt_sigsuspend_split": "unewset:pointer sigsetsize:integer",
	"lchown_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; uid_t user; gid_t group;} lchown_args;",
	"lchown_data": "typedef struct {event_info_t event_info; char filename[64]; u64 user; u64 group;} lchown_data;",
	"lchown_split": "filename:string user:integer group:integer",
	"fallocate_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long mode; loff_t offset; loff_t len;} fallocate_args;",
	"fallocate_data": "typedef struct {event_info_t event_info; u64 fd; u64 mode; u64 offset; u64 len;} fallocate_data;",
	"fallocate_split": "fd:integer mode:integer offset:integer len:integer",
	"ioprio_set_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; long who; long ioprio;} ioprio_set_args;",
	"ioprio_set_data": "typedef struct {event_info_t event_info; u64 which; u64 who; u64 ioprio;} ioprio_set_data;",
	"ioprio_set_split": "which:integer who:integer ioprio:integer",
	"mknodat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; umode_t mode; u64 dev;} mknodat_args;",
	"mknodat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 mode; u64 dev;} mknodat_data;",
	"mknodat_split": "dfd:integer filename:string mode:integer dev:integer",
	"pipe_args": "typedef struct {u64 __unused__; int __syscall_nr; long * fildes;} pipe_args;",
	"pipe_data": "typedef struct {event_info_t event_info; u64 fildes; u64 readfd; u64 writefd;} pipe_data;",
	"pipe_split": "fildes:pointer readfd:integer writefd:integer",
	"reboot_args": "typedef struct {u64 __unused__; int __syscall_nr; long magic1; long magic2; u64 cmd; void * arg;} reboot_args;",
	"reboot_data": "typedef struct {event_info_t event_info; u64 magic1; u64 magic2; u64 cmd; u64 arg;} reboot_data;",
	"reboot_split": "magic1:integer magic2:integer cmd:integer arg:pointer",
	"eventfd2_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 count; long flags;} eventfd2_args;",
	"eventfd2_data": "typedef struct {event_info_t event_info; u64 count; u64 flags;} eventfd2_data;",
	"eventfd2_split": "count:integer flags:integer",
	"unlink_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname;} unlink_args;",
	"unlink_data": "typedef struct {event_info_t event_info; char pathname[64];} unlink_data;",
	"unlink_split": "pathname:string",
	"recvmmsg_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct mmsghdr * mmsg; u64 vlen; u64 flags; struct timespec * timeout;} recvmmsg_args;",
	"recvmmsg_data": "typedef struct {event_info_t event_info; u64 fd; u64 mmsg; u64 vlen; u64 flags; u64 timeout;} recvmmsg_data;",
	"recvmmsg_split": "fd:integer mmsg:pointer vlen:integer flags:integer timeout:pointer",
	"msync_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len; long flags;} msync_args;",
	"msync_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 flags;} msync_data;",
	"msync_split": "start:integer len:integer flags:integer",
	"access_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; long mode;} access_args;",
	"access_data": "typedef struct {event_info_t event_info; char filename[64]; u64 mode;} access_data;",
	"access_split": "filename:string mode:integer",
	"signalfd4_args": "typedef struct {u64 __unused__; int __syscall_nr; long ufd; sigset_t * user_mask; size_t sizemask; long flags;} signalfd4_args;",
	"signalfd4_data": "typedef struct {event_info_t event_info; u64 ufd; u64 user_mask; u64 sizemask; u64 flags;} signalfd4_data;",
	"signalfd4_split": "ufd:integer user_mask:pointer sizemask:integer flags:integer",
	"mbind_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; unsigned long len; unsigned long mode; unsigned long * nmask; unsigned long maxnode; u64 flags;} mbind_args;",
	"mbind_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 mode; u64 nmask; u64 maxnode; u64 flags;} mbind_data;",
	"mbind_split": "start:integer len:integer mode:integer nmask:pointer maxnode:integer flags:integer",
	"mknod_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; umode_t mode; unsigned dev;} mknod_args;",
	"mknod_data": "typedef struct {event_info_t event_info; char filename[64]; u64 mode; u64 dev;} mknod_data;",
	"mknod_split": "filename:string mode:integer dev:integer",
	"munlock_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len;} munlock_args;",
	"munlock_data": "typedef struct {event_info_t event_info; u64 start; u64 len;} munlock_data;",
	"munlock_split": "start:integer len:integer",
	"getpgid_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid;} getpgid_args;",
	"getpgid_data": "typedef struct {event_info_t event_info; u64 pid;} getpgid_data;",
	"getpgid_split": "pid:integer",
	"getresuid_args": "typedef struct {u64 __unused__; int __syscall_nr; uid_t * ruidp; uid_t * euidp; uid_t * suidp;} getresuid_args;",
	"getresuid_data": "typedef struct {event_info_t event_info; u64 ruidp; u64 euidp; u64 suidp;} getresuid_data;",
	"getresuid_split": "ruidp:pointer euidp:pointer suidp:pointer",
	"fchownat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; uid_t user; gid_t group; long flag;} fchownat_args;",
	"fchownat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 user; u64 group; u64 flag;} fchownat_data;",
	"fchownat_split": "dfd:integer filename:string user:integer group:integer flag:integer",
	"perf_event_open_args": "typedef struct {u64 __unused__; int __syscall_nr; struct perf_event_attr * attr_uptr; pid_t pid; long cpu; long group_fd; unsigned long flags;} perf_event_open_args;",
	"perf_event_open_data": "typedef struct {event_info_t event_info; u64 attr_uptr; u64 pid; u64 cpu; u64 group_fd; u64 flags;} perf_event_open_data;",
	"perf_event_open_split": "attr_uptr:pointer pid:integer cpu:integer group_fd:integer flags:integer",
	"newuname_args": "typedef struct {u64 __unused__; int __syscall_nr; struct new_utsname * name;} newuname_args;",
	"newuname_data": "typedef struct {event_info_t event_info; u64 name;} newuname_data;",
	"newuname_split": "name:pointer",
	"timerfd_create_args": "typedef struct {u64 __unused__; int __syscall_nr; long clockid; long flags;} timerfd_create_args;",
	"timerfd_create_data": "typedef struct {event_info_t event_info; u64 clockid; u64 flags;} timerfd_create_data;",
	"timerfd_create_split": "clockid:integer flags:integer",
	"shmdt_args": "typedef struct {u64 __unused__; int __syscall_nr; char * shmaddr;} shmdt_args;",
	"shmdt_data": "typedef struct {event_info_t event_info; char shmaddr[64];} shmdt_data;",
	"shmdt_split": "shmaddr:string",
	"rmdir_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname;} rmdir_args;",
	"rmdir_data": "typedef struct {event_info_t event_info; char pathname[64];} rmdir_data;",
	"rmdir_split": "pathname:string",
	"open_by_handle_at_args": "typedef struct {u64 __unused__; int __syscall_nr; long mountdirfd; struct file_handle * handle; long flags;} open_by_handle_at_args;",
	"open_by_handle_at_data": "typedef struct {event_info_t event_info; u64 mountdirfd; u64 handle; u64 flags;} open_by_handle_at_data;",
	"open_by_handle_at_split": "mountdirfd:integer handle:pointer flags:integer",
	"socketpair_args": "typedef struct {u64 __unused__; int __syscall_nr; long family; long type; long protocol; long * usockvec;} socketpair_args;",
	"socketpair_data": "typedef struct {event_info_t event_info; u64 family; u64 type; u64 protocol; u64 usockvec;} socketpair_data;",
	"socketpair_split": "family:integer type:integer protocol:integer usockvec:pointer",
	"setresgid_args": "typedef struct {u64 __unused__; int __syscall_nr; gid_t rgid; gid_t egid; gid_t sgid;} setresgid_args;",
	"setresgid_data": "typedef struct {event_info_t event_info; u64 rgid; u64 egid; u64 sgid;} setresgid_data;",
	"setresgid_split": "rgid:integer egid:integer sgid:integer",
	"getitimer_args": "typedef struct {u64 __unused__; int __syscall_nr; long which; struct itimerval * value;} getitimer_args;",
	"getitimer_data": "typedef struct {event_info_t event_info; u64 which; u64 value;} getitimer_data;",
	"getitimer_split": "which:integer value:pointer",
	"mq_getsetattr_args": "typedef struct {u64 __unused__; int __syscall_nr; mqd_t mqdes; struct mq_attr * u_mqstat; struct mq_attr * u_omqstat;} mq_getsetattr_args;",
	"mq_getsetattr_data": "typedef struct {event_info_t event_info; u64 mqdes; u64 u_mqstat; u64 u_omqstat;} mq_getsetattr_data;",
	"mq_getsetattr_split": "mqdes:integer u_mqstat:pointer u_omqstat:pointer",
	"chdir_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename;} chdir_args;",
	"chdir_data": "typedef struct {event_info_t event_info; char filename[64];} chdir_data;",
	"chdir_split": "filename:string",
	"fchdir_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd;} fchdir_args;",
	"fchdir_data": "typedef struct {event_info_t event_info; u64 fd;} fchdir_data;",
	"fchdir_split": "fd:integer",
	"mmap_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long addr; unsigned long len; unsigned long prot; unsigned long flags; unsigned long fd; unsigned long off;} mmap_args;",
	"mmap_data": "typedef struct {event_info_t event_info; u64 addr; u64 len; u64 prot; u64 flags; u64 fd; u64 off;} mmap_data;",
	"mmap_split": "addr:integer len:integer prot:integer flags:integer fd:integer off:integer",
	"lookup_dcookie_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 cookie64; char * buf; size_t len;} lookup_dcookie_args;",
	"lookup_dcookie_data": "typedef struct {event_info_t event_info; u64 cookie64; char buf[64]; u64 len;} lookup_dcookie_data;",
	"lookup_dcookie_split": "cookie64:integer buf:string len:integer",
	"syslog_args": "typedef struct {u64 __unused__; int __syscall_nr; long type; char * buf; long len;} syslog_args;",
	"syslog_data": "typedef struct {event_info_t event_info; u64 type; char buf[64]; u64 len;} syslog_data;",
	"syslog_split": "type:integer buf:string len:integer",
	"accept_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * upeer_sockaddr; long * upeer_addrlen;} accept_args;",
	"accept_data": "typedef struct {event_info_t event_info; u64 fd; u64 upeer_sockaddr; u64 upeer_addrlen;} accept_data;",
	"accept_split": "fd:integer upeer_sockaddr:pointer upeer_addrlen:pointer",
	"set_mempolicy_args": "typedef struct {u64 __unused__; int __syscall_nr; long mode; unsigned long * nmask; unsigned long maxnode;} set_mempolicy_args;",
	"set_mempolicy_data": "typedef struct {event_info_t event_info; u64 mode; u64 nmask; u64 maxnode;} set_mempolicy_data;",
	"set_mempolicy_split": "mode:integer nmask:pointer maxnode:integer",
	"mkdirat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * pathname; umode_t mode;} mkdirat_args;",
	"mkdirat_data": "typedef struct {event_info_t event_info; u64 dfd; char pathname[64]; u64 mode; u64 fd;} mkdirat_data;",
	"mkdirat_split": "dfd:integer pathname:string mode:integer",
	"fchmodat_args": "typedef struct {u64 __unused__; int __syscall_nr; long dfd; char * filename; umode_t mode;} fchmodat_args;",
	"fchmodat_data": "typedef struct {event_info_t event_info; u64 dfd; char filename[64]; u64 mode; u64 fd;} fchmodat_data;",
	"fchmodat_split": "dfd:integer filename:string mode:integer",
	"mkdir_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; umode_t mode;} mkdir_args;",
	"mkdir_data": "typedef struct {event_info_t event_info; char pathname[64]; u64 mode;} mkdir_data;",
	"mkdir_split": "pathname:string mode:integer",
	"mount_args": "typedef struct {u64 __unused__; int __syscall_nr; char * dev_name; char * dir_name; char * type; unsigned long flags; void * data;} mount_args;",
	"mount_data": "typedef struct {event_info_t event_info; char dev_name[64]; char dir_name[64]; char type[64]; u64 flags; u64 data;} mount_data;",
	"mount_split": "dev_name:string dir_name:string type:string flags:integer data:pointer",
	"sched_setaffinity_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; u64 len; unsigned long * user_mask_ptr;} sched_setaffinity_args;",
	"sched_setaffinity_data": "typedef struct {event_info_t event_info; u64 pid; u64 len; u64 user_mask_ptr;} sched_setaffinity_data;",
	"sched_setaffinity_split": "pid:integer len:integer user_mask_ptr:pointer",
	"mq_timedreceive_args": "typedef struct {u64 __unused__; int __syscall_nr; mqd_t mqdes; char * u_msg_ptr; size_t msg_len; u64 * u_msg_prio; struct timespec * u_abs_timeout;} mq_timedreceive_args;",
	"mq_timedreceive_data": "typedef struct {event_info_t event_info; u64 mqdes; char u_msg_ptr[64]; u64 msg_len; u64 u_msg_prio; u64 u_abs_timeout;} mq_timedreceive_data;",
	"mq_timedreceive_split": "mqdes:integer u_msg_ptr:string msg_len:integer u_msg_prio:pointer u_abs_timeout:pointer",
	"getsid_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid;} getsid_args;",
	"getsid_data": "typedef struct {event_info_t event_info; u64 pid;} getsid_data;",
	"getsid_split": "pid:integer",
	"unshare_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long unshare_flags;} unshare_args;",
	"unshare_data": "typedef struct {event_info_t event_info; u64 unshare_flags;} unshare_data;",
	"unshare_split": "unshare_flags:integer",
	"capget_args": "typedef struct {u64 __unused__; int __syscall_nr; cap_user_header_t header; cap_user_data_t dataptr;} capget_args;",
	"capget_data": "typedef struct {event_info_t event_info; u64 header; u64 dataptr;} capget_data;",
	"capget_split": "header:integer dataptr:integer",
	"linkat_args": "typedef struct {u64 __unused__; int __syscall_nr; long olddfd; char * oldname; long newdfd; char * newname; long flags;} linkat_args;",
	"linkat_data": "typedef struct {event_info_t event_info; u64 olddfd; char oldname[64]; u64 newdfd; char newname[64]; u64 flags;} linkat_data;",
	"linkat_split": "olddfd:integer oldname:string newdfd:integer newname:string flags:integer",
	"alarm_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 seconds;} alarm_args;",
	"alarm_data": "typedef struct {event_info_t event_info; u64 seconds;} alarm_data;",
	"alarm_split": "seconds:integer",
	"io_setup_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned nr_events; aio_context_t * ctxp;} io_setup_args;",
	"io_setup_data": "typedef struct {event_info_t event_info; u64 nr_events; u64 ctxp;} io_setup_data;",
	"io_setup_split": "nr_events:integer ctxp:pointer",
	"mq_timedsend_args": "typedef struct {u64 __unused__; int __syscall_nr; mqd_t mqdes; char * u_msg_ptr; size_t msg_len; u64 msg_prio; struct timespec * u_abs_timeout;} mq_timedsend_args;",
	"mq_timedsend_data": "typedef struct {event_info_t event_info; u64 mqdes; char u_msg_ptr[64]; u64 msg_len; u64 msg_prio; u64 u_abs_timeout;} mq_timedsend_data;",
	"mq_timedsend_split": "mqdes:integer u_msg_ptr:string msg_len:integer msg_prio:integer u_abs_timeout:pointer",
	"getcwd_args": "typedef struct {u64 __unused__; int __syscall_nr; char * buf; unsigned long size;} getcwd_args;",
	"getcwd_data": "typedef struct {event_info_t event_info; char buf[64]; u64 size;} getcwd_data;",
	"getcwd_split": "buf:string size:integer",
	"epoll_wait_args": "typedef struct {u64 __unused__; int __syscall_nr; long epfd; struct epoll_event * events; long maxevents; long timeout;} epoll_wait_args;",
	"epoll_wait_data": "typedef struct {event_info_t event_info; u64 epfd; u64 events; u64 maxevents; u64 timeout;} epoll_wait_data;",
	"epoll_wait_split": "epfd:integer events:pointer maxevents:integer timeout:integer",
	"ioperm_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long from; unsigned long num; long turn_on;} ioperm_args;",
	"ioperm_data": "typedef struct {event_info_t event_info; u64 from; u64 num; u64 turn_on;} ioperm_data;",
	"ioperm_split": "from:integer num:integer turn_on:integer",
	"flock_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; u64 cmd;} flock_args;",
	"flock_data": "typedef struct {event_info_t event_info; u64 fd; u64 cmd;} flock_data;",
	"flock_split": "fd:integer cmd:integer",
	"epoll_ctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long epfd; long op; long fd; struct epoll_event * event;} epoll_ctl_args;",
	"epoll_ctl_data": "typedef struct {event_info_t event_info; u64 epfd; u64 op; u64 fd; u64 event;} epoll_ctl_data;",
	"epoll_ctl_split": "epfd:integer op:integer fd:integer event:pointer",
	"clock_gettime_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; struct timespec * tp;} clock_gettime_args;",
	"clock_gettime_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 tp;} clock_gettime_data;",
	"clock_gettime_split": "which_clock:integer tp:pointer",
	"semctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long semid; long semnum; long cmd; unsigned long arg;} semctl_args;",
	"semctl_data": "typedef struct {event_info_t event_info; u64 semid; u64 semnum; u64 cmd; u64 arg;} semctl_data;",
	"semctl_split": "semid:integer semnum:integer cmd:integer arg:integer",
	"rt_sigprocmask_args": "typedef struct {u64 __unused__; int __syscall_nr; long how; sigset_t * nset; sigset_t * oset; size_t sigsetsize;} rt_sigprocmask_args;",
	"rt_sigprocmask_data": "typedef struct {event_info_t event_info; u64 how; u64 nset; u64 oset; u64 sigsetsize;} rt_sigprocmask_data;",
	"rt_sigprocmask_split": "how:integer nset:pointer oset:pointer sigsetsize:integer",
	"personality_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 personality;} personality_args;",
	"personality_data": "typedef struct {event_info_t event_info; u64 personality;} personality_data;",
	"personality_split": "personality:integer",
	"llistxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; char * pathname; char * list; size_t size;} llistxattr_args;",
	"llistxattr_data": "typedef struct {event_info_t event_info; char pathname[64]; char list[64]; u64 size;} llistxattr_data;",
	"llistxattr_split": "pathname:string list:string size:integer",
	"ptrace_args": "typedef struct {u64 __unused__; int __syscall_nr; long request; long pid; unsigned long addr; unsigned long data;} ptrace_args;",
	"ptrace_data": "typedef struct {event_info_t event_info; u64 request; u64 pid; u64 addr; u64 data;} ptrace_data;",
	"ptrace_split": "request:integer pid:integer addr:integer data:integer",
	"setdomainname_args": "typedef struct {u64 __unused__; int __syscall_nr; char * name; long len;} setdomainname_args;",
	"setdomainname_data": "typedef struct {event_info_t event_info; char name[64]; u64 len;} setdomainname_data;",
	"setdomainname_split": "name:string len:integer",
	"process_vm_readv_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct iovec * lvec; unsigned long liovcnt; struct iovec * rvec; unsigned long riovcnt; unsigned long flags;} process_vm_readv_args;",
	"process_vm_readv_data": "typedef struct {event_info_t event_info; u64 pid; u64 lvec; u64 liovcnt; u64 rvec; u64 riovcnt; u64 flags;} process_vm_readv_data;",
	"process_vm_readv_split": "pid:integer lvec:pointer liovcnt:integer rvec:pointer riovcnt:integer flags:integer",
	"vhangup_args": "typedef struct {u64 __unused__; int __syscall_nr;} vhangup_args;",
	"vhangup_data": "typedef struct {event_info_t event_info;} vhangup_data;",
	"vhangup_split": "",
	"arch_prctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long option; unsigned long arg2;} arch_prctl_args;",
	"arch_prctl_data": "typedef struct {event_info_t event_info; u64 option; u64 arg2;} arch_prctl_data;",
	"arch_prctl_split": "option:integer arg2:integer",
	"recvmsg_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct user_msghdr * msg; u64 flags;} recvmsg_args;",
	"recvmsg_data": "typedef struct {event_info_t event_info; u64 fd; u64 msg; u64 flags;} recvmsg_data;",
	"recvmsg_split": "fd:integer msg:pointer flags:integer",
	"nanosleep_args": "typedef struct {u64 __unused__; int __syscall_nr; struct timespec * rqtp; struct timespec * rmtp;} nanosleep_args;",
	"nanosleep_data": "typedef struct {event_info_t event_info; u64 rqtp; u64 rmtp;} nanosleep_data;",
	"nanosleep_split": "rqtp:pointer rmtp:pointer",
	"fcntl_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; u64 cmd; unsigned long arg;} fcntl_args;",
	"fcntl_data": "typedef struct {event_info_t event_info; u64 fd; u64 cmd; u64 arg;} fcntl_data;",
	"fcntl_split": "fd:integer cmd:integer arg:integer",
	"io_cancel_args": "typedef struct {u64 __unused__; int __syscall_nr; aio_context_t ctx_id; struct iocb * iocb; struct io_event * result;} io_cancel_args;",
	"io_cancel_data": "typedef struct {event_info_t event_info; u64 ctx_id; u64 iocb; u64 result;} io_cancel_data;",
	"io_cancel_split": "ctx_id:integer iocb:pointer result:pointer",
	"getdents64_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; struct linux_dirent64 * dirent; u64 count;} getdents64_args;",
	"getdents64_data": "typedef struct {event_info_t event_info; u64 fd; u64 dirent; u64 count;} getdents64_data;",
	"getdents64_split": "fd:integer dirent:pointer count:integer",
	"inotify_rm_watch_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; __s32 wd;} inotify_rm_watch_args;",
	"inotify_rm_watch_data": "typedef struct {event_info_t event_info; u64 fd; u64 wd;} inotify_rm_watch_data;",
	"inotify_rm_watch_split": "fd:integer wd:integer",
	"flistxattr_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; char * list; size_t size;} flistxattr_args;",
	"flistxattr_data": "typedef struct {event_info_t event_info; u64 fd; char list[64]; u64 size;} flistxattr_data;",
	"flistxattr_split": "fd:integer list:string size:integer",
	"read_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; char * buf; size_t count;} read_args;",
	"read_data": "typedef struct {event_info_t event_info; u64 fd; char buf[64]; u64 count;} read_data;",
	"read_split": "fd:integer buf:string count:integer",
	"clock_nanosleep_args": "typedef struct {u64 __unused__; int __syscall_nr; clockid_t which_clock; long flags; struct timespec * rqtp; struct timespec * rmtp;} clock_nanosleep_args;",
	"clock_nanosleep_data": "typedef struct {event_info_t event_info; u64 which_clock; u64 flags; u64 rqtp; u64 rmtp;} clock_nanosleep_data;",
	"clock_nanosleep_split": "which_clock:integer flags:integer rqtp:pointer rmtp:pointer",
	"sysctl_args": "typedef struct {u64 __unused__; int __syscall_nr; struct __sysctl_args * args;} sysctl_args;",
	"sysctl_data": "typedef struct {event_info_t event_info; u64 args;} sysctl_data;",
	"sysctl_split": "args:pointer",
	"chown_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; uid_t user; gid_t group;} chown_args;",
	"chown_data": "typedef struct {event_info_t event_info; char filename[64]; u64 user; u64 group;} chown_data;",
	"chown_split": "filename:string user:integer group:integer",
	"setgroups_args": "typedef struct {u64 __unused__; int __syscall_nr; long gidsetsize; gid_t * grouplist;} setgroups_args;",
	"setgroups_data": "typedef struct {event_info_t event_info; u64 gidsetsize; u64 grouplist;} setgroups_data;",
	"setgroups_split": "gidsetsize:integer grouplist:pointer",
	"newfstat_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; struct stat * statbuf;} newfstat_args;",
	"newfstat_data": "typedef struct {event_info_t event_info; u64 fd; u64 statbuf;} newfstat_data;",
	"newfstat_split": "fd:integer statbuf:pointer",
	"madvise_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len_in; long behavior;} madvise_args;",
	"madvise_data": "typedef struct {event_info_t event_info; u64 start; u64 len_in; u64 behavior;} madvise_data;",
	"madvise_split": "start:integer len_in:integer behavior:integer",
	"fchown_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; uid_t user; gid_t group;} fchown_args;",
	"fchown_data": "typedef struct {event_info_t event_info; u64 fd; u64 user; u64 group;} fchown_data;",
	"fchown_split": "fd:integer user:integer group:integer",
	"inotify_init1_args": "typedef struct {u64 __unused__; int __syscall_nr; long flags;} inotify_init1_args;",
	"inotify_init1_data": "typedef struct {event_info_t event_info; u64 flags;} inotify_init1_data;",
	"inotify_init1_split": "flags:integer",
	"add_key_args": "typedef struct {u64 __unused__; int __syscall_nr; char * _type; char * _description; void * _payload; size_t plen; key_serial_t ringid;} add_key_args;",
	"add_key_data": "typedef struct {event_info_t event_info; char _type[64]; char _description[64]; u64 _payload; u64 plen; u64 ringid;} add_key_data;",
	"add_key_split": "_type:string _description:string _payload:pointer plen:integer ringid:integer",
	"memfd_create_args": "typedef struct {u64 __unused__; int __syscall_nr; char * uname; u64 flags;} memfd_create_args;",
	"memfd_create_data": "typedef struct {event_info_t event_info; char uname[64]; u64 flags;} memfd_create_data;",
	"memfd_create_split": "uname:string flags:integer",
	"mq_open_args": "typedef struct {u64 __unused__; int __syscall_nr; char * u_name; long oflag; umode_t mode; struct mq_attr * u_attr;} mq_open_args;",
	"mq_open_data": "typedef struct {event_info_t event_info; char u_name[64]; u64 oflag; u64 mode; u64 u_attr;} mq_open_data;",
	"mq_open_split": "u_name:string oflag:integer mode:integer u_attr:pointer",
	"init_module_args": "typedef struct {u64 __unused__; int __syscall_nr; void * umod; unsigned long len; char * uargs;} init_module_args;",
	"init_module_data": "typedef struct {event_info_t event_info; u64 umod; u64 len; char uargs[64];} init_module_data;",
	"init_module_split": "umod:pointer len:integer uargs:string",
	"sched_setattr_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct sched_attr * uattr; u64 flags;} sched_setattr_args;",
	"sched_setattr_data": "typedef struct {event_info_t event_info; u64 pid; u64 uattr; u64 flags;} sched_setattr_data;",
	"sched_setattr_split": "pid:integer uattr:pointer flags:integer",
	"restart_syscall_args": "typedef struct {u64 __unused__; int __syscall_nr;} restart_syscall_args;",
	"restart_syscall_data": "typedef struct {event_info_t event_info;} restart_syscall_data;",
	"restart_syscall_split": "",
	"ioctl_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; u64 cmd; unsigned long arg;} ioctl_args;",
	"ioctl_data": "typedef struct {event_info_t event_info; u64 fd; u64 cmd; u64 arg;} ioctl_data;",
	"ioctl_split": "fd:integer cmd:integer arg:integer",
	"request_key_args": "typedef struct {u64 __unused__; int __syscall_nr; char * _type; char * _description; char * _callout_info; key_serial_t destringid;} request_key_args;",
	"request_key_data": "typedef struct {event_info_t event_info; char _type[64]; char _description[64]; char _callout_info[64]; u64 destringid;} request_key_data;",
	"request_key_split": "_type:string _description:string _callout_info:string destringid:integer",
	"inotify_init_args": "typedef struct {u64 __unused__; int __syscall_nr;} inotify_init_args;",
	"inotify_init_data": "typedef struct {event_info_t event_info;} inotify_init_data;",
	"inotify_init_split": "",
	"umount_args": "typedef struct {u64 __unused__; int __syscall_nr; char * name; long flags;} umount_args;",
	"umount_data": "typedef struct {event_info_t event_info; char name[64]; u64 flags;} umount_data;",
	"umount_split": "name:string flags:integer",
	"preadv_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen; unsigned long pos_l; unsigned long pos_h;} preadv_args;",
	"preadv_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen; u64 pos_l; u64 pos_h;} preadv_data;",
	"preadv_split": "fd:integer vec:pointer vlen:integer pos_l:integer pos_h:integer",
	"vmsplice_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct iovec * uiov; unsigned long nr_segs; u64 flags;} vmsplice_args;",
	"vmsplice_data": "typedef struct {event_info_t event_info; u64 fd; u64 uiov; u64 nr_segs; u64 flags;} vmsplice_data;",
	"vmsplice_split": "fd:integer uiov:pointer nr_segs:integer flags:integer",
	"sysinfo_args": "typedef struct {u64 __unused__; int __syscall_nr; struct sysinfo * info;} sysinfo_args;",
	"sysinfo_data": "typedef struct {event_info_t event_info; u64 info;} sysinfo_data;",
	"sysinfo_split": "info:pointer",
	"timer_settime_args": "typedef struct {u64 __unused__; int __syscall_nr; timer_t timer_id; long flags; struct itimerspec * new_setting; struct itimerspec * old_setting;} timer_settime_args;",
	"timer_settime_data": "typedef struct {event_info_t event_info; u64 timer_id; u64 flags; u64 new_setting; u64 old_setting;} timer_settime_data;",
	"timer_settime_split": "timer_id:integer flags:integer new_setting:pointer old_setting:pointer",
	"quotactl_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 cmd; char * special; qid_t id; void * addr;} quotactl_args;",
	"quotactl_data": "typedef struct {event_info_t event_info; u64 cmd; char special[64]; u64 id; u64 addr;} quotactl_data;",
	"quotactl_split": "cmd:integer special:string id:integer addr:pointer",
	"getgroups_args": "typedef struct {u64 __unused__; int __syscall_nr; long gidsetsize; gid_t * grouplist;} getgroups_args;",
	"getgroups_data": "typedef struct {event_info_t event_info; u64 gidsetsize; u64 grouplist;} getgroups_data;",
	"getgroups_split": "gidsetsize:integer grouplist:pointer",
	"fchmod_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; umode_t mode;} fchmod_args;",
	"fchmod_data": "typedef struct {event_info_t event_info; u64 fd; u64 mode;} fchmod_data;",
	"fchmod_split": "fd:integer mode:integer",
	"fadvise64_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; loff_t offset; size_t len; long advice;} fadvise64_args;",
	"fadvise64_data": "typedef struct {event_info_t event_info; u64 fd; u64 offset; u64 len; u64 advice;} fadvise64_data;",
	"fadvise64_split": "fd:integer offset:integer len:integer advice:integer",
	"io_submit_args": "typedef struct {u64 __unused__; int __syscall_nr; aio_context_t ctx_id; long nr; struct iocb * * iocbpp;} io_submit_args;",
	"io_submit_data": "typedef struct {event_info_t event_info; u64 ctx_id; u64 nr; u64 iocbpp;} io_submit_data;",
	"io_submit_split": "ctx_id:integer nr:integer iocbpp:pointer",
	"chmod_args": "typedef struct {u64 __unused__; int __syscall_nr; char * filename; umode_t mode;} chmod_args;",
	"chmod_data": "typedef struct {event_info_t event_info; char filename[64]; u64 mode;} chmod_data;",
	"chmod_split": "filename:string mode:integer",
	"pwrite64_args": "typedef struct {u64 __unused__; int __syscall_nr; u64 fd; char * buf; size_t count; loff_t pos;} pwrite64_args;",
	"pwrite64_data": "typedef struct {event_info_t event_info; u64 fd; char buf[64]; u64 count; u64 pos;} pwrite64_data;",
	"pwrite64_split": "fd:integer buf:string count:integer pos:integer",
	"settimeofday_args": "typedef struct {u64 __unused__; int __syscall_nr; struct timeval * tv; struct timezone * tz;} settimeofday_args;",
	"settimeofday_data": "typedef struct {event_info_t event_info; u64 tv; u64 tz;} settimeofday_data;",
	"settimeofday_split": "tv:pointer tz:pointer",
	"sched_getparam_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct sched_param * param;} sched_getparam_args;",
	"sched_getparam_data": "typedef struct {event_info_t event_info; u64 pid; u64 param;} sched_getparam_data;",
	"sched_getparam_split": "pid:integer param:pointer",
	"sched_getaffinity_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; u64 len; unsigned long * user_mask_ptr;} sched_getaffinity_args;",
	"sched_getaffinity_data": "typedef struct {event_info_t event_info; u64 pid; u64 len; u64 user_mask_ptr;} sched_getaffinity_data;",
	"sched_getaffinity_split": "pid:integer len:integer user_mask_ptr:pointer",
	"msgctl_args": "typedef struct {u64 __unused__; int __syscall_nr; long msqid; long cmd; struct msqid_ds * buf;} msgctl_args;",
	"msgctl_data": "typedef struct {event_info_t event_info; u64 msqid; u64 cmd; u64 buf;} msgctl_data;",
	"msgctl_split": "msqid:integer cmd:integer buf:pointer",
	"timerfd_settime_args": "typedef struct {u64 __unused__; int __syscall_nr; long ufd; long flags; struct itimerspec * utmr; struct itimerspec * otmr;} timerfd_settime_args;",
	"timerfd_settime_data": "typedef struct {event_info_t event_info; u64 ufd; u64 flags; u64 utmr; u64 otmr;} timerfd_settime_data;",
	"timerfd_settime_split": "ufd:integer flags:integer utmr:pointer otmr:pointer",
	"setsid_args": "typedef struct {u64 __unused__; int __syscall_nr;} setsid_args;",
	"setsid_data": "typedef struct {event_info_t event_info;} setsid_data;",
	"setsid_split": "",
	"connect_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; struct sockaddr * uservaddr; long addrlen;} connect_args;",
	"connect_data": "typedef struct {event_info_t event_info; u64 fd; u64 uservaddr; u64 addrlen;} connect_data;",
	"connect_split": "fd:integer uservaddr:pointer addrlen:integer",
	"sendto_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; void * buff; size_t len; u64 flags; struct sockaddr * addr; long addr_len;} sendto_args;",
	"sendto_data": "typedef struct {event_info_t event_info; u64 fd; u64 buff; u64 len; u64 flags; u64 addr; u64 addr_len;} sendto_data;",
	"sendto_split": "fd:integer buff:pointer len:integer flags:integer addr:pointer addr_len:integer",
	"bpf_args": "typedef struct {u64 __unused__; int __syscall_nr; long cmd; union bpf_attr * uattr; u64 size;} bpf_args;",
	"bpf_data": "typedef struct {event_info_t event_info; u64 cmd; u64 uattr; u64 size;} bpf_data;",
	"bpf_split": "cmd:integer uattr:pointer size:integer",
	"kcmp_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid1; pid_t pid2; long type; unsigned long idx1; unsigned long idx2;} kcmp_args;",
	"kcmp_data": "typedef struct {event_info_t event_info; u64 pid1; u64 pid2; u64 type; u64 idx1; u64 idx2;} kcmp_data;",
	"kcmp_split": "pid1:integer pid2:integer type:integer idx1:integer idx2:integer",
	"mlock2_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long start; size_t len; long flags;} mlock2_args;",
	"mlock2_data": "typedef struct {event_info_t event_info; u64 start; u64 len; u64 flags;} mlock2_data;",
	"mlock2_split": "start:integer len:integer flags:integer",
	"pwritev2_args": "typedef struct {u64 __unused__; int __syscall_nr; unsigned long fd; struct iovec * vec; unsigned long vlen; unsigned long pos_l; unsigned long pos_h; rwf_t flags;} pwritev2_args;",
	"pwritev2_data": "typedef struct {event_info_t event_info; u64 fd; u64 vec; u64 vlen; u64 pos_l; u64 pos_h; u64 flags;} pwritev2_data;",
	"pwritev2_split": "fd:integer vec:pointer vlen:integer pos_l:integer pos_h:integer flags:integer",
	"sched_setparam_args": "typedef struct {u64 __unused__; int __syscall_nr; pid_t pid; struct sched_param * param;} sched_setparam_args;",
	"sched_setparam_data": "typedef struct {event_info_t event_info; u64 pid; u64 param;} sched_setparam_data;",
	"sched_setparam_split": "pid:integer param:pointer",
	"swapoff_args": "typedef struct {u64 __unused__; int __syscall_nr; char * specialfile;} swapoff_args;",
	"swapoff_data": "typedef struct {event_info_t event_info; char specialfile[64];} swapoff_data;",
	"swapoff_split": "specialfile:string",
	"userfaultfd_args": "typedef struct {u64 __unused__; int __syscall_nr; long flags;} userfaultfd_args;",
	"userfaultfd_data": "typedef struct {event_info_t event_info; u64 flags;} userfaultfd_data;",
	"userfaultfd_split": "flags:integer",
	"io_pgetevents_args": "typedef struct {u64 __unused__; int __syscall_nr; aio_context_t ctx_id; long min_nr; long nr; struct io_event * events; struct timespec * timeout; struct __aio_sigset * usig;} io_pgetevents_args;",
	"io_pgetevents_data": "typedef struct {event_info_t event_info; u64 ctx_id; u64 min_nr; u64 nr; u64 events; u64 timeout; u64 usig;} io_pgetevents_data;",
	"io_pgetevents_split": "ctx_id:integer min_nr:integer nr:integer events:pointer timeout:pointer usig:pointer",
	"listen_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long backlog;} listen_args;",
	"listen_data": "typedef struct {event_info_t event_info; u64 fd; u64 backlog;} listen_data;",
	"listen_split": "fd:integer backlog:integer",
	"get_robust_list_args": "typedef struct {u64 __unused__; int __syscall_nr; long pid; struct robust_list_head * * head_ptr; size_t * len_ptr;} get_robust_list_args;",
	"get_robust_list_data": "typedef struct {event_info_t event_info; u64 pid; u64 head_ptr; u64 len_ptr;} get_robust_list_data;",
	"get_robust_list_split": "pid:integer head_ptr:pointer len_ptr:pointer",
	"setns_args": "typedef struct {u64 __unused__; int __syscall_nr; long fd; long nstype;} setns_args;",
	"setns_data": "typedef struct {event_info_t event_info; u64 fd; u64 nstype;} setns_data;",
	"setns_split": "fd:integer nstype:integer",
}
