global:
  image: 
    registry: ""
    repository: ""

image:
  registry: localhost:32000
  repository: tensorsecurity
  name: tensorsec-image-validator
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

certgen:
  image:
    registry: localhost:32000
    repository: tensorsecurity
    name: tensorsec-certgen
    tag: v1.5.1

nameOverride: "image-validator"
fullnameOverride: "tensorsec-image-validator"

service:
  type: ClusterIP
  port: 443
  targetPort: 9443
  # Specify the nodePort value for the NodePort service types.
  #nodePort:

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
