env:
  - name: LD_PRELOAD
    # value: "/tensorsec/dp.so"
    value: "/tmp/dp.so"
  # - name: TENSORSEC_EVENTCENTER_NEW_ADDR
  - name: EVENTCENTER_NEW_ADDR
    value: "{{ .Values.eventcenter.addr }}"
  # - name: TENSORSEC_EVENTCENTER_NEW_PORT
  - name: EVENTCENTER_NEW_PORT
    value: "{{ .Values.eventcenter.port }}"
volumemounts:
  - name: "{{ .Values.volumes.clientName }}"
    mountpath: "{{ .Values.volumes.clientMountPath }}"
    readonly: true
  - name: "{{ .Values.volumes.caName }}"
    mountpath: "{{ .Values.volumes.caMountPath }}"
    readonly: true
volumes:
  - name: "{{ .Values.volumes.clientName }}"
    volumesource:
      secret:
        defaultmode: 420
        secretname: "{{ .Values.volumes.clientSecretName }}"
  - name: "{{ .Values.volumes.caName }}"
    volumesource:
      secret:
        defaultmode: 420
        secretname: "{{ .Values.volumes.caSecretName }}"
