{{- if .Values.global.multiCluster.isMemberCluster -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dockerregistry-normal" (include "common.scanner.defaultName" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: safe-dockerregistry-normal
type: Opaque
data:
  pass: {{ .Values.bufRegistry.bufRegistryPass | b64enc | quote }}
{{- end -}}
