info:
  contact: {}
  license: {}
paths:
  /api/v1/scan/one:
    post:
      description: Scan one image
      operationId: v1-scan-one-post
      produces:
      - application/json
      summary: Scan one image
swagger: "2.0"
