info:
  contact: {}
  license: {}
paths:
  /api/v1/scan/forceInvalidateCache:
    post:
      description: Force layer cache invalidation. Then reinitialize it.
      produces:
      - application/json
      summary: Force layer cache invalidation.
  /api/v1/scan/harborScanAll:
    post:
      description: Trigger scan of all images in Harbor. This API is exposed for testing purpose.
      produces:
      - application/json
      summary: Trigger scan of all images in Harbor.
  /api/v1/scan/one:
    post:
      description: Scan one image
      operationId: v1-scan-one-post
      produces:
      - application/json
      summary: Scan one image
swagger: "2.0"
