{{- if .Values.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "daemon.serviceAccount" . }}-cluster-role
  labels:
    app: "{{ template "daemon.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
- apiGroups:
  - ""
  - "security-profiles-operator.x-k8s.io"
  - "apps"
  resources:
  - seccompprofiles
  - namespaces
  - pods
  - services
  verbs:
  - list
  - watch
  - get
{{- end -}}
