---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "daemon.fullname" . }}
  labels:
    app: "{{ template "daemon.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: "{{ template "daemon.fullname" . }}"
      release: {{ .Release.Name | quote }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.filebeatConfig }}
        configChecksum: {{ include (print .Template.BasePath "/filebeat-configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      name: "{{ template "daemon.fullname" . }}"
      labels:
        app: "{{ template "daemon.fullname" . }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 -}}
      {{- end }}
      serviceAccountName: {{ template "daemon.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      volumes:
      - name: server-cert
        secret:
          defaultMode: 400
          secretName: eventcenter-tls-server-cert-secret
      - name: sys
        hostPath:
          path: /sys
      - name: time
        hostPath:
        path: /etc/localtime
      - name: modules
        hostPath:
          path: /lib/modules
      - name: usr
        hostPath:
          path: /usr/src
      - name: proc
        hostPath:
          path: /proc
      - name: syscall-data
        emptyDir: { }
      {{- range .Values.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.filebeatConfig }}
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      {{- end }}
      - name: data
        hostPath:
          path: {{ .Values.hostPathRoot }}/{{ template "daemon.fullname" . }}-{{ .Release.Namespace }}-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # filebeat accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      - name: "postgre-listener"
        image: "registry.t-appagile.com/tensorsecurity/alpine:latest"
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 tensorsec-postgresql 5432 && exit 0 || sleep 3; done; exit 1"
        ]

      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: tensordig
        image: "{{ .Values.global.ourDockerRepo }}/{{ .Values.tensordig.image.name }}:{{ .Values.tensordig.image.tag }}"
        imagePullPolicy: {{ .Values.tensordig.image.pullPolicy }}
        securityContext:
          privileged: true
          runAsUser: 0
        command:
          - /bin/bash
          - -c
          - "/go/src/app/configs/tensordig/entrypoint.sh"
        args: [
          "--dbHost=tensorsec-postgresql",
          "--dbUser=postgres",
          "--dbPassword=password",
          "--dbName=postgres",
          "--dbPort=5432",
        ]
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1.5"
          limits:
            memory: "2048Mi"
            cpu: "1.5"
        env:
          - name: EVENT_GRPC_URL
            value: {{ .Values.eventcenter.eventGrpcUrl }}
          - name: EVENT_GRPC_CERT_PATH
            value: /auth/server/tls.crt
          - name: EVENT_GRPC_CERT_SERVER_NAME
            value: {{ .Values.eventcenter.eventGrpcCertServerName }}

          - name: TENSORSEC_CONSOLE_HOST
            value: "{{ .Values.console.addr }}"
          - name: TENSORSEC_CONSOLE_PORT
            value: "{{ .Values.console.port }}"
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumeMounts:
          - name: modules
            mountPath: /lib/modules
            readOnly: true
          - name: usr
            mountPath: /usr/src
            readOnly: true
          - name: time
            mountPath: /etc/localtime
            readOnly: true
          - name: sys
            mountPath: /sys
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: syscall-data
            mountPath: /data
          - mountPath: /auth/server
            name: server-cert
            readOnly: true