---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "daemon.fullname" . }}
  labels:
    app: "{{ template "daemon.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: "{{ template "daemon.fullname" . }}"
      release: {{ .Release.Name | quote }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.filebeatConfig }}
        configChecksum: {{ include (print .Template.BasePath "/filebeat-configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
      name: "{{ template "daemon.fullname" . }}"
      labels:
        app: "{{ template "daemon.fullname" . }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName  }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 -}}
      {{- end }}
      serviceAccountName: {{ template "daemon.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      volumes:
      - name: syskerneldebug
        hostPath:
          path: /sys/kernel/debug
      - name: sysfscgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: sysfsbpf
        hostPath:
          path: /sys/fs/bpf
      - name: time
        hostPath:
        path: /etc/localtime
      - name: modules
        hostPath:
          path: /lib/modules
      - name: usr
        hostPath:
          path: /usr/src
      - name: proc
        hostPath:
          path: /proc
      - name: syscall-data
        emptyDir: { }
      {{- range .Values.secretMounts }}
      - name: {{ .name }}
        secret:
          secretName: {{ .secretName }}
      {{- end }}
      {{- if .Values.filebeatConfig }}
      - name: digconfig
        configMap:
          name: {{ template "daemon.fullname" . }}-config
          defaultMode: 0600
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      {{- end }}
      - name: data
        hostPath:
          path: {{ .Values.hostPathRoot }}/{{ template "daemon.fullname" . }}-{{ .Release.Namespace }}-data
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: varrundockersock
        hostPath:
          path: /var/run/docker.sock
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.extraInitContainers }}
      initContainers:
      # All the other beats accept a string here while
      # filebeat accepts a valid yaml array. We're keeping
      # this as a backwards compatible change, while adding
      # also a way to pass a string as other templates to
      # make these implementations consistent.
      # https://github.com/elastic/helm-charts/issues/490
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 8 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: logrotate
        image: blacklabelops/logrotate:latest
        imagePullPolicy: Always
        env:
          - name: LOGS_DIRECTORIES
            value: /data
          - name: LOGROTATE_INTERVAL
            value: hourly 
          - name: LOG_FILE_ENDINGS
            value: json 
          - name: LOGROTATE_SIZE
            value: 10M
        volumeMounts:
          - name: syscall-data
            mountPath: /data    
      - name: tensordig
        image: "{{ .Values.global.ourDockerRepo }}/{{ .Values.tensordig.image.name }}:{{ .Values.tensordig.image.tag }}"
        imagePullPolicy: {{ .Values.tensordig.image.pullPolicy }}
        securityContext:
          privileged: true
          runAsUser: 0
        command:
          - /bin/bash
          - -c
          - "/go/src/app/configs/tensordig/entrypoint.sh"
        resources:
          limits:
            memory: 200Mi
        volumeMounts:
          - name: digconfig
            mountPath: "/config"
          - name: modules
            mountPath: /lib/modules
            readOnly: true
          - name: usr
            mountPath: /usr/src
            readOnly: true
          - name: time
            mountPath: /etc/localtime
            readOnly: true
          - name: syskerneldebug
            mountPath: /sys/kernel/debug
          - name: sysfsbpf
            mountPath: /sys/fs/bpf
          - name: sysfscgroup
            mountPath: /sys/fs/cgroup            
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: syscall-data
            mountPath: /data
      - name: "filebeat"
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        args:
        - "-e"
        - "-E"
        - "http.enabled=true"
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 8 }}
{{- end }}
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
{{- end }}
{{- if .Values.podSecurityContext }}
        securityContext:
{{ toYaml .Values.podSecurityContext | indent 10 }}
{{- end }}
        volumeMounts:
        - name: syscall-data
          mountPath: /data
          readOnly: true
        {{- range .Values.secretMounts }}
        - name: {{ .name }}
          mountPath: {{ .path }}
          {{- if .subPath }}
          subPath: {{ .subPath }}
          {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.filebeatConfig }}
        - name: filebeat-config
          mountPath: /usr/share/filebeat/{{ $path }}
          readOnly: true
          subPath: {{ $path }}
        {{- end }}
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        # Necessary when using autodiscovery; avoid mounting it otherwise
        # See: https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover.html
        - name: varrundockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
        {{- end }}
      {{- if .Values.extraContainers }}
{{ tpl .Values.extraContainers . | indent 6 }}
      {{- end }}
