##custom_config_inits
- key: miner_domains
  name:
    zh: "挖矿域名"
    en: "Miner Domains Pool"
  effect:
    zh: 可检测对应域名的挖矿连接
    en: It could detect connections from the miner to the given domains
  type: list
  # rulesAppliedSteps规范: the first item must be a rule; the others must be macros
  rulesAppliedSteps:
  - - Detect outbound connections to common miner pool ports
    - net_miner_pool
    - minerpool_other

- key: sensitive_paths
  name:
    zh: "敏感文件路径"
    en: "Sensitive File Paths"
  effect:
    zh: 可检测对应文件遭到的读写或修改
    en: It could detect the reads/writes of the specified file paths
  type: list
  rulesAppliedSteps:
  - - Gaining environment information

- key: monitored_directories
  name:
    zh: 敏感目录
    en: Sensitive Directories
  effect:
    zh: 可检测对应目录下的文件读写或修改
    en: It could detect the reads/writes of the specified directories
  type: list
  rulesAppliedSteps:
  - - Write below monitored dir
    - monitored_dir





