- mozart:
  - name: 'fuchao-Using vim_suid to execute commands for linux privilege escalation'
    enabled: true
    trigger: 'Generated child process shell after starting the container'
    steps:
      - name: checkRelatedExists
        params: [ 'Running vim in container', 1s, trigger.payload.output_map.proc_pid, payload.output_map.proc_pid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-尝试利用vim_suid执行命令提权, rule: 'fuchao-Using vim_suid to execute commands for linux privilege escalation' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Using vim_suid to execute commands for linux privilege escalation'
        zh: 'fuchao-尝试利用vim_suid执行命令提权'
      suggestion:
        en: 'Use the Immune Defence training application to restrict user permissions on sensitive files and commands.'
        zh: '请排查容器内vim命令是否被授予s权限，从而被黑客尝试利用提权，可尝试采用微隔离和免疫防御阻止风险进一步扩散。'
      rule_type: Privilege_Escalation
      priority: EMERGENCY
      urgency: true

  - name: 'fuchao-Using vim to run commands'
    enabled: true
    trigger: 'Generated child process shell after starting the container'
    steps:
      - name: checkRelatedExists
        params: [ 'Running vim in container', 1s, trigger.payload.output_map.proc_ppid, payload.output_map.proc_pid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-通过vim执行命令, rule: 'fuchao-Using vim to run commands' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Using vim to run commands'
        zh: 'fuchao-通过vim执行命令'
      suggestion:
        en: 'Use the Immune Defence training application to restrict user permissions on sensitive files and commands.'
        zh: '使用免疫防御训练应用，限制敏感文件和命令的用户权限。'
      rule_type: Execution
      priority: WARNING
      urgency: true

  - name: 'fuchao-Reverse shell through telnet'
    enabled: true
    trigger: 'Generated child process shell after starting the container'
    steps:
      - name: checkRelatedExists
        params: [ 'Running telnet in container', 1s, trigger.payload.output_map.proc_pgid, payload.output_map.proc_pgid ]
      - name: checkRelatedExists
        params: [ 'Contact remote server from container', 1s, trigger.payload.output_map.proc_pgid, payload.output_map.proc_pgid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-黑客在容器内通过telnet反弹shell, rule: 'fuchao-Reverse shell through telnet' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Telnet Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)'
        zh: 'fuchao-黑客在容器内通过telnet反弹shell'
      suggestion:
        en: 'The container is intruded, it is necessary to isolate the container, investigate other attacks, and confirm the security of the cluster.'
        zh: '容器遭到入侵，需隔离该容器，同时排查其他攻击行为，确认集群安全。'
      rule_type: Execution
      priority: EMERGENCY
      urgency: true

  - name: 'fuchao-Reverse shell through ruby'
    enabled: true
    trigger: 'Generated child process shell after starting the container'
    steps:
      - name: checkRelatedExists
        params: [ 'Created remote connection through ruby in container', 5s, trigger.payload.output_map.proc_pgid, payload.output_map.proc_pgid ]
      - name: checkRelatedExists
        params: [ 'Contact remote server from container', 5s, trigger.payload.output_map.proc_pgid, payload.output_map.proc_pgid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-黑客在容器内通过ruby反弹shell, rule: 'fuchao-Reverse shell through ruby' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Ruby Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)'
        zh: 'fuchao-黑客在容器内通过ruby反弹shell'
      suggestion:
        en: 'The container is intruded, it is necessary to isolate the container, investigate other attacks, and confirm the security of the cluster.'
        zh: '容器遭到入侵，需隔离该容器，同时排查其他攻击行为，确认集群安全。'
      rule_type: Execution
      priority: EMERGENCY
      urgency: true

  - name: 'fuchao-Connecting to a remote server through redis client in container'
    enabled: true
    trigger: 'Connecting to a remote server through redis client in container'
    steps:
      - name: checkRelatedExists
        params: [ 'Contact remote server from container', 1s, trigger.payload.output_map.proc_pid, payload.output_map.proc_pid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-容器内通过redis客户端连接远程服务器, rule: 'fuchao-Connecting to a remote server through redis client in container' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Connecting to a remote server through redis client in container'
        zh: 'fuchao-容器内通过redis客户端连接远程服务器'
      suggestion:
        en: 'Please confirm whether the Redis connection is a normal service connection and check the cause of the connection.'
        zh: '请确认该redis连接是否为业务正常连接，排查出现该连接原因。'
      rule_type: Execution
      priority: WARNING
      urgency: true

  - name: 'fuchao-Execute commands through webshell'
    enabled: true
    trigger: 'Execute commands through webshell'
    steps:
      - name: checkRelatedExists
        params: [ 'Generated child process shell after starting the container', 1s, trigger.payload.output_map.proc_name, payload.output_map.proc_pname ]
      - name: checkValue
        params: [ trigger.payload.output_map.proc_name, java ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-通过向Tomcat上传webshell并执行命令, rule: 'fuchao-Execute commands through webshell' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Execute commands through webshell'
        zh: 'fuchao-通过向Tomcat上传webshell并执行命令'
      suggestion:
        en: 'Use the Immune Defence training application to restrict user permissions on sensitive files and commands.'
        zh: '建议排查是否有攻击者已获取内部容器权限，同时使用免疫防御限制攻击者进行进一步攻击。'
      rule_type: Execution
      priority: EMERGENCY
      urgency: true

  - name: 'fuchao-Using vim_suid to modify sensitive file for linux privilege escalation'
    enabled: true
    trigger: 'Linux Privilege Escalation by modifying sensitive files with suid binaries'
    steps:
      - name: checkRelatedExists
        params: [ 'Running vim in container', 10s, trigger.payload.output_map.proc_pid, payload.output_map.proc_pid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-尝试利用vim_suid修改敏感文件提权, rule: 'fuchao-Using vim_suid to modify sensitive file for linux privilege escalation' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Using vim_suid to modify sensitive file for linux privilege escalation'
        zh: 'fuchao-尝试利用vim_suid修改敏感文件提权'
      suggestion:
        en: 'Please check whether the vim command in the container has been granted s permission, so that hackers try to use it to improve their rights. You can try to use micro isolation and immune defense to prevent the risk from spreading further.'
        zh: '容器可能已遭到入侵，可使用免疫防御训练应用，限制敏感文件和命令的用户权限。'
      rule_type: Privilege_Escalation
      priority: EMERGENCY
      urgency: true

  - name: 'fuchao-Using visudo to modify sensitive file for linux privilege escalation'
    enabled: true
    trigger: 'Write to /etc/sudoers'
    steps:
      - name: checkRelatedExists
        params: [ 'Running visudo in container', 10s, trigger.payload.output_map.proc_pid, payload.output_map.proc_pid ]
      - name: execGenerateSignal
        params: { zh_msg: fuchao-尝试利用visudo修改敏感文件提权, rule: 'fuchao-Using visudo to modify sensitive file for linux privilege escalation' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'fuchao-Using visudo to modify sensitive file for linux privilege escalation'
        zh: 'fuchao-尝试利用visudo修改敏感文件提权'
      suggestion:
        en: 'Please check whether the vim command in the container has been granted s permission, so that hackers try to use it to improve their rights. You can try to use micro isolation and immune defense to prevent the risk from spreading further.'
        zh: '容器可能已遭到入侵，可使用免疫防御训练应用，限制敏感文件和命令的用户权限。'
      rule_type: Privilege_Escalation
      priority: EMERGENCY
      urgency: true

  - name: 'shifeng-Brute force hacking detected'
    enabled: true
    trigger: 'Contact remote server from container'
    steps:
      - name: checkRuleRecentCount
        params: [ 'Contact remote server from container', 10s, 5, '["server_ip", "server_port", "client_ip"]', '[]', 1m ]
      - name: execGenerateSignal
        params: { zh_msg: shifeng-检测到正在暴力破解, rule: 'shifeng-Brute force hacking detected' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'Brute force hacking detected'
        zh: '检测到正在暴力破解'
      suggestion:
        en: 'There may be brute force cracking, it is recommended to confirm whether there is a weak password in the service where the port is located.'
        zh: '可能存在暴力破解行为，建议确认端口所在服务是否存在弱口令。'
      rule_type: Exfiltration
      priority: ALERT
      urgency: true

  - name: 'shifeng-Scanning ports detected'
    enabled: true
    trigger: 'Contact remote server from container'
    steps:
      - name: checkRuleRecentCount
        params: [ 'Contact remote server from container', 10s, 5, '["server_ip", "client_ip"]', '["server_port"]', 1m ]
      - name: execGenerateSignal
        params: { zh_msg: shifeng-检测到正在扫描敏感端口, rule: 'shifeng-Scanning ports detected' }
      - name: execSendPalace
        params: ''
    info:
      desc:
        en: 'Scanning ports detected'
        zh: '检测到正在扫描敏感端口'
      suggestion:
        en: 'There may be port scanning behavior, it is recommended to confirm whether there is a vulnerability in the service where the port is located.'
        zh: '可能存在敏感端口扫描行为，建议确认端口所在服务是否存在漏洞。'
      rule_type: Exfiltration
      priority: ALERT
      urgency: true