##attck_rule_type=trigger
- rule: Generated child process shell after starting the container
  hid: trigger_01
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Use the Immune Defence training application to restrict user permissions on sensitive files and commands."
    zh:
      key: "处置建议"
      value: "使用免疫防御训练应用，限制敏感文件和命令的用户权限。"
  desc: Generated child process shell after starting the container
  condition: >
   spawned_process and evt.res!=ENOENT and
   container and not container_entrypoint and
   shell_procs and not proc.cmdline contains "vimglob"
  output: >
    Generated child process shell after starting the container(zh_msg=启动容器后生成子进程shell,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_name=%proc.name,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,evt.arg.exe=%evt.arg.exe,terminal=%proc.tty,user_uid=%user.uid,container_id=%container.id,container_name=%container.name,parent=%proc.pname,gparent=%proc.aname[2],ggparent=%proc.aname[3],aname[4]=%proc.aname[4],aname[5]=%proc.aname[5],aname[6]=%proc.aname[6],aname[7]=%proc.aname[7],proc_pgid=%proc.vpgid)
  priority: WARNING
  tags: [ATT&CK, filesystem, mitre_privilege_escalation, related, triggered]