package apikey

import (
	"context"
	"fmt"
	"net/http"
	"sync"

	"github.com/tomogoma/go-api-guard"
	typederrs "github.com/tomogoma/go-typed-errors"
	"gitlab.com/piccolo_su/vegeta/pkg/apperror"
	"gitlab.com/piccolo_su/vegeta/pkg/logging"
)

const (
	// only use for scanner ci/cd, hardcode for now,should be abandoned later
	//apiSecret = "WUuPjoFnNUIzxbbX"
	// hardcode customer's api key, generated by function:  GenerateApiKey(secret, user string)
	scannerApiKey = "dGVuc29yc2VjLWNpY2QtdXNlcg==.qBFMMAvbbm3afG3y42CqKaN7WQe4Q7hiqtg5Jzwen7tWHhZG16P62kvv"
	scannerUser   = "tensorsec-cicd-user"
)

var (
	apiKeyManager *KeyManager
)

type KeyManager struct {
	lock     sync.Mutex
	apiGuard *api.Guard
}

type APIKey struct {
	Val []byte
}

func (k APIKey) Value() []byte {
	return k.Val
}

type DB struct {
	typederrs.NotFoundErrCheck

	APIKey api.Key
	UserID string
}

func init() {
	db := &DB{}
	//hard code user and key
	_, err := db.InsertAPIKey(scannerUser, []byte(scannerApiKey))
	if err != nil {
		fmt.Println("insert api key err", err)
	}
	g, _ := api.NewGuard(
		db,
	)
	apiKeyManager = &KeyManager{
		apiGuard: g,
	}
}

func (db *DB) APIKeyByUserIDVal(userID string, key []byte) (api.Key, error) {
	if db.APIKey == nil {
		return nil, typederrs.NewNotFound("not found api key")
	}
	if len(db.UserID) == 0 {
		return nil, typederrs.NewNotFound("not found user")
	}
	return db.APIKey, nil
}

func (db *DB) InsertAPIKey(userID string, key []byte) (api.Key, error) {
	db.UserID = userID
	db.APIKey = APIKey{Val: key}
	return APIKey{Val: key}, nil
}

type KeyGen struct {
	ExpSRBsErr error
	ExpSRBs    []byte
}

func (kg *KeyGen) SecureRandomBytes(length int) ([]byte, error) {
	if kg.ExpSRBsErr != nil {
		return nil, kg.ExpSRBsErr
	}
	return kg.ExpSRBs, kg.ExpSRBsErr
}

// GenerateApiKey generate api for user with given secret
func GenerateApiKey(secret, user string) (string, error) {
	db := &DB{}

	// mocking key generation to demonstrate resulting API key
	keyGen := &KeyGen{ExpSRBs: []byte(secret)}

	g, _ := api.NewGuard(
		db,
		api.WithKeyGenerator(keyGen), // This is optional
	)

	// Generate API key
	APIKey, err := g.NewAPIKey(user)
	if err != nil {
		return "", nil
	}
	return string(APIKey.Value()), nil
}

func ValidateApiKey(key, user string) (bool, error) {
	apiKeyManager.lock.Lock()
	defer func() {
		apiKeyManager.lock.Unlock()
	}()

	decodeUser, err := apiKeyManager.apiGuard.APIKeyValid([]byte(key))
	if err != nil {
		logging.GetLogger().Error().
			Err(err).Str("req user", decodeUser).
			Str("check user", user).Str("req key", key).
			Msg("invalid api key")
		return false, err
	}
	if decodeUser != user {
		logging.GetLogger().Error().
			Str("req user", decodeUser).
			Str("check user", user).Str("req key", key).
			Msg("user not match key")
		return false, nil
	}
	return true, nil
}

func ScannerValid() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			key := r.Header.Get("X-Tensorsec-cicd-key")
			valid, err := ValidateApiKey(key, scannerUser)
			if err != nil || !valid {
				apperror.RespAndLog(w, r.Context(),
					apperror.NewInvalidAuthToken(http.StatusUnauthorized,
						fmt.Errorf("invalid ci/cd api key: %w", err)))
				return
			}
			ctx := context.WithValue(r.Context(), scannerUser, key)
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
