apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: sec-prof-man
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: sec-prof-man
    spec:
      serviceAccountName: {{ include "common.names.fullname" . }}
      initContainers:
      - name: "stan-listener"
        image: {{ include "initContainers.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ include "common.stan.defaultName" . }}-headless 4222 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.initContainers.resources | indent 10 }}
      - name: "postgres-listener"
        image: {{ include "initContainers.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ include "common.pgpool.defaultName" . }} 5432 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.initContainers.resources | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "secProfilesManager.image" . }}
        command: ["/security-profiles-manager"]
        args: [
          "--redis-endpoint={{ include "common.redis.sentinel.address" . }}",
          "--stan-client-id={{ .Values.stan.clientID }}",
          "--stan-cluster-id={{ .Values.stan.clusterID }}",
          "--stan-url={{ include "common.stan.defaultName" .}}-headless:4222",
          "--console-postgres={{ include "common.pgpool.DSN" . }}"
        ]
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SEC_PROFILES_CONTAINER_CONFIGMAP
          value: {{ printf "%s-container" (include "common.names.fullname" .) }}
        - name: HOLMES_LABEL
          value: {{ .Values.holmes.podLabel }}
        - name: HOLMES_CONFIGMAP
          value: {{ .Values.holmes.rulesConfigMap }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.redis-ha.defaultName" . }}
              key: auth
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
          - containerPort: {{ .Values.service.containerPort }}
            name: sec-prof-man
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
