apiVersion: v1
data:
kind: ConfigMap
metadata:
  name: {{ printf "%s-container" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-container
