apiVersion: v1
data:
kind: ConfigMap
metadata:
  name: {{ template "secProfilesManager.fullname" . }}-container
  labels:
    app: {{ include "secProfilesManager.fullname" . }}-container
    chart: {{ include "secProfilesManager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
