producers:
  syscalls:
    - syscallOpen:
      name: openat
      filters:
        - fnFilter:
          id: f1
          field: filename
          operation: inArray
          values:
            - v: /etc/passwd
            - v: /etc/group
            - v: /etc/netconfig
            - v: /etc/networks
            - v: /etc/sudoers
            - v: /etc/services
            - v: /etc/hosts
        - flagFilter:
          id: f2
          field: flags
          operation: equalTo
          values:
            - v: 0
      logic: f1&&f2
    - syscallMkdir:
      name: mkdir
      filters:
        - pnFilter:
          field: pathname
          operation: notStartsWithArray
          values:
            - v: /var/log
            - v: /sys/fs/cgroup
            - v: /run/systemd
    - syscallGetcwd:
      name: getcwd
    - syscallChmod:
      name: chmod
    - syscallRmdir:
      name: rmdir
      filters:
        - pnFilter:
          field: pathname
          operation: notStartsWithArray
          values:
            - v: /var/log
            - v: /sys/fs/cgroup
            - v: /run/systemd
    - syscallStatfs:
      name: statfs
    - syscallExecve:
      name: execve
      filters:
#        - fnFilterNE:
#          id: f
#          field: filename
#          operation: notEqualTo
#          values:
#            - v: /bin/grex
#        - fnFilterNE:
#          field: filename
#          operation: notEqualTo
#          values:
#            - v: /bin/grey
#        - fnFilterNE:
#          id: f1
#          field: filename
#          operation: notEqualTo
#          values:
#            - v: /bin/grex
#        - fnFilterNE:
#          id: fuck-a
#          field: filename
#          operation: notEqualTo
#          values:
#            - v: /bin/grex
        - fnFilterNE:
          id: f1
          field: filename
          operation: notEqualTo
          values:
            - v: /bin/grep
        - fnFilterSh:
          id: f2
          field: filename
          operation: inArray
          values:
            - v: /bin/zsh
            - v: /bin/bash
            - v: /bin/rbash
            - v: /bin/rzsh
            - v: /bin/dash
            - v: /bin/sh
        - fnFilter:
          id: f3
          field: filename
          operation: notStartsWithArray
          values:
            - v: /sbin
            - v: /usr/local
            - v: /usr/sbin
            - v: /usr/bin
      logic: f1&&(f2||f3)
    - syscallCreat:
      name: creat
    - syscallSymlink:
      name: symlink
consumers:
  - Print