producers:
    syscalls:
      - syscallExecve:
        name: execve
        filters:
          - filenameFilter:
            id: f1
            field: filename
            operation: inArray
            values:
              - v: /bin/nc
              - v: /usr/bin/ncat
          - argv1Filter:
            id: f2
            field: argv1
            operation: inArray
            values:
              - v: -e
              - v: -c
              - v: --sh-exec
              - v: --exec
              - v: --lua-exec
          - argv2Filter:
            id: f3
            field: argv2
            operation: inArray
            values:
              - v: -e
              - v: -c
              - v: --sh-exec
              - v: --exec
              - v: --lua-exec
          - argv3Filter:
            id: f4
            field: argv3
            operation: inArray
            values:
              - v: -e
              - v: -c
              - v: --sh-exec
              - v: --exec
              - v: --lua-exec
        logic: f1&&(f2||f3||f4)
consumers:
  - Json
