producers:
  syscalls:
  - syscallOpenat:
    name: openat
    filters:
    - fnFilter:
      field: filename
      operation: equalTo
      values:
      - v: /tmp/f
  - syscallSocket:
    name: socket
    filters:
    - familyFilter:
      id: f1
      field: family
      operation: equalTo
      values:
      - v: 2
  - syscallRead:
    name: read
  - syscallWrite:
    name: write
  - syscallClose:
    name: close
  - syscallExecve:
    name: execve
  - syscallDup:
    name: dup
  - syscallDup2:
    name: dup2
  - syscallFork:
    name: fork
  - syscallClone:
    name: clone
    filters:
    - flagFilter:
      field: clone_flags
      operation: andIs
      values:
      - v: 1024
      - v: 0
  - syscallMknod:
    name: mknod
    filters:
    - modeFilter:
      id: f1
      field: mode
      operation: equalTo
      values:
      - v: 4534
  - syscallMemfdCreate:
    name: memfd_create
  - syscallPipe:
    name: pipe
  - syscallPipe2:
    name: pipe2
  - syscallConnect:
    name: connect
  - syscallListen:
    name: listen
#  - syscallFcntl:
#    name: fcntl
#    filters:
#    - dupCmd:
#      id: dup
#      field: cmd
#      operation: equalTo
#      values:
#      - v: 0
#    - setCmd:
#      id: set
#      field: cmd
#      operation: equalTo
#      values:
#      - v: 2
#    - cloExecArg:
#      id: cloexec
#      field: arg
#      operation: equalTo
#      values:
#      - v: 1030
#    logic: dup||(set&&cloexec)
consumers:
  # - Databus
  # - Print
  # - Count
  # - Collect
  - Json
   
