image:
  registry: localhost:32000
  repository: tensorsecurity
  name: tensordig
  tag: latest
  pullPolicy: Always


# Extra environment variables to append to the DaemonSet pod spec.
# This will be appended to the current 'env:' key. You can use any of the kubernetes env
# syntax here
extraEnvs: []
#  - name: MY_ENVIRONMENT_VAR
#    value: the_value_goes_here

extraVolumeMounts: []
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true

extraVolumes: []
  # - name: extras
  #   emptyDir: {}

extraContainers: ""
# - name: dummy-init
#   image: busybox
#   command: ['echo', 'hey']

extraInitContainers:
  esListerner:
    enabled: true
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: alpine
      tag: latest
      PullPolicy: IfNotPresent
  pgListerner:
    enabled: true
    image:
      registry: localhost:32000
      repository: tensorsecurity
      name: alpine
      tag: latest
      PullPolicy: IfNotPresent

envFrom: []
# - configMapRef:
#     name: configmap-name

hostNetworking: true
imagePullSecrets:
- name: "harbor-admin-secret"
  

# Whether this chart should self-manage its service account, role, and associated role binding.
managedServiceAccount: true

# additionals labels
labels: {}

podAnnotations: {}
  # iam.amazonaws.com/role: es-cluster


# Custom service account override that the pod will use
serviceAccount: ""

# Annotations to add to the ServiceAccount that is created if the serviceAccount value isn't set.
serviceAccountAnnotations: {}
  # eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/k8s.clustername.namespace.serviceaccount

# A list of secrets and their paths to mount inside the pod
# This is useful for mounting certificates for security other sensitive values
secretMounts: []


# How long to wait for pods to stop gracefully
terminationGracePeriod: 30

tolerations: []

nodeSelector: {}

affinity: {}

# This is the PriorityClass settings as defined in
# https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: ""

updateStrategy: RollingUpdate

# Override various naming aspects of this chart
# Only edit these if you know what you're doing
# nameOverride: ""
# fullnameOverride: ""

nameOverride: "daemon"
fullnameOverride: "tensorsec-daemon"

# Not flexible enough, temporarily closed.
# console:
#   addr: tensorsec-console.tensorsec.svc.cluster.local
#   port: "8889"

eventcenter:
  eventGrpcUrl: tensorsec-eventcenter:9090
  eventGrpcCertServerName: tensorsec-eventcenter
