apiVersion: {{ include "tensorsec.common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  labels:
    app: faulty
  name: faulty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faulty
  template:
    metadata:
      labels:
        app: faulty
        tensorsec.driftprevent: prevent
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: {{ include "tensorsec.faulty.image" . }}
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/bin/python3 
              - /test/attack.py 
              - --attck all
        name: faulty
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /host/tmp
          name: tmp
      imagePullSecrets:
      - name: harbor-admin-secret
      volumes:
      - hostPath:
          path: /tmp
          type: ""
        name: tmp
