name: logstash-tcp
type: frequency
index: logstash-*
num_events: 1
query_key: "@timestamp"
timeframe:
  hours: 23
realert:
  minutes: 0
filter:
- query:
    query_string:
      query: "port: [4999 TO 999999]"
alert:
- "alerter.mongo_alerter.MongoAlerter"
