{{- if .Values.managedServiceAccount }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ template "secProfilesManager.serviceAccount" . }}-daemon-cluster-role-binding
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
roleRef:
  kind: ClusterRole
  name: {{ template "secProfilesManager.serviceAccount" . }}-daemon-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "secProfilesManager.serviceAccount" . }}-daemon
  namespace: {{ .Release.Namespace }}
{{- end -}}
