{{- if .Values.managedServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- with .Values.serviceAccountAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-daemon" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-daemon
{{- end -}}
