global:
  image: 
    registry: ""
    repository: ""


# imagePullSecrets:
#   - name: vegeta-gitlab

image:
  registry:  localhost:32000
  repository: library
  name: security-profiles-manager
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

certgen:
  image:
    registry: localhost:32000
    repository: library
    name: kube-webhook-certgen
    tag: v1.1.1

nameOverride: "sec-prof-man"
fullnameOverride: "sec-prof-man"

restartPolicy: Always

service:
  type: ClusterIP
  port: 8887
  containerPort: 8080

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "100m"
    memory: "200Mi"

initContainers:
  image:
    registry:  localhost:32000
    repository: library
    name: alpine
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "50m"

webhook:
  image:
    registry: localhost:32000
    repository: library
    name: security-profiles-webhook
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "50m"
      memory: "50Mi"

loader:
  image:
    registry: localhost:32000
    repository: library
    name: security-profiles-loader
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "50m"
      memory: "50Mi"

audit:
  image:
    registry: localhost:32000
    repository: library
    name: go-audit
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
    limits:
      cpu: "50m"
      memory: "50Mi"

holmes:
  rulesConfigMap: holmes-rules
  podLabel: holmes

stan:
  clientID: sec-profile-manager
  clusterID: manager

volumes:
  clientName: "client-cert"
  clientSecretName: "eventcenter-tls-client-cert-secret"
  clientMountPath: "/auth/client"
  caName: "ca-cert"
  caSecretName: "eventcenter-tls-ca-secret"
  caMountPath: "/auth/ca"

eventcenter:
  addr: eventcenter
  port: "8080"

managedServiceAccount: true
