common:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
    name: "storage-provisioner"
  useAlphaAPI: false
  setPVOwnerRef: false
  useJobForCleaning: false
  useNodeNameOnly: false

classes:
- name: local-storage
  hostDir: /mnt/disks
  volumeMode: Filesystem
  fsType: ext4
  namePattern: "*"
  blockCleanerCommand:
   - "/scripts/blkdiscard.sh"
  storageClass:
    reclaimPolicy: Delete
    isDefaultClass: true

daemonset:
  image: quay.io/external_storage/local-volume-provisioner:v2.3.4

serviceMonitor:
  enabled: false
  
nameOverride: ""
fullnameOverride: ""