apiVersion: {{ include "tensorsec.common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "console.serviceAccount" . }}-cluster-role
  labels:
    app: "{{ template "console.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
