{{- if .Values.persistence.enabled -}}
apiVersion: {{ include "tensorsec.common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: {{ .Values.persistence.tensorsecCleaner.coldCronjob.fullnameOverride }}
  labels:
    app: {{ .Values.persistence.tensorsecCleaner.coldCronjob.nameOverride }}
spec:
  schedule: {{ .Values.persistence.tensorsecCleaner.coldCronjob.cronString }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
            - command:
                - /app/tensor-cleaner
                - clear-cold-storage-tool
              env:
                - name: PGSQL_HOST
                  value: tensorsec-postgresql
                - name: PGSQL_USER
                  value: postgres
                - name: PGSQL_DBNAME
                  value: postgres
                - name: PGSQL_SSL_MODE
                  value: disable
                - name: PGSQL_PASSWORD
                  value: password
                - name: AUDIT_PATH
                  value: /audit
              image: {{ include "jobs.cleaner.image" . }}
              imagePullPolicy: {{ .Values.persistence.tensorsecCleaner.image.pullPolicy }}
              name: {{ .Values.persistence.tensorsecCleaner.coldCronjob.nameOverride }}
              resources:
{{ toYaml .Values.persistence.tensorsecCleaner.coldCronjob.resources | indent 16 }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /audit
                  name: audit
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.persistence.tensorsecCleaner.image.pullSecret }}
          volumes:
            - name: audit
              persistentVolumeClaim:
                claimName: audit-pvc
{{- end -}}