---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "console.fullname" . }}
  labels:
{{ include "console.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "console.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "console.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
      initContainers:
      - name: "elasticsearch-listener"
        image: {{ include "console.registryPath" . }}/alpine:latest
        imagePullPolicy: "IfNotPresent"
        resources:
{{ toYaml .Values.initResources | trim | indent 10 }}
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 tensorsec-elasticsearch-master 9200 && exit 0 || sleep 3; done; exit 1"
        ]
      serviceAccount: {{ template "console.serviceAccount" . }}-sa
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "console.image" . }}
        command: ["/tensor-console"]
        args: [
          "--mongo-endpoint=tensorsec-mongodb-0.tensorsec-mongodb-headless:27017",
          "--mongo-database={{ .Values.mongo.mongoDatabase }}",
          "--mongo-username={{ .Values.mongo.mongoUsername }}",
          "--mongo-k8secretname={{ .Values.mongo.mongoSecretName }}",
          "--mongo-pvc=datadir-tensorsec-mongodb-0",
          "--mongo-pod=tensorsec-mongodb-0",
          "--mongo-data-path={{ .Values.mongo.mongoDataPath }}",
          "--console-postgres=postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable",
          "--postgres-pvc=data-tensorsec-db-postgresql-0",
          "--postgres-pod=tensorsec-db-postgresql-0",
          "--postgres-data-path={{ .Values.postgresql.postgresqlDataDir }}",
          "--email-check={{ .Values.emailCheck.smtpEnabled }}",
          {{- if .Values.emailCheck.smtpEnabled }}
          "--email-username={{ .Values.emailCheck.smtpUsername }}",
          "--email-host={{ .Values.emailCheck.smtpHost }}",
          "--email-port={{ .Values.emailCheck.smtpPort }}",
          {{- end }}
          "--vegeta-scanner-host=tensorsec-scanner",
          "--vegeta-scanner-port=8888",
          "--microseg-host=tensorsec-microseg",
          "--microseg-port=8090",
          "--redis-endpoint=tensorsec-redis-ha-announce-0:26379,tensorsec-redis-ha-announce-1:26379,tensorsec-redis-ha-announce-2:26379",
          "--scap-job-repo={{ include "console.registryPath" . }}",
          "--scap-job-tag={{ .Values.scap.tag }}",
          "--elastic-host={{ .Values.elastic.host }}",
          "--elastic-port={{ .Values.elastic.port }}",
          "--elastic-index={{ .Values.elastic.index }}",
          "--elastic-username={{ (index .Values.elasticsearch.extraEnvs 0).value }}",
          "--elastic-pvc=tensorsec-elasticsearch-master-tensorsec-elasticsearch-master-0",
          "--elastic-pod=tensorsec-elasticsearch-master-0",
          "--elastic-data-path={{ .Values.elastic.elasticDataPath }}",
          "--harbor-username={{ .Values.harbor.harborUsername }}",
          "--harbor-url={{ .Values.harbor.harborURL }}",
          "--harbor-skiptlsverify", # Insecure
          "-v"]

        volumeMounts:
          - name: available-rules-volume
            mountPath: "/available-rules"
          - mountPath: /auth/server
            name: server-cert
            readOnly: true
          - mountPath: /audit
            name: audit
            readOnly: true
        env:
        # Required for managing scap jobs
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: TENSORSEC_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.redisSecretName }}
              key: auth
        {{- if .Values.emailCheck.smtpEnabled }}
        - name: TENSORSEC_EMAIL_PASSWORD
          value: {{ .Values.emailCheck.smtpPassword }}
        {{- end }}
        - name: TENSORSEC_HARBOR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.harbor.harborSecretName }}
              key: password
        - name: TENSORSEC_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.mongoSecretName }}
              key: mongodb-password
        - name: TENSORSEC_ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.elasticsearch.elasticSecretName }}
              key: password
        - name: EVENT_GRPC_URL
          value: {{ .Values.eventcenter.eventGrpcUrl }}
        - name: EVENT_GRPC_CERT_PATH
          value: /auth/server/tls.crt
        - name: EVENT_GRPC_CERT_SERVER_NAME
          value: {{ .Values.eventcenter.eventGrpcCertServerName }}
        - name: CLEANER_IMAGE
          value: "{{ include "console.cleaner.image" . }}"
        - name: AUDIT_PVC
          value: audit-pvc
        - name: AUDIT_PATH
          value: /audit
        - name: TENSORSEC_PPROF_PORT
          value: "{{ .Values.debugService.containerPort }}"
        - name: SOFT_NAME
          value: {{ .Values.version.softName }}
        - name: SOFT_VERSION
          value: {{ .Values.version.softVersion }}
        - name: K8S_AUDIT_INDEX_PREFIX
          value: {{ .Values.k8sAudit.prefix }}
        - name: K8S_AUDIT_SYSLOG_ENABLE
          value: {{ .Values.k8sAudit.syslog.enable | quote }}
        - name: K8S_AUDIT_SYSLOG_NETWORK
          value: {{ .Values.k8sAudit.syslog.network }}
        - name: K8S_AUDIT_SYSLOG_SERVER_ADDR
          value: {{ .Values.k8sAudit.syslog.addr }}
        - name: K8S_AUDIT_SYSLOG_FACILITY
          value: {{ .Values.k8sAudit.syslog.facility | quote }}
        - name: K8S_AUDIT_SYSLOG_SEVERITY
          value: {{ .Values.k8sAudit.syslog.severity | quote }}
        - name: K8S_AUDIT_SYSLOG_TAG
          value: {{ .Values.k8sAudit.syslog.tag }}
        - name: OPEN_API_GUIDE_URL
          value: {{ .Values.openapi.guideURL }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        ports:
          - containerPort: {{ .Values.service.containerPort }}
            name: {{ include "console.name" . }}
          - containerPort: {{ .Values.debugService.containerPort }}
            name: pprof
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "tensorsec.tplvalues" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: tmp
        hostPath:
          path: /tmp/
      - name: available-rules-volume
        configMap:
          name: available-rules-config
          defaultMode: 0600
      - name: server-cert
        secret:
          defaultMode: 400
          secretName: eventcenter-tls-server-cert-secret
{{- if not .Values.persistence.enabled }}
      - name: audit
        emptyDir: {}
{{- else }}
      - name: audit
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.claimName }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
