apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "console.fullname" . }}
  labels:
{{ include "console.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "console.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "console.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.ourDockerRepo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command: ["/vegeta-console"]
        args: [
          "--mongo-endpoint=tensorsec-mongodb:27017",
          "--mongo-database={{ .Values.mongo.mongoDatabase }}",
          "--mongo-username={{ .Values.mongo.mongoUsername }}",
          "--mongo-k8secretname={{ .Values.mongo.mongoSecretName }}",
          "--vegeta-scanner-host=tensorsec-scanner",
          "--vegeta-scanner-port=8888",
          "--scap-job-repo={{ .Values.global.ourDockerRepo }}",
          "-v"]

        env:
        - name: TENSORSEC_MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mongo.mongoSecretName }}
              key: password

        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.containerPort }}
            name: {{ include "console.name" . }}
        env:
        # Required for managing scap jobs
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: tmp
        hostPath:
          path: /tmp/
