apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-elasticsearch" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: elasticsearch
type: Opaque
data:
  password: {{ (index .Values.elasticsearch.extraEnvs 1).value | b64enc | quote }}
