apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.elasticSecretName }}
  labels:
    helm.sh/chart: {{ include "console.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ (index .Values.elasticsearch.extraEnvs 1).value | b64enc | quote }}
