apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.mongoSecretName }}
  labels:
    helm.sh/chart: {{ include "console.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.mongo.mongoPassword | b64enc | quote }}
