apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "console.serviceAccount" . }}-sa
  labels:
    app: "{{ template "console.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}