apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ include "common.names.fullname" . }}
    - name: k8s-audit-webhook
      port: {{ .Values.service.k8sAuditWebHookPort }}
      protocol: TCP
      targetPort: {{ .Values.service.k8sAuditWebHookContainerPort }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-pprof
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: pprof
spec:
  type: {{ .Values.debugService.type }}
  ports:
    - port: {{ .Values.debugService.port }}
      targetPort: {{ .Values.debugService.containerPort }}
      protocol: TCP
      name: {{ include "common.names.name" . }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}