apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}
  labels:
    helm.sh/chart: {{ include "console.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: {{ include "console.name" . }}
    - name: k8s-audit-webhook
      port: {{ .Values.service.k8sAuditWebHookPort }}
      protocol: TCP
      targetPort: {{ .Values.service.k8sAuditWebHookContainerPort }}
  selector:
    app.kubernetes.io/name: {{ include "console.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console.fullname" . }}-pprof
  labels:
    helm.sh/chart: {{ include "console.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.debugService.type }}
  ports:
    - port: {{ .Values.debugService.port }}
      targetPort: {{ .Values.debugService.containerPort }}
      protocol: TCP
      name: {{ include "console.name" . }}-debug
  selector:
    app.kubernetes.io/name: {{ include "console.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}