apiVersion: v1
kind: Secret
metadata:
  name: eventcenter-tls-client-cert-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "auth/client.crt" | b64enc }}
  tls.key: {{ .Files.Get "auth/client.key" | b64enc }}