apiVersion: v1
kind: Secret
metadata:
  name: eventcenter-tls-server-cert-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "auth/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "auth/server.key" | b64enc }}