apiVersion: v1
kind: Secret
metadata:
  name: eventcenter-tls-ca-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "auth/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "auth/ca.key" | b64enc }}