{{- if .Values.managedServiceAccount }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - "apps"
  - "batch"
  - "extensions"
  resources:
  - pods
  - replicasets
  verbs:
  - list
  - watch
  - get
{{- end -}}
