---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-scanner-report
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: kube-scanner-report
    spec:
      containers:
        - name: kube-scanner-report
          image: localhost:32000/kube-scanner-report:latest
          command: ["/kube-scanner-report"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "500m"
            limits:
              memory: "100Mi"
              cpu: "500m"
        - name: kube-scanner
          image: localhost:32000/kube-scanner:0.6.2
          command: [ "kube-scanner" ]
          args: ["--pod", "--report", "json", "--dispatch", "http"]
          env:
            - name: KUBEHUNTER_HTTP_DISPATCH_URL
              value: "http://localhost:8080"
            - name: KUBEHUNTER_HTTP_DISPATCH_METHOD
              value: "POST"
          resources:
            requests:
              cpu: "500m"
              memory: "100Mi"
            limits:
              memory: "100Mi"
              cpu: "500m"
      restartPolicy: Never
      imagePullSecrets:
        - name: harbor-admin-secret

  backoffLimit: 0
