// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: cluster.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ClusterService_SendMessage_FullMethodName = "/pb.ClusterService/SendMessage"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	SendMessage(ctx context.Context, opts ...grpc.CallOption) (ClusterService_SendMessageClient, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) SendMessage(ctx context.Context, opts ...grpc.CallOption) (ClusterService_SendMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClusterService_ServiceDesc.Streams[0], ClusterService_SendMessage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &clusterServiceSendMessageClient{stream}
	return x, nil
}

type ClusterService_SendMessageClient interface {
	Send(*ClusterMessage) error
	Recv() (*ClusterMessage, error)
	grpc.ClientStream
}

type clusterServiceSendMessageClient struct {
	grpc.ClientStream
}

func (x *clusterServiceSendMessageClient) Send(m *ClusterMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterServiceSendMessageClient) Recv() (*ClusterMessage, error) {
	m := new(ClusterMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations should embed UnimplementedClusterServiceServer
// for forward compatibility
type ClusterServiceServer interface {
	SendMessage(ClusterService_SendMessageServer) error
}

// UnimplementedClusterServiceServer should be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (UnimplementedClusterServiceServer) SendMessage(ClusterService_SendMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServiceServer).SendMessage(&clusterServiceSendMessageServer{stream})
}

type ClusterService_SendMessageServer interface {
	Send(*ClusterMessage) error
	Recv() (*ClusterMessage, error)
	grpc.ServerStream
}

type clusterServiceSendMessageServer struct {
	grpc.ServerStream
}

func (x *clusterServiceSendMessageServer) Send(m *ClusterMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterServiceSendMessageServer) Recv() (*ClusterMessage, error) {
	m := new(ClusterMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMessage",
			Handler:       _ClusterService_SendMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
