// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: compliance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplianceScanReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClusterKey     string   `protobuf:"bytes,1,opt,name=clusterKey,proto3" json:"clusterKey,omitempty"`
	NodeName       string   `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	RequestID      string   `protobuf:"bytes,3,opt,name=requestID,proto3" json:"requestID,omitempty"`
	CheckIds       []string `protobuf:"bytes,4,rep,name=checkIds,proto3" json:"checkIds,omitempty"`
	CheckType      string   `protobuf:"bytes,5,opt,name=checkType,proto3" json:"checkType,omitempty"`
	RuntimeName    string   `protobuf:"bytes,6,opt,name=runtimeName,proto3" json:"runtimeName,omitempty"`
	RuntimeVersion string   `protobuf:"bytes,7,opt,name=runtimeVersion,proto3" json:"runtimeVersion,omitempty"`
}

func (x *ComplianceScanReq) Reset() {
	*x = ComplianceScanReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_compliance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplianceScanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceScanReq) ProtoMessage() {}

func (x *ComplianceScanReq) ProtoReflect() protoreflect.Message {
	mi := &file_compliance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceScanReq.ProtoReflect.Descriptor instead.
func (*ComplianceScanReq) Descriptor() ([]byte, []int) {
	return file_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ComplianceScanReq) GetClusterKey() string {
	if x != nil {
		return x.ClusterKey
	}
	return ""
}

func (x *ComplianceScanReq) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ComplianceScanReq) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *ComplianceScanReq) GetCheckIds() []string {
	if x != nil {
		return x.CheckIds
	}
	return nil
}

func (x *ComplianceScanReq) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *ComplianceScanReq) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *ComplianceScanReq) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

var File_compliance_proto protoreflect.FileDescriptor

var file_compliance_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xf1, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x49,
	0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x49,
	0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_compliance_proto_rawDescOnce sync.Once
	file_compliance_proto_rawDescData = file_compliance_proto_rawDesc
)

func file_compliance_proto_rawDescGZIP() []byte {
	file_compliance_proto_rawDescOnce.Do(func() {
		file_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(file_compliance_proto_rawDescData)
	})
	return file_compliance_proto_rawDescData
}

var file_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_compliance_proto_goTypes = []interface{}{
	(*ComplianceScanReq)(nil), // 0: pb.complianceScanReq
}
var file_compliance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_compliance_proto_init() }
func file_compliance_proto_init() {
	if File_compliance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_compliance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplianceScanReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_compliance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_compliance_proto_goTypes,
		DependencyIndexes: file_compliance_proto_depIdxs,
		MessageInfos:      file_compliance_proto_msgTypes,
	}.Build()
	File_compliance_proto = out.File
	file_compliance_proto_rawDesc = nil
	file_compliance_proto_goTypes = nil
	file_compliance_proto_depIdxs = nil
}
