// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: image_sec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageSecReqType int32

const (
	ImageSecReqType_NodeImageScan        ImageSecReqType = 0
	ImageSecReqType_TiDBUpdate           ImageSecReqType = 1
	ImageSecReqType_ClamavDBUpdate       ImageSecReqType = 2
	ImageSecReqType_SyncResult           ImageSecReqType = 3
	ImageSecReqType_SyncConfig           ImageSecReqType = 4
	ImageSecReqType_AviraDBUpdate        ImageSecReqType = 5
	ImageSecReqType_RegistryImageScan    ImageSecReqType = 6
	ImageSecReqType_RegistryHealthyCheck ImageSecReqType = 7
	ImageSecReqType_RegistryImageSync    ImageSecReqType = 8
)

// Enum value maps for ImageSecReqType.
var (
	ImageSecReqType_name = map[int32]string{
		0: "NodeImageScan",
		1: "TiDBUpdate",
		2: "ClamavDBUpdate",
		3: "SyncResult",
		4: "SyncConfig",
		5: "AviraDBUpdate",
		6: "RegistryImageScan",
		7: "RegistryHealthyCheck",
		8: "RegistryImageSync",
	}
	ImageSecReqType_value = map[string]int32{
		"NodeImageScan":        0,
		"TiDBUpdate":           1,
		"ClamavDBUpdate":       2,
		"SyncResult":           3,
		"SyncConfig":           4,
		"AviraDBUpdate":        5,
		"RegistryImageScan":    6,
		"RegistryHealthyCheck": 7,
		"RegistryImageSync":    8,
	}
)

func (x ImageSecReqType) Enum() *ImageSecReqType {
	p := new(ImageSecReqType)
	*p = x
	return p
}

func (x ImageSecReqType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageSecReqType) Descriptor() protoreflect.EnumDescriptor {
	return file_image_sec_proto_enumTypes[0].Descriptor()
}

func (ImageSecReqType) Type() protoreflect.EnumType {
	return &file_image_sec_proto_enumTypes[0]
}

func (x ImageSecReqType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageSecReqType.Descriptor instead.
func (ImageSecReqType) EnumDescriptor() ([]byte, []int) {
	return file_image_sec_proto_rawDescGZIP(), []int{0}
}

type ImageSecDstType int32

const (
	ImageSecDstType_SubScanner     ImageSecDstType = 0
	ImageSecDstType_Console        ImageSecDstType = 1
	ImageSecDstType_ClusterManager ImageSecDstType = 2
	ImageSecDstType_MainScanner    ImageSecDstType = 3
)

// Enum value maps for ImageSecDstType.
var (
	ImageSecDstType_name = map[int32]string{
		0: "SubScanner",
		1: "Console",
		2: "ClusterManager",
		3: "MainScanner",
	}
	ImageSecDstType_value = map[string]int32{
		"SubScanner":     0,
		"Console":        1,
		"ClusterManager": 2,
		"MainScanner":    3,
	}
)

func (x ImageSecDstType) Enum() *ImageSecDstType {
	p := new(ImageSecDstType)
	*p = x
	return p
}

func (x ImageSecDstType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageSecDstType) Descriptor() protoreflect.EnumDescriptor {
	return file_image_sec_proto_enumTypes[1].Descriptor()
}

func (ImageSecDstType) Type() protoreflect.EnumType {
	return &file_image_sec_proto_enumTypes[1]
}

func (x ImageSecDstType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageSecDstType.Descriptor instead.
func (ImageSecDstType) EnumDescriptor() ([]byte, []int) {
	return file_image_sec_proto_rawDescGZIP(), []int{1}
}

type ImageSecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageSecReqType ImageSecReqType `protobuf:"varint,1,opt,name=ImageSecReqType,proto3,enum=pb.ImageSecReqType" json:"ImageSecReqType,omitempty"`
	ImageSecDstType ImageSecDstType `protobuf:"varint,2,opt,name=ImageSecDstType,proto3,enum=pb.ImageSecDstType" json:"ImageSecDstType,omitempty"`
	ImageSecDstPath string          `protobuf:"bytes,3,opt,name=ImageSecDstPath,proto3" json:"ImageSecDstPath,omitempty"`
	ClusterKey      string          `protobuf:"bytes,4,opt,name=ClusterKey,proto3" json:"ClusterKey,omitempty"`
	RequestID       string          `protobuf:"bytes,5,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	NodeName        []string        `protobuf:"bytes,6,rep,name=NodeName,proto3" json:"NodeName,omitempty"`
	Payload         []byte          `protobuf:"bytes,7,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *ImageSecReq) Reset() {
	*x = ImageSecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_sec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSecReq) ProtoMessage() {}

func (x *ImageSecReq) ProtoReflect() protoreflect.Message {
	mi := &file_image_sec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSecReq.ProtoReflect.Descriptor instead.
func (*ImageSecReq) Descriptor() ([]byte, []int) {
	return file_image_sec_proto_rawDescGZIP(), []int{0}
}

func (x *ImageSecReq) GetImageSecReqType() ImageSecReqType {
	if x != nil {
		return x.ImageSecReqType
	}
	return ImageSecReqType_NodeImageScan
}

func (x *ImageSecReq) GetImageSecDstType() ImageSecDstType {
	if x != nil {
		return x.ImageSecDstType
	}
	return ImageSecDstType_SubScanner
}

func (x *ImageSecReq) GetImageSecDstPath() string {
	if x != nil {
		return x.ImageSecDstPath
	}
	return ""
}

func (x *ImageSecReq) GetClusterKey() string {
	if x != nil {
		return x.ClusterKey
	}
	return ""
}

func (x *ImageSecReq) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *ImageSecReq) GetNodeName() []string {
	if x != nil {
		return x.NodeName
	}
	return nil
}

func (x *ImageSecReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ImageSecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusMessage string   `protobuf:"bytes,1,opt,name=StatusMessage,proto3" json:"StatusMessage,omitempty"`
	Status        int32    `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
	ErrNode       []string `protobuf:"bytes,3,rep,name=ErrNode,proto3" json:"ErrNode,omitempty"`
}

func (x *ImageSecResp) Reset() {
	*x = ImageSecResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_sec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageSecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSecResp) ProtoMessage() {}

func (x *ImageSecResp) ProtoReflect() protoreflect.Message {
	mi := &file_image_sec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSecResp.ProtoReflect.Descriptor instead.
func (*ImageSecResp) Descriptor() ([]byte, []int) {
	return file_image_sec_proto_rawDescGZIP(), []int{1}
}

func (x *ImageSecResp) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ImageSecResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ImageSecResp) GetErrNode() []string {
	if x != nil {
		return x.ErrNode
	}
	return nil
}

var File_image_sec_proto protoreflect.FileDescriptor

var file_image_sec_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xa9, 0x02, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x65, 0x63, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65,
	0x63, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x52, 0x65, 0x71, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x52, 0x65, 0x71,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63,
	0x44, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x44, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x44, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x44,
	0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x44, 0x73, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4e,
	0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x66, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x45, 0x72, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x2a, 0xc3, 0x01, 0x0a, 0x0f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x52, 0x65, 0x71, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a,
	0x0d, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x69, 0x44, 0x42, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x6d, 0x61, 0x76, 0x44, 0x42, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x76, 0x69, 0x72, 0x61, 0x44, 0x42, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x63, 0x61, 0x6e, 0x10, 0x06, 0x12, 0x18,
	0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x79, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x10, 0x08, 0x2a,
	0x53, 0x0a, 0x0f, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x44, 0x73, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x10, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_sec_proto_rawDescOnce sync.Once
	file_image_sec_proto_rawDescData = file_image_sec_proto_rawDesc
)

func file_image_sec_proto_rawDescGZIP() []byte {
	file_image_sec_proto_rawDescOnce.Do(func() {
		file_image_sec_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_sec_proto_rawDescData)
	})
	return file_image_sec_proto_rawDescData
}

var file_image_sec_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_image_sec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_sec_proto_goTypes = []interface{}{
	(ImageSecReqType)(0), // 0: pb.ImageSecReqType
	(ImageSecDstType)(0), // 1: pb.ImageSecDstType
	(*ImageSecReq)(nil),  // 2: pb.ImageSecReq
	(*ImageSecResp)(nil), // 3: pb.ImageSecResp
}
var file_image_sec_proto_depIdxs = []int32{
	0, // 0: pb.ImageSecReq.ImageSecReqType:type_name -> pb.ImageSecReqType
	1, // 1: pb.ImageSecReq.ImageSecDstType:type_name -> pb.ImageSecDstType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_image_sec_proto_init() }
func file_image_sec_proto_init() {
	if File_image_sec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_sec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_sec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageSecResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_sec_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_sec_proto_goTypes,
		DependencyIndexes: file_image_sec_proto_depIdxs,
		EnumInfos:         file_image_sec_proto_enumTypes,
		MessageInfos:      file_image_sec_proto_msgTypes,
	}.Build()
	File_image_sec_proto = out.File
	file_image_sec_proto_rawDesc = nil
	file_image_sec_proto_goTypes = nil
	file_image_sec_proto_depIdxs = nil
}
