// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: microseg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MicrosegAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=PodNamespace,proto3" json:"PodNamespace,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=PodName,proto3" json:"PodName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosegAddress) Reset() {
	*x = MicrosegAddress{}
	mi := &file_microseg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosegAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosegAddress) ProtoMessage() {}

func (x *MicrosegAddress) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosegAddress.ProtoReflect.Descriptor instead.
func (*MicrosegAddress) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{0}
}

func (x *MicrosegAddress) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *MicrosegAddress) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *MicrosegAddress) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type MicrosegIPBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CIDR          string                 `protobuf:"bytes,1,opt,name=CIDR,proto3" json:"CIDR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosegIPBlock) Reset() {
	*x = MicrosegIPBlock{}
	mi := &file_microseg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosegIPBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosegIPBlock) ProtoMessage() {}

func (x *MicrosegIPBlock) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosegIPBlock.ProtoReflect.Descriptor instead.
func (*MicrosegIPBlock) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{1}
}

func (x *MicrosegIPBlock) GetCIDR() string {
	if x != nil {
		return x.CIDR
	}
	return ""
}

type MicrosegPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	EndPort       int32                  `protobuf:"varint,3,opt,name=EndPort,proto3" json:"EndPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosegPort) Reset() {
	*x = MicrosegPort{}
	mi := &file_microseg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosegPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosegPort) ProtoMessage() {}

func (x *MicrosegPort) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosegPort.ProtoReflect.Descriptor instead.
func (*MicrosegPort) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{2}
}

func (x *MicrosegPort) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *MicrosegPort) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *MicrosegPort) GetEndPort() int32 {
	if x != nil {
		return x.EndPort
	}
	return 0
}

type MicrosegHttp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=Method,proto3" json:"Method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=Host,proto3" json:"Host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosegHttp) Reset() {
	*x = MicrosegHttp{}
	mi := &file_microseg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosegHttp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosegHttp) ProtoMessage() {}

func (x *MicrosegHttp) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosegHttp.ProtoReflect.Descriptor instead.
func (*MicrosegHttp) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{3}
}

func (x *MicrosegHttp) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MicrosegHttp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MicrosegHttp) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type MicrosegNodeRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=Priority,proto3" json:"Priority,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=Direction,proto3" json:"Direction,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=Action,proto3" json:"Action,omitempty"`
	Ports         []*MicrosegPort        `protobuf:"bytes,6,rep,name=Ports,proto3" json:"Ports,omitempty"`
	ToAddresses   []*MicrosegAddress     `protobuf:"bytes,7,rep,name=ToAddresses,proto3" json:"ToAddresses,omitempty"`
	ToIPBlock     []*MicrosegIPBlock     `protobuf:"bytes,8,rep,name=ToIPBlock,proto3" json:"ToIPBlock,omitempty"`
	FromAddress   []*MicrosegAddress     `protobuf:"bytes,9,rep,name=FromAddress,proto3" json:"FromAddress,omitempty"`
	FromIPBlock   []*MicrosegIPBlock     `protobuf:"bytes,10,rep,name=FromIPBlock,proto3" json:"FromIPBlock,omitempty"`
	Http          *MicrosegHttp          `protobuf:"bytes,11,opt,name=Http,proto3" json:"Http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicrosegNodeRule) Reset() {
	*x = MicrosegNodeRule{}
	mi := &file_microseg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicrosegNodeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosegNodeRule) ProtoMessage() {}

func (x *MicrosegNodeRule) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosegNodeRule.ProtoReflect.Descriptor instead.
func (*MicrosegNodeRule) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{4}
}

func (x *MicrosegNodeRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MicrosegNodeRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MicrosegNodeRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *MicrosegNodeRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *MicrosegNodeRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MicrosegNodeRule) GetPorts() []*MicrosegPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *MicrosegNodeRule) GetToAddresses() []*MicrosegAddress {
	if x != nil {
		return x.ToAddresses
	}
	return nil
}

func (x *MicrosegNodeRule) GetToIPBlock() []*MicrosegIPBlock {
	if x != nil {
		return x.ToIPBlock
	}
	return nil
}

func (x *MicrosegNodeRule) GetFromAddress() []*MicrosegAddress {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MicrosegNodeRule) GetFromIPBlock() []*MicrosegIPBlock {
	if x != nil {
		return x.FromIPBlock
	}
	return nil
}

func (x *MicrosegNodeRule) GetHttp() *MicrosegHttp {
	if x != nil {
		return x.Http
	}
	return nil
}

type NetworkPolicyRuleGroupPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Policy        string                 `protobuf:"bytes,2,opt,name=Policy,proto3" json:"Policy,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	Rules         []*MicrosegNodeRule    `protobuf:"bytes,4,rep,name=Rules,proto3" json:"Rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRuleGroupPayload) Reset() {
	*x = NetworkPolicyRuleGroupPayload{}
	mi := &file_microseg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRuleGroupPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRuleGroupPayload) ProtoMessage() {}

func (x *NetworkPolicyRuleGroupPayload) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRuleGroupPayload.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRuleGroupPayload) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkPolicyRuleGroupPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRuleGroupPayload) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *NetworkPolicyRuleGroupPayload) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NetworkPolicyRuleGroupPayload) GetRules() []*MicrosegNodeRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type NetworkPolicyRuleGroupReq struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RuleGroup     *NetworkPolicyRuleGroupPayload `protobuf:"bytes,1,opt,name=RuleGroup,proto3" json:"RuleGroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRuleGroupReq) Reset() {
	*x = NetworkPolicyRuleGroupReq{}
	mi := &file_microseg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRuleGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRuleGroupReq) ProtoMessage() {}

func (x *NetworkPolicyRuleGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRuleGroupReq.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRuleGroupReq) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkPolicyRuleGroupReq) GetRuleGroup() *NetworkPolicyRuleGroupPayload {
	if x != nil {
		return x.RuleGroup
	}
	return nil
}

type NetworkPolicyRuleGroupSyncReq struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	RuleGroups    []*NetworkPolicyRuleGroupPayload `protobuf:"bytes,1,rep,name=RuleGroups,proto3" json:"RuleGroups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRuleGroupSyncReq) Reset() {
	*x = NetworkPolicyRuleGroupSyncReq{}
	mi := &file_microseg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRuleGroupSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRuleGroupSyncReq) ProtoMessage() {}

func (x *NetworkPolicyRuleGroupSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRuleGroupSyncReq.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRuleGroupSyncReq) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkPolicyRuleGroupSyncReq) GetRuleGroups() []*NetworkPolicyRuleGroupPayload {
	if x != nil {
		return x.RuleGroups
	}
	return nil
}

type NetworkPolicyRuleGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRuleGroupResp) Reset() {
	*x = NetworkPolicyRuleGroupResp{}
	mi := &file_microseg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRuleGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRuleGroupResp) ProtoMessage() {}

func (x *NetworkPolicyRuleGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_microseg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRuleGroupResp.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRuleGroupResp) Descriptor() ([]byte, []int) {
	return file_microseg_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkPolicyRuleGroupResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NetworkPolicyRuleGroupResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_microseg_proto protoreflect.FileDescriptor

const file_microseg_proto_rawDesc = "" +
	"\n" +
	"\x0emicroseg.proto\x12\x02pb\"_\n" +
	"\x0fMicrosegAddress\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\"\n" +
	"\fPodNamespace\x18\x02 \x01(\tR\fPodNamespace\x12\x18\n" +
	"\aPodName\x18\x03 \x01(\tR\aPodName\"%\n" +
	"\x0fMicrosegIPBlock\x12\x12\n" +
	"\x04CIDR\x18\x01 \x01(\tR\x04CIDR\"X\n" +
	"\fMicrosegPort\x12\x1a\n" +
	"\bProtocol\x18\x01 \x01(\tR\bProtocol\x12\x12\n" +
	"\x04Port\x18\x02 \x01(\tR\x04Port\x12\x18\n" +
	"\aEndPort\x18\x03 \x01(\x05R\aEndPort\"N\n" +
	"\fMicrosegHttp\x12\x16\n" +
	"\x06Method\x18\x01 \x01(\tR\x06Method\x12\x12\n" +
	"\x04Path\x18\x02 \x01(\tR\x04Path\x12\x12\n" +
	"\x04Host\x18\x03 \x01(\tR\x04Host\"\xba\x03\n" +
	"\x10MicrosegNodeRule\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bPriority\x18\x02 \x01(\x05R\bPriority\x12\x1a\n" +
	"\bProtocol\x18\x03 \x01(\tR\bProtocol\x12\x1c\n" +
	"\tDirection\x18\x04 \x01(\tR\tDirection\x12\x16\n" +
	"\x06Action\x18\x05 \x01(\tR\x06Action\x12&\n" +
	"\x05Ports\x18\x06 \x03(\v2\x10.pb.MicrosegPortR\x05Ports\x125\n" +
	"\vToAddresses\x18\a \x03(\v2\x13.pb.MicrosegAddressR\vToAddresses\x121\n" +
	"\tToIPBlock\x18\b \x03(\v2\x13.pb.MicrosegIPBlockR\tToIPBlock\x125\n" +
	"\vFromAddress\x18\t \x03(\v2\x13.pb.MicrosegAddressR\vFromAddress\x125\n" +
	"\vFromIPBlock\x18\n" +
	" \x03(\v2\x13.pb.MicrosegIPBlockR\vFromIPBlock\x12$\n" +
	"\x04Http\x18\v \x01(\v2\x10.pb.MicrosegHttpR\x04Http\"\x93\x01\n" +
	"\x1dNetworkPolicyRuleGroupPayload\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Policy\x18\x02 \x01(\tR\x06Policy\x12\x1a\n" +
	"\bNodeName\x18\x03 \x01(\tR\bNodeName\x12*\n" +
	"\x05Rules\x18\x04 \x03(\v2\x14.pb.MicrosegNodeRuleR\x05Rules\"\\\n" +
	"\x19NetworkPolicyRuleGroupReq\x12?\n" +
	"\tRuleGroup\x18\x01 \x01(\v2!.pb.NetworkPolicyRuleGroupPayloadR\tRuleGroup\"b\n" +
	"\x1dNetworkPolicyRuleGroupSyncReq\x12A\n" +
	"\n" +
	"RuleGroups\x18\x01 \x03(\v2!.pb.NetworkPolicyRuleGroupPayloadR\n" +
	"RuleGroups\"L\n" +
	"\x1aNetworkPolicyRuleGroupResp\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05ErrorB\aZ\x05./;pbb\x06proto3"

var (
	file_microseg_proto_rawDescOnce sync.Once
	file_microseg_proto_rawDescData []byte
)

func file_microseg_proto_rawDescGZIP() []byte {
	file_microseg_proto_rawDescOnce.Do(func() {
		file_microseg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_microseg_proto_rawDesc), len(file_microseg_proto_rawDesc)))
	})
	return file_microseg_proto_rawDescData
}

var file_microseg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_microseg_proto_goTypes = []any{
	(*MicrosegAddress)(nil),               // 0: pb.MicrosegAddress
	(*MicrosegIPBlock)(nil),               // 1: pb.MicrosegIPBlock
	(*MicrosegPort)(nil),                  // 2: pb.MicrosegPort
	(*MicrosegHttp)(nil),                  // 3: pb.MicrosegHttp
	(*MicrosegNodeRule)(nil),              // 4: pb.MicrosegNodeRule
	(*NetworkPolicyRuleGroupPayload)(nil), // 5: pb.NetworkPolicyRuleGroupPayload
	(*NetworkPolicyRuleGroupReq)(nil),     // 6: pb.NetworkPolicyRuleGroupReq
	(*NetworkPolicyRuleGroupSyncReq)(nil), // 7: pb.NetworkPolicyRuleGroupSyncReq
	(*NetworkPolicyRuleGroupResp)(nil),    // 8: pb.NetworkPolicyRuleGroupResp
}
var file_microseg_proto_depIdxs = []int32{
	2, // 0: pb.MicrosegNodeRule.Ports:type_name -> pb.MicrosegPort
	0, // 1: pb.MicrosegNodeRule.ToAddresses:type_name -> pb.MicrosegAddress
	1, // 2: pb.MicrosegNodeRule.ToIPBlock:type_name -> pb.MicrosegIPBlock
	0, // 3: pb.MicrosegNodeRule.FromAddress:type_name -> pb.MicrosegAddress
	1, // 4: pb.MicrosegNodeRule.FromIPBlock:type_name -> pb.MicrosegIPBlock
	3, // 5: pb.MicrosegNodeRule.Http:type_name -> pb.MicrosegHttp
	4, // 6: pb.NetworkPolicyRuleGroupPayload.Rules:type_name -> pb.MicrosegNodeRule
	5, // 7: pb.NetworkPolicyRuleGroupReq.RuleGroup:type_name -> pb.NetworkPolicyRuleGroupPayload
	5, // 8: pb.NetworkPolicyRuleGroupSyncReq.RuleGroups:type_name -> pb.NetworkPolicyRuleGroupPayload
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_microseg_proto_init() }
func file_microseg_proto_init() {
	if File_microseg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_microseg_proto_rawDesc), len(file_microseg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_microseg_proto_goTypes,
		DependencyIndexes: file_microseg_proto_depIdxs,
		MessageInfos:      file_microseg_proto_msgTypes,
	}.Build()
	File_microseg_proto = out.File
	file_microseg_proto_goTypes = nil
	file_microseg_proto_depIdxs = nil
}
