version: "3.7"
services:
  clair:
    image: arminc/clair-local-scan:v2.0.6
    ports:
      - "6060:6060"
    links:
    - clair-db:postgres
    depends_on:
      - clair-db
    restart: always

  clair-db:
    image: arminc/clair-db:latest

  etcd:
    image: quay.io/coreos/etcd:v3.4.0
    ports:
      - "2379:2379"
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=default
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --auto-compaction-retention=24

  etcd-init:
    image: quay.io/coreos/etcd:v3.4.0
    volumes:
      - ./etcd:/usr/share/etcd:ro
    command:
      - /usr/share/etcd/init.sh
    depends_on:
      - etcd

  mongo:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: redstone
      MONGO_INITDB_ROOT_PASSWORD: redstoneMongo123

  mongo-express:
    image: mongo-express:0.49.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: redstone
      ME_CONFIG_MONGODB_ADMINPASSWORD: redstoneMongo123

  # registry:
  #   image: registry:2
  #   ports:
  #     - 5001:5000
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
      - transport.host=localhost
      - transport.tcp.port=9300
      - http.port=9200
      - http.host=0.0.0.0
      - cluster.name=vegeta
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  #
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.3.1
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   command: -f /usr/share/logstash/pipeline/logstash.conf
  #   ports:
  #     - "5000:5000"
  #     - "9600:9600"
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.3.1
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

  scanner:
    image: vegeta-scanner:latest
    expose:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      MONGO_ENDPOINT: "mongo:27017"
      CLAIR_REMOTE_ADDRESS: "clair"
      CLAIR_ADDRESS: "scanner"

  console:
    image: vegeta-console:latest
    ports:
      - 8080:8080
    environment:
      ETCD_ENDPOINTS: "etcd:2379"
      MONGO_ENDPOINT: "mongo:27017"
