{{- if .Values.persistence.enabled -}}
apiVersion: {{ include "common.capabilities.cronjob.apiVersion" . }}
kind: CronJob
metadata:
  name: cron-data-gc-coldcleaner
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: coldcleaner
spec:
  schedule: {{ .Values.persistence.Cleaner.coldCronjob.cronString }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      template:
        spec:
          containers:
            - command:
                - /app/cleaner
                - clear-cold-storage-tool
              env:
                - name: RDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "common.postgresql.defaultName" . }}
                      key: postgresql-password
                - name: AUDIT_PATH
                  value: /audit
              envFrom:
                - configMapRef:
                    name: common-env
              image: {{ include "jobs.cleaner.image" . }}
              imagePullPolicy: {{ .Values.persistence.Cleaner.image.pullPolicy }}
              name: coldcleaner
              resources:
{{ toYaml .Values.persistence.Cleaner.coldCronjob.resources | indent 16 }}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /audit
                  name: audit
          restartPolicy: Never
          imagePullSecrets:
            - name: {{ .Values.persistence.Cleaner.image.pullSecret }}
          volumes:
            - name: audit
              persistentVolumeClaim:
                claimName: audit-pvc
{{- end -}}