apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongo-express.fullname" . }}
  labels:
{{ include "mongo-express.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "mongo-express.name" . }}
      release: "{{ .Release.Name }}"
  replicas: 1
  template:
    metadata:
      labels:
{{ include "mongo-express.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ template "mongo-express.fullname" . }}
        image: mongo-express:{{ .Values.image.tag }}
        ports:
          - name: mongo-express
            containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_SERVER
            value: {{ .Values.mongodbHost | default (printf "%s-mongodb" .Release.Name) | quote }}
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: {{ quote .Values.mongodbPassword }}
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: {{ quote .Values.mongodbUsername }}
