{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - "security-profiles-operator.x-k8s.io"
      - "apps"
    resources:
      - seccompprofiles
      - namespaces
      - pods
      - services
      - deployments
      - replicasets
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - extensions
      - ""
    resources:
      - nodes
      - namespaces
      - pods
      - replicationcontrollers
      - replicasets
      - services
      - daemonsets
      - deployments
      - events
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /healthz
      - /healthz/*
    verbs:
      - get
{{- if .Values.podSecurityPolicy.create }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "common.names.fullname" . }}
{{- if .Values.fakeEventGenerator.enabled }}
      - event-generator-{{ include "common.names.fullname" . }}
{{- end }}
    verbs:
      - use
{{- end }}
{{- end }}
