apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rules
data:
{{- range $file, $content :=  .Values.customRules }}
  {{ $file }}: |-
{{ $content | indent 4}}
{{- end }}
