apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: holmes
  template:
    metadata:
      name: {{ include "common.names.fullname" . }}
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: holmes
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/rules: {{ include (print $.Template.BasePath "/configmap-rules.yaml") . | sha256sum }}
        {{- if .Values.certs }}
        checksum/certs: {{ include (print $.Template.BasePath "/secret-certs.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.daemonset.podAnnotations }}
{{ toYaml .Values.daemonset.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "common.names.fullname" . }}
      {{- if or (and .Values.ebpf.enabled .Values.ebpf.settings.hostNetwork) .Values.daemon.enabled }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: daemon
          image: {{ include "daemon.image" . }}
          imagePullPolicy: {{ .Values.daemon.image.pullPolicy }}
          volumeMounts:
            - mountPath: /auth/server
              name: server-cert
              readOnly: true
            {{- if and .Values.falco.grpc.enabled .Values.falco.grpc.unixSocketPath }}
            - mountPath: {{ include "falco.unixSocketDir" . }}
              name: grpc-socket-dir
            {{- end }}
          securityContext:
            privileged: true
            runAsUser: 0
          args: []
          resources:
{{ toYaml .Values.daemon.resources | trim | indent 12 }}
          env:
            - name: RTDETECT_UDS_ADDR
              value: {{ .Values.falco.grpc.unixSocketPath }}
            - name: STAN_CLUSTER_ID
              value: manager
            - name: STAN_URL
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "{{ include "common.stan.defaultName" . }}-headless:4222"
              {{- else }}
              value: "{{ .Values.global.multiCluster.configs.stanExternalHost }}:{{ .Values.global.multiCluster.configs.stanExternalPort }}"
              {{- end }}
            - name: CONSOLE_ADDR
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "http://{{ include "common.console.defaultName" . }}:8889"
              {{- else }}
              value: "{{ .Values.global.multiCluster.configs.consoleExternalAdd }}"
              {{- end }}
            - name: CLUSTER_ADDR
              value: "http://{{ include "common.cluster-manager.defaultName" . }}:9443"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_HOST_IP
              valueFrom:
               fieldRef:
                   fieldPath: status.hostIP
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: EVENT_GRPC_URL
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "{{ include "common.eventcenter.defaultName" . }}:9090"
              {{- else }}
              value: {{ .Values.global.multiCluster.configs.eventcenterGrpcExternalAddr }}
              {{- end }}
            - name: EVENT_GRPC_CERT_PATH
              value: /auth/server/tls.crt
            - name: EVENT_GRPC_CERT_SERVER_NAME
              value: eventcenter
            - name: REDIS_ADDR
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "{{ include "common.redis.sentinel.address" . }}"
              {{- else }}
              value: ""
              {{- end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.redis-ha.defaultName" . }}
                  key: auth
        - name: falco
          image: {{ template "falco.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | trim | indent 12 }}
          securityContext:
            privileged: true
          args:
            - /usr/bin/holmes
            {{- if .Values.containerd.enabled }}
            - --cri
            - /run/containerd/containerd.sock
            {{- end }}
            - -K
            - /var/run/secrets/kubernetes.io/serviceaccount/token
            - -k
            - "https://$(KUBERNETES_SERVICE_HOST)"
            - -pk
        {{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 12 }}
        {{- end }}
          readinessProbe:
            exec:
              command:
              - grep
              - -q
              - "ready"
              - /var/log/holmes.log
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: CONSOLE_HTTP_ADDR
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "http://{{ include "common.console.defaultName" . }}:8889"
              {{- else }}
              value: "{{ .Values.global.multiCluster.configs.consoleExternalAdd }}"
              {{- end }}
            - name: EVENT_GRPC_URL
              {{- if .Values.global.multiCluster.isMainCluster }}
              value: "{{ include "common.eventcenter.defaultName" . }}:9090"
              {{- else }}
              value: {{ .Values.global.multiCluster.configs.eventcenterGrpcExternalAddr }}
              {{- end }}
            - name: EVENT_GRPC_CERT_PATH
              value: /auth/server/tls.crt
            - name: EVENT_GRPC_CERT_SERVER_NAME
              value: {{ include "common.eventcenter.defaultName" . }}
          {{- if .Values.ebpf.enabled }}
            - name: HOLMES_BPF_PROBE
              value: {{ .Values.ebpf.path }}
          {{- end }}
          {{- if .Values.proxy.httpProxy }}
            - name: http_proxy
              value: {{ .Values.proxy.httpProxy }}
          {{- end }}
          {{- if .Values.proxy.httpsProxy }}
            - name: https_proxy
              value: {{ .Values.proxy.httpsProxy }}
          {{- end }}
          {{- if .Values.proxy.noProxy }}
            - name: no_proxy
              value: {{ .Values.proxy.noProxy }}
          {{- end }}
          {{- if .Values.timezone }}
            - name: TZ
              value: {{ .Values.timezone }}
          {{- end }}
          {{- range $key, $value := .Values.daemonset.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          volumeMounts:
            {{- if .Values.docker.enabled }}
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            {{- end}}
            {{- if .Values.containerd.enabled }}
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            {{- end}}
            - mountPath: /auth/server
              name: server-cert
            - mountPath: /host/dev
              name: dev-fs
              readOnly: true
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              name: etc-fs
              readOnly: true
            - mountPath: /etc/holmes
              name: config-volume
            - mountPath: /etc/holmes/rules.d
              name: rules-volume
            {{- if and .Values.falco.grpc.enabled .Values.falco.grpc.unixSocketPath }}
            - mountPath: {{ include "falco.unixSocketDir" . }}
              name: grpc-socket-dir
            {{- end }}
            {{- if or .Values.falco.webserver.sslEnabled (and .Values.falco.grpc.enabled (not .Values.falco.grpc.unixSocketPath)) }}
            - mountPath: /etc/holmes/certs
              name: certs-volume
              readOnly: true
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.docker.enabled }}
        - name: docker-socket
          hostPath:
            path: {{ .Values.docker.socket }}
        {{- end}}
        {{- if .Values.containerd.enabled }}
        - name: containerd-socket
          hostPath:
            path: {{ .Values.containerd.socket }}
        {{- end}}
        - name: dev-fs
          hostPath:
            path: /dev
        - name: proc-fs
          hostPath:
            path: /proc
        - name: boot-fs
          hostPath:
            path: /boot
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: usr-fs
          hostPath:
            path: /usr
        - name: etc-fs
          hostPath:
            path: /etc
        - name: server-cert
          secret:
            defaultMode: 400
            secretName: eventcenter-tls-server-cert-secret
        - name: config-volume
          configMap:
            name: {{ include "common.names.fullname" . }}
            items:
              - key: holmes.yaml
                path: holmes.yaml
              # - key: falco_rules.yaml
              #   path: falco_rules.yaml
              # - key: falco_rules.local.yaml
              #   path: falco_rules.local.yaml
              # - key: application_rules.yaml
              #   path: rules.available/application_rules.yaml
              # {{- if .Values.auditLog.enabled }}
              # - key: k8s_audit_rules.yaml
              #   path: k8s_audit_rules.yaml
              # {{- end }}
        - name: rules-volume
          configMap:
            name: {{ include "common.names.fullname" . }}-rules
        {{- if and .Values.falco.grpc.enabled .Values.falco.grpc.unixSocketPath }}
        - name: grpc-socket-dir
          hostPath:
            path: {{ include "falco.unixSocketDir" . }}
            type: DirectoryOrCreate
        {{- end }}
        {{- if or .Values.falco.webserver.sslEnabled (and .Values.falco.grpc.enabled (not .Values.falco.grpc.unixSocketPath)) }}
        - name: certs-volume
          secret:
            secretName: {{ include "common.names.fullname" . }}-certs
            items:
              - key: server.key
                path: server.key
              - key: server.crt
                path: server.crt
              - key: server.pem
                path: server.pem
              - key: ca.crt
                path: ca.crt
        {{- end }}
        {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end }}
  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}
