{{- if .Values.fakeEventGenerator.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-event-generator" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas:  {{ .Values.fakeEventGenerator.replicas }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: event-generator
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: event-generator
    spec:
      serviceAccountName: {{ template "falco.serviceAccountName" .}}
      containers:
      - name: {{ printf "%s-event-generator" (include "common.names.fullname" .) }}
        securityContext:
            privileged: false
        image: falcosecurity/event-generator:latest
{{- with .Values.fakeEventGenerator.args }}
        args:
{{ toYaml . | indent 10 }}
{{- end }}
{{- end }}
