{{- if .Values.podSecurityPolicy.create}}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodSecurityPolicy
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  privileged: true
  hostNetwork: true
  allowedCapabilities: ['*']
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes: ['*']
{{- end }}
{{- if (and .Values.podSecurityPolicy.create .Values.fakeEventGenerator.enabled) }}
---
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodSecurityPolicy
metadata:
  name: {{ printf "%s-event-generator" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: event-generator
spec:
  privileged: false
  hostNetwork: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes: []
{{- end }}
