apiVersion: v1
kind: Service
metadata:
  name: tensorsec-webhook
  namespace: tensorsec-test-cn
  labels:
    app: tensorsec-webhook
spec:
  ports:
    - port: 443
      targetPort: 9443
      #nodePort: 30443
  #type: NodePort
  selector:
    app: tensorsec-webhook