FROM ubuntu

ARG MIRROR=archive.ubuntu.com
RUN sed -i "s!archive.ubuntu.com/!${MIRROR}/!g" /etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get install -y --no-install-recommends build-essential

ADD src /src

WORKDIR /src

RUN gcc -shared -fPIC -o dp.so preload.c log.c -ldl

CMD ["tail", "-f", "/dev/null"]
