FROM alpine

ARG MIRROR=dl-cdn.alpinelinux.org
RUN sed -i "s/dl-cdn.alpinelinux.org/${MIRROR}/g" /etc/apk/repositories

RUN apk update && apk add --virtual build-dependencies \
    build-base \
    gcc \
    make \
    openssl \
    openssl-dev

ADD src /src

WORKDIR /src

# RUN gcc -shared -fPIC -o dp.so preload.c log.c -ldl -lssl -lcrypto
RUN make all

CMD ["tail", "-f", "/dev/null"]
