##attck_rule_type=Credential_Access
- key: Gaining environment information
  hid: ca_01
  condition: >
    open_read and container and
    ((proc.name in (show_information_binaries)) and (fd.filename in (sensitive_paths) or fd.name in (sensitive_paths) or fd.directory in (sensitive_paths)) 
    or (proc.name in (show_env_binaries)))
    and not tensorsec_namespace
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,fd_name=%fd.name,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Gaining environment information"
      zh: "容器内获取环境信息"
    desc:
      en: "Generally, we believe that normal users in the container will not perform this behavior. There is a high probability that after the attack, the attacker will execute env, access hosts, .dockerenv, mountinfo and other sensitive files in order to obtain environment information in the container, which are considered potential attacks. behavior because obtaining environmental information may include attempts to identify and exploit vulnerabilities or weaknesses in the container or host system. Obtain the environment information within the container, including environment variables, host name, IP address, file system structure, process information, network connection information, mount information, etc., to learn more about the container's configuration and potential weaknesses to perform potential malicious activities."
      zh: "通常我们认为在容器内正常用户不会进行此行为，大概率是攻击者在进行攻击后，为了在容器内获取环境信息执行env、访问hosts、.dockerenv、mountinfo等敏感文件被视为潜在的攻击行为，这是因为获取环境信息可能包括试图识别和利用容器或主机系统中的漏洞或弱点。获取容器内的环境信息，包括环境变量、主机名、IP地址、文件系统结构、进程信息、网络连接信息、挂载信息等，以详细了解容器的配置和潜在弱点，从而执行潜在的恶意活动。"
    suggestion:
      en: "(1). Please first combine the process command line, (parent) process name, file path and other fields of the alarm to initially determine whether it is a business, R&D/operation and maintenance behavior (2). If it is a repeated expected behavior, and after investigation After judging that the security risk is controllable, you can consider whitening it (3). If it is an unexpected behavior, please conduct correlation analysis through the container ID, associated alarm list, etc., and check whether the command line includes env, capsh and other commands or read /proc/self/status, /etc/hosts and other files, contact security personnel promptly for further investigation"
      zh: "(1).请先结合告警的进程命令行、(父)进程名、文件路径等字段初步判断是否为业务、研发/运维的行为 (2).如果是重复出现的预期行为，且经排查后判断安全风险可控，可以考虑对其进行加白 (3).如果是非预期行为，请通过容器id、关联告警列表等内容进行关联分析，查看命令行是否包括env、capsh等命令或读取/proc/self/status、/etc/hosts等文件，及时联系安全人员进一步排查"
    rule_type: Credential_Access
    priority: WARNING
    urgency: true
    tags: [ATT&CK, exec, container, mitre_credential_access, L2]

# - key: Read sensitive file trusted after startup
#   hid: ca_02
#   condition: >
#     sensitive_files and open_read and server_procs and not proc_is_new and proc.name!="sshd" and not user_known_read_sensitive_files_activities and not tensorsec_namespace
#   output: >
#     proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,parent=%proc.pname,file=%fd.name,parent=%proc.pname,gparent=%proc.aname[2],container_id=%container.id,container_name=%container.name,image=%container.image.repository
#   info:
#     name:
#       en: "Read sensitive file trusted after startup"
#       zh: "敏感文件在启动后被受信任的程序读取"
#     desc:
#       en: "an attempt to read any sensitive file (e.g. files containing user/password/authentication information) by a trusted program after startup. Trusted programs might read these files at startup to load initial state, but not afterwards."
#       zh: "容器内敏感文件启动后被受信任的程序读取"
#     suggestion:
#       en: "Please confirm whether the reading behavior is as expected. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit mounting sensitive directories and files."
#       zh: "请确认该读取行为是否属于进程的正常行为，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
#     rule_type: Credential_Access
#     priority: INFO
#     urgency: true
#     tags: [ATT&CK, filesystem, mitre_credential_access]

- key: Search Private Keys or Passwords
  hid: ca_03
  condition: >
    spawned_process and
    ((grep_commands and private_key_or_password) or
     (proc.name = "find" and (proc.args contains "id_rsa" or proc.args contains "id_dsa")))
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container_id=%container.id,container_name=%container.name,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Search Private Keys or Passwords"
      zh: "容器内查找私钥或密码"
    desc:
      en: "Usually we believe that normal users in the container will not perform this behavior. The high probability is that after the attack, the attacker searches for secret key files such as keys and tokens in order to find the private key or password in the container, and is marked as an attack. behavior because this involves accessing sensitive credentials and confidential information that generally should not be accessed by unauthorized entities. Attackers attempt to find information containing sensitive credentials, private keys, or passwords within the container to gain unauthorized access or conduct malicious activity."
      zh: "通常我们认为在容器内正常用户不会进行此行为，大概率是攻击者在进行攻击后，为了在容器内查找私钥或密码执行了搜索key、token之类的秘钥文件，被标记为攻击行为是因为这涉及访问敏感凭据和机密信息，这些信息通常不应由未经授权的实体访问。攻击者试图在容器内查找包含敏感凭据、私钥或密码的信息，以获取未经授权的访问或进行恶意活动。"
    suggestion:
      en: "(1). Please first combine the process command line, (parent) process name, file path and other fields of the alarm to initially determine whether it is a business, R&D/operation and maintenance behavior (2). If it is a repeated expected behavior, and after investigation After judging that the security risk is controllable, you can consider whitening it (3). If it is an unexpected behavior, please conduct correlation analysis through the container id, associated alarm list, etc., and check whether the command line includes find, grep, ag, etc. to find id_rsa , pass, etc., promptly contact security personnel for further investigation"
      zh: "(1).请先结合告警的进程命令行、(父)进程名、文件路径等字段初步判断是否为业务、研发/运维的行为 (2).如果是重复出现的预期行为，且经排查后判断安全风险可控，可以考虑对其进行加白 (3).如果是非预期行为，请通过容器id、关联告警列表等内容进行关联分析，查看命令行是否包括find、grep、ag等查找id_rsa、pass等，及时联系安全人员进一步排查"
    rule_type: Credential_Access
    priority: WARNING
    urgency: true
    tags: [ATT&CK, filesystem, container, mitre_credential_access, L4]