{{- if  eq .Values.auditdLogging true }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "seccompGenerator.fullname" . }}-audit
  labels:
    app: {{ include "seccompGenerator.fullname" . }}-audit
    chart: {{ include "seccompGenerator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "seccompGenerator.fullname" . }}-audit
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ template "seccompGenerator.fullname" . }}-audit
      labels:
        app: {{ include "seccompGenerator.fullname" . }}-audit
        chart: {{ include "seccompGenerator.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ template "seccompGenerator.fullname" . }}-audit
        image: "{{ .Values.global.ourDockerRepo }}/{{ .Values.audit.image.name }}:{{ .Values.audit.image.tag }}"
        imagePullPolicy: {{ .Values.audit.image.pullPolicy }}
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: TENSORSEC_CONSOLE_HOST
          value: tensorsec-console.tensorsec-test.svc.cluster.local
        - name: TENSORSEC_CONSOLE_PORT
          value: "8889"
        volumeMounts:
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /host/proc
          readOnly: true
        resources:
          limits:
            memory: 200Mi
      imagePullSecrets:
      - name: {{ .Values.audit.image.pullSecret }}
      hostPID: true
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
{{ end }}
