---
apiVersion: batch/v1
kind: Job
metadata:
  name: host-bench
spec:
  template:
    metadata:
      labels:
        app: host-bench
    spec:
      containers:
        - name: host-bench
          image: localhost:32000/host-bench:latest
          command: ["./entrypoint.sh"]
          imagePullPolicy: Always
          volumeMounts:
            - name: mnt-root
              mountPath: /mnt/root
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: mnt-root
          hostPath:
            path: "/"
