global:
  image: 
    registry: ""
    repository: ""


image:
  registry: localhost:32000
  repository: library
  name: scanner
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

dockerregistry:
  image:
    registry: localhost:32000
    repository: library
    name: scanner-registry
    tag: latest
  resources:
    requests:
      cpu: "200m"
      memory: "500Mi"
    limits:
      cpu: "200m"
      memory: "500Mi"
  service:
    type: ClusterIP
    # clusterIP:
    httpPort: 5000
    gcPort: 8081
    # httpNodePort:
    # gcNodePort:
  persistence:
    enabled: true
    storageClass: "nfs-client-provisioner"
    size: 10Gi
    accessMode: 'ReadWriteOnce'
  # Set this to name of secret for tls certs
  # tlsSecretName: registry.docker.example.com
  secrets:
    # If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
    # e.g. "htpasswd -nbBC10 $username $password"
    # Default: admin:Registry@Passw0rd
    htpasswd: "admin:$2y$10$yWUFU9JunbmozLTeFEKxsOLnRaf1465xBQ6GWGDcmGy5GBa2WVHs6"
  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
  securityContext:
    enabled: true
    runAsUser: 1000
    fsGroup: 1000

webshell:
  image:
    registry:  localhost:32000
    repository: library
    name: webshell-server
    tag: latest
  replicas: 2
  resources:
    limits:
      cpu: "200m"
      memory: "200Mi" 
    requests:
      cpu: "200m"
      memory: "200Mi"
  service:
    type: ClusterIP
    # clusterIP:
    port: 80
    # nodePort:

scanreport:
  image:
    registry: localhost:32000
    repository: library
    name: scan-report
    tag: latest
  replicas: 1
  resources:
    limits:
      cpu: "200m"
      memory: "300Mi" 
    requests:
      cpu: "200m"
      memory: "300Mi"
  interval: 5m
  emailCheck:
    smtpHost: smtp.feishu.cn
    smtpPort: 465
    smtpUsername: console-robot@example.com
    smtpPassword: password

## Deployment pod host aliases
#  hostAliases:
#  - ip: "192.168.x.x"
#    hostnames:
#    - "xxx.xxx.com"
hostAliases: []

nameOverride: "scanner"
fullnameOverride: "scanner"

restartPolicy: Always

service:
  type: NodePort
  ApiPort: 8888
  ApiContainerPort: 8080
  CachePort: 9278
  ImageCacheServerPort: 9278

replicaCount: 1

apiInstallLabel: "scanner/install"

resources:
  requests:
    cpu: "2000m"
    memory: "4000Mi"
  limits:
    cpu: "2000m"
    memory: "4000Mi"

init: 
  image:
    registry: localhost:32000
    repository: library
    name: alpine
    tag: latest
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

persistence:
  enabled: true
  storageClass: "nfs-client-provisioner"
  accessModes:
    - ReadWriteOnce
  size: 4Gi