global:
  image: 
    registry: ""
    repository: ""


## tensorsec scannner image name
image:
  registry:  localhost:32000
  repository: tensorsecurity
  name: tensorsec-scanner
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

dockerregistry:
  image:
    registry:  localhost:32000
    repository: tensorsecurity
    name: tensorsec-scanner-registry
    tag: latest
  resources:
    requests:
      cpu: "200m"
      memory: "500Mi"
    limits:
      cpu: "200m"
      memory: "500Mi"
  service:
    type: ClusterIP
    # clusterIP:
    httpPort: 5000
    gcPort: 8081
    # httpNodePort:
    # gcNodePort:
  persistence:
    enabled: true
    storageClass: "nfs-client-provisioner"
    size: 10Gi
    accessMode: 'ReadWriteOnce'
  # Set this to name of secret for tls certs
  # tlsSecretName: registry.docker.example.com
  secrets:
    # If you update the username or password of registry, make sure use cli tool htpasswd to generate the bcrypt hash
    # e.g. "htpasswd -nbBC10 $username $password"
    # Default: tensorsec:TensorSec@Passw0rd
    htpasswd: "tensorsec:$2y$10$zYHR.AGhdeKnjpxIKU3.3.XH9MeEUdmSJZil9MUWlqB8b2Q3th7PK"
  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
  securityContext:
    enabled: true
    runAsUser: 1000
    fsGroup: 1000

webshell:
  image:
    registry:  localhost:32000
    repository: tensorsecurity
    name: webshell-server
    tag: latest
  replicas: 2
  resources:
    limits:
      cpu: "100m"
      memory: "200Mi" 
    requests:
      cpu: "100m"
      memory: "200Mi"
  service:
    type: ClusterIP
    # clusterIP:
    port: 80
    # nodePort:

## Deployment pod host aliases
#  hostAliases:
#  - ip: "192.168.x.x"
#    hostnames:
#    - "xxx.xxx.com"
hostAliases: []

nameOverride: "scanner"
fullnameOverride: "tensorsec-scanner"

restartPolicy: Always

service:
  type: NodePort
  ApiPort: 8888
  ApiContainerPort: 8080
  LayerPort: 9278
  LayerContainerPort: 9278

replicaCount: 1

apiInstallLabel: "scanner.tensorsec/install"

resources:
  requests:
    cpu: "1000m"
    memory: "2000Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"

clair:
  postgresURI: "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"

redis:
  redisSecretName: redis-secret

mongo:
  mongoUsername: redstone
  mongoDatabase: vegeta
  mongoSecretName: tensorsec-mongodb # needs keey mongodb-password

init: 
  image:
    registry:  localhost:32000
    repository: tensorsecurity
    name: alpine
    tag: latest
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
