imagePullSecrets:
  - name: vegeta-gitlab

nameOverride: "scanner"
fullnameOverride: "scanner"

serviceNamespace: default
restartPolicy: Always

service:
  type: ClusterIP
  port: 8888

replicaCount: 1

apiInstallLabel: "scanner.vegeta/install"

image:
  repository: registry.gitlab.com/piccolo_su/vegeta
  tag: scanner
  pullPolicy: IfNotPresent
