{{- if .Values.global.multiCluster.isMemberCluster -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-redis
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  auth: {{ .Values.redis.password | b64enc | quote }}
{{- end -}}