apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dockerregistry-htpasswd" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dockerregistry-htpasswd
type: Opaque
data:
  htpasswd: {{ (include "scanner.docker.registry.htpasswd" .) | b64enc | quote }}