apiVersion: v1
kind: Service
metadata:
  name: {{ template "scanner.fullname" . }}-dockerregistry
  labels:
    app: {{ template "scanner.fullname" . }}-dockerregistry
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.dockerregistry.service.type }}
  {{- if (and (eq .Values.dockerregistry.service.type "ClusterIP") (not (empty .Values.dockerregistry.service.clusterIP))) }}
  clusterIP: {{ .Values.dockerregistry.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.dockerregistry.service.port }}
      protocol: TCP
      name: http
      targetPort: 5000
      {{- if (and (eq .Values.dockerregistry.service.type "NodePort") (not (empty .Values.dockerregistry.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "scanner.fullname" . }}-dockerregistry
    release: {{ .Release.Name }}