{{- if .Values.dockerregistry.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dockerregistry
spec:
  accessModes:
    - {{ .Values.dockerregistry.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dockerregistry.persistence.size | quote }}
  {{ include "common.storage.class" (dict "persistence" .Values.dockerregistry.persistence "global" .Values.global) }}
{{- end -}}
