apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dockerregistry-normal" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dockerregistry-normal
type: Opaque
data:
  pass: {{ .Values.dockerregistry.secrets.password | b64enc | quote }}