apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dockerregistry
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: dockerregistry
  replicas: 1
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: dockerregistry
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      {{- if .Values.dockerregistry.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.dockerregistry.securityContext.fsGroup }}
        runAsUser: {{ .Values.dockerregistry.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: dockerregistry
          image: {{ include "scanner.docker.registry.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.dockerregistry.service.httpPort }}
              name: http
            - containerPort: {{ .Values.dockerregistry.service.gcPort }}
              name: gc
          resources:
{{ toYaml .Values.dockerregistry.resources | indent 12 }}
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            {{- if .Values.dockerregistry.tlsSecretName }}
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /etc/ssl/docker/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /etc/ssl/docker/tls.key
            {{- end }}
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
            {{- if .Values.dockerregistry.persistence.deleteEnabled }}
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
            {{- end }}
          volumeMounts:
            - name: auth
              mountPath: /auth
              readOnly: true
            - name: data
              mountPath: /var/lib/registry/
            - name: "{{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}"
              mountPath: "/etc/docker/registry"
            {{- if .Values.dockerregistry.tlsSecretName }}
            - mountPath: /etc/ssl/docker
              name: tls-cert
              readOnly: true
            {{- end }}
      volumes:
        - name: auth
          secret:
            secretName: {{ printf "%s-dockerregistry-htpasswd" (include "common.names.fullname" .) }}
            items:
            - key: htpasswd
              path: htpasswd
        - name: data
          {{- if .Values.dockerregistry.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
          configMap:
            name: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
        {{- if .Values.dockerregistry.tlsSecretName }}
        - name: tls-cert
          secret:
            secretName: {{ .Values.dockerregistry.tlsSecretName }}
        {{- end }}