apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dockerregistry
type: Opaque
data:
  {{- if .Values.dockerregistry.secrets.htpasswd }}
  htpasswd: {{ .Values.dockerregistry.secrets.htpasswd | b64enc }}
  {{- end }}