{{- if .Values.dockerregistry.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "scanner.fullname" . }}-dockerregistry
  labels:
    app: {{ template "scanner.fullname" . }}-dockerregistry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.dockerregistry.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.dockerregistry.persistence.size | quote }}
  {{ include "tensorsec.common.storage.class" (dict "persistence" .Values.dockerregistry.persistence "global" .Values.global) }}
{{- end -}}
