apiVersion: v1
kind: Secret
metadata:
  name: {{ template "scanner.fullname" . }}-dockerregistry
  labels:
    app: {{ template "scanner.fullname" . }}-dockerregistry
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.dockerregistry.secrets.htpasswd }}
  htpasswd: {{ .Values.dockerregistry.secrets.htpasswd | b64enc }}
  {{- end }}