global:
  image: 
    registry: ""
    repository: ""

image:
  registry:  localhost:32000
  repository: library
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

nameOverride: "palace"
fullnameOverride: "palace"

restartPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"

initContainers:
  image:
    registry:  localhost:32000
    repository: library
    name: alpine
    tag: latest
    pullPolicy: Always
    pullSecret: harbor-admin-secret
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "50m"
stan:
  clusterID: manager

managedServiceAccount: true
