apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-webhook-certgen" (include "common.names.fullname" .) }}-{{ .Release.Revision }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
spec:
  template:
    metadata:
      name: {{ printf "%s-webhook-certgen" (include "common.names.fullname" .) }}-{{ .Release.Revision }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: sec-prof-man-webhook
    spec:
      initContainers:
        - name: create
          image: {{ include "secProfilesManager.certgen.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - create
            - --host={{ printf "%s-webhook" (include "common.names.fullname" .) }},{{ printf "%s-webhook" (include "common.names.fullname" .) }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ printf "%s-webhook" (include "common.names.fullname" .) }}
            - --cert-name=tls.crt
            - --key-name=tls.key
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      containers:
        - name: patch
          image: {{ include "secProfilesManager.certgen.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ printf "%s-webhook" (include "common.names.fullname" .) }}
            - --namespace={{ .Release.Namespace }}
            - --patch-mutating=true
            - --patch-validating=false
            - --secret-name={{ printf "%s-webhook" (include "common.names.fullname" .) }}
            - --patch-failure-policy=Ignore
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      restartPolicy: OnFailure
      serviceAccountName: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
