apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
    namespace: {{ .Release.Namespace }}
