---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "secProfilesManager.fullname" . }}-config
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  presets.yaml: |
    env:
    - name: LD_PRELOAD
      value: "/tensorsec/dp.so"
    - name: TENSORSEC_EVENTCENTER_NEW_ADDR
      value: "{{ .Values.eventcenter.addr }}.{{ .Release.Namespace }}.svc.cluster.local"
    - name: TENSORSEC_EVENTCENTER_NEW_PORT
      value: "{{ .Values.eventcenter.port }}"
    volumemounts:
    - name: "{{ .Values.volumes.clientName }}"
      mountpath: "{{ .Values.volumes.clientMountPath }}"
      readonly: true
    - name: {{ .Values.volumes.caName }}
      mountpath: "{{ .Values.volumes.caMountPath }}"
      readonly: true
    volumes:
      - name: "{{ .Values.volumes.clientName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.clientSecretName }}"
      - name: "{{ .Values.volumes.caName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.caSecretName }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "secProfilesManager.serviceAccount" . }}-webhook-cluster-role
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-webhook"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups:
    - ""
    - "apps"
    - "batch"
    - "extensions"
    resources:
    - pods
    - replicasets
    verbs:
    - list
    - watch
    - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "secProfilesManager.serviceAccount" . }}-webhook-service-account
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-webhook"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "secProfilesManager.serviceAccount" . }}-webhook-cluster-role-binding
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-webhook"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "secProfilesManager.serviceAccount" . }}-webhook-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "secProfilesManager.serviceAccount" . }}-webhook-service-account
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "secProfilesManager.fullname" . }}-webhook-service
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-webhook"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: {{ template "secProfilesManager.fullname" . }}-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "secProfilesManager.fullname" . }}-webhook
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-webhook"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "secProfilesManager.fullname" . }}-webhook
  template:
    metadata:
      labels:
        app: {{ template "secProfilesManager.fullname" . }}-webhook
    spec:
      serviceAccountName: {{ template "secProfilesManager.serviceAccount" . }}-webhook-service-account
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: "postgres-listener"
        image: {{ include "initContainers.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ .Values.postgres.host }} {{ .Values.postgres.port }} && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.initContainers.resources | indent 10 }}
      containers:
      - name: {{ template "secProfilesManager.fullname" . }}-webhook
        image: {{ include "secProfilesWebhook.image" . }}
        imagePullPolicy: "{{ .Values.webhook.image.pullPolicy }}"
        # command: ["/bin/sh", "-c", "sleep 360000"]
        args:
        - --preset=/etc/config/presets.yaml
        - --cert=/etc/certs/tls.crt
        - --key=/etc/certs/tls.key
        - --port=8443
        - --console-postgres=postgres://postgres:password@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/postgres?sslmode=disable
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: certs
          mountPath: /etc/certs
          readOnly: true
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.webhook.resources | trim | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "secProfilesManager.fullname" . }}-config
      - name: certs
        secret:
          secretName: {{ template "secProfilesManager.fullname" . }}-webhook-certs
