---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
data:
  presets.yaml: |
    env:
    - name: LD_PRELOAD
      value: "/tmp/dp.so"
    - name: EVENTCENTER_NEW_ADDR
      value: "{{ .Values.eventcenter.addr }}.{{ .Release.Namespace }}.svc.cluster.local"
    - name: EVENTCENTER_NEW_PORT
      value: "{{ .Values.eventcenter.port }}"
    volumemounts:
    - name: "{{ .Values.volumes.clientName }}"
      mountpath: "{{ .Values.volumes.clientMountPath }}"
      readonly: true
    - name: {{ .Values.volumes.caName }}
      mountpath: "{{ .Values.volumes.caMountPath }}"
      readonly: true
    volumes:
      - name: "{{ .Values.volumes.clientName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.clientSecretName }}"
      - name: "{{ .Values.volumes.caName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.caSecretName }}"
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups:
    - ""
    - "apps"
    - "batch"
    - "extensions"
    resources:
    - pods
    - replicasets
    verbs:
    - list
    - watch
    - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-webhook
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: sec-prof-man-webhook
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: sec-prof-man-webhook
    spec:
      serviceAccountName: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: "postgres-listener"
        image: {{ include "initContainers.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ include "common.pgpool.defaultName" . }} 5432 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.initContainers.resources | indent 10 }}
      containers:
      - name: sec-prof-man-webhook
        image: {{ include "secProfilesWebhook.image" . }}
        imagePullPolicy: "{{ .Values.webhook.image.pullPolicy }}"
        # command: ["/bin/sh", "-c", "sleep 360000"]
        args:
        - --preset=/etc/config/presets.yaml
        - --cert=/etc/certs/tls.crt
        - --key=/etc/certs/tls.key
        - --port=8443
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: certs
          mountPath: /etc/certs
          readOnly: true
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PRE119
          value: "false"
        - name: RDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "common.postgresql.defaultName" . }}
              key: postgresql-password
        envFrom:
        - configMapRef:
            name: common-env
        resources:
{{ toYaml .Values.webhook.resources | trim | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
      - name: certs
        secret:
          secretName: {{ printf "%s-webhook" (include "common.names.fullname" .) }}
