apiVersion: {{ include "tensorsec.common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
{{ include "webhook.labels" . | indent 4 }}
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update