apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
{{ include "webhook.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}