apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webhook.fullname" . }}-webhook-certgen-{{ .Release.Revision }}
  labels:
{{ include "webhook.labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ include "webhook.fullname" . }}-webhook-certgen-{{ .Release.Revision }}
      labels:
        app.kubernetes.io/name: {{ include "webhook.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: create
          image: "{{ template "tensorsec.certgen.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - create
            - --host={{ include "webhook.fullname" . }},{{ include "webhook.fullname" . }}.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ include "webhook.fullname" . }}-certs
            - --cert-name=tls.crt
            - --key-name=tls.key
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      containers:
        - name: patch
          image: "{{ template "tensorsec.certgen.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ include "webhook.fullname" . }}
            - --namespace={{ .Release.Namespace }}
            - --patch-mutating=true
            - --patch-validating=true
            - --secret-name={{ include "webhook.fullname" . }}-certs
            - --patch-failure-policy=Ignore
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      restartPolicy: OnFailure
      serviceAccountName: {{ include "webhook.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
