apiVersion: {{ include "tensorsec.common.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
{{ include "webhook.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "webhook.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}