package iac

var DockerfileRules = []DockerfileRule{
	{
		1,
		"ts-misc-dockerfile-000",
		"Least Privilege User",
		"Image user should not be 'root'",
		"HIGH",
		"AVD-DS-0002",
	},
	{
		2,
		"ts-misc-dockerfile-001",
		"No Dist Upgrade",
		"'apt-get dist-upgrade' used",
		"HIGH",
		"AVD-DS-0024",
	},
	{
		3,
		"ts-misc-dockerfile-002",
		"No Duplicate Alias",
		"Duplicate aliases defined in different FROMs",
		"CRITICAL",
		"AVD-DS-0012",
	},
	{
		4,
		"ts-misc-dockerfile-003",
		"No Healthcheck",
		"No HEALTHCHECK defined",
		"LOW",
		"AVD-DS-0026",
	},
	{
		5,
		"ts-misc-dockerfile-004",
		"No Maintainer",
		"Deprecated MAINTAINER used",
		"HIGH",
		"AVD-DS-0022",
	},
	{
		6,
		"ts-misc-dockerfile-005",
		"No Orphan Package Update",
		"'RUN  update' instruction alone",
		"HIGH",
		"AVD-DS-0017",
	},
	{
		7,
		"ts-misc-dockerfile-006",
		"No Self Referencing Copy From",
		"COPY '-from' referring to the current image",
		"CRITICAL",
		"AVD-DS-0006",
	},
	{
		8,
		"ts-misc-dockerfile-007",
		"No Ssh Port",
		"Port 22 exposed",
		"MEDIUM",
		"AVD-DS-0004",
	},
	{
		9,
		"ts-misc-dockerfile-008",
		"No Sudo Run",
		"RUN using 'sudo'",
		"CRITICAL",
		"AVD-DS-0010",
	},
	{
		10,
		"ts-misc-dockerfile-009",
		"Only One Cmd",
		"Multiple CMD instructions listed",
		"HIGH",
		"AVD-DS-0016",
	},
	{
		11,
		"ts-misc-dockerfile-010",
		"Only One Entrypoint",
		"Multiple ENTRYPOINT instructions listed",
		"CRITICAL",
		"AVD-DS-0007",
	},
	{
		12,
		"ts-misc-dockerfile-011",
		"Only One Healthcheck",
		"Multiple HEALTHCHECK defined",
		"MEDIUM",
		"AVD-DS-0023",
	},
	{
		13,
		"ts-misc-dockerfile-012",
		"Port Out Of Range",
		"Exposed port out of range",
		"CRITICAL",
		"AVD-DS-0008",
	},
	{
		14,
		"ts-misc-dockerfile-013",
		"Purge Apk Package Cache",
		"'apk add' is missing '-no-cache'",
		"HIGH",
		"AVD-DS-0025",
	},
	{
		15,
		"ts-misc-dockerfile-014",
		"Purge Dnf Package Cache",
		"'dnf clean all' missing",
		"HIGH",
		"AVD-DS-0019",
	},
	{
		16,
		"ts-misc-dockerfile-015",
		"Purge Microdnf Package Cache",
		"'microdnf clean all' missing",
		"HIGH",
		"AVD-DS-0027",
	},
	{
		17,
		"ts-misc-dockerfile-016",
		"Purge Yum Package Cache",
		"'yum clean all' missing",
		"HIGH",
		"AVD-DS-0015",
	},
	{
		18,
		"ts-misc-dockerfile-017",
		"Purge Zipper Cache",
		"'zypper clean' missing",
		"HIGH",
		"AVD-DS-0020",
	},
	{
		19,
		"ts-misc-dockerfile-018",
		"Standardise Remote Get",
		"RUN using 'wget' and 'curl'",
		"LOW",
		"AVD-DS-0014",
	},
	{
		20,
		"ts-misc-dockerfile-019",
		"Use Apt Auto Confirm",
		"'apt-get' missing '-y' to avoid manual input",
		"HIGH",
		"AVD-DS-0021",
	},
	{
		21,
		"ts-misc-dockerfile-020",
		"Use Apt No Install Recommends",
		"'apt-get' missing '-no-install-recommends'",
		"HIGH",
		"AVD-DS-0029",
	},
	{
		22,
		"ts-misc-dockerfile-021",
		"Use Copy Over Add",
		"ADD instead of COPY",
		"LOW",
		"AVD-DS-0005",
	},
	{
		23,
		"ts-misc-dockerfile-022",
		"Use Slash For Copy Args",
		"COPY with more than two arguments not ending with slash",
		"CRITICAL",
		"AVD-DS-0011",
	},
	{
		24,
		"ts-misc-dockerfile-023",
		"Use Specific Tags",
		"':latest' tag used",
		"MEDIUM",
		"AVD-DS-0001",
	},
	{
		25,
		"ts-misc-dockerfile-024",
		"Use Workdir Over Cd",
		"'RUN cd ...' to change directory",
		"MEDIUM",
		"AVD-DS-0013",
	},
	{
		26,
		"ts-misc-dockerfile-025",
		"User Absolute Workdir",
		"WORKDIR path not absolute",
		"HIGH",
		"AVD-DS-0009",
	},
}

var YamlRules = []YamlRule{
	{1,
		"ts-misc-yaml-000",
		"Cluster Admin0 Role Only Used Where Required",
		"Ensure that the cluster-admin role is only used where required",
		"MEDIUM",
		"AVD-KSV-0111",
	},
	{
		2,
		"ts-misc-yaml-001",
		"Configmap_with_secrets",
		"ConfigMap with secrets",
		"HIGH",
		"AVD-KSV-0109",
	},
	{
		3,
		"ts-misc-yaml-002",
		"Configmap_with_sensitive",
		"ConfigMap with sensitive content",
		"HIGH",
		"AVD-KSV-01010",
	},
	{
		4,
		"ts-misc-yaml-003",
		"Containers Not Run As Root",
		"Containers must not set runAsUser to 0",
		"LOW",
		"AVD-KSV-0105",
	},
	{
		5,
		"ts-misc-yaml-004",
		"Default Namespace Should Not Be Used",
		"The default namespace should not be used",
		"LOW",
		"AVD-KSV-0110",
	},
	{
		6,
		"ts-misc-yaml-005",
		"Deny Create Update Malicious Pod",
		"Do not allow update/create of a malicious pod",
		"HIGH",
		"AVD-KSV-0048",
	},
	{
		7,
		"ts-misc-yaml-006",
		"Disable Anonymous Requests Kubelet Server",
		"Ensure that the --anonymous-auth argument is set to false",
		"CRITICAL",
		"AVD-KCV-0079",
	},
	{
		8,
		"ts-misc-yaml-007",
		"Disable Timeouts Streaming Connections",
		"Ensure that the --streaming-connection-idle-timeout argument is not set to 0",
		"HIGH",
		"AVD-KCV-0085",
	},
	{
		9,
		"ts-misc-yaml-008",
		"Do Not Allow Role Binding Associate Privileged Role",
		"Do not allow role binding creation and association with privileged role/clusterrole",
		"HIGH",
		"AVD-KSV-0051",
	},
	{
		10,
		"ts-misc-yaml-009",
		"Drop Caps Add Bind Svc",
		"Container capabilities must only include NET_BIND_SERVICE",
		"LOW",
		"AVD-KSV-0106",
	},
	{
		11,
		"ts-misc-yaml-010",
		"Drop Default Capabilities",
		"Default capabilities not dropped",
		"LOW",
		"AVD-KSV-0003",
	},
	{
		12,
		"ts-misc-yaml-011",
		"Ensure Admin Config File Permissions Set 600 Or More Restrictive",
		"Ensure that the admin config file permissions are set to 600 or more restrictive",
		"CRITICAL",
		"AVD-KCV-0060",
	},
	{
		13,
		"ts-misc-yaml-012",
		"Ensure Admin Config Ownership Set Root:root",
		"Ensure that the admin config  file ownership is set to root:root",
		"CRITICAL",
		"AVD-KCV-0061",
	},
	{
		14,
		"ts-misc-yaml-013",
		"Ensure Admission Control Plugin Always Admit Is Not Set",
		"Ensure that the admission control plugin AlwaysAdmit is not set",
		"LOW",
		"AVD-KCV-0011",
	},
	{
		15,
		"ts-misc-yaml-014",
		"Ensure Admission Control Plugin Always Pull Images Is Set",
		"Ensure that the admission control plugin AlwaysPullImages is set",
		"LOW",
		"AVD-KCV-0012",
	},
	{
		16,
		"ts-misc-yaml-015",
		"Ensure Admission Control Plugin Event Rate Limit Is Set",
		"Ensure that the admission control plugin EventRateLimit is set",
		"LOW",
		"AVD-KCV-0010",
	},
	{
		17,
		"ts-misc-yaml-016",
		"Ensure Admission Control Plugin Namespace Lifecycle Is Set",
		"Ensure that the admission control plugin NamespaceLifecycle is set",
		"LOW",
		"AVD-KCV-0015",
	},
	{
		18,
		"ts-misc-yaml-017",
		"Ensure Admission Control Plugin Node Restriction Is Set",
		"Ensure that the admission control plugin NodeRestriction is set",
		"LOW",
		"AVD-KCV-0016",
	},
	{
		19,
		"ts-misc-yaml-018",
		"Ensure Admission Control Plugin Security Context Deny Is Set If Pod Security Policy Is Not Used",
		"Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used",
		"LOW",
		"AVD-KCV-0013",
	},
	{
		20,
		"ts-misc-yaml-019",
		"Ensure Admission Control Plugin Service Account Is Set",
		"Ensure that the admission control plugin ServiceAccount is set",
		"LOW",
		"AVD-KCV-0014",
	},
	{
		21,
		"ts-misc-yaml-020",
		"Ensure Anonymous Auth Argument Is False",
		"Ensure that the --anonymous-auth argument is set to false",
		"MEDIUM",
		"AVD-KCV-0001",
	},
	{
		22,
		"ts-misc-yaml-021",
		"Ensure Api Server Pod Specification File Permissions Set 600 Or More Restrictive",
		"Ensure that the API server pod specification file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0048",
	},
	{
		23,
		"ts-misc-yaml-022",
		"Ensure Api Server Pod Specification Ownership Set Root:root",
		"Ensure that the API server pod specification file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0049",
	},
	{
		24,
		"ts-misc-yaml-023",
		"Ensure Audit Log Maxage Argument Is Set To 30 Or As Appropriate",
		"Ensure that the --audit-log-maxage argument is set to 30 or as appropriate",
		"LOW",
		"AVD-KCV-0020",
	},
	{
		25,
		"ts-misc-yaml-024",
		"Ensure Audit Log Maxbackup Argument Is Set To 10 Or As Appropriate",
		"Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate",
		"LOW",
		"AVD-KCV-0021",
	},
	{
		26,
		"ts-misc-yaml-025",
		"Ensure Audit Log Maxsize Argument Is Set To 100 Or As Appropriate",
		"Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate",
		"LOW",
		"AVD-KCV-0022",
	},
	{
		27,
		"ts-misc-yaml-026",
		"Ensure Audit Log Path Argument Is Set",
		"Ensure that the --audit-log-path argument is set",
		"LOW",
		"AVD-KCV-0019",
	},
	{
		28,
		"ts-misc-yaml-027",
		"Ensure Authorization Mode Argument Includes Node",
		"Ensure that the --authorization-mode argument includes Node",
		"LOW",
		"AVD-KCV-0008",
	},
	{
		29,
		"ts-misc-yaml-028",
		"Ensure Authorization Mode Argument Includes Rbac",
		"Ensure that the --authorization-mode argument includes RBAC",
		"LOW",
		"AVD-KCV-0009",
	},
	{
		30,
		"ts-misc-yaml-029",
		"Ensure Authorization Mode Argument Is Not Set To Alwaysallow",
		"Ensure that the --authorization-mode argument is not set to AlwaysAllow",
		"LOW",
		"AVD-KCV-0007",
	},
	{
		31,
		"ts-misc-yaml-030",
		"Ensure Authorization Mode Argument Set Alwaysallow",
		"Ensure that the --authorization-mode argument is not set to AlwaysAllow",
		"HIGH",
		"AVD-KCV-0080",
	},
	{
		32,
		"ts-misc-yaml-031",
		"Ensure Auto Tls Argument Is Not Set To True",
		"Ensure that the --auto-tls argument is not set to true",
		"LOW",
		"AVD-KCV-0044",
	},
	{
		33,
		"ts-misc-yaml-032",
		"Ensure Cert File And Key File Arguments Are Set As Appropriate",
		"Ensure that the --cert-file and --key-file arguments are set as appropriate",
		"LOW",
		"AVD-KCV-0042",
	},
	{
		34,
		"ts-misc-yaml-033",
		"Ensure Certificate Authorities File Permissions 600 Or More Restrictive",
		"Ensure that the certificate authorities file permissions are set to 600 or more restrictive",
		"CRITICAL",
		"AVD-KCV-0075",
	},
	{
		35,
		"ts-misc-yaml-034",
		"Ensure Certificate_authorities Ownership Set Root:root",
		"Ensure that the client certificate authorities file ownership is set to root:root",
		"CRITICAL",
		"AVD-KCV-0076",
	},
	{
		36,
		"ts-misc-yaml-035",
		"Ensure Client Ca Argument Set Appropriate",
		"Ensure that the --client-ca-file argument is set as appropriate",
		"CRITICAL",
		"AVD-KCV-0081",
	},
	{
		37,
		"ts-misc-yaml-036",
		"Ensure Client Ca File Argument Is Set As Appropriate",
		"Ensure that the --client-ca-file argument is set as appropriate",
		"LOW",
		"AVD-KCV-0028",
	},
	{
		38,
		"ts-misc-yaml-037",
		"Ensure Client Cert Auth Argument Is Set To True",
		"Ensure that the --client-cert-auth argument is set to true",
		"LOW",
		"AVD-KCV-0043",
	},
	{
		39,
		"ts-misc-yaml-038",
		"Ensure Container Network Interface File Permissions Set 600 Or More Restrictive",
		"Ensure that the container network interface file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0056",
	},
	{
		40,
		"ts-misc-yaml-039",
		"Ensure Container Network Interface Ownership Set Root:root",
		"Ensure that the container network interface file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0057",
	},
	{
		41,
		"ts-misc-yaml-040",
		"Ensure Controller Manager Bind Address Is Loopback",
		"Ensure that the --bind-address argument is set to 127.0.0.1",
		"LOW",
		"AVD-KCV-0039",
	},
	{
		42,
		"ts-misc-yaml-041",
		"Ensure Controller Manager Config File Permissions Set 600 Or More Restrictive",
		"Ensure that the controller-manager config file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0064",
	},
	{
		43,
		"ts-misc-yaml-042",
		"Ensure Controller Manager Config Ownership Set Root:root",
		"Ensure that the controller-manager config  file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0065",
	},
	{
		44,
		"ts-misc-yaml-043",
		"Ensure Controller Manager Pod Specification File Permissions Set 600 Or More Restrictive",
		"Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0050",
	},
	{
		45,
		"ts-misc-yaml-044",
		"Ensure Controller Manager Pod Specification Ownership Set Root:root",
		"Ensure that the controller manager pod specification file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0051",
	},
	{
		46,
		"ts-misc-yaml-045",
		"Ensure Deny Service External Ips Is Not Set",
		"Ensure that the --DenyServiceExternalIPs is not set",
		"LOW",
		"AVD-KCV-0003",
	},
	{
		47,
		"ts-misc-yaml-046",
		"Ensure Etcd Cafile Argument Is Set As Appropriate",
		"Ensure that the --etcd-cafile argument is set as appropriate",
		"LOW",
		"AVD-KCV-0029",
	},
	{
		48,
		"ts-misc-yaml-047",
		"Ensure Etcd Certfile And Etcd Keyfile Arguments Are Set As Appropriate",
		"Ensure that the --etcd-certfile and --etcd-keyfile arguments are set as appropriate",
		"LOW",
		"AVD-KCV-0026",
	},
	{
		49,
		"ts-misc-yaml-048",
		"Ensure Etcd Data Directory Ownership Set Etcd:etcd",
		"Ensure that the etcd data directory ownership is set to etcd:etcd",
		"LOW",
		"AVD-KCV-0059",
	},
	{
		50,
		"ts-misc-yaml-049",
		"Ensure Etcd Data Directory Permissions Set 700 Or More Restrictive",
		"Ensure that the etcd data directory permissions are set to 700 or more restrictive",
		"LOW",
		"AVD-KCV-0058",
	},
	{
		51,
		"ts-misc-yaml-050",
		"Ensure Etcd Pod Specification File Permissions Set 600 Or More Restrictive",
		"Ensure that the etcd pod specification file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0054",
	},
	{
		52,
		"ts-misc-yaml-051",
		"Ensure Etcd Pod Specification Ownership Set Root:root",
		"Ensure that the etcd pod specification file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0055",
	},
	{
		53,
		"ts-misc-yaml-052",
		"Ensure Event Qps Argument Set 0 Or Level Forappropriate Event Capture",
		"Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture",
		"HIGH",
		"AVD-KCV-0087",
	},
	{
		54,
		"ts-misc-yaml-053",
		"Ensure Hostname Override Argument Not Set",
		"Ensure that the --hostname-override argument is not set",
		"HIGH",
		"AVD-KCV-0086",
	},
	{
		55,
		"ts-misc-yaml-054",
		"Ensure Kubeconfig Kubelet Config.yaml Ownership Set Root:root",
		"If the kubelet config.yaml configuration file is being used validate file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0078",
	},
	{
		56,
		"ts-misc-yaml-055",
		"Ensure Kubeconfig Kubelet.conf Ownership Set Root:root",
		"Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0074",
	},
	{
		57,
		"ts-misc-yaml-056",
		"Ensure Kubelet Certificate Authority Argument Is Set",
		"Ensure that the --kubelet-certificate-authority argument is set as appropriate",
		"LOW",
		"AVD-KCV-0006",
	},
	{
		58,
		"ts-misc-yaml-057",
		"Ensure Kubelet Client Certificate And Kubelet Client Key Are Set",
		"Ensure that the --kubelet-client-certificate and --kubelet-client-key arguments are set as appropriate",
		"LOW",
		"AVD-KCV-0005",
	},
	{
		59,
		"ts-misc-yaml-058",
		"Ensure Kubelet Config.yaml  Permissions 600 Or More Restrictive",
		"If the kubelet config.yaml configuration file is being used validate permissions set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0077",
	},
	{
		60,
		"ts-misc-yaml-059",
		"Ensure Kubelet Https Argument Is Set To True",
		"Ensure that the --kubelet-https argument is set to true",
		"LOW",
		"AVD-KCV-0004",
	},
	{
		61,
		"ts-misc-yaml-060",
		"Ensure Kubelet Only Makes Use Strong Cryptographic Ciphers",
		"Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers",
		"CRITICAL",
		"AVD-KCV-0092",
	},
	{
		62,
		"ts-misc-yaml-061",
		"Ensure Kubelet Service File Ownership Set Root:root",
		"Ensure that the kubelet service file ownership is set to root:root",
		"CRITICAL",
		"AVD-KCV-0070",
	},
	{
		63,
		"ts-misc-yaml-062",
		"Ensure Kubelet Service File Permissions Set 600 Or More Restrictive",
		"Ensure that the kubelet service file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0069",
	},
	{
		64,
		"ts-misc-yaml-063",
		"Ensure Kubelet.conf File Permissions 600 Or More Restrictive",
		"Ensure that the --kubeconfig kubelet.conf file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0073",
	},
	{
		65,
		"ts-misc-yaml-064",
		"Ensure Kubernetes Pki Cert File Permission Set 600",
		"Ensure that the Kubernetes PKI certificate file permission is set to 600",
		"HIGH",
		"AVD-KCV-0068",
	},
	{
		66,
		"ts-misc-yaml-065",
		"Ensure Kubernetes Pki Directory File Ownership Set Root:root",
		"Ensure that the Kubernetes PKI directory and file file ownership is set to root:root",
		"CRITICAL",
		"AVD-KCV-0066",
	},
	{
		67,
		"ts-misc-yaml-066",
		"Ensure Kubernetes Pki Key File Permission Set 600",
		"Ensure that the Kubernetes PKI key file permission is set to 600",
		"CRITICAL",
		"AVD-KCV-0067",
	},
	{
		68,
		"ts-misc-yaml-067",
		"Ensure Make Iptables Util Chains Argument Set True",
		"Ensure that the --make-iptables-util-chains argument is set to true",
		"HIGH",
		"AVD-KCV-0084",
	},
	{
		69,
		"ts-misc-yaml-068",
		"Ensure Peer Auto Tls Argument Is Not Set To True",
		"Ensure that the --peer-auto-tls argument is not set to true",
		"LOW",
		"AVD-KCV-0047",
	},
	{
		70,
		"ts-misc-yaml-069",
		"Ensure Peer Cert File And Peer Key File Arguments Are Set As Appropriate",
		"Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate",
		"LOW",
		"AVD-KCV-0045",
	},
	{
		71,
		"ts-misc-yaml-070",
		"Ensure Peer Client Cert Auth Argument Is Set To True",
		"Ensure that the --peer-client-cert-auth argument is set to true",
		"LOW",
		"AVD-KCV-0046",
	},
	{
		72,
		"ts-misc-yaml-071",
		"Ensure Profiling Argument Is Set To False",
		"Ensure that the --profiling argument is set to false",
		"LOW",
		"AVD-KCV-0018",
	},
	{
		73,
		"ts-misc-yaml-072",
		"Ensure Profiling Argument Is Set To False",
		"Ensure that the --profiling argument is set to false",
		"LOW",
		"AVD-KCV-0034",
	},
	{
		74,
		"ts-misc-yaml-073",
		"Ensure Profiling Argument Is Set To False",
		"Ensure that the --profiling argument is set to false",
		"LOW",
		"AVD-KCV-0040",
	},
	{
		75,
		"ts-misc-yaml-074",
		"Ensure Protect Kernel Defaults Set True",
		"Ensure that the --protect-kernel-defaults is set to true",
		"HIGH",
		"AVD-KCV-0083",
	},
	{
		76,
		"ts-misc-yaml-075",
		"Ensure Proxy Kubeconfig Ownership Set Root:root If Exist",
		"if proxy kubeconfig file exists ensure ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0072",
	},
	{
		77,
		"ts-misc-yaml-076",
		"Ensure Proxy Kubeconfig Permissions Set 600 Or More Restrictive If Exist",
		"If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0071",
	},
	{
		78,
		"ts-misc-yaml-077",
		"Ensure Root Ca File Argument Is Set As Appropriate",
		"Ensure that the --root-ca-file argument is set as appropriate",
		"LOW",
		"AVD-KCV-0037",
	},
	{
		79,
		"ts-misc-yaml-078",
		"Ensure Rotate Certificates Argument Set False",
		"Ensure that the --rotate-certificates argument is not set to false",
		"HIGH",
		"AVD-KCV-0090",
	},
	{
		80,
		"ts-misc-yaml-079",
		"Ensure Rotate Kubelet Server Certificate Argument Set True",
		"Verify that the RotateKubeletServerCertificate argument is set to true",
		"HIGH",
		"AVD-KCV-0091",
	},
	{
		81,
		"ts-misc-yaml-080",
		"Ensure Scheduler Bind Address Is Loopback",
		"Ensure that the --bind-address argument is set to 127.0.0.1",
		"LOW",
		"AVD-KCV-0041",
	},
	{
		82,
		"ts-misc-yaml-081",
		"Ensure Scheduler Config File Permissions Set 600 Or More Restrictive",
		"Ensure that the scheduler config file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0062",
	},
	{
		83,
		"ts-misc-yaml-082",
		"Ensure Scheduler Config Ownership Set Root:root",
		"Ensure that the scheduler config  file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0063",
	},
	{
		84,
		"ts-misc-yaml-083",
		"Ensure Scheduler Pod Specification File Permissions Set 600 Or More Restrictive",
		"Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive",
		"HIGH",
		"AVD-KCV-0052",
	},
	{
		85,
		"ts-misc-yaml-084",
		"Ensure Scheduler Pod Specification Ownership Set Root:root",
		"Ensure that the scheduler pod specification file ownership is set to root:root",
		"HIGH",
		"AVD-KCV-0053",
	},
	{
		86,
		"ts-misc-yaml-085",
		"Ensure Secure Port Argument Is Not Set To 0",
		"Ensure that the --secure-port argument is not set to 0",
		"LOW",
		"AVD-KCV-0017",
	},
	{
		87,
		"ts-misc-yaml-086",
		"Ensure Service Account Key File Argument Is Set As Appropriate",
		"Ensure that the --service-account-key-file argument is set as appropriate",
		"LOW",
		"AVD-KCV-0025",
	},
	{
		88,
		"ts-misc-yaml-087",
		"Ensure Service Account Lookup Argument Is Set To True",
		"Ensure that the --service-account-lookup argument is set to true",
		"LOW",
		"AVD-KCV-0024",
	},
	{
		89,
		"ts-misc-yaml-088",
		"Ensure Service Account Private Key File Argument Is Set As Appropriate",
		"Ensure that the --service-account-private-key-file argument is set as appropriate",
		"LOW",
		"AVD-KCV-0036",
	},
	{
		90,
		"ts-misc-yaml-089",
		"Ensure Terminated Pod Gc Threshold Argument Is Set As Appropriate",
		"Ensure that the --terminated-pod-gc-threshold argument is set as appropriate",
		"LOW",
		"AVD-KCV-0033",
	},
	{
		91,
		"ts-misc-yaml-090",
		"Ensure That The   Encryption Provider Config Argument Is Set As Appropriate",
		"Ensure that the --encryption-provider-config argument is set as appropriate",
		"LOW",
		"AVD-KCV-0030",
	},
	{
		92,
		"ts-misc-yaml-091",
		"Ensure That The Rotatekubeletservercertificate Argument Is Set To True",
		"Ensure that the RotateKubeletServerCertificate argument is set to true",
		"LOW",
		"AVD-KCV-0038",
	},
	{
		93,
		"ts-misc-yaml-092",
		"Ensure Tls Cert File And Tls Private Key File Arguments Are Set As Appropriate",
		"Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate",
		"LOW",
		"AVD-KCV-0027",
	},
	{
		94,
		"ts-misc-yaml-093",
		"Ensure Tls Cert File Argument Set Appropriate",
		"Ensure that the --tls-cert-file argument are set as appropriate",
		"CRITICAL",
		"AVD-KCV-0088",
	},
	{
		95,
		"ts-misc-yaml-094",
		"Ensure Tls Key File Argument Set Appropriate",
		"Ensure that the --tls-key-file argument are set as appropriate",
		"CRITICAL",
		"AVD-KCV-0089",
	},
	{
		96,
		"ts-misc-yaml-095",
		"Ensure Token Auth File Parameter Is Not Set",
		"Ensure that the --token-auth-file parameter is not set",
		"LOW",
		"AVD-KCV-0002",
	},
	{
		97,
		"ts-misc-yaml-096",
		"Ensure Use Service Account Credentials Argument Is Set To True",
		"Ensure that the --use-service-account-credentials argument is set to true",
		"LOW",
		"AVD-KCV-0035",
	},
	{
		98,
		"ts-misc-yaml-097",
		"Evaluate K8s Deprecated Removed Apis",
		"Evaluate k8s deprecated and removed APIs",
		"LOW",
		"AVD-KSV-0107",
	},
	{
		99,
		"ts-misc-yaml-098",
		"Limit Cpu",
		"CPU not limited",
		"LOW",
		"AVD-KSV-0011",
	},
	{
		100,
		"ts-misc-yaml-099",
		"Limit Memory",
		"Memory not limited",
		"LOW",
		"AVD-KSV-0018",
	},
	{
		101,
		"ts-misc-yaml-100",
		"No Attaching Shell Pods",
		"Do not allow attaching to shell on pods",
		"HIGH",
		"AVD-KSV-0054",
	},
	{
		102,
		"ts-misc-yaml-101",
		"No Auto Mount Service Token",
		"Protecting Pod service account tokens",
		"MEDIUM",
		"AVD-KSV-0036",
	},
	{
		103,
		"ts-misc-yaml-102",
		"No Custom Proc Mask",
		"Non-default /proc masks set",
		"MEDIUM",
		"AVD-KSV-0027",
	},
	{
		104,
		"ts-misc-yaml-103",
		"No Custom Selinux Options",
		"SELinux custom options set",
		"MEDIUM",
		"AVD-KSV-0025",
	},
	{
		105,
		"ts-misc-yaml-104",
		"No Delete Pod Logs",
		"Do not allow deletion of pod logs",
		"MEDIUM",
		"AVD-KSV-0042",
	},
	{
		106,
		"ts-misc-yaml-105",
		"No Docker Sock Mount",
		"hostPath volume mounted with docker.sock",
		"HIGH",
		"AVD-KSV-0006",
	},
	{
		107,
		"ts-misc-yaml-106",
		"No Getting Shell Pods",
		"Do not allow getting shell on pods",
		"HIGH",
		"AVD-KSV-0053",
	},
	{
		108,
		"ts-misc-yaml-107",
		"No Host Network",
		"Access to host network",
		"HIGH",
		"AVD-KSV-0009",
	},
	{
		109,
		"ts-misc-yaml-108",
		"No Host Pid",
		"Access to host PID",
		"HIGH",
		"AVD-KSV-0010",
	},
	{
		110,
		"ts-misc-yaml-109",
		"No Host Port Access",
		"Access to host ports",
		"HIGH",
		"AVD-KSV-0024",
	},
	{
		111,
		"ts-misc-yaml-110",
		"No Hostprocess Containers",
		"HostProcess container defined",
		"MEDIUM",
		"AVD-KSV-0103",
	},
	{
		112,
		"ts-misc-yaml-111",
		"No Impersonate Privileged Groups",
		"Do not allow impersonation of privileged groups",
		"CRITICAL",
		"AVD-KSV-0043",
	},
	{
		113,
		"ts-misc-yaml-112",
		"No Manage Configmaps",
		"Do not allow management of configmaps",
		"MEDIUM",
		"AVD-KSV-0049",
	},
	{
		114,
		"ts-misc-yaml-113",
		"No Manage Networking Resources",
		"Do not allow management of networking resources",
		"HIGH",
		"AVD-KSV-0056",
	},
	{
		115,
		"ts-misc-yaml-114",
		"No Manage Rbac Resources",
		"Do not allow management of RBAC resources",
		"CRITICAL",
		"AVD-KSV-0050",
	},
	{
		116,
		"ts-misc-yaml-115",
		"No Manage Secrets",
		"Do not allow management of secrets",
		"CRITICAL",
		"AVD-KSV-0041",
	},
	{
		117,
		"ts-misc-yaml-116",
		"No Mounted Hostpath",
		"hostPath volumes mounted",
		"MEDIUM",
		"AVD-KSV-0023",
	},
	{
		118,
		"ts-misc-yaml-117",
		"No Non Default Capabilities",
		"Non-default capabilities added",
		"MEDIUM",
		"AVD-KSV-0022",
	},
	{
		119,
		"ts-misc-yaml-118",
		"No Non Ephemeral Volumes",
		"Non-ephemeral volume types used",
		"LOW",
		"AVD-KSV-0028",
	},
	{
		120,
		"ts-misc-yaml-119",
		"No Privilege Escalation From Node Proxy",
		"Do not allow privilege escalation from node proxy",
		"HIGH",
		"AVD-KSV-0047",
	},
	{
		121,
		"ts-misc-yaml-120",
		"No Privileged Containers",
		"Privileged container",
		"HIGH",
		"AVD-KSV-0017",
	},
	{
		122,
		"ts-misc-yaml-121",
		"No Root",
		"Runs as root user",
		"MEDIUM",
		"AVD-KSV-0012",
	},
	{
		123,
		"ts-misc-yaml-122",
		"No Seccomp Unconfined",
		"Seccomp profile unconfined",
		"MEDIUM",
		"AVD-KSV-0104",
	},
	{
		124,
		"ts-misc-yaml-123",
		"No Self Privesc",
		"Process can elevate its own privileges",
		"MEDIUM",
		"AVD-KSV-0001",
	},
	{
		125,
		"ts-misc-yaml-124",
		"No Shared Ipc Namespace",
		"Access to host IPC namespace",
		"HIGH",
		"AVD-KSV-0008",
	},
	{
		126,
		"ts-misc-yaml-125",
		"No Sysadmin Capability",
		"SYS_ADMIN capability added",
		"HIGH",
		"AVD-KSV-0005",
	},
	{
		127,
		"ts-misc-yaml-126",
		"No Tiller",
		"Tiller Is Deployed",
		"CRITICAL",
		"AVD-KSV-0102",
	},
	{
		128,
		"ts-misc-yaml-127",
		"No Unsafe Sysctl",
		"Unsafe sysctl options set",
		"MEDIUM",
		"AVD-KSV-0026",
	},
	{
		129,
		"ts-misc-yaml-128",
		"No Unspecified Cpu Requests",
		"CPU requests not specified",
		"LOW",
		"AVD-KSV-0015",
	},
	{
		130,
		"ts-misc-yaml-129",
		"No Unspecified Memory Requests",
		"Memory requests not specified",
		"LOW",
		"AVD-KSV-0016",
	},
	{
		131,
		"ts-misc-yaml-130",
		"No User Pods In System Namespace",
		"User Pods should not be placed in kube-system namespace",
		"MEDIUM",
		"AVD-KSV-0037",
	},
	{
		132,
		"ts-misc-yaml-131",
		"No Wildcard Resource Role",
		"No wildcard resource roles",
		"CRITICAL",
		"AVD-KSV-0046",
	},
	{
		133,
		"ts-misc-yaml-132",
		"No Wildcard Verb Resource Role",
		"No wildcard verb and resource roles",
		"CRITICAL",
		"AVD-KSV-0044",
	},
	{
		134,
		"ts-misc-yaml-133",
		"No Wildcard Verb Role",
		"No wildcard verb roles",
		"CRITICAL",
		"AVD-KSV-0045",
	},
	{
		135,
		"ts-misc-yaml-134",
		"No_svc_with_extip",
		"Service with External IP",
		"HIGH",
		"AVD-KSV-0108",
	},
	{
		136,
		"ts-misc-yaml-135",
		"Selector Usage In Network Policies",
		"Selector usage in network policies",
		"MEDIUM",
		"AVD-KSV-0038",
	},
	{
		137,
		"ts-misc-yaml-136",
		"Use Default Apparmor Profile",
		"Default AppArmor profile not set",
		"MEDIUM",
		"AVD-KSV-0002",
	},
	{
		138,
		"ts-misc-yaml-137",
		"Use Default Seccomp",
		"Default Seccomp profile not set",
		"LOW",
		"AVD-KSV-0030",
	},
	{
		139,
		"ts-misc-yaml-138",
		"Use High Gid",
		"Runs with low group ID",
		"LOW",
		"AVD-KSV-0021",
	},
	{
		140,
		"ts-misc-yaml-139",
		"Use High Uid",
		"Runs with low user ID",
		"LOW",
		"AVD-KSV-0020",
	},
	{
		141,
		"ts-misc-yaml-140",
		"Use Readonly Filesystem",
		"Root file system is not read-only",
		"LOW",
		"AVD-KSV-0014",
	},
	{
		142,
		"ts-misc-yaml-141",
		"Use Specific Tags",
		"Image tag ':latest' used",
		"MEDIUM",
		"AVD-KSV-0013",
	},
	{
		143,
		"ts-misc-yaml-142",
		"Verify Read Only Port Argument Set 0",
		"Verify that the --read-only-port argument is set to 0",
		"HIGH",
		"AVD-KCV-0082",
	},
	{
		144,
		"ts-misc-yaml-143",
		"View All Secrets",
		"Do not allow users in a rolebinding to add other users to their rolebindings",
		"LOW",
		"AVD-KSV-0055",
	},
}
