package iac

var DockerfileRules = []DockerfileRule{
	{
		ID:           1,
		BuiltinID:    "ts-misc-dockerfile-000",
		Name:         "Least Privilege User",
		Description:  "Image user should not be 'root'",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0002",
	},
	{
		ID:           2,
		BuiltinID:    "ts-misc-dockerfile-001",
		Name:         "No Dist Upgrade",
		Description:  "'apt-get dist-upgrade' used",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0024",
	},
	{
		ID:           3,
		BuiltinID:    "ts-misc-dockerfile-002",
		Name:         "No Duplicate Alias",
		Description:  "Duplicate aliases defined in different FROMs",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0012",
	},
	{
		ID:           4,
		BuiltinID:    "ts-misc-dockerfile-003",
		Name:         "No Healthcheck",
		Description:  "No HEALTHCHECK defined",
		Severity:     "LOW",
		ThirdPartyID: "AVD-DS-0026",
	},
	{
		ID:           5,
		BuiltinID:    "ts-misc-dockerfile-004",
		Name:         "No Maintainer",
		Description:  "Deprecated MAINTAINER used",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0022",
	},
	{
		ID:           6,
		BuiltinID:    "ts-misc-dockerfile-005",
		Name:         "No Orphan Package Update",
		Description:  "'RUN  update' instruction alone",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0017",
	},
	{
		ID:           7,
		BuiltinID:    "ts-misc-dockerfile-006",
		Name:         "No Self Referencing Copy From",
		Description:  "COPY '-from' referring to the current image",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0006",
	},
	{
		ID:           8,
		BuiltinID:    "ts-misc-dockerfile-007",
		Name:         "No Ssh Port",
		Description:  "Port 22 exposed",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-DS-0004",
	},
	{
		ID:           9,
		BuiltinID:    "ts-misc-dockerfile-008",
		Name:         "No Sudo Run",
		Description:  "RUN using 'sudo'",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0010",
	},
	{
		ID:           10,
		BuiltinID:    "ts-misc-dockerfile-009",
		Name:         "Only One Cmd",
		Description:  "Multiple CMD instructions listed",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0016",
	},
	{
		ID:           11,
		BuiltinID:    "ts-misc-dockerfile-010",
		Name:         "Only One Entrypoint",
		Description:  "Multiple ENTRYPOINT instructions listed",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0007",
	},
	{
		ID:           12,
		BuiltinID:    "ts-misc-dockerfile-011",
		Name:         "Only One Healthcheck",
		Description:  "Multiple HEALTHCHECK defined",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-DS-0023",
	},
	{
		ID:           13,
		BuiltinID:    "ts-misc-dockerfile-012",
		Name:         "Port Out Of Range",
		Description:  "Exposed port out of range",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0008",
	},
	{
		ID:           14,
		BuiltinID:    "ts-misc-dockerfile-013",
		Name:         "Purge Apk Package Cache",
		Description:  "'apk add' is missing '-no-cache'",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0025",
	},
	{
		ID:           15,
		BuiltinID:    "ts-misc-dockerfile-014",
		Name:         "Purge Dnf Package Cache",
		Description:  "'dnf clean all' missing",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0019",
	},
	{
		ID:           16,
		BuiltinID:    "ts-misc-dockerfile-015",
		Name:         "Purge Microdnf Package Cache",
		Description:  "'microdnf clean all' missing",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0027",
	},
	{
		ID:           17,
		BuiltinID:    "ts-misc-dockerfile-016",
		Name:         "Purge Yum Package Cache",
		Description:  "'yum clean all' missing",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0015",
	},
	{
		ID:           18,
		BuiltinID:    "ts-misc-dockerfile-017",
		Name:         "Purge Zipper Cache",
		Description:  "'zypper clean' missing",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0020",
	},
	{
		ID:           19,
		BuiltinID:    "ts-misc-dockerfile-018",
		Name:         "Standardise Remote Get",
		Description:  "RUN using 'wget' and 'curl'",
		Severity:     "LOW",
		ThirdPartyID: "AVD-DS-0014",
	},
	{
		ID:           20,
		BuiltinID:    "ts-misc-dockerfile-019",
		Name:         "Use Apt Auto Confirm",
		Description:  "'apt-get' missing '-y' to avoid manual input",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0021",
	},
	{
		ID:           21,
		BuiltinID:    "ts-misc-dockerfile-020",
		Name:         "Use Apt No Install Recommends",
		Description:  "'apt-get' missing '-no-install-recommends'",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0029",
	},
	{
		ID:           22,
		BuiltinID:    "ts-misc-dockerfile-021",
		Name:         "Use Copy Over Add",
		Description:  "ADD instead of COPY",
		Severity:     "LOW",
		ThirdPartyID: "AVD-DS-0005",
	},
	{
		ID:           23,
		BuiltinID:    "ts-misc-dockerfile-022",
		Name:         "Use Slash For Copy Args",
		Description:  "COPY with more than two arguments not ending with slash",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-DS-0011",
	},
	{
		ID:           24,
		BuiltinID:    "ts-misc-dockerfile-023",
		Name:         "Use Specific Tags",
		Description:  "':latest' tag used",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-DS-0001",
	},
	{
		ID:           25,
		BuiltinID:    "ts-misc-dockerfile-024",
		Name:         "Use Workdir Over Cd",
		Description:  "'RUN cd ...' to change directory",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-DS-0013",
	},
	{
		ID:           26,
		BuiltinID:    "ts-misc-dockerfile-025",
		Name:         "Use Absolute Workdir",
		Description:  "WORKDIR path not absolute",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-DS-0009",
	},
}

var YamlRules = []YamlRule{
	{
		ID:           1,
		BuiltinID:    "ts-misc-yaml-000",
		Name:         "Cluster Admin Role Only Used Where Required",
		Description:  "Ensure that the cluster-admin role is only used where required",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0111",
	},
	{
		ID:           2,
		BuiltinID:    "ts-misc-yaml-001",
		Name:         "Configmap with secrets",
		Description:  "ConfigMap with secrets",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0109",
	},
	{
		ID:           3,
		BuiltinID:    "ts-misc-yaml-002",
		Name:         "Configmap with sensitive",
		Description:  "ConfigMap with sensitive content",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-01010",
	},
	{
		ID:           4,
		BuiltinID:    "ts-misc-yaml-003",
		Name:         "Containers Not Run As Root",
		Description:  "Containers must not set runAsUser to 0",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0105",
	},
	{
		ID:           5,
		BuiltinID:    "ts-misc-yaml-004",
		Name:         "Default Namespace Should Not Be Used",
		Description:  "The default namespace should not be used",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0110",
	},
	{
		ID:           6,
		BuiltinID:    "ts-misc-yaml-005",
		Name:         "Deny Create Update Malicious Pod",
		Description:  "Do not allow update/create of a malicious pod",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0048",
	},
	{
		ID:           7,
		BuiltinID:    "ts-misc-yaml-006",
		Name:         "Disable Anonymous Requests Kubelet Server",
		Description:  "Ensure that the --anonymous-auth argument is set to false",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0079",
	},
	{
		ID:           8,
		BuiltinID:    "ts-misc-yaml-007",
		Name:         "Disable Timeouts Streaming Connections",
		Description:  "Ensure that the --streaming-connection-idle-timeout argument is not set to 0",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0085",
	},
	{
		ID:           9,
		BuiltinID:    "ts-misc-yaml-008",
		Name:         "Do Not Allow Role Binding Associate Privileged Role",
		Description:  "Do not allow role binding creation and association with privileged role/clusterrole",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0051",
	},
	{
		ID:           10,
		BuiltinID:    "ts-misc-yaml-009",
		Name:         "Drop Caps Add Bind Svc",
		Description:  "Container capabilities must only include NET_BIND_SERVICE",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0106",
	},
	{
		ID:           11,
		BuiltinID:    "ts-misc-yaml-010",
		Name:         "Drop Default Capabilities",
		Description:  "Default capabilities not dropped",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0003",
	},
	{
		ID:           12,
		BuiltinID:    "ts-misc-yaml-011",
		Name:         "Ensure Admin Config File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the admin config file permissions are set to 600 or more restrictive",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0060",
	},
	{
		ID:           13,
		BuiltinID:    "ts-misc-yaml-012",
		Name:         "Ensure Admin Config Ownership Set root:root",
		Description:  "Ensure that the admin config  file ownership is set to root:root",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0061",
	},
	{
		ID:           14,
		BuiltinID:    "ts-misc-yaml-013",
		Name:         "Ensure Admission Control Plugin Always Admit Is Not Set",
		Description:  "Ensure that the admission control plugin AlwaysAdmit is not set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0011",
	},
	{
		ID:           15,
		BuiltinID:    "ts-misc-yaml-014",
		Name:         "Ensure Admission Control Plugin Always Pull Images Is Set",
		Description:  "Ensure that the admission control plugin AlwaysPullImages is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0012",
	},
	{
		ID:           16,
		BuiltinID:    "ts-misc-yaml-015",
		Name:         "Ensure Admission Control Plugin Event Rate Limit Is Set",
		Description:  "Ensure that the admission control plugin EventRateLimit is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0010",
	},
	{
		ID:           17,
		BuiltinID:    "ts-misc-yaml-016",
		Name:         "Ensure Admission Control Plugin Namespace Lifecycle Is Set",
		Description:  "Ensure that the admission control plugin NamespaceLifecycle is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0015",
	},
	{
		ID:           18,
		BuiltinID:    "ts-misc-yaml-017",
		Name:         "Ensure Admission Control Plugin Node Restriction Is Set",
		Description:  "Ensure that the admission control plugin NodeRestriction is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0016",
	},
	{
		ID:           19,
		BuiltinID:    "ts-misc-yaml-018",
		Name:         "Ensure Admission Control Plugin Security Context Deny Is Set If Pod Security Policy Is Not Used",
		Description:  "Ensure that the admission control plugin SecurityContextDeny is set if PodSecurityPolicy is not used",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0013",
	},
	{
		ID:           20,
		BuiltinID:    "ts-misc-yaml-019",
		Name:         "Ensure Admission Control Plugin Service Account Is Set",
		Description:  "Ensure that the admission control plugin ServiceAccount is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0014",
	},
	{
		ID:           21,
		BuiltinID:    "ts-misc-yaml-020",
		Name:         "Ensure Anonymous Auth Argument Is False",
		Description:  "Ensure that the --anonymous-auth argument is set to false",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KCV-0001",
	},
	{
		ID:           22,
		BuiltinID:    "ts-misc-yaml-021",
		Name:         "Ensure Api Server Pod Specification File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the API server pod specification file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0048",
	},
	{
		ID:           23,
		BuiltinID:    "ts-misc-yaml-022",
		Name:         "Ensure Api Server Pod Specification Ownership Set root:root",
		Description:  "Ensure that the API server pod specification file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0049",
	},
	{
		ID:           24,
		BuiltinID:    "ts-misc-yaml-023",
		Name:         "Ensure Audit Log Maxage Argument Is Set To 30 Or As Appropriate",
		Description:  "Ensure that the --audit-log-maxage argument is set to 30 or as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0020",
	},
	{
		ID:           25,
		BuiltinID:    "ts-misc-yaml-024",
		Name:         "Ensure Audit Log Maxbackup Argument Is Set To 10 Or As Appropriate",
		Description:  "Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0021",
	},
	{
		ID:           26,
		BuiltinID:    "ts-misc-yaml-025",
		Name:         "Ensure Audit Log Maxsize Argument Is Set To 100 Or As Appropriate",
		Description:  "Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0022",
	},
	{
		ID:           27,
		BuiltinID:    "ts-misc-yaml-026",
		Name:         "Ensure Audit Log Path Argument Is Set",
		Description:  "Ensure that the --audit-log-path argument is set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0019",
	},
	{
		ID:           28,
		BuiltinID:    "ts-misc-yaml-027",
		Name:         "Ensure Authorization Mode Argument Includes Node",
		Description:  "Ensure that the --authorization-mode argument includes Node",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0008",
	},
	{
		ID:           29,
		BuiltinID:    "ts-misc-yaml-028",
		Name:         "Ensure Authorization Mode Argument Includes Rbac",
		Description:  "Ensure that the --authorization-mode argument includes RBAC",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0009",
	},
	{
		ID:           30,
		BuiltinID:    "ts-misc-yaml-029",
		Name:         "Ensure Authorization Mode Argument Is Not Set To AlwaysAllow",
		Description:  "Ensure that the --authorization-mode argument is not set to AlwaysAllow",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0007",
	},
	{
		ID:           31,
		BuiltinID:    "ts-misc-yaml-030",
		Name:         "Ensure Authorization Mode Argument Set AlwaysAllow",
		Description:  "Ensure that the --authorization-mode argument is not set to AlwaysAllow",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0080",
	},
	{
		ID:           32,
		BuiltinID:    "ts-misc-yaml-031",
		Name:         "Ensure Auto Tls Argument Is Not Set To True",
		Description:  "Ensure that the --auto-tls argument is not set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0044",
	},
	{
		ID:           33,
		BuiltinID:    "ts-misc-yaml-032",
		Name:         "Ensure Cert File And Key File Arguments Are Set As Appropriate",
		Description:  "Ensure that the --cert-file and --key-file arguments are set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0042",
	},
	{
		ID:           34,
		BuiltinID:    "ts-misc-yaml-033",
		Name:         "Ensure Certificate Authorities File Permissions 600 Or More Restrictive",
		Description:  "Ensure that the certificate authorities file permissions are set to 600 or more restrictive",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0075",
	},
	{
		ID:           35,
		BuiltinID:    "ts-misc-yaml-034",
		Name:         "Ensure Certificate_authorities Ownership Set root:root",
		Description:  "Ensure that the client certificate authorities file ownership is set to root:root",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0076",
	},
	{
		ID:           36,
		BuiltinID:    "ts-misc-yaml-035",
		Name:         "Ensure Client Ca Argument Set Appropriate",
		Description:  "Ensure that the --client-ca-file argument is set as appropriate",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0081",
	},
	{
		ID:           37,
		BuiltinID:    "ts-misc-yaml-036",
		Name:         "Ensure Client Ca File Argument Is Set As Appropriate",
		Description:  "Ensure that the --client-ca-file argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0028",
	},
	{
		ID:           38,
		BuiltinID:    "ts-misc-yaml-037",
		Name:         "Ensure Client Cert Auth Argument Is Set To True",
		Description:  "Ensure that the --client-cert-auth argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0043",
	},
	{
		ID:           39,
		BuiltinID:    "ts-misc-yaml-038",
		Name:         "Ensure Container Network Interface File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the container network interface file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0056",
	},
	{
		ID:           40,
		BuiltinID:    "ts-misc-yaml-039",
		Name:         "Ensure Container Network Interface Ownership Set root:root",
		Description:  "Ensure that the container network interface file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0057",
	},
	{
		ID:           41,
		BuiltinID:    "ts-misc-yaml-040",
		Name:         "Ensure Controller Manager Bind Address Is Loopback",
		Description:  "Ensure that the --bind-address argument is set to 127.0.0.1",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0039",
	},
	{
		ID:           42,
		BuiltinID:    "ts-misc-yaml-041",
		Name:         "Ensure Controller Manager Config File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the controller-manager config file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0064",
	},
	{
		ID:           43,
		BuiltinID:    "ts-misc-yaml-042",
		Name:         "Ensure Controller Manager Config Ownership Set root:root",
		Description:  "Ensure that the controller-manager config  file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0065",
	},
	{
		ID:           44,
		BuiltinID:    "ts-misc-yaml-043",
		Name:         "Ensure Controller Manager Pod Specification File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the controller manager pod specification file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0050",
	},
	{
		ID:           45,
		BuiltinID:    "ts-misc-yaml-044",
		Name:         "Ensure Controller Manager Pod Specification Ownership Set root:root",
		Description:  "Ensure that the controller manager pod specification file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0051",
	},
	{
		ID:           46,
		BuiltinID:    "ts-misc-yaml-045",
		Name:         "Ensure Deny Service External Ips Is Not Set",
		Description:  "Ensure that the --DenyServiceExternalIPs is not set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0003",
	},
	{
		ID:           47,
		BuiltinID:    "ts-misc-yaml-046",
		Name:         "Ensure Etcd Cafile Argument Is Set As Appropriate",
		Description:  "Ensure that the --etcd-cafile argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0029",
	},
	{
		ID:           48,
		BuiltinID:    "ts-misc-yaml-047",
		Name:         "Ensure Etcd Certfile And Etcd Keyfile Arguments Are Set As Appropriate",
		Description:  "Ensure that the --etcd-certfile and --etcd-keyfile arguments are set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0026",
	},
	{
		ID:           49,
		BuiltinID:    "ts-misc-yaml-048",
		Name:         "Ensure Etcd Data Directory Ownership Set etcd:etcd",
		Description:  "Ensure that the etcd data directory ownership is set to etcd:etcd",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0059",
	},
	{
		ID:           50,
		BuiltinID:    "ts-misc-yaml-049",
		Name:         "Ensure Etcd Data Directory Permissions Set 700 Or More Restrictive",
		Description:  "Ensure that the etcd data directory permissions are set to 700 or more restrictive",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0058",
	},
	{
		ID:           51,
		BuiltinID:    "ts-misc-yaml-050",
		Name:         "Ensure Etcd Pod Specification File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the etcd pod specification file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0054",
	},
	{
		ID:           52,
		BuiltinID:    "ts-misc-yaml-051",
		Name:         "Ensure Etcd Pod Specification Ownership Set root:root",
		Description:  "Ensure that the etcd pod specification file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0055",
	},
	{
		ID:           53,
		BuiltinID:    "ts-misc-yaml-052",
		Name:         "Ensure Event Qps Argument Set 0 Or Level Forappropriate Event Capture",
		Description:  "Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0087",
	},
	{
		ID:           54,
		BuiltinID:    "ts-misc-yaml-053",
		Name:         "Ensure Hostname Override Argument Not Set",
		Description:  "Ensure that the --hostname-override argument is not set",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0086",
	},
	{
		ID:           55,
		BuiltinID:    "ts-misc-yaml-054",
		Name:         "Ensure Kubeconfig Kubelet Config.yaml Ownership Set root:root",
		Description:  "If the kubelet config.yaml configuration file is being used validate file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0078",
	},
	{
		ID:           56,
		BuiltinID:    "ts-misc-yaml-055",
		Name:         "Ensure Kubeconfig Kubelet.conf Ownership Set root:root",
		Description:  "Ensure that the --kubeconfig kubelet.conf file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0074",
	},
	{
		ID:           57,
		BuiltinID:    "ts-misc-yaml-056",
		Name:         "Ensure Kubelet Certificate Authority Argument Is Set",
		Description:  "Ensure that the --kubelet-certificate-authority argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0006",
	},
	{
		ID:           58,
		BuiltinID:    "ts-misc-yaml-057",
		Name:         "Ensure Kubelet Client Certificate And Kubelet Client Key Are Set",
		Description:  "Ensure that the --kubelet-client-certificate and --kubelet-client-key arguments are set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0005",
	},
	{
		ID:           59,
		BuiltinID:    "ts-misc-yaml-058",
		Name:         "Ensure Kubelet Config.yaml  Permissions 600 Or More Restrictive",
		Description:  "If the kubelet config.yaml configuration file is being used validate permissions set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0077",
	},
	{
		ID:           60,
		BuiltinID:    "ts-misc-yaml-059",
		Name:         "Ensure Kubelet Https Argument Is Set To True",
		Description:  "Ensure that the --kubelet-https argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0004",
	},
	{
		ID:           61,
		BuiltinID:    "ts-misc-yaml-060",
		Name:         "Ensure Kubelet Only Makes Use Strong Cryptographic Ciphers",
		Description:  "Ensure that the Kubelet only makes use of Strong Cryptographic Ciphers",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0092",
	},
	{
		ID:           62,
		BuiltinID:    "ts-misc-yaml-061",
		Name:         "Ensure Kubelet Service File Ownership Set root:root",
		Description:  "Ensure that the kubelet service file ownership is set to root:root",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0070",
	},
	{
		ID:           63,
		BuiltinID:    "ts-misc-yaml-062",
		Name:         "Ensure Kubelet Service File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the kubelet service file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0069",
	},
	{
		ID:           64,
		BuiltinID:    "ts-misc-yaml-063",
		Name:         "Ensure Kubelet.conf File Permissions 600 Or More Restrictive",
		Description:  "Ensure that the --kubeconfig kubelet.conf file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0073",
	},
	{
		ID:           65,
		BuiltinID:    "ts-misc-yaml-064",
		Name:         "Ensure Kubernetes Pki Cert File Permission Set 600",
		Description:  "Ensure that the Kubernetes PKI certificate file permission is set to 600",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0068",
	},
	{
		ID:           66,
		BuiltinID:    "ts-misc-yaml-065",
		Name:         "Ensure Kubernetes Pki Directory File Ownership Set root:root",
		Description:  "Ensure that the Kubernetes PKI directory and file ownership is set to root:root",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0066",
	},
	{
		ID:           67,
		BuiltinID:    "ts-misc-yaml-066",
		Name:         "Ensure Kubernetes Pki Key File Permission Set 600",
		Description:  "Ensure that the Kubernetes PKI key file permission is set to 600",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0067",
	},
	{
		ID:           68,
		BuiltinID:    "ts-misc-yaml-067",
		Name:         "Ensure Make Iptables Util Chains Argument Set True",
		Description:  "Ensure that the --make-iptables-util-chains argument is set to true",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0084",
	},
	{
		ID:           69,
		BuiltinID:    "ts-misc-yaml-068",
		Name:         "Ensure Peer Auto Tls Argument Is Not Set To True",
		Description:  "Ensure that the --peer-auto-tls argument is not set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0047",
	},
	{
		ID:           70,
		BuiltinID:    "ts-misc-yaml-069",
		Name:         "Ensure Peer Cert File And Peer Key File Arguments Are Set As Appropriate",
		Description:  "Ensure that the --peer-cert-file and --peer-key-file arguments are set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0045",
	},
	{
		ID:           71,
		BuiltinID:    "ts-misc-yaml-070",
		Name:         "Ensure Peer Client Cert Auth Argument Is Set To True",
		Description:  "Ensure that the --peer-client-cert-auth argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0046",
	},
	{
		ID:           72,
		BuiltinID:    "ts-misc-yaml-071",
		Name:         "Ensure ApiServer Profiling Argument Is Set To False",
		Description:  "Ensure ApiServer that the --profiling argument is set to false",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0018",
	},
	{
		ID:           73,
		BuiltinID:    "ts-misc-yaml-072",
		Name:         "Ensure Controller Manager Profiling Argument Is Set To False",
		Description:  "Ensure Controller Manager that the --profiling argument is set to false",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0034",
	},
	{
		ID:           74,
		BuiltinID:    "ts-misc-yaml-073",
		Name:         "Ensure Scheduler Profiling Argument Is Set To False",
		Description:  "Ensure Scheduler that the --profiling argument is set to false",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0040",
	},
	{
		ID:           75,
		BuiltinID:    "ts-misc-yaml-074",
		Name:         "Ensure Protect Kernel Defaults Set True",
		Description:  "Ensure that the --protect-kernel-defaults is set to true",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0083",
	},
	{
		ID:           76,
		BuiltinID:    "ts-misc-yaml-075",
		Name:         "Ensure Proxy Kubeconfig Ownership Set root:root If Exist",
		Description:  "if proxy kubeconfig file exists ensure ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0072",
	},
	{
		ID:           77,
		BuiltinID:    "ts-misc-yaml-076",
		Name:         "Ensure Proxy Kubeconfig Permissions Set 600 Or More Restrictive If Exist",
		Description:  "If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0071",
	},
	{
		ID:           78,
		BuiltinID:    "ts-misc-yaml-077",
		Name:         "Ensure Root Ca File Argument Is Set As Appropriate",
		Description:  "Ensure that the --root-ca-file argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0037",
	},
	{
		ID:           79,
		BuiltinID:    "ts-misc-yaml-078",
		Name:         "Ensure Rotate Certificates Argument Set False",
		Description:  "Ensure that the --rotate-certificates argument is not set to false",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0090",
	},
	{
		ID:           80,
		BuiltinID:    "ts-misc-yaml-079",
		Name:         "Ensure Rotate Kubelet Server Certificate Argument Set True",
		Description:  "Verify that the RotateKubeletServerCertificate argument is set to true",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0091",
	},
	{
		ID:           81,
		BuiltinID:    "ts-misc-yaml-080",
		Name:         "Ensure Scheduler Bind Address Is Loopback",
		Description:  "Ensure that the --bind-address argument is set to 127.0.0.1",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0041",
	},
	{
		ID:           82,
		BuiltinID:    "ts-misc-yaml-081",
		Name:         "Ensure Scheduler Config File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the scheduler config file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0062",
	},
	{
		ID:           83,
		BuiltinID:    "ts-misc-yaml-082",
		Name:         "Ensure Scheduler Config Ownership Set root:root",
		Description:  "Ensure that the scheduler config  file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0063",
	},
	{
		ID:           84,
		BuiltinID:    "ts-misc-yaml-083",
		Name:         "Ensure Scheduler Pod Specification File Permissions Set 600 Or More Restrictive",
		Description:  "Ensure that the scheduler pod specification file permissions are set to 600 or more restrictive",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0052",
	},
	{
		ID:           85,
		BuiltinID:    "ts-misc-yaml-084",
		Name:         "Ensure Scheduler Pod Specification Ownership Set root:root",
		Description:  "Ensure that the scheduler pod specification file ownership is set to root:root",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0053",
	},
	{
		ID:           86,
		BuiltinID:    "ts-misc-yaml-085",
		Name:         "Ensure Secure Port Argument Is Not Set To 0",
		Description:  "Ensure that the --secure-port argument is not set to 0",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0017",
	},
	{
		ID:           87,
		BuiltinID:    "ts-misc-yaml-086",
		Name:         "Ensure Service Account Key File Argument Is Set As Appropriate",
		Description:  "Ensure that the --service-account-key-file argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0025",
	},
	{
		ID:           88,
		BuiltinID:    "ts-misc-yaml-087",
		Name:         "Ensure Service Account Lookup Argument Is Set To True",
		Description:  "Ensure that the --service-account-lookup argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0024",
	},
	{
		ID:           89,
		BuiltinID:    "ts-misc-yaml-088",
		Name:         "Ensure Service Account Private Key File Argument Is Set As Appropriate",
		Description:  "Ensure that the --service-account-private-key-file argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0036",
	},
	{
		ID:           90,
		BuiltinID:    "ts-misc-yaml-089",
		Name:         "Ensure Terminated Pod Gc Threshold Argument Is Set As Appropriate",
		Description:  "Ensure that the --terminated-pod-gc-threshold argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0033",
	},
	{
		ID:           91,
		BuiltinID:    "ts-misc-yaml-090",
		Name:         "Ensure That The Encryption Provider Config Argument Is Set As Appropriate",
		Description:  "Ensure that the --encryption-provider-config argument is set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0030",
	},
	{
		ID:           92,
		BuiltinID:    "ts-misc-yaml-091",
		Name:         "Ensure That The Rotatekubeletservercertificate Argument Is Set To True",
		Description:  "Ensure that the RotateKubeletServerCertificate argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0038",
	},
	{
		ID:           93,
		BuiltinID:    "ts-misc-yaml-092",
		Name:         "Ensure Tls Cert File And Tls Private Key File Arguments Are Set As Appropriate",
		Description:  "Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0027",
	},
	{
		ID:           94,
		BuiltinID:    "ts-misc-yaml-093",
		Name:         "Ensure Tls Cert File Argument Set Appropriate",
		Description:  "Ensure that the --tls-cert-file argument are set as appropriate",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0088",
	},
	{
		ID:           95,
		BuiltinID:    "ts-misc-yaml-094",
		Name:         "Ensure Tls Key File Argument Set Appropriate",
		Description:  "Ensure that the --tls-key-file argument are set as appropriate",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KCV-0089",
	},
	{
		ID:           96,
		BuiltinID:    "ts-misc-yaml-095",
		Name:         "Ensure Token Auth File Parameter Is Not Set",
		Description:  "Ensure that the --token-auth-file parameter is not set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0002",
	},
	{
		ID:           97,
		BuiltinID:    "ts-misc-yaml-096",
		Name:         "Ensure Use Service Account Credentials Argument Is Set To True",
		Description:  "Ensure that the --use-service-account-credentials argument is set to true",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KCV-0035",
	},
	{
		ID:           98,
		BuiltinID:    "ts-misc-yaml-097",
		Name:         "Evaluate K8s Deprecated Removed Apis",
		Description:  "Evaluate k8s deprecated and removed APIs",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0107",
	},
	{
		ID:           99,
		BuiltinID:    "ts-misc-yaml-098",
		Name:         "Limit Cpu",
		Description:  "CPU not limited",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0011",
	},
	{
		ID:           100,
		BuiltinID:    "ts-misc-yaml-099",
		Name:         "Limit Memory",
		Description:  "Memory not limited",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0018",
	},
	{
		ID:           101,
		BuiltinID:    "ts-misc-yaml-100",
		Name:         "No Attaching Shell Pods",
		Description:  "Do not allow attaching to shell on pods",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0054",
	},
	{
		ID:           102,
		BuiltinID:    "ts-misc-yaml-101",
		Name:         "No Auto Mount Service Token",
		Description:  "Protecting Pod service account tokens",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0036",
	},
	{
		ID:           103,
		BuiltinID:    "ts-misc-yaml-102",
		Name:         "No Custom Proc Mask",
		Description:  "Non-default /proc masks set",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0027",
	},
	{
		ID:           104,
		BuiltinID:    "ts-misc-yaml-103",
		Name:         "No Custom Selinux Options",
		Description:  "SELinux custom options set",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0025",
	},
	{
		ID:           105,
		BuiltinID:    "ts-misc-yaml-104",
		Name:         "No Delete Pod Logs",
		Description:  "Do not allow deletion of pod logs",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0042",
	},
	{
		ID:           106,
		BuiltinID:    "ts-misc-yaml-105",
		Name:         "No Docker Sock Mount",
		Description:  "hostPath volume mounted with docker.sock",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0006",
	},
	{
		ID:           107,
		BuiltinID:    "ts-misc-yaml-106",
		Name:         "No Getting Shell Pods",
		Description:  "Do not allow getting shell on pods",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0053",
	},
	{
		ID:           108,
		BuiltinID:    "ts-misc-yaml-107",
		Name:         "No Host Network",
		Description:  "Access to host network",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0009",
	},
	{
		ID:           109,
		BuiltinID:    "ts-misc-yaml-108",
		Name:         "No Host Pid",
		Description:  "Access to host PID",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0010",
	},
	{
		ID:           110,
		BuiltinID:    "ts-misc-yaml-109",
		Name:         "No Host Port Access",
		Description:  "Access to host ports",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0024",
	},
	{
		ID:           111,
		BuiltinID:    "ts-misc-yaml-110",
		Name:         "No Hostprocess Containers",
		Description:  "HostProcess container defined",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0103",
	},
	{
		ID:           112,
		BuiltinID:    "ts-misc-yaml-111",
		Name:         "No Impersonate Privileged Groups",
		Description:  "Do not allow impersonation of privileged groups",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0043",
	},
	{
		ID:           113,
		BuiltinID:    "ts-misc-yaml-112",
		Name:         "No Manage Configmaps",
		Description:  "Do not allow management of configmaps",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0049",
	},
	{
		ID:           114,
		BuiltinID:    "ts-misc-yaml-113",
		Name:         "No Manage Networking Resources",
		Description:  "Do not allow management of networking resources",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0056",
	},
	{
		ID:           115,
		BuiltinID:    "ts-misc-yaml-114",
		Name:         "No Manage Rbac Resources",
		Description:  "Do not allow management of RBAC resources",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0050",
	},
	{
		ID:           116,
		BuiltinID:    "ts-misc-yaml-115",
		Name:         "No Manage Secrets",
		Description:  "Do not allow management of secrets",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0041",
	},
	{
		ID:           117,
		BuiltinID:    "ts-misc-yaml-116",
		Name:         "No Mounted Hostpath",
		Description:  "hostPath volumes mounted",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0023",
	},
	{
		ID:           118,
		BuiltinID:    "ts-misc-yaml-117",
		Name:         "No Non Default Capabilities",
		Description:  "Non-default capabilities added",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0022",
	},
	{
		ID:           119,
		BuiltinID:    "ts-misc-yaml-118",
		Name:         "No Non Ephemeral Volumes",
		Description:  "Non-ephemeral volume types used",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0028",
	},
	{
		ID:           120,
		BuiltinID:    "ts-misc-yaml-119",
		Name:         "No Privilege Escalation From Node Proxy",
		Description:  "Do not allow privilege escalation from node proxy",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0047",
	},
	{
		ID:           121,
		BuiltinID:    "ts-misc-yaml-120",
		Name:         "No Privileged Containers",
		Description:  "Privileged container",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0017",
	},
	{
		ID:           122,
		BuiltinID:    "ts-misc-yaml-121",
		Name:         "No Root",
		Description:  "Runs as root user",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0012",
	},
	{
		ID:           123,
		BuiltinID:    "ts-misc-yaml-122",
		Name:         "No Seccomp Unconfined",
		Description:  "Seccomp profile unconfined",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0104",
	},
	{
		ID:           124,
		BuiltinID:    "ts-misc-yaml-123",
		Name:         "No Self Privesc",
		Description:  "Process can elevate its own privileges",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0001",
	},
	{
		ID:           125,
		BuiltinID:    "ts-misc-yaml-124",
		Name:         "No Shared Ipc Namespace",
		Description:  "Access to host IPC namespace",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0008",
	},
	{
		ID:           126,
		BuiltinID:    "ts-misc-yaml-125",
		Name:         "No Sysadmin Capability",
		Description:  "SYS_ADMIN capability added",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0005",
	},
	{
		ID:           127,
		BuiltinID:    "ts-misc-yaml-126",
		Name:         "No Tiller",
		Description:  "Tiller Is Deployed",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0102",
	},
	{
		ID:           128,
		BuiltinID:    "ts-misc-yaml-127",
		Name:         "No Unsafe Sysctl",
		Description:  "Unsafe sysctl options set",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0026",
	},
	{
		ID:           129,
		BuiltinID:    "ts-misc-yaml-128",
		Name:         "No Unspecified Cpu Requests",
		Description:  "CPU requests not specified",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0015",
	},
	{
		ID:           130,
		BuiltinID:    "ts-misc-yaml-129",
		Name:         "No Unspecified Memory Requests",
		Description:  "Memory requests not specified",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0016",
	},
	{
		ID:           131,
		BuiltinID:    "ts-misc-yaml-130",
		Name:         "No User Pods In System Namespace",
		Description:  "User Pods should not be placed in kube-system namespace",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0037",
	},
	{
		ID:           132,
		BuiltinID:    "ts-misc-yaml-131",
		Name:         "No Wildcard Resource Role",
		Description:  "No wildcard resource roles",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0046",
	},
	{
		ID:           133,
		BuiltinID:    "ts-misc-yaml-132",
		Name:         "No Wildcard Verb Resource Role",
		Description:  "No wildcard verb and resource roles",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0044",
	},
	{
		ID:           134,
		BuiltinID:    "ts-misc-yaml-133",
		Name:         "No Wildcard Verb Role",
		Description:  "No wildcard verb roles",
		Severity:     "CRITICAL",
		ThirdPartyID: "AVD-KSV-0045",
	},
	{
		ID:           135,
		BuiltinID:    "ts-misc-yaml-134",
		Name:         "No svc with extip",
		Description:  "Service with External IP",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KSV-0108",
	},
	{
		ID:           136,
		BuiltinID:    "ts-misc-yaml-135",
		Name:         "Selector Usage In Network Policies",
		Description:  "Selector usage in network policies",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0038",
	},
	{
		ID:           137,
		BuiltinID:    "ts-misc-yaml-136",
		Name:         "Use Default Apparmor Profile",
		Description:  "Default AppArmor profile not set",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0002",
	},
	{
		ID:           138,
		BuiltinID:    "ts-misc-yaml-137",
		Name:         "Use Default Seccomp",
		Description:  "Default Seccomp profile not set",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0030",
	},
	{
		ID:           139,
		BuiltinID:    "ts-misc-yaml-138",
		Name:         "Use High Gid",
		Description:  "Runs with low group ID",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0021",
	},
	{
		ID:           140,
		BuiltinID:    "ts-misc-yaml-139",
		Name:         "Use High Uid",
		Description:  "Runs with low user ID",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0020",
	},
	{
		ID:           141,
		BuiltinID:    "ts-misc-yaml-140",
		Name:         "Use Readonly Filesystem",
		Description:  "Root file system is not read-only",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0014",
	},
	{
		ID:           142,
		BuiltinID:    "ts-misc-yaml-141",
		Name:         "Use Specific Tags",
		Description:  "Image tag ':latest' used",
		Severity:     "MEDIUM",
		ThirdPartyID: "AVD-KSV-0013",
	},
	{
		ID:           143,
		BuiltinID:    "ts-misc-yaml-142",
		Name:         "Verify Read Only Port Argument Set 0",
		Description:  "Verify that the --read-only-port argument is set to 0",
		Severity:     "HIGH",
		ThirdPartyID: "AVD-KCV-0082",
	},
	{
		ID:           144,
		BuiltinID:    "ts-misc-yaml-143",
		Name:         "No Allow Users Rolebinding Add Other Users Rolebindings",
		Description:  "Do not allow users in a rolebinding to add other users to their rolebindings",
		Severity:     "LOW",
		ThirdPartyID: "AVD-KSV-0055",
	},
}
