{{- if .Values.managedServiceAccount }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ template "secProfilesManager.serviceAccount" . }}-ep-cluster-role
  labels:
    app: "{{ template "secProfilesManager.fullname" . }}-ep"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
- apiGroups:
  - ""
  - "apps"
  - "batch"
  - "extensions"
  resources:
  - pods
  - replicasets
  verbs:
  - list
  - watch
  - get
{{- end -}}
