{{- if .Values.managedServiceAccount }}
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-processor" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sec-prof-man-processor
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-processor" (include "common.names.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-processor" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
