{{- if .Values.global.multiCluster.isMainCluster -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-sidecar" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: webhook-sidecar
data:
  proxyconfig.json: |
    {
      "interception_mode": "REDIRECT",
      "nats_urls": "nats://{{ include "common.stan.defaultName" . }}-headless.{{ .Release.Namespace }}.svc:4222",
      "nats_subject": {{ .Values.nats.natsSubject | quote }},
      "nats_cluster_id": {{ .Values.nats.clusterId | quote }},
      "ignored_name_spaces": [{{ .Values.sidecar.ignoredNameSpaces  | quote }},{{ .Release.Namespace | quote }}],
      "init_container_image": {{ include "webhook.sidecar.init.image" . | quote }},
      "container_image": {{ include "webhook.sidecar.image" . | quote }},
      "image_pull_secrets": {{ .Values.image.pullSecret | quote }}
    }
  sidecar-template.yaml: |
{{ .Files.Get "sidecar.yaml" | indent 4}}
{{- end -}}