{{- if .Values.global.multiCluster.isMainCluster -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  image-trust-mutator.yaml: |-
    ignored_name_spaces:
    - kube-system
    - {{ .Release.Namespace }}
    pg_addr: {{ include "common.pgpool.DSN" . }}
  image-trust-validator.yaml: |-
    image_trust_url: http://{{ include "common.scanner.defaultName" . }}.{{ .Release.Namespace }}.svc:8888/api/v1/imagereject/online_moniter
    ignored_name_spaces:
    - kube-system
    - {{ .Release.Namespace }}
  microseg.yaml: |-
    pgMaster:
      host: "{{ include "common.pgpool.defaultName" . }}"
      user: "postgres"
      password: "password"
      dbName: "postgres"
      port: "5432"
    runMode: "dev"
  presets.yaml: |-
    env:
    - name: LD_PRELOAD
      value: "/tmp/dp.so"
    - name: EVENTCENTER_NEW_ADDR
      value: "eventcenter.{{ .Release.Namespace }}.svc.cluster.local"
    - name: EVENTCENTER_NEW_PORT
      value: "8080"
    volumemounts:
    - name: "{{ .Values.presets.volumes.clientName }}"
      mountpath: "{{ .Values.presets.volumes.clientMountPath }}"
      readonly: true
    - name: {{ .Values.presets.volumes.caName }}
      mountpath: "{{ .Values.presets.volumes.caMountPath }}"
      readonly: true
    volumes:
      - name: "{{ .Values.presets.volumes.clientName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.presets.volumes.clientSecretName }}"
      - name: "{{ .Values.presets.volumes.caName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.presets.volumes.caSecretName }}"
{{- end -}}