{{- if .Values.global.multiCluster.isMasterCluster -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "webhook.fullname" . }}-sidecar
  labels:
{{ include "webhook.labels" . | indent 4 }}
data:
  proxyconfig.json: |
    {
      "interception_mode": "REDIRECT",
      "nats_urls": {{ .Values.nats.natsUrl | quote }},
      "nats_subject": {{ .Values.nats.natsSubject | quote }},
      "ignored_name_spaces": [{{ .Values.sidecar.ignoredNameSpaces  | quote }},{{ .Release.Namespace | quote }}],
      "init_container_image": {{ include "tensorsec.webhook.sidecar.init.image" . | quote }},
      "container_image": {{ include "tensorsec.webhook.sidecar.image" . | quote }},
      "image_pull_secrets": {{ .Values.image.pullSecret | quote }},
      "pg_addr": "postgres://postgres:password@tensorsec-postgresql:5432/postgres?sslmode=disable"
    }
  sidecar-template.yaml: |
{{ .Files.Get "sidecar.yaml" | indent 4}}
{{- end -}}