apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "common.names.fullname" . }}
      containers:
      - name: webhook
        image: {{ include "webhook.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 9443
          protocol: TCP
        args:
        {{- if .Values.global.multiCluster.isMainCluster }}
        - --validators={{ .Values.validators }}
        - --mutators={{ .Values.mutators }}
        - --pgAddr={{ include "common.pgpool.DSN" . }}
        {{- else if .Values.global.multiCluster.isMemberCluster }}
        - proxy
        - --target-host={{ .Values.global.multiCluster.configs.consoleExternalAdd }}
        - --clusterMgrAddress=http://{{ include "common.cluster-manager.defaultName" . }}:9443
        {{- end }}
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
        volumeMounts:
        - mountPath: /etc/webhook/certs
          name: webhook-certs
          readOnly: true
        {{- if .Values.global.multiCluster.isMainCluster }}
        - mountPath: /etc/webhook/config
          name: webhook-config
        - mountPath: /etc/webhook/sidecar
          name: config-sidecar
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      restartPolicy: Always
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "common.names.fullname" . }}
      {{- if .Values.global.multiCluster.isMainCluster }}
      - name: webhook-config
        configMap:
          name: {{ include "common.names.fullname" . }}
      - name: config-sidecar
        configMap:
          name: {{ printf "%s-sidecar" (include "common.names.fullname" .) }}
      {{- end }}   

