package api

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/jwtauth"
	"github.com/patrickmn/go-cache"
	httpSwagger "github.com/swaggo/http-swagger"
	"go.mongodb.org/mongo-driver/mongo"

	_ "gitlab.com/piccolo_su/vegeta/cmd/console/docs" // docs is generated by Swag CLI
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/cluster"
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/cron"
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/scapper"
	"gitlab.com/piccolo_su/vegeta/pkg/locale"
	"gitlab.com/piccolo_su/vegeta/pkg/logging"
	"gitlab.com/piccolo_su/vegeta/pkg/response"
)

type key int

const (
	userKey key = iota
)

var (
	log *logging.Logger
)

func init() {
	log = logging.GetLogger()
}

// SetupRoutes is to set up the chi router
func SetupRoutes(
	ctx context.Context,
	r *chi.Mux,
	sessionExpiration time.Duration,
	mongodb *mongo.Database,
	scapper *scapper.Scapper,
	scannerURL string,
	cronService *cron.CronService,
	clusterService *cluster.ClusterService,
) {
	log.Debug().Msg("setting up routes...")

	r.Get("/*", static())
	r.Get("/ping", response.Pong)
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("swagger/doc.json")))

	api := newAPI(ctx, sessionExpiration, mongodb, scapper, scannerURL, cronService, clusterService)
	r.Route("/api", func(r chi.Router) {
		r.Route("/v1", func(r chi.Router) {
			r.Route("/rest-auth", api.restAuth())

			// needs authentication
			r.Group(func(r chi.Router) {
				r.Use(jwtauth.Verifier(api.tokenAuth))

				// custom authenticator
				r.Use(jwtAuthenticator(api.userCache))

				r.Route("/config", api.config())
				r.Route("/scanner", api.scanner())
				r.Route("/scap", api.scap())
			})
		})
	})
}

func jwtAuthenticator(userCache *cache.Cache) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			token, claims, err := jwtauth.FromContext(r.Context())

			if err != nil {
				response.Unauthorized(w, response.WithMessage(locale.Error(locale.InvalidAuthToken, r)))
				logging.GetLogger().Info().Err(err).Msg("Error when getting token & claims from context")
				return
			}
			if token == nil || !token.Valid {
				response.Unauthorized(w, response.WithMessage(locale.Error(locale.InvalidAuthToken, r)))
				logging.GetLogger().Info().Str("token", fmt.Sprintf("%v", token)).Msg("Token empty or invalid")
				return
			}

			// check if we can find the user's session
			username := claims["username"].(string)
			userPtr, ok := userCache.Get(username)
			if !ok {
				response.Unauthorized(w, response.WithMessage(locale.Error(locale.SessionExpired, r)))
				logging.GetLogger().Info().Str("username", username).Msg("User not in cache")
				return
			}

			// reset the TTL for the user if found
			userCache.Set(
				username,
				userPtr,
				cache.DefaultExpiration)

			ctx := context.WithValue(r.Context(), userKey, userPtr)

			// Token is authenticated, pass it through
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func static() http.HandlerFunc {
	currentDir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
	filesDir := filepath.Join(currentDir, "ui")
	return http.StripPrefix("/", http.FileServer(http.Dir(filesDir))).ServeHTTP
}
