package api

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"path/filepath"
	"time"

	elasticsearch "github.com/elastic/go-elasticsearch/v7"
	"github.com/go-chi/chi"
	"github.com/go-chi/jwtauth"
	"github.com/golang/gddo/httputil/header"
	"github.com/patrickmn/go-cache"
	httpSwagger "github.com/swaggo/http-swagger"
	"go.etcd.io/etcd/clientv3"
	"go.mongodb.org/mongo-driver/mongo"

	_ "gitlab.com/piccolo_su/vegeta/cmd/console/docs" // docs is generated by Swag CLI
	"gitlab.com/piccolo_su/vegeta/pkg/logging"
	"gitlab.com/piccolo_su/vegeta/pkg/response"
)

type key int

const (
	userKey key = iota
)

var (
	log *logging.Logger
)

func init() {
	log = logging.GetLogger()
}

// SetupRoutes is to set up the chi router
func SetupRoutes(
	ctx context.Context,
	r *chi.Mux,
	sessionExpiration time.Duration,
	esClient *elasticsearch.Client,
	etcdClient *clientv3.Client,
	mongodb *mongo.Database,
	scapper *Scapper,
	scannerURL string,
) {
	log.Debug().Msg("setting up routes...")

	r.Get("/*", static())
	r.Get("/ping", response.Pong)
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("swagger/doc.json")))

	api := newAPI(ctx, sessionExpiration, esClient, etcdClient, mongodb, scapper, scannerURL)
	r.Route("/api", func(r chi.Router) {
		r.Route("/v1", func(r chi.Router) {
			r.Route("/rest-auth", api.restAuth())

			// no authentication in dev
			r.Route("/overall", api.restStat())
			// no authentication in dev
			r.Route("/assets", api.restAsset())

			// no authentication in dev
			r.Route("/detail", api.restDetail())

			// no authentication in dev
			r.Route("/alarms", api.restAlarms())

			// no authentication in dev
			r.Route("/profiles", api.restProfiles())

			// needs authentication
			r.Group(func(r chi.Router) {
				r.Use(jwtauth.Verifier(api.tokenAuth))

				// custom authenticator
				r.Use(jwtAuthenticator(api.userCache))

				r.Route("/config", api.config())
				r.Route("/journals", api.journals())
				r.Route("/scanner", api.scanner())
				r.Route("/scap", api.scap())
			})
		})
	})
}

func jwtAuthenticator(userCache *cache.Cache) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			token, claims, err := jwtauth.FromContext(r.Context())
			if err != nil || token == nil || !token.Valid {
				response.Unauthorized(w, "Invalid token")
				return
			}

			// check if we can find the user's session
			username := claims["username"].(string)
			userPtr, ok := userCache.Get(username)
			if !ok {
				response.Unauthorized(w, "User session expired")
				return
			}

			// reset the TTL for the user if found
			userCache.Set(
				username,
				userPtr,
				cache.DefaultExpiration)

			ctx := context.WithValue(r.Context(), userKey, userPtr)

			// Token is authenticated, pass it through
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}

func static() http.HandlerFunc {
	currentDir, _ := filepath.Abs(filepath.Dir(os.Args[0]))
	filesDir := filepath.Join(currentDir, "ui")
	return http.StripPrefix("/", http.FileServer(http.Dir(filesDir))).ServeHTTP
}

func decodeJSONBody(w http.ResponseWriter, r *http.Request, dst interface{}) error {
	if r.Header.Get("Content-Type") != "" {
		value, _ := header.ParseValueAndParams(r.Header, "Content-Type")
		if value != "application/json" {
			return errors.New("The http header is not application/json")
		}
	}

	r.Body = http.MaxBytesReader(w, r.Body, 1048576)

	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()

	err := dec.Decode(&dst)
	if err != nil {
		return err
	}

	if dec.More() {
		return errors.New("Request body must only contain a single JSON object")
	}

	return nil
}
