package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/jwtauth"
	"github.com/go-redis/redis/v8"
	"github.com/patrickmn/go-cache"
	httpSwagger "github.com/swaggo/http-swagger"
	"go.mongodb.org/mongo-driver/mongo"

	_ "gitlab.com/piccolo_su/vegeta/cmd/console/docs" // docs is generated by Swag CLI
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/cluster"
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/cron"
	"gitlab.com/piccolo_su/vegeta/cmd/console/service/scapper"
	. "gitlab.com/piccolo_su/vegeta/pkg/apperror"
	"gitlab.com/piccolo_su/vegeta/pkg/logging"
	"gitlab.com/piccolo_su/vegeta/pkg/response"
)

type key int

const (
	userKey key = iota
)

var (
	log *logging.Logger
)

func init() {
	log = logging.GetLogger()
}

// SetupRoutes is to set up the chi router
func SetupRoutes(
	ctx context.Context,
	r *chi.Mux,
	sessionExpiration time.Duration,
	mongodb *mongo.Database,
	scapper *scapper.Scapper,
	scannerURL string,
	cronService *cron.CronService,
	clusterService *cluster.ClusterService,
	redisClient *redis.Client,
) {
	log.Debug().Msg("setting up routes...")

	api := newAPI(ctx, sessionExpiration, mongodb, scapper, scannerURL, cronService, clusterService, redisClient)

	r.Get("/ping", response.Pong)
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("swagger/doc.json")))
	r.Route("/harbor/api/v1", api.harbor())
	r.Route("/api/v1", func(r chi.Router) {
		r.Route("/auth", api.restAuth())

		// needs authentication
		r.Group(func(r chi.Router) {
			r.Use(jwtauth.Verifier(api.tokenAuth))

			// custom authenticator
			r.Use(jwtAuthenticator(api.userCache))

			r.Route("/config", api.config())
			r.Route("/scanner", api.scanner())
			r.Route("/scap", api.scap())
		})
	})
}

func jwtAuthenticator(userCache *cache.Cache) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			token, claims, err := jwtauth.FromContext(r.Context())

			if err != nil {
				RespAndLog(w, r,
					NewInvalidAuthToken(http.StatusUnauthorized,
						fmt.Errorf("Error when getting token & claims from context: %w", err)))
				return
			}
			if token == nil || !token.Valid {
				RespAndLog(w, r,
					NewInvalidAuthToken(http.StatusUnauthorized,
						fmt.Errorf("Token empty or invalid")))
				return
			}

			// check if we can find the user's session
			username := claims["username"].(string)
			userPtr, ok := userCache.Get(username)
			if !ok {
				RespAndLog(w, r,
					NewSessionExpired(http.StatusUnauthorized,
						fmt.Errorf("User not in cache")))
				return
			}

			// reset the TTL for the user if found
			userCache.Set(
				username,
				userPtr,
				cache.DefaultExpiration)

			ctx := context.WithValue(r.Context(), userKey, userPtr)

			// Token is authenticated, pass it through
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
