image:
  registry:  localhost:32000
  repository: tensorsecurity
  name: tensorsec-drift-prevention
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

eventcenter:
  addr: tensorsec-eventcenter.tensorsec.svc.cluster.local
  port: "8080"

nameOverride: "drift-prevention"
fullnameOverride: "tensorsec-drift-prevention"

volumes:
  clientName: "client-cert"
  clientSecretName: "eventcenter-tls-client-cert-secret"
  clientMountPath: "/auth/client"
  caName: "ca-cert"
  caSecretName: "eventcenter-tls-ca-secret"
  caMountPath: "/auth/ca"

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "64Mi"
    cpu: "50m"
