console:
  addr: tensorsec-console.tensorsec.svc.cluster.local
  port: "8889"

nameOverride: "drift-prevention"
fullnameOverride: "tensorsec-drift-prevention"

image:
  name: tensorsec-drift-prevention
  # repository: localhost:32000
  tag: latest
  pullPolicy: Always

imagePullSecrets:
- name: "harbor-admin-secret"
