image:
  registry:  localhost:32000
  repository: tensorsecurity
  name: tensorsec-drift-prevention
  tag: latest
  pullPolicy: Always

eventcenter:
  addr: tensorsec-eventcenter.tensorsec.svc.cluster.local
  port: "8080"

nameOverride: "drift-prevention"
fullnameOverride: "tensorsec-drift-prevention"

imagePullSecrets:
- name: "harbor-admin-secret"

volumes:
  clientName: "client-cert"
  clientSecretName: "eventcenter-tls-client-cert-secret"
  clientMountPath: "/auth/client"
  caName: "ca-cert"
  caSecretName: "eventcenter-tls-ca-secret"
  caMountPath: "/auth/ca"
