##attck_rule_type=Credential_Access
- key: Gaining environment information
  hid: ca_01
  condition: >
    open_read and container and
    ((proc.name in (show_information_binaries)) and (fd.filename in (sensitive_paths) or fd.name in (sensitive_paths) or fd.directory in (sensitive_paths)) or (proc.name in (show_env_binaries))) and not
    tensorsec_namespace and
    shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,fd_name=%fd.name,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Gaining environment information"
      zh: "容器内获取环境信息"
    desc:
      en: "Gaining environment information"
      zh: "容器内获取环境信息"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of a known process and whether it is executed by malware, and you can use the immune defense training application to restrict user permissions for sensitive files and commands."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，可使用免疫防御训练应用，限制敏感文件和命令的用户权限。"
    rule_type: Credential_Access
    priority: WARNING
    urgency: true
    tags: [ATT&CK, L2]

# - key: Read sensitive file trusted after startup
#   hid: ca_02
#   condition: >
#     sensitive_files and open_read and server_procs and not proc_is_new and proc.name!="sshd" and not user_known_read_sensitive_files_activities and not tensorsec_namespace
#   output: >
#     proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,parent=%proc.pname,file=%fd.name,parent=%proc.pname,gparent=%proc.aname[2],container_id=%container.id,container_name=%container.name,image=%container.image.repository
#   info:
#     name:
#       en: "Read sensitive file trusted after startup"
#       zh: "敏感文件在启动后被受信任的程序读取"
#     desc:
#       en: "an attempt to read any sensitive file (e.g. files containing user/password/authentication information) by a trusted program after startup. Trusted programs might read these files at startup to load initial state, but not afterwards."
#       zh: "容器内敏感文件启动后被受信任的程序读取"
#     suggestion:
#       en: "Please confirm whether the reading behavior is as expected. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit mounting sensitive directories and files."
#       zh: "请确认该读取行为是否属于进程的正常行为，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
#     rule_type: Credential_Access
#     priority: INFO
#     urgency: true
#     tags: [ATT&CK, filesystem, mitre_credential_access]

- key: Search Private Keys or Passwords
  hid: ca_03
  condition: >
    spawned_process and
    ((grep_commands and private_key_or_password) or
     (proc.name = "find" and (proc.args contains "id_rsa" or proc.args contains "id_dsa")))
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container_id=%container.id,container_name=%container.name,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Search Private Keys or Passwords"
      zh: "容器内查找私钥或密码"
    desc:
      en: "Detect private keys or passwords activity"
      zh: "容器内查找私钥或密码"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, whether the key in the container is leaked, and also correlate other attacks."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，容器内密钥是否泄漏，同时关联其他攻击行为。"
    rule_type: Credential_Access
    priority: WARNING
    urgency: true
    tags: [ATT&CK, process, mitre_credential_access, L4]
