##attck_rule_type=Defense_Evasion
- key: Modify log activities
  hid: def_01
  condition: >
    open_write and
    access_log_files and
    evt.arg.flags contains "O_TRUNC" and
    shell_parent_procs and
    not trusted_logging_images and
    not allowed_clear_log_files and 
    not tensorsec_namespace
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Modify log activities"
      zh: "日志文件被篡改"
    desc:
      en: "Modify critical log files"
      zh: "日志文件被篡改"
    suggestion:
      en: "Please go through the process tree to determine whether the command is a normal behavior of a known process and executed by malware, otherwise it may be a hacker removing traces of the attack."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，否则可能是黑客清除攻击痕迹。"
    rule_type: Defense_Evasion
    priority: WARNING
    urgency: true
    tags: [ATT&CK, file, mitre_defense_evasion, L1]

- key: Delete bash history
  hid: def_02
  condition: >
    ((spawned_process and proc.name in (shred, rm, mv) and proc.args contains "bash_history") or
     (open_write and fd.name contains "bash_history" and evt.arg.flags contains "O_TRUNC")) and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,type=%evt.type,fd_name=%fd.name,name=%evt.arg.name,path=%evt.arg.path,oldpath=%evt.arg.oldpath,container.info=%container.info,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Delete bash history"
      zh: "bash历史文件被删除"
    desc:
      en: "Detect bash history deletion"
      zh: "检测到bash历史文件被删除"
    suggestion:
      en: "This behavior may occur when the hacker cleans up the attack trace. Please confirm whether the execution object of this behavior meets the expectation."
      zh: "通常该行为发生于黑客清除攻击痕迹，请确认是否遭到入侵。"
    rule_type: Defense_Evasion
    priority: WARNING
    urgency: true
    tags: [ATT&CK, process, mitre_defense_evasion, L3]

- key: Create Symlink Over Sensitive Files
  hid: def_03
  condition: >
    create_symlink
    and (evt.arg.target in (sensitive_file_names) or evt.arg.target in (sensitive_directory_names) or link_sensitive_files)
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,target=%evt.arg.target,linkpath=%evt.arg.linkpath,parent_process=%proc.pname,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Create Symlink Over Sensitive Files"
      zh: "通过敏感文件创建符号链接"
    desc:
      en: "Detect symlink created over sensitive files"
      zh: "检测到通过敏感文件创建符号链接"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of a known process and whether it is executed by malware. Hackers may bypass defense detection through this behavior and may use immune defense training applications to restrict user permissions for sensitive files and commands."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，黑客可能通过该行为绕过防御检测，可使用免疫防御训练应用，限制敏感文件和命令的用户权限。"
    rule_type: Defense_Evasion
    priority: ERROR
    urgency: true
    tags: [ATT&CK, file, mitre_exfiltration, L3]