##attck_rule_type=Discovery
- key: Read sensitive file untrusted
  hid: disc_01
  condition: >
    sensitive_files and open_read and container
    and proc_name_exists
    and shell_parent_procs
    and not proc.name in (user_mgmt_binaries, userexec_binaries, package_mgmt_binaries,
     cron_binaries, read_sensitive_file_binaries, shell_binaries, hids_binaries,
     vpn_binaries, mail_config_binaries, nomachine_binaries, sshkit_script_binaries,
     in.proftpd, mandb, salt-minion, postgres_mgmt_binaries,
     google_oslogin_
     )
    and not cmp_cp_by_passwd
    and not ansible_running_python
    and not proc.cmdline contains /usr/bin/mandb
    and not run_by_qualys
    and not run_by_chef
    and not run_by_google_accounts_daemon
    and not user_read_sensitive_file_conditions
    and not perl_running_plesk
    and not perl_running_updmap
    and not veritas_driver_script
    and not perl_running_centrifydc
    and not runuser_reading_pam
    and not linux_bench_reading_etc_shadow
    and not user_known_read_sensitive_files_activities
    and not user_read_sensitive_file_containers
    and not runc_writing_passwd
    and not tensorsec_namespace
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,program=%proc.name,file=%fd.name,parent=%proc.pname,gparent=%proc.aname[2],ggparent=%proc.aname[3],gggparent=%proc.aname[4],container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Read sensitive file untrusted"
      zh: "未受信任的程序试图读取敏感文件"
    desc:
      en: "an attempt to read any sensitive file (e.g. files containing user/password/authentication information). Exceptions are made for known trusted programs."
      zh: "试图读取任何敏感文件（例如包含用户/密码/身份验证信息的文件）。对于已知的受信任程序除外。"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of a known process and whether it is executed by malware. You can use the immune defense training application to restrict the user rights of sensitive files and commands and prohibit the mounting of sensitive directories and files."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK, filesystem, mitre_credential_access, mitre_discovery]

- key: View network information in the container
  hid: disc_02
  condition: >
    spawned_process and container and proc.name in (namespace_bypass_cmds) and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "View network information in the container"
      zh: "容器内查看网络信息"
    desc:
      en: "View network information in the container"
      zh: "容器内查看网络信息"
    suggestion:
      en: "Please use the process tree to determine whether the behavior is executed by the operation and maintenance personnel or initiated by a trusted probe type program, if not, please correlate other attacks to confirm whether the container has been compromised."
      zh: "请通过进程树判断该行为是否为运维人员执行或可信探针类程序发起，如果不是请关联其他攻击行为，确认容器是否遭到入侵。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: Read Shell Configuration File
  hid: disc_03
  condition: >
    open_read and
    shell_parent_procs and
    (fd.filename in (shell_config_filenames) or
    fd.name in (shell_config_files) or
    fd.directory in (shell_config_directories)) and
    not proc.name in (shell_binaries) and
    not fd.name contains "history"
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Read Shell Configuration File"
      zh: "非shell程序读取shell配置文件"
    desc:
      en: "Detect attempts to read shell configuration files by non-shell programs"
      zh: "检测非shell程序试图读取shell配置文件的行为"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of known processes and whether it is executed by malware, otherwise you can use offset defense to restrict its execution."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，否则可使用偏移防御限制其执行。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK, file, mitre_discovery]

- key: Read ssh information
  hid: disc_04
  condition: >
    ((open_read or open_directory) and
     consider_ssh_reads and
     (user_ssh_directory or fd.name startswith /root/.ssh) and
     not user_known_read_ssh_information_activities and
     not proc.name in (ssh_binaries))
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,parent=%proc.pname,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Read ssh information"
      zh: "非ssh用户查看ssh信息"
    desc:
      en: "Any attempt to read files below ssh directories by non-ssh programs"
      zh: "任何非ssh程序试图读取ssh目录下的文件"
    suggestion:
      en: "This behavior may be that hackers collect information, can use immune defense training applications, restrict user permissions of sensitive files and commands, and prohibit mounting sensitive directories and files."
      zh: "该行为可能是黑客进行信息收集，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
    rule_type: Discovery
    priority: ERROR
    urgency: true
    tags: [ATT&CK, filesystem, mitre_discovery]

- key: Contact K8S API Server From Container
  hid: disc_05
  condition: >
    evt.type=connect and evt.dir=< and
    (fd.typechar=4 or fd.typechar=6) and
    container and
    not k8s_containers and
    k8s_api_server and
    not ignore_proc_args and
    not user_known_contact_k8s_api_server_activities and 
    shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_info=%container.info,image=%container.image.repository,image_tag=%container.image.tag,connection=%fd.name,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Contact K8S API Server From Container"
      zh: "容器内访问K8S-API-Server"
    desc:
      en: "Detect attempts to contact the K8S API Server from a container"
      zh: "检测容器内试图访问K8S API Server的行为"
    suggestion:
      en: "Please confirm whether this behavior is generated by the trusted application in the container. You can use the white list to let go of the connection request initiated by the trusted program, or you can use micro isolation to restrict the container."
      zh: "请确认该行为是否由容器内可信应用产生，可使用白名单放过可信程序发起的连接请求，否则可采用微隔离对该容器进行限制。"
    rule_type: Discovery
    priority: NOTICE
    urgency: true
    tags: [ATT&CK, network, k8s, container, mitre_discovery]

- key: Launch Suspicious Network Tool on Host
  hid: disc_06
  condition: >
    spawned_process and
    not container and
    consider_network_tools_on_host and
    network_tool_procs and
    not user_known_network_tool_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,parent_process=%proc.pname,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Launch Suspicious Network Tool on Host"
      zh: "在主机中启动可疑的网络工具"
    desc:
      en: "Detect network tools launched on the host"
      zh: "检测在主机中启动的可疑网络工具"
    suggestion:
      en: "Please confirm whether the hacker uses tools to collect information, or the operation and maintenance personnel can use offset defense to limit the execution of suspicious processes."
      zh: "请确认是否为黑客使用工具进行信息收集，或运维人员自身操作，可使用偏移防御限制可疑进程执行。"
    rule_type: Discovery
    priority: ERROR
    urgency: true
    tags: [ATT&CK, network, process, mitre_discovery, mitre_exfiltration]

- key: View process information in the container
  disable: true
  hid: disc_07
  condition: >
    open_read and container and fd.name startswith "/proc/" and fd.name contains "pid_max" and evt.arg.flags = O_RDONLY and shell_parent_procs and not k8s.pod.name contains "holmes" and not k8s.pod.name contains "calico" and not k8s.pod.name contains "node-exporter" and not k8s.pod.name contains "console" and not k8s.pod.name contains "51c1c6" and not k8s.pod.name contains "prometheus"
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container.info=%container.info,shell=%proc.name,parent=%proc.pname,terminal=%proc.tty,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "View process information in the container"
      zh: "容器内查看进程信息"
    desc:
      en: "Detect attempts to view process information in the container"
      zh: "检测容器内查看进程信息的行为"
    suggestion:
      en: "Please confirm whether information collection is carried out for hackers, or operation and maintenance personnel can use immune defense training applications to block new or modified executable files, and restrict users and recipients of commands."
      zh: "请确认是否为黑客进行信息收集，或运维人员自身操作，可使用免疫防御训练应用，阻拦新的或被修改的可执行文件，限制执行命令的用户和接收对象。"
    rule_type: Discovery
    priority: INFO
    urgency: true
    tags: [ATT&CK, container, shell, mitre_execution]

- key: View disk information in the container
  hid: disc_08
  condition: >
    open_read and container and (proc.cmdline contains "fdisk -l" or (fd.name startswith "/sys/dev/block/" and evt.arg.flags contains O_RDONLY)) and not tensorsec_namespace and shell_parent_procs
  output: >
    fd_name=%fd.name,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "View disk information in the container"
      zh: "容器内查看磁盘信息"
    desc:
      en: "Detect attempts to view disk information in the container"
      zh: "检测容器内查看磁盘信息的行为"
    suggestion:
      en: "Please confirm whether information collection is carried out for hackers, or operation and maintenance personnel can use immune defense training applications to block new or modified executable files, and restrict users and recipients of commands."
      zh: "请确认是否为黑客进行信息收集，或运维人员自身操作，可使用免疫防御训练应用，阻拦新的或被修改的可执行文件，限制执行命令的用户和接收对象。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: Scanning web directories in the container
  hid: disc_09
  condition: >
    open_read and container
    and (fd.directory contains "www" or fd.directory contains "apache" or fd.directory contains "tomcat" or fd.directory contains "web" or fd.directory contains "http")
    and (fd.name contains ".jsp" or fd.name contains ".php" or fd.name contains ".config" or fd.name contains ".bak" or fd.name contains ".old" or fd.name contains ".log")
    and not tensorsec_namespace
    and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Scanning web directories in the container"
      zh: "容器内扫描web目录"
    desc:
      en: "Detect attempts to scan web directories in the container"
      zh: "检测容器内扫描web目录的行为"
    suggestion:
      en: "Please confirm whether this behavior is a third-party trusted application scanning. If not, it may be a hacker tool behavior. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit the mounting of sensitive directories and files."
      zh: "请确认该行为是否为第三方可信应用扫描，如果不是则可能为黑客工具行为，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: Find files with suid privilege by non-root users
  hid: disc_10
  condition: >
    evt.type = write and user.uid != 0 and
    (proc.name = find and proc.cmdline contains "-perm" ) and (
    evt.arg.data = "/usr/bin/find." or
    evt.arg.data contains "nmap" or
    evt.arg.data contains "vim" or
    evt.arg.data contains "bash" or
    evt.arg.data contains "less" or
    evt.arg.data contains "more" or
    evt.arg.data contains "nano" or
    evt.arg.data contains "cp" or
    evt.arg.data contains "awk"
    )
    and shell_parent_procs
  output: >
    fd_name=%fd.name,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Find files with suid privilege by non-root users"
      zh: "非root用户查找具有suid权限的文件"
    desc:
      en: "Find files with suid privilege by non-root users"
      zh: "非root用户查找具有suid权限的文件"
    suggestion:
      en: "This behavior probably refers to the information collection operation before the hacker attempts to raise authority. The container may be invaded. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit the mounting of sensitive directories and files."
      zh: "该行为大概率为黑客尝试提权前的信息收集操作，容器可能遭到入侵，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: View login information in the container
  hid: disc_11
  condition: >
    open_read and container and (fd.name="/var/log/lastlog" or fd.name="/var/log/wtmp") and not proc.cmdline contains "bash" and not tensorsec_namespace and not k8s.pod.name contains "calico" and shell_parent_procs
  output: >
    fd_name=%fd.name,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "View login information in the container"
      zh: "容器内查看登录信息"
    desc:
      en: "View login information in the container"
      zh: "容器内查看登录信息"
    suggestion:
      en: "It may be an act of hacker information collection. Please confirm the execution object. You can use the immune defense training application to limit the user permissions of sensitive files and commands, and prohibit mounting sensitive directories and files."
      zh: "可能为黑客信息收集行为，请确认执行对象，可使用免疫防御训练应用，限制敏感文件和命令的用户权限，禁止挂载敏感目录和文件。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: View history command file in container
  hid: disc_12
  condition: >
    open_read and (fd.name contains ".bash_history" or fd.name contains ".zsh_history") and
    container and
    shell_parent_procs and not shell_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "View history command file in container"
      zh: "容器内查看历史命令文件"
    desc:
      en: "View history command file in container"
      zh: "容器内查看历史命令文件"
    suggestion:
      en: "Please confirm the reason for viewing the history file and make sure it is not a malicious activity, otherwise it may be a hacker information gathering behavior, please confirm the execution object."
      zh: "请确认查看历史文件的原因，确保其不是恶意活动，否则可能为黑客信息收集行为，请确认执行对象。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]

- key: Get ApiServer_token through kubectl
  disable: true
  hid: disc_13
  condition: >
    evt.type = execve and (proc.cmdline contains "kubectl config view" or proc.cmdline contains "kubectl describe secrets") and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Get ApiServer_token through kubectl"
      zh: "通过kubectl获取ApiServer_token"
    desc:
      en: "Get ApiServer_token through kubectl"
      zh: "通过kubectl获取ApiServer_token"
    suggestion:
      en: "Please confirm whether this behavior is initiated by a trusted person or program, or the container may be invaded. You can use the immune defense training application to limit the user permissions of sensitive files and commands."
      zh: "请确认该行为发起对象是否为可信人员或程序，否则容器可能遭到入侵，可使用免疫防御训练应用，限制敏感文件和命令的用户权限。"
    rule_type: Discovery
    priority: WARNING
    urgency: true
    tags: [ATT&CK]