##attck_rule_type=Lateral_Movement
- key: Launch Sensitive Mount Container
  disable: true
  hid: move_01
  condition: >
    container_started and container
    and sensitive_mount
    and not falco_sensitive_mount_containers
    and not user_sensitive_mount_containers
    and not tensorsec_namespace
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container.info=%container.info,image=%container.image.repository,image_tag=%container.image.tag,mounts=%container.mounts,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Launch Sensitive Mount Container"
      zh: "启动挂载敏感路径容器"
    desc:
      en: "Detect the initial process started by a container that has a mount from a sensitive host directory (i.e. /proc). Exceptions are made for known trusted images."
      zh: "检测到容器启动时挂载了敏感主机目录（如/proc）的进程，已知信任镜像除外。"
    suggestion:
      en: "Unsafe mount startup is vulnerable to hackers' attacks. Please confirm whether the mount is necessary, and if not, please change the mount path."
      zh: "不安全挂载启动，容易遭受黑客提权攻击，请确认挂载是否为必须，非必要请更换挂载路径。"
    rule_type: Lateral_Movement
    priority: INFO
    urgency: false
    tags: [ATT&CK, container, cis, mitre_lateral_movement]

- key: Change thread namespace
  hid: move_02
  condition: >
    spawned_process and container and not user_known_k8s_client_container_parens and proc.name in (k8s_client_binaries) and not tensorsec_namespace and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container.info=%container.info,parent=%proc.pname,image=%container.image.repository,image_tag=%container.image.tag,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Change thread namespace"
      zh: "更改线程命名空间"
    desc:
      en: "an attempt to change a program/thread's namespace (commonly done as a part of creating a container) by calling setns."
      zh: "通过调用setns尝试更改程序/线程的命名空间"
    suggestion:
      en: "Immune defense is used to prevent sensitive directories and files from being mounted, prevent sensitive containers from being started, and update the software version in the containers."
      zh: "采用免疫防御禁止挂载敏感目录和文件，禁止敏感容器启动，更新容器内软件版本。"
    rule_type: Lateral_Movement
    priority: NOTICE
    urgency: false
    tags: [ATT&CK, process, mitre_privilege_escalation, mitre_lateral_movement]

- key: The k8s client is executed in a container
  hid: move_03
  condition: >
    spawned_process and container and not user_known_k8s_client_container_parens and proc.name in (k8s_client_binaries) and not tensorsec_namespace and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container.info=%container.info,parent=%proc.pname,image=%container.image.repository,image_tag=%container.image.tag,container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "The k8s client is executed in a container"
      zh: "容器中使用k8s相关二进制程序"
    desc:
      en: "Detect a k8s client tool executed inside a container"
      zh: "检测到在容器中执行k8s客户端工具"
    suggestion:
      en: "Please confirm whether the program is introduced as expected, or use offset defense to limit the program's operation, and check whether the container is invaded by hackers."
      zh: "请确认该程序引入是否符合预期，否则则采用偏移防御限制该程序运行，并排查容器是否遭到黑客入侵。"
    rule_type: Lateral_Movement
    priority: WARNING
    urgency: true
    tags: [ATT&CK, container, mitre_execution]

- key: Launch Disallowed Container
  hid: move_04
  condition: >
    container_started and container and not allowed_containers
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container.info=%container.info,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Launch Disallowed Container"
      zh: "启动黑名单中的容器"
    desc:
      en: "Detect the initial process started by a container that is not in a list of allowed containers."
      zh: "检测到在黑名单列表中的容器启动"
    suggestion:
      en: "Confirm whether the startup of the container is as expected, and check the reason for startup."
      zh: "确认该容器启动是否符合预期，排查启动原因。"
    rule_type: Lateral_Movement
    priority: WARNING
    urgency: true
    tags: [ATT&CK, container, mitre_lateral_movement]