##attck_rule_type=Persistence
- key: Schedule Cron Jobs
  disable: true
  hid: pers_01
  condition: >
    ((open_write and cron_dir_action) or
     (spawned_process and proc.name = "crontab")) and
    not consider_all_cron_jobs and container and
    not user_known_cron_jobs and
    shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Schedule Cron Jobs"
      zh: "运行计划任务"
    desc:
      en: "Detect cron jobs scheduled"
      zh: "检测到运行计划任务"
    suggestion:
      en: "Please judge through the process tree whether the command belongs to the normal behavior of known processes, whether it is executed by malware, confirm whether the planned task is operated by operation and maintenance personnel, if it is a necessary operation can use whitelist to let go of the alarm, otherwise it may be a hacker backdoor."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该计划任务是否为运维人员操作，如果是必要操作可采用白名单放过告警，否则则可能为黑客后门。"
    rule_type: Persistence
    priority: WARNING
    urgency: false
    tags: [ATT&CK, file, mitre_persistence, L2]

- key: Run user mgmt binaries
  hid: pers_02
  condition: >
    spawned_process and proc.name in (user_mgmt_binaries) and shell_parent_procs and
    not proc.name in (su, sudo, lastlog, nologin, unix_chkpwd) and
    not proc.pname in (cron_binaries, systemd, systemd.postins, udev.postinst, run-parts) and
    not proc.cmdline startswith "passwd -S" and
    not proc.cmdline startswith "useradd -D" and
    not proc.cmdline startswith "systemd --version" and
    not run_by_qualys and
    not run_by_sumologic_securefiles and
    not run_by_yum and
    not run_by_ms_oms and
    not run_by_google_accounts_daemon and
    not chage_list and
    not user_known_user_management_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,parent=%proc.pname,gparent=%proc.aname[2],ggparent=%proc.aname[3],gggparent=%proc.aname[4],container_id=%container.id,container_name=%container.name
  info:
    name:
      en: "Run user management binaries"
      zh: "运行管理用户、密码或权限的命令"
    desc:
      en: "Activity by any programs that can manage users, passwords, or permissions. sudo and su are excluded. Activity in containers is also excluded--some containers create custom users on top of a base linux distribution at startup. Some innocuous commandlines that don't actually change anything are excluded."
      zh: "任何可以管理用户、密码或权限的程序的活动。sudo和su除外。一些容器在启动时在基本的Linux发行版之上创建自定义用户除外。一些不会实际更改任何内容的无害命令行也被排除在外。"
    suggestion:
      en: "Please use the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and confirm whether it is an administrator or trusted application operation, otherwise it may be a hacker operation, please check the system security."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认是否为管理员或可信应用操作，否则则可能是黑客操作，请排查系统安全。"
    rule_type: Persistence
    priority: WARNING
    urgency: false
    tags: [ATT&CK, host, users, mitre_persistence, L2]

- key: Package management process launched in container
  hid: pers_03
  condition: >
    spawned_process
    and container
    and user.name != "_apt"
    and package_mgmt_procs
    and shell_parent_procs
    and not package_mgmt_ancestor_procs
    and not user_known_package_manager_in_container
    and not (tensorsec_namespace and k8s.pod.name contains "-frontend")
  output: >
    Pproc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container_id=%container.id,container_name=%container.name,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Package management process launched in container"
      zh: "容器内启动包安装管理流程"
    desc:
      en: "Package management process ran inside container"
      zh: "容器内启动包安装管理流程"
    suggestion:
      en: "Please go through the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and whether package management normally does not occur in the container to confirm that the process is as expected."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，通常容器内不会出现包管理情况，确认该流程是否符合预期。"
    rule_type: Persistence
    priority: NOTICE
    urgency: false
    tags: [ATT&CK, process, mitre_persistence, L3]

- key: Update package repository
  hid: pers_04
  condition: >
    ((open_write and access_repositories) or (modify and modify_repositories))
    and shell_parent_procs
    and not package_mgmt_procs
    and not package_mgmt_ancestor_procs
    and not exe_running_docker_save
    and not user_known_update_package_registry
    and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Update package repository"
      zh: "更新软件源"
    desc:
      en: "Update package repository"
      zh: "更新软件源"
    suggestion:
      en: "Please go through the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and whether the update operation is as expected and triggered by operation and maintenance personnel."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该更新操作是否符合预期，是否为运维人员触发。"
    rule_type: Persistence
    priority: WARNING
    urgency: false
    tags: [ATT&CK, filesystem, mitre_persistence, L3]

# - key: Write below rpm database
#   hid: pers_05
#   condition: >
#     fd.name startswith /var/lib/rpm and open_write
#     and shell_parent_procs
#     and not rpm_procs
#     and not ansible_running_python
#     and not python_running_chef
#     and not exe_running_docker_save
#     and not amazon_linux_running_python_yum
#     and not user_known_write_rpm_database_activities
#   output: >
#     proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,file=%fd.name,parent=%proc.pname,container_id=%container.id,container_name=%container.name,image=%container.image.repository
#   info:
#     name:
#       en: "Write below rpm database"
#       zh: "写入rpm数据库"
#     desc:
#       en: "an attempt to write to the rpm database by any non-rpm related program"
#       zh: "任何非rpm相关程序尝试写入rpm数据库"
#     suggestion:
#       en: "Please go through the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and whether the operation is as expected."
#       zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该操作是否符合预期。"
#     rule_type: Persistence
#     priority: WARNING
#     urgency: false
#     tags: [ATT&CK, filesystem, software_mgmt, mitre_persistence]

- key: Remove Bulk Data from Disk
  hid: pers_06
  condition: >
    spawned_process and clear_data_procs and not user_known_remove_data_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,container_id=%container.id,container_name=%container.name,image=%container.image.repository,image_tag=%container.image.tag
  info:
    name:
      en: "Remove bulk data from disk"
      zh: "发现大量数据从硬盘删除"
    desc:
      en: "Bulk data has been removed from disk"
      zh: "大量数据从硬盘删除"
    suggestion:
      en: "Please go through the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and whether the data deletion operation is as expected."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该数据删除操作是否符合预期。"
    rule_type: Persistence
    priority: WARNING
    urgency: true
    tags: [ATT&CK, process, mitre_persistence, L4]

- key: Modify shell configuration file
  hid: pers_07
  condition: >
    open_write and shell_parent_procs and
    (fd.filename in (shell_config_filenames) or
     fd.name in (shell_config_files) or
     fd.directory in (shell_config_directories))
    and not proc.name in (shell_binaries)
    and not exe_running_docker_save
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Modify shell configuration file"
      zh: "修改shell配置文件"
    desc:
      en: "Modify shell configuration file"
      zh: "修改shell配置文件"
    suggestion:
      en: "Please go through the process tree to determine whether the command is a normal behavior of a known process, whether it is executed by malware, and whether the modification is operated by the operation and maintenance personnel."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该修改是否为运维人员操作。"
    rule_type: Persistence
    priority: WARNING
    urgency: false
    tags: [ATT&CK, file, mitre_persistence, L4]

- key: Create files below dev
  hid: pers_08
  condition: >
    fd.directory = /dev and
    (evt.type = creat or (evt.type in (open,openat,openat2) and evt.arg.flags contains O_CREAT))
    and not proc.name in (dev_creation_binaries)
    and not fd.name in (allowed_dev_files)
    and not fd.name startswith /dev/tty
    and not user_known_create_files_below_dev_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Create files below dev"
      zh: "在/dev目录下创建文件"
    desc:
      en: "Create files below dev"
      zh: "在/dev目录下创建文件"
    suggestion:
      en: "Please judge through the process tree whether the command belongs to the normal behavior of the known process, whether it is executed by malware, and confirm whether the modification is operated by the operation and maintenance personnel, otherwise it may have the risk of intrusion, and it is recommended to exclude it."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该修改是否为运维人员操作，否则可能会有入侵风险，建议排查。"
    rule_type: Persistence
    priority: INFO
    urgency: false
    tags: [ATT&CK, filesystem, mitre_persistence, L3]

# - key: Create hidden files or directories
#   hid: pers_09
#   condition: >
#     ((modify and evt.arg.newpath contains "/.") or
#      (mkdir and evt.arg.path contains "/.") or
#      (open_write and evt.arg.flags contains "O_CREAT" and fd.name contains "/." and not fd.name pmatch (exclude_hidden_directories))) and
#     consider_hidden_file_creation and
#     not user_known_create_hidden_file_activities
#     and not exe_running_docker_save
#   output: >
#     proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,container_id=%container.id,container_name=%container.name,image=%container.image.repository
#   info:
#     name:
#       en: "Create hidden files or directories"
#       zh: "创建隐藏文件或目录"
#     desc:
#       en: "Create hidden files or directories"
#       zh: "创建隐藏文件或目录"
#     suggestion:
#       en: "Please use the process tree to determine whether the command belongs to the normal behavior of known processes, whether it is executed by malware, confirm whether the modification is operated by operation and maintenance personnel, and check whether the file content is safe."
#       zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该修改是否为运维人员操作，排查文件内容是否安全。"
#     rule_type: Persistence
#     priority: NOTICE
#     urgency: false
#     tags: [ATT&CK, file, mitre_persistence]

- key: Write below monitored dir
  hid: pers_11
  condition: >
    evt.dir = < and open_write and monitored_dir
    and shell_family_procs
    and not package_mgmt_procs
    and not coreos_write_ssh_dir
    and not exe_running_docker_save
    and not python_running_get_pip
    and not python_running_ms_oms
    and not google_accounts_daemon_writing_ssh
    and not cloud_init_writing_ssh
    and not user_known_write_monitored_dir_conditions
    and not tensorsec_namespace
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,parent=%proc.pname,gparent=%proc.aname[2],container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Write below monitored dir"
      zh: "尝试修改受监控的目录下的文件"
    desc:
      en: "Write below monitored dir"
      zh: "尝试修改受监控的目录下的文件"
    suggestion:
      en: "Please use the process tree to determine whether the command belongs to the normal behavior of known processes, whether it is executed by malware, confirm whether the modification is operated by operation and maintenance personnel, and check whether the file content is safe."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该修改是否为运维人员操作，排查文件内容是否安全。"
    rule_type: Persistence
    priority: ERROR
    urgency: true
    tags: [ATT&CK, filesystem, mitre_persistence, L1]

- key: Write below binary dir
  hid: pers_12
  condition: >
    bin_dir and evt.dir = < and open_write
    and shell_family_procs
    and not package_mgmt_procs
    and not exe_running_docker_save
    and not python_running_get_pip
    and not python_running_ms_oms
    and not user_known_write_below_binary_dir_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,file=%fd.name,parent=%proc.pname,gparent=%proc.aname[2],container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Write below binary dir"
      zh: "尝试修改二进制目录下面的文件"
    desc:
      en: "Write below binary dir"
      zh: "尝试修改二进制目录下面的文件"
    suggestion:
      en: "Please use the process tree to determine whether the command belongs to the normal behavior of known processes, whether it is executed by malware, confirm whether the modification is operated by operation and maintenance personnel, and check whether the file content is safe."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，确认该修改是否为运维人员操作，排查文件内容是否安全。"
    rule_type: Persistence
    priority: WARNING
    urgency: false
    tags: [ATT&CK, filesystem, mitre_persistence, L3]

- key: Modify binary dirs
  hid: pers_13
  condition: >
    bin_dir_rename and modify and not package_mgmt_procs and not exe_running_docker_save and not user_known_modify_bin_dir_activities
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,operation=%evt.type,file=%fd.name,evt.args=%evt.args,container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Modify binary dirs"
      zh: "移动或删除二进制目录"
    desc:
      en: "an attempt to modify any file below a set of binary directories"
      zh: "移动或删除二进制目录"
    suggestion:
      en: "Please use the process tree to determine whether the command belongs to the normal behavior of known processes, whether it is executed by malware, the behavior may be a hacker backdoor residency behavior, please confirm the modified file function, you can use offset defense to block new or modified executable files."
      zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，该行为可能为黑客后门驻留行为，请确认被修改文件功能，可使用偏移防御阻拦新的或被修改的可执行文件。"
    rule_type: Persistence
    priority: ERROR
    urgency: false
    tags: [ATT&CK, filesystem, mitre_persistence, L3]

# - key: Mkdir binary dirs
#   hid: pers_14
#   condition: >
#     mkdir
#     and bin_dir_mkdir
#     and not package_mgmt_procs
#     and not user_known_mkdir_bin_dir_activities
#     and not exe_running_docker_save
#   output: >
#     proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,directory=%evt.arg.path,container_id=%container.id,container_name=%container.name,image=%container.image.repository
#   info:
#     name:
#       en: "Mkdir binary dirs"
#       zh: "在二进制文件路径下创建目录"
#     desc:
#       en: "an attempt to create a directory below a set of binary directories"
#       zh: "在二进制文件路径下创建目录"
#     suggestion:
#       en: "Please use the process tree to determine whether the command belongs to the normal behavior of known processes, whether it is executed by malware, the behavior may be a hacker backdoor residency behavior, please confirm the modified file function, you can use offset defense to block new or modified executable files."
#       zh: "请通过进程树判断该命令是否属于已知进程的正常行为，是否由恶意软件执行，该行为可能为黑客后门驻留行为，请确认被修改文件功能，可使用偏移防御阻拦新的或被修改的可执行文件。"
#     rule_type: Persistence
#     priority: ERROR
#     urgency: false
#     tags: [ATT&CK, filesystem, mitre_persistence]

- key: Write below etc
  disable: true
  hid: pers_15
  condition: >
    write_etc_common and not (tensorsec_namespace and k8s.pod.name contains "holmes") and shell_parent_procs
  output: >
    proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name,user_loginuid=%user.loginuid,parent=%proc.pname,file=%fd.name,program=%proc.name,gparent=%proc.aname[2],ggparent=%proc.aname[3],gggparent=%proc.aname[4],container_id=%container.id,container_name=%container.name,image=%container.image.repository
  info:
    name:
      en: "Write below etc"
      zh: "尝试修改/etc路径下的文件"
    desc:
      en: "an attempt to write to any file below /etc"
      zh: "尝试修改/etc路径下的文件"
    suggestion:
      en: "Usually, few programs can operate on the contents of the /etc directory, which may be a hacker's behavior. Please confirm whether the modified files are at risk."
      zh: "通常很少有程序会操作/etc目录下内容，可能是黑客行为，请确认被修改文件是否存在风险。"
    rule_type: Persistence
    priority: WARNING
    urgency: true
    tags: [ATT&CK, filesystem, mitre_persistence, L2]
