global:
  image: 
    registry: ""
    repository: ""


image:
  registry: localhost:32000
  repository: tensorsecurity
  name: tensorsec-webhook
  tag: latest
  pullPolicy: Always
  pullSecret: harbor-admin-secret

certgen:
  image:
    registry: localhost:32000
    repository: tensorsecurity
    name: kube-webhook-certgen
    tag: v1.1.1

nameOverride: "webhook"
fullnameOverride: "tensorsec-webhook"

args:
  consoleUrl: "http://tensorsec-console:8889"
  clusterManagerUrl: "http://tensorsec-cluster-manager:9443"

service:
  type: ClusterIP
  port: 443
  targetPort: 9443
  ## Specify the nodePort value for the NodePort service types.
  #nodePort:

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 100Mi

validators: ImageTrustValidator
mutators: "DriftPreventionMutator,MicroSegMutator,ImageTrustMutator"

microseg:
  appCfg:
    pgMaster:
      host: "tensorsec-postgresql"
      user: "postgres"
      password: "password"
      dbName: "postgres"
      port: "5432"
    runMode: "dev"

presets:
  volumes:
    clientName: "client-cert"
    clientSecretName: "eventcenter-tls-client-cert-secret"
    clientMountPath: "/auth/client"
    caName: "ca-cert"
    caSecretName: "eventcenter-tls-ca-secret"
    caMountPath: "/auth/ca"
