producers:
    syscalls:
      # - syscallDup2:
      #   name: dup2
      #   filters:
      #     - newfdFilter:
      #       id: f1
      #       field: newfd
      #       operation: inArray
      #       values:
      #       - v: 0
      #       - v: 1
      #       - v: 2
      - syscallSocket:
        name: socket
        filters:
          - protoFilter:
            id: f1
            field: protocol
            operation: equalTo
            values:
            - v: 132 #IPPROTO_SCTP
        #   - familyFilter:
        #     id: f2
        #     field: family
        #     operation: inArray
        #     values:
        #     - v: 17 #AF_PACKET
        #     - v: 2 #AF_INET             
        # logic: f1||f2
      # - syscallExecve:
      #   name: execve
      #   filters:
      #     - filenameFilter:
      #       id: f1
      #       field: filename
      #       operation: equalTo
      #       values:
      #         - v: /usr/bin/sudo
      #     - argv1Filter:
      #       id: f2
      #       field: argv1
      #       operation: inArray
      #       values:
      #         - v: -u#-1
      #         - v: -u#4294967295
      #     - filenameRSNCFilter:
      #       id: f3
      #       field: filename
      #       operation: inArray
      #       values:
      #         - v: /bin/nc
      #         - v: /usr/bin/ncat
      #     - argv1RSNCFilter:
      #       id: f4
      #       field: argv1
      #       operation: inArray
      #       values:
      #         - v: -e
      #         - v: -c
      #         - v: --sh-exec
      #         - v: --exec
      #         - v: --lua-exec
      #     - argv2RSNCFilter:
      #       id: f5
      #       field: argv2
      #       operation: inArray
      #       values:
      #         - v: -e
      #         - v: -c
      #         - v: --sh-exec
      #         - v: --exec
      #         - v: --lua-exec
      #     - argv3RSNCFilter:
      #       id: f6
      #       field: argv3
      #       operation: inArray
      #       values:
      #         - v: -e
      #         - v: -c
      #         - v: --sh-exec
      #         - v: --exec
      #         - v: --lua-exec
      #   logic: (f1&&f2)||(f3&&(f4||f5||f6))    
      # - syscallOpen:
      #   name: open
      #   filters:
      #     - filenameFilter:
      #       id: f1
      #       field: filename
      #       operation: startsWithArray
      #       values: 
      #         - v: /proc/self/exe
      #         - v: /proc/self/fd
      #     - modeFilter:
      #       id: f2
      #       field: mode
      #       operation: andIs
      #       values:
      #       - v: 1
      #       - v: 1
      #     - modeFilter:
      #       id: f3
      #       field: mode
      #       operation: andIs
      #       values:
      #       - v: 2
      #       - v: 2
      #   logic: f1&&(f2||f3)
      # - syscallOpenat:
      #   name: openat
      #   filters:
      #     - filenameFilter:
      #       id: f1
      #       field: filename
      #       operation: startsWithArray
      #       values: 
      #         - v: /proc/self/exe
      #         - v: /proc/self/fd
      #     - modeFilter:
      #       id: f2
      #       field: mode
      #       operation: andIs
      #       values:
      #       - v: 1
      #       - v: 1
      #     - modeFilter:
      #       id: f3
      #       field: mode
      #       operation: andIs
      #       values:
      #       - v: 2
      #       - v: 2
      #   logic: f1&&(f2||f3)
consumers:
  - File
