name: Reverse shell (Netcat)

type: any

index: filebeat-*

terms_window_size:
  days: 90

filter:
  - query:
      query_string:
          query: 'execve__filename:"/bin/nc" OR execve__filename:"/usr/bin/ncat"'
    
alert:
  - command
command: ["echo", "Reverse shell (Netcat)"]
          
alert_text: "Reverse Shell (Netcat)"
