##attck_rule_type=Execution
- rule: DB program spawned process
  hid: exec_01
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Please confirm whether it is the normal behavior of the process, otherwise it is recommended to check whether the database is under injection attack, there is the phenomenon of executing system commands through the database, you can use immune defense to block the further behavior of hackers."
    zh:
      key: "处置建议"
      value: "请确认是否属于进程的正常行为，否则建议排查数据库是否遭到注入攻击，存在通过数据库执行系统命令现象，可使用免疫防御阻断黑客进一步行为。"
  desc: >
    a database-server related program spawned a new process other than itself.
    This shouldn\'t occur and is a follow on from some SQL injection attacks.
  condition: >
    proc.pname in (db_server_binaries)
    and spawned_process
    and shell_parent_procs
    and not proc.name in (db_server_binaries)
    and not postgres_running_wal_e
    and not user_known_db_spawned_processes
    and not tensorsec_namespace
  output: >
    Database-related program spawned process other than itself (zh_msg=数据库服务生成非自身进程,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid parent=%proc.pname
    container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: ERROR
  tags: [ATT&CK, process, database, mitre_execution]

- rule: Run shell untrusted
  hid: exec_02
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Please confirm whether it is a normal behavior of the process, whether malicious commands are executed, and confirm whether there is a security vulnerability in that binary file. You can use the immune defense training application to block new or modified executable files and restrict the users and recipients of the executed commands."
    zh:
      key: "处置建议"
      value: "请确认是否属于进程的正常行为，是否执行了恶意命令，确认该二进制文件是否存在安全漏洞，可使用免疫防御训练应用，阻拦新的或被修改的可执行文件，限制执行命令的用户和接收对象。"
  desc: an attempt to spawn a shell below a non-shell application. Specific applications are monitored.
  condition: >
    spawned_process
    and shell_procs
    and proc.pname exists
    and protected_shell_spawner
    and not proc.pname in (shell_binaries, gitlab_binaries, cron_binaries, user_known_shell_spawn_binaries,
                           needrestart_binaries,
                           mesos_shell_binaries,
                           erl_child_setup, exechealthz,
                           PM2, PassengerWatchd, c_rehash, svlogd, logrotate, hhvm, serf,
                           lb-controller, nvidia-installe, runsv, statsite, erlexec, calico-node,
                           "puma reactor")
    and not proc.cmdline in (known_shell_spawn_cmdlines)
    and not proc.aname in (unicorn_launche)
    and not consul_running_net_scripts
    and not consul_running_alert_checks
    and not nginx_starting_nginx
    and not nginx_running_aws_s3_cp
    and not run_by_package_mgmt_binaries
    and not serf_script
    and not check_process_status
    and not run_by_foreman
    and not python_mesos_marathon_scripting
    and not splunk_running_forwarder
    and not postgres_running_wal_e
    and not redis_running_prepost_scripts
    and not rabbitmq_running_scripts
    and not rabbitmqctl_running_scripts
    and not run_by_appdynamics
    and not user_shell_container_exclusions
  output: >
    Shell spawned by untrusted binary (zh_msg=未受信任的二进制文件产生shell ,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type, webshell_name=%fd.name
    original_info=user=%user.name user_loginuid=%user.loginuid shell=%proc.name parent=%proc.pname
    gparent=%proc.aname[2] ggparent=%proc.aname[3]
    aname[4]=%proc.aname[4] aname[5]=%proc.aname[5] aname[6]=%proc.aname[6] aname[7]=%proc.aname[7] container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: WARNING
  tags: [ATT&CK, shell, mitre_execution]

- rule: Terminal shell in container
  hid: exec_03
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Check the alert details, troubleshoot the reason for shell generation, confirm whether the user who entered the container and the time are as expected, and pay attention to whether the subsequent execution of malicious commands."
    zh:
      key: "处置建议"
      value: "查看告警详情，排查shell产生原因，确认进入容器的用户和时间是否符合预期，关注后续是否执行恶意命令。"
  desc: A shell was used as the entrypoint/exec point into a container with an attached terminal.
  condition: >
    spawned_process and container
    and shell_procs and proc.tty != 0
    and container_entrypoint
    and not user_expected_terminal_shell_in_container_conditions
    and not tensorsec_namespace
  output: >
    A shell was spawned in a container with an attached terminal (zh_msg=通过entrypoint/exec的shell进入容器,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid %container.info
    shell=%proc.name parent=%proc.pname terminal=%proc.tty container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: WARNING
  tags: [ATT&CK, container, shell, mitre_execution]

- rule: Netcat Remote Code Execution in Container
  hid: exec_04
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "Confirm whether the container has been invaded. If it is not for special reasons, immediately remove the hacker tool, isolate the container, investigate other attacks, and confirm the cluster security"
    zh:
      key: "处置建议"
      value: "确认容器是否遭到入侵，如果非特殊原因则立即清除该黑客工具，并隔离该容器，同时排查其他攻击行为，确认集群安全。"
  desc: Netcat Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)
  condition: >
    spawned_process and container and
    (((proc.name = "nc" or proc.name = "nc.openbsd") and (proc.args contains "-e" or proc.args contains "-c")) or
    (proc.name = "ncat" and (proc.args contains "--sh-exec" or proc.args contains "--exec" or proc.args contains "-e " or proc.args contains "-c " or proc.args contains "--lua-exec"))) and
    not (k8s.pod.name contains "-kafka-zookeeper-" or tensorsec_namespace or ignore_proc_args)
  output: >
     Netcat runs inside container that allows remote code execution (zh_msg=容器里通过黑客工具netcat执行远程命令,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,original_info=user=%user.name user_loginuid=%user.loginuid,container_id=%container.id,container_name=%container.name,image=%container.image.repository:%container.image.tag)
  priority: ALERT
  tags: [ATT&CK, network, process, mitre_execution]

- rule: Reverse shell through telnet
  hid: exec_05
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "If the container is intruded, we need to isolate the container, get the remote ip address of the attacker, and check other attacks to confirm the security of the cluster."
    zh:
      key: "处置建议"
      value: "容器遭到入侵，需隔离该容器，获取攻击者远程ip地址，同时排查其他攻击行为，确认集群安全。"
  desc: Telnet Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)
  condition: >
    evt.type=recvfrom and proc.name contains "telnet" and container and not ignore_proc_args and remote_server_subnet and shell_parent_procs
  output: >
    Telnet runs inside container that allows remote code execution (zh_msg=容器内通过telnet反弹shell),rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_name=%proc.name,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid
    container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag
    connection=%fd.name,client_ip=%fd.cip,client_port=%fd.cport,server_ip=%fd.sip,server_port=%fd.sport)
  priority: ALERT
  tags: [ATT&CK, network, process, mitre_execution]

- rule: Reverse shell through ruby
  hid: exec_06
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "If the container is intruded, we need to isolate the container, get the remote ip address of the attacker, and check other attacks to confirm the security of the cluster."
    zh:
      key: "处置建议"
      value: "容器遭到入侵，需隔离该容器，获取攻击者远程ip地址，同时排查其他攻击行为，确认集群安全。"
  desc: Ruby Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)
  condition: >
    evt.type=socket and evt.res!=ENOENT and (proc.pname contains "ruby" or proc.name contains "ruby") and proc.cmdline contains "TCPSocket" and container and shell_parent_procs
  output: >
    Ruby runs inside container that allows remote code execution (zh_msg=容器内通过ruby反弹shell),rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid
    container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag
    connection=%fd.name,client_ip=%fd.cip,client_port=%fd.cport,server_ip=%fd.sip,server_port=%fd.sport)
  priority: ALERT
  tags: [ATT&CK, network, process, mitre_execution]

- rule: Reverse shell through awk
  hid: exec_07
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "If the container is intruded, we need to isolate the container, get the remote ip address of the attacker, and check other attacks to confirm the security of the cluster."
    zh:
      key: "处置建议"
      value: "容器遭到入侵，需隔离该容器，获取攻击者远程ip地址，同时排查其他攻击行为，确认集群安全。"
  desc: awk Program runs inside container that allows remote code execution(Risk of Reverse Shell exploit)
  condition: >
    evt.type=connect and not evt.res contains "ECONNREFUSED" and evt.arg.res!=0 and container and not ignore_proc_args and proc.name contains "awk" and proc.cmdline contains "/inet/tcp/" and shell_parent_procs
  output: >
    awk runs inside container that allows remote code execution (zh_msg=容器内通过awk反弹shell),rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,evt.args=%evt.args
    original_info=user=%user.name user_loginuid=%user.loginuid
    container_id=%container.id container_name=%container.name image=%container.image.repository:%container.image.tag
    connection=%fd.name,client_ip=%fd.cip,client_port=%fd.cport,server_ip=%fd.sip,server_port=%fd.sport)
  priority: ALERT
  tags: [ATT&CK, network, process, mitre_execution]

- rule: Reverse shell through socket and dup
  hid: exec_08
  hthreats: 1
  suggestion:
    en:
      key: "Suggestions"
      value: "If the container is intruded, we need to isolate the container, get the remote ip address of the attacker, and check other attacks to confirm the security of the cluster."
    zh:
      key: "处置建议"
      value: "容器遭到入侵，需隔离该容器，获取攻击者远程ip地址，同时排查其他攻击行为，确认集群安全。"
  desc: Reverse shell through socket and dup
  condition: >
    evt.type in (dup, dup2) and
    fd.num in (0, 1, 2) and fd.type in ("ipv4", "ipv6", "pipe") and fd.name contains "->" and
    container and shell_family_procs and
    not k8s.pod.name contains "98166d" and not k8s.pod.name contains "42cca6"
  output: >
    Reverse shell through socket and dup (zh_msg=容器内通过socket和dup反弹shell,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name %container.info process=%proc.name parent=%proc.pname terminal=%proc.tty container_id=%container.id container_name=%container.name image=%container.image.repository fd_name=%fd.name fd.num=%fd.num fd.type=%fd.type connection=%fd.name,client_ip=%fd.cip,client_port=%fd.cport,server_ip=%fd.sip,server_port=%fd.sport)
  priority: ALERT
  tags: [ATT&CK, container, shell, mitre_execution]

- rule: Running k8s malicious tools in the container
  hid: exec_09
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Please confirm whether the container has been invaded. You can use the immune defense training application to block new or modified executables, and limit the users and recipients who execute commands."
    zh:
      key: "处置建议"
      value: "请确认容器是否遭到入侵，可使用免疫防御训练应用，阻拦新的或被修改的可执行文件，限制执行命令的用户和接收对象。"
  desc: Running malicious tools in the container
  condition: >
    evt.type = execve and container and
    shell_parent_procs and 
    (not tensorsec_namespace) and
    (proc.cmdline contains "cdk eva" or
     proc.cmdline contains "k0otkit" or
     proc.cmdline contains "kubesploit" or
     proc.cmdline contains "red-kube" or
     proc.cmdline contains "kubestriker" or
     proc.cmdline contains "kube-hunter" or
     proc.cmdline contains "kubiscan"
      )
  output: >
    Running malicious tools in the container (zh_msg=容器内运行k8s恶意工具,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid %container.info
    shell=%proc.name parent=%proc.pname terminal=%proc.tty container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: WARNING
  tags: [ATT&CK, container, shell, mitre_execution, strict]

- rule: Connecting to a remote server through redis client in container
  hid: exec_10
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Please use the process tree to determine whether the command is executed by malware, confirm whether the redis connection is a normal business connection, and investigate the reason for the connection."
    zh:
      key: "处置建议"
      value: 请通过进程树判断该命令是否由恶意软件执行，确认该redis连接是否为业务正常连接，排查出现该连接原因。"
  desc: Connecting to a remote server through redis client in container
  condition: >
    evt.type=openat and container and evt.arg.name contains ".rediscli_history" and proc.cmdline  contains " -h " and not proc.cmdline contains "localhost" and not proc.cmdline contains "127.0. 0.1" and not k8s.pod.name contains "51c1c6"
  output: >
    Connecting to a remote server through redis client in container (zh_msg=容器内通过redis客户端连接远程服务器,rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,user=%user.name user_loginuid=%user.loginuid parent=%proc.pname terminal=%proc.tty container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: WARNING
  tags: [ATT&CK, container, shell, mitre_execution, strict]

- rule: Docker build vulnerability(CVE-2019-13139)
  hid: exec_11
  hthreats: 0
  suggestion:
    en:
      key: "Suggestions"
      value: "Ensure your Docker engine is up to date and if possible avoid using remote context’s for builds, especially if supplied by third-parties."
    zh:
      key: "处置建议"
      value: "确保Docker版本是最新的,尽可能避免使用远程环境进行构建，特别是由第三方提供的。"
  desc: Docker build vulnerability
  condition: >
    evt.type=execve and proc.name=docker and
    (proc.cmdline contains "build" and proc.cmdline contains "git@" and proc.cmdline contains "--upload-pack") and
    shell_parent_procs
  output: >
    Docker build vulnerability (zh_msg=Docker构建漏洞导致代码执行(CVE-2019-13139),rule_type=Execution,proc_pid=%proc.pid,proc_ppid=%proc.ppid,proc_cmdline=%proc.cmdline,proc_pname=%proc.pname,pod_id=%k8s.pod.id,syscall_name=%syscall.type,
    original_info=user=%user.name user_loginuid=%user.loginuid %container.info
    shell=%proc.name parent=%proc.pname terminal=%proc.tty container_id=%container.id container_name=%container.name image=%container.image.repository)
  priority: CRITICAL
  tags: [ATT&CK, container, shell, mitre_execution]