global:
  image: 
    registry: ""
    repository: ""

faulty:
  image:
    regsitry: localhost:32000
    repository: tensorsecurity
    name: faulty
    tag: latest

test:
  image:
    regsitry: localhost:32000
    repository: tensorsecurity
    name: nginx
    tag: alpine-curl
