package model

var ClassifiedKubeMap = map[string][]string{
	"1.1.1":  {"访问控制专项", "Access Control"},
	"1.1.2":  {"访问控制专项", "Access Control"},
	"1.1.3":  {"访问控制专项", "Access Control"},
	"1.1.4":  {"访问控制专项", "Access Control"},
	"1.1.5":  {"访问控制专项", "Access Control"},
	"1.1.6":  {"访问控制专项", "Access Control"},
	"1.1.7":  {"访问控制专项", "Access Control"},
	"1.1.8":  {"访问控制专项", "Access Control"},
	"1.1.9":  {"访问控制专项", "Access Control"},
	"1.1.10": {"访问控制专项", "Access Control"},
	"1.1.11": {"访问控制专项", "Access Control"},
	"1.1.12": {"访问控制专项", "Access Control"},
	"1.1.13": {"访问控制专项", "Access Control"},
	"1.1.14": {"访问控制专项", "Access Control"},
	"1.1.15": {"访问控制专项", "Access Control"},
	"1.1.16": {"访问控制专项", "Access Control"},
	"1.1.17": {"访问控制专项", "Access Control"},
	"1.1.18": {"访问控制专项", "Access Control"},
	"1.1.19": {"访问控制专项", "Access Control"},
	"1.1.20": {"访问控制专项", "Access Control"},
	"1.1.21": {"访问控制专项", "Access Control"},
	"1.2.1":  {"身份鉴别专项", "Authentication"},
	"1.2.2":  {"身份鉴别专项", "Authentication"},
	"1.2.3":  {"身份鉴别专项", "Authentication"},
	"1.2.4":  {"身份鉴别专项", "Authentication"},
	"1.2.5":  {"身份鉴别专项", "Authentication"},
	"1.2.6":  {"身份鉴别专项", "Authentication"},
	"1.2.7":  {"身份鉴别专项", "Authentication"},
	"1.2.8":  {"身份鉴别专项", "Authentication"},
	"1.2.9":  {"身份鉴别专项", "Authentication"},
	"1.2.10": {"资源控制专项", "Resource Control"},
	"1.2.11": {"访问控制专项", "Access Control"},
	"1.2.12": {"访问控制专项", "Access Control"},
	"1.2.13": {"入侵防御专项", "Intrusion Detection"},
	"1.2.14": {"访问控制专项", "Access Control"},
	"1.2.15": {"资源控制专项", "Resource Control"},
	"1.2.16": {"访问控制专项", "Access Control"},
	"1.2.17": {"访问控制专项", "Access Control"},
	"1.2.18": {"访问控制专项", "Access Control"},
	"1.2.19": {"入侵防御专项", "Intrusion Detection"},
	"1.2.20": {"入侵防御专项", "Intrusion Detection"},
	"1.2.21": {"访问控制专项", "Access Control"},
	"1.2.22": {"安全审计专项", "Auditing"},
	"1.2.23": {"安全审计专项", "Auditing"},
	"1.2.24": {"安全审计专项", "Auditing"},
	"1.2.25": {"安全审计专项", "Auditing"},
	"1.2.26": {"访问控制专项", "Access Control"},
	"1.2.27": {"访问控制专项", "Access Control"},
	"1.2.28": {"访问控制专项", "Access Control"},
	"1.2.29": {"访问控制专项", "Access Control"},
	"1.2.30": {"访问控制专项", "Access Control"},
	"1.2.31": {"访问控制专项", "Access Control"},
	"1.2.32": {"访问控制专项", "Access Control"},
	"1.2.33": {"访问控制专项", "Access Control"},
	"1.2.34": {"访问控制专项", "Access Control"},
	"1.2.35": {"访问控制专项", "Access Control"},
	"1.3.1":  {"访问控制专项", "Access Control"},
	"1.3.2":  {"访问控制专项", "Access Control"},
	"1.3.3":  {"访问控制专项", "Access Control"},
	"1.3.4":  {"访问控制专项", "Access Control"},
	"1.3.5":  {"身份鉴别专项", "Authentication"},
	"1.3.6":  {"身份鉴别专项", "Authentication"},
	"1.3.7":  {"访问控制专项", "Access Control"},
	"1.4.1":  {"访问控制专项", "Access Control"},
	"1.4.2":  {"访问控制专项", "Access Control"},
	"2.1":    {"身份鉴别专项", "Authentication"},
	"2.2":    {"身份鉴别专项", "Authentication"},
	"2.3":    {"身份鉴别专项", "Authentication"},
	"2.4":    {"身份鉴别专项", "Authentication"},
	"2.5":    {"身份鉴别专项", "Authentication"},
	"2.6":    {"身份鉴别专项", "Authentication"},
	"2.7":    {"身份鉴别专项", "Authentication"},
	"3.1.1":  {"身份鉴别专项", "Authentication"},
	"3.2.1":  {"身份鉴别专项", "Authentication"},
	"3.2.2":  {"身份鉴别专项", "Authentication"},
	"4.1.1":  {"访问控制专项", "Access Control"},
	"4.1.2":  {"访问控制专项", "Access Control"},
	"4.1.3":  {"访问控制专项", "Access Control"},
	"4.1.4":  {"访问控制专项", "Access Control"},
	"4.1.5":  {"访问控制专项", "Access Control"},
	"4.1.6":  {"访问控制专项", "Access Control"},
	"4.1.7":  {"访问控制专项", "Access Control"},
	"4.1.8":  {"访问控制专项", "Access Control"},
	"4.1.9":  {"访问控制专项", "Access Control"},
	"4.1.10": {"访问控制专项", "Access Control"},
	"4.2.1":  {"访问控制专项", "Access Control"},
	"4.2.2":  {"访问控制专项", "Access Control"},
	"4.2.3":  {"访问控制专项", "Access Control"},
	"4.2.4":  {"访问控制专项", "Access Control"},
	"4.2.5":  {"访问控制专项", "Access Control"},
	"4.2.6":  {"访问控制专项", "Access Control"},
	"4.2.7":  {"访问控制专项", "Access Control"},
	"4.2.8":  {"访问控制专项", "Access Control"},
	"4.2.9":  {"访问控制专项", "Access Control"},
	"4.2.10": {"访问控制专项", "Access Control"},
	"4.2.11": {"访问控制专项", "Access Control"},
	"4.2.12": {"访问控制专项", "Access Control"},
	"4.2.13": {"资源控制专项", "Resource Control"},
	"5.1.1":  {"身份鉴别专项", "Authentication"},
	"5.1.2":  {"身份鉴别专项", "Authentication"},
	"5.1.3":  {"身份鉴别专项", "Authentication"},
	"5.1.4":  {"身份鉴别专项", "Authentication"},
	"5.1.5":  {"身份鉴别专项", "Authentication"},
	"5.1.6":  {"身份鉴别专项", "Authentication"},
	"5.2.1":  {"资源控制专项", "Resource Control"},
	"5.2.2":  {"资源控制专项", "Resource Control"},
	"5.2.3":  {"资源控制专项", "Resource Control"},
	"5.2.4":  {"资源控制专项", "Resource Control"},
	"5.2.5":  {"资源控制专项", "Resource Control"},
	"5.2.6":  {"资源控制专项", "Resource Control"},
	"5.2.7":  {"资源控制专项", "Resource Control"},
	"5.2.8":  {"资源控制专项", "Resource Control"},
	"5.2.9":  {"资源控制专项", "Resource Control"},
	"5.3.1":  {"访问控制专项", "Access Control"},
	"5.3.2":  {"访问控制专项", "Access Control"},
	"5.4.1":  {"资源控制专项", "Resource Control"},
	"5.4.2":  {"资源控制专项", "Resource Control"},
	"5.5.1":  {"安全审计专项", "Auditing"},
	"5.7.1":  {"资源控制专项", "Resource Control"},
	"5.7.2":  {"入侵防御专项", "Intrusion Detection"},
	"5.7.3":  {"入侵防御专项", "Intrusion Detection"},
	"5.7.4":  {"资源控制专项", "Resource Control"},
}

var ClassifiedDockerMap = map[string][]string{
	"0.1.1":  {"入侵防御", "Intrusion Detection"},
	"0.2.1":  {"资源控制", "Resource Control"},
	"1.1.1":  {"访问控制", "Access Control"},
	"1.1.2":  {"访问控制", "Access Control"},
	"1.2.1":  {"资源控制", "Resource Control"},
	"1.2.2":  {"身份鉴别", "Authentication"},
	"1.2.3":  {"安全审计", "Auditing"},
	"1.2.4":  {"安全审计", "Auditing"},
	"1.2.5":  {"安全审计", "Auditing"},
	"1.2.6":  {"安全审计", "Auditing"},
	"1.2.7":  {"安全审计", "Auditing"},
	"1.2.8":  {"安全审计", "Auditing"},
	"1.2.9":  {"安全审计", "Auditing"},
	"1.2.10": {"安全审计", "Auditing"},
	"1.2.11": {"安全审计", "Auditing"},
	"1.2.12": {"安全审计", "Auditing"},
	"2.1":    {"访问控制", "Access Control"},
	"2.2":    {"安全审计", "Auditing"},
	"2.3":    {"访问控制", "Access Control"},
	"2.4":    {"入侵防御", "Intrusion Detection"},
	"2.5":    {"入侵防御", "Intrusion Detection"},
	"2.6":    {"身份鉴别", "Authentication"},
	"2.7":    {"资源控制", "Resource Control"},
	"2.8":    {"访问控制", "Access Control"},
	"2.9":    {"资源控制", "Resource Control"},
	"2.10":   {"资源控制", "Resource Control"},
	"2.11":   {"身份鉴别", "Authentication"},
	"2.12":   {"安全审计", "Auditing"},
	"2.13":   {"访问控制", "Access Control"},
	"2.14":   {"访问控制", "Access Control"},
	"2.15":   {"访问控制", "Access Control"},
	"2.16":   {"访问控制", "Access Control"},
	"2.17":   {"访问控制", "Access Control"},
	"3.1":    {"访问控制", "Access Control"},
	"3.2":    {"访问控制", "Access Control"},
	"3.3":    {"访问控制", "Access Control"},
	"3.4":    {"访问控制", "Access Control"},
	"3.5":    {"访问控制", "Access Control"},
	"3.6":    {"访问控制", "Access Control"},
	"3.7":    {"访问控制", "Access Control"},
	"3.8":    {"访问控制", "Access Control"},
	"3.9":    {"访问控制", "Access Control"},
	"3.10":   {"访问控制", "Access Control"},
	"3.11":   {"访问控制", "Access Control"},
	"3.12":   {"访问控制", "Access Control"},
	"3.13":   {"访问控制", "Access Control"},
	"3.14":   {"访问控制", "Access Control"},
	"3.15":   {"访问控制", "Access Control"},
	"3.16":   {"访问控制", "Access Control"},
	"3.17":   {"访问控制", "Access Control"},
	"3.18":   {"访问控制", "Access Control"},
	"3.19":   {"访问控制", "Access Control"},
	"3.20":   {"访问控制", "Access Control"},
	"3.21":   {"访问控制", "Access Control"},
	"3.22":   {"访问控制", "Access Control"},
	"4.1":    {"身份鉴别", "Authentication"},
	"4.2":    {"恶意代码防护", "Malicious code"},
	"4.3":    {"恶意代码防护", "Malicious code"},
	"4.4":    {"入侵防御", "Intrusion Detection"},
	"4.5":    {"恶意代码防护", "Malicious code"},
	"4.6":    {"资源控制", "Resource Control"},
	"4.7":    {"访问控制", "Access Control"},
	"4.8":    {"访问控制", "Access Control"},
	"4.9":    {"访问控制", "Access Control"},
	"4.10":   {"业务监测", "Business Monitoring"},
	"4.11":   {"恶意代码防护", "Malicious code"},
	"5.1":    {"访问控制", "Access Control"},
	"5.2":    {"访问控制", "Access Control"},
	"5.3":    {"访问控制", "Access Control"},
	"5.4":    {"访问控制", "Access Control"},
	"5.5":    {"访问控制", "Access Control"},
	"5.6":    {"入侵防御", "Intrusion Detection"},
	"5.7":    {"访问控制", "Access Control"},
	"5.8":    {"访问控制", "Access Control"},
	"5.9":    {"访问控制", "Access Control"},
	"5.10":   {"资源控制", "Resource Control"},
	"5.11":   {"访问控制", "Access Control"},
	"5.12":   {"访问控制", "Access Control"},
	"5.13":   {"访问控制", "Access Control"},
	"5.14":   {"资源控制", "Resource Control"},
	"5.15":   {"访问控制", "Access Control"},
	"5.16":   {"访问控制", "Access Control"},
	"5.17":   {"访问控制", "Access Control"},
	"5.18":   {"资源控制", "Resource Control"},
	"5.19":   {"访问控制", "Access Control"},
	"5.20":   {"访问控制", "Access Control"},
	"5.21":   {"访问控制", "Access Control"},
	"5.22":   {"恶意代码防护", "Malicious code"},
	"5.23":   {"恶意代码防护", "Malicious code"},
	"5.24":   {"资源控制", "Resource Control"},
	"5.25":   {"访问控制", "Access Control"},
	"5.26":   {"入侵防御", "Intrusion Detection"},
	"5.27":   {"入侵防御", "Intrusion Detection"},
	"5.28":   {"资源控制", "Resource Control"},
	"5.29":   {"入侵防御", "Intrusion Detection"},
	"5.30":   {"访问控制", "Access Control"},
	"5.31":   {"访问控制", "Access Control"},
	"6.1":    {"业务监控", "Business Monitoring"},
	"6.2":    {"业务监控", "Business Monitoring"},
	"7.1":    {"访问控制", "Access Control"},
	"7.2":    {"访问控制", "Access Control"},
	"7.3":    {"访问控制", "Access Control"},
	"7.4":    {"身份鉴别", "Authentication"},
	"7.5":    {"业务监控", "Business Monitoring"},
	"7.6":    {"资源控制", "Resource Control"},
	"7.7":    {"业务监控", "Business Monitoring"},
	"7.8":    {"身份鉴别", "Authentication"},
	"7.9":    {"身份鉴别", "Authentication"},
	"7.10":   {"资源控制", "Resource Control"},
}
