package model

var ClassifiedKubeMap = map[string][]string{
	"1.1.1":   {"身份鉴别", "Authentication"},
	"1.1.2":   {"身份鉴别", "Authentication"},
	"1.1.3":   {"身份鉴别", "Authentication"},
	"1.1.4":   {"身份鉴别", "Authentication"},
	"1.1.5":   {"入侵防御", "Intrusion Detection"},
	"1.1.6":   {"入侵防御", "Intrusion Detection"},
	"1.1.7":   {"入侵防御", "Intrusion Detection"},
	"1.1.8":   {"访问控制", "Access Control"},
	"1.1.9":   {"入侵防御", "Intrusion Detection"},
	"1.1.10":  {"访问控制", "Access Control"},
	"1.1.11":  {"访问控制", "Access Control"},
	"1.1.12":  {"访问控制", "Access Control"},
	"1.1.13":  {"访问控制", "Access Control"},
	"1.1.14":  {"资源控制", "Resource Control"},
	"1.1.15":  {"安全审计", "Auditing"},
	"1.1.16":  {"安全审计", "Auditing"},
	"1.1.17":  {"安全审计", "Auditing"},
	"1.1.18":  {"安全审计", "Auditing"},
	"1.1.19":  {"访问控制", "Access Control"},
	"1.1.20":  {"身份鉴别", "Authentication"},
	"1.1.21":  {"身份鉴别", "Authentication"},
	"1.1.22":  {"身份鉴别", "Authentication"},
	"1.1.23":  {"身份鉴别", "Authentication"},
	"1.1.24":  {"入侵防御", "Intrusion Detection"},
	"1.1.25":  {"身份鉴别", "Authentication"},
	"1.1.26":  {"身份鉴别", "Authentication"},
	"1.1.27":  {"身份鉴别", "Authentication"},
	"1.1.28":  {"身份鉴别", "Authentication"},
	"1.1.29":  {"身份鉴别", "Authentication"},
	"1.1.30":  {"资源控制", "Resource Control"},
	"1.1.31":  {"身份鉴别", "Authentication"},
	"1.1.32":  {"访问控制", "Access Control"},
	"1.1.33":  {"资源控制", "Resource Control"},
	"1.1.34":  {"身份鉴别", "Authentication"},
	"1.1.35":  {"身份鉴别", "Authentication"},
	"1.1.36":  {"资源控制", "Resource Control"},
	"1.1.37a": {"安全审计", "Auditing"},
	"1.1.37b": {"安全审计", "Auditing"},
	"1.1.38":  {"资源控制", "Resource Control"},
	"1.1.39":  {"身份鉴别", "Authentication"},
	"1.2.1":   {"访问控制", "Access Control"},
	"1.2.2":   {"入侵防御", "Intrusion Detection"},
	"1.3.1":   {"资源控制", "Resource Control"},
	"1.3.2":   {"访问控制", "Access Control"},
	"1.3.3":   {"身份鉴别", "Authentication"},
	"1.3.4":   {"身份鉴别", "Authentication"},
	"1.3.5":   {"身份鉴别", "Authentication"},
	"1.3.6":   {"身份鉴别", "Authentication"},
	"1.3.7":   {"入侵防御", "Intrusion Detection"},
	"1.4.1":   {"访问控制", "Access Control"},
	"1.4.2":   {"访问控制", "Access Control"},
	"1.4.3":   {"访问控制", "Access Control"},
	"1.4.4":   {"访问控制", "Access Control"},
	"1.4.5":   {"访问控制", "Access Control"},
	"1.4.6":   {"访问控制", "Access Control"},
	"1.4.7":   {"访问控制", "Access Control"},
	"1.4.8":   {"访问控制", "Access Control"},
	"1.4.9":   {"访问控制", "Access Control"},
	"1.4.10":  {"访问控制", "Access Control"},
	"1.4.11":  {"访问控制", "Access Control"},
	"1.4.12":  {"访问控制", "Access Control"},
	"1.4.13":  {"访问控制", "Access Control"},
	"1.4.14":  {"访问控制", "Access Control"},
	"1.4.15":  {"访问控制", "Access Control"},
	"1.4.16":  {"访问控制", "Access Control"},
	"1.4.17":  {"访问控制", "Access Control"},
	"1.4.18":  {"访问控制", "Access Control"},
	"1.5.1":   {"身份鉴别", "Authentication"},
	"1.5.2":   {"身份鉴别", "Authentication"},
	"1.5.3":   {"身份鉴别", "Authentication"},
	"1.5.4":   {"身份鉴别", "Authentication"},
	"1.5.5":   {"身份鉴别", "Authentication"},
	"1.5.6":   {"身份鉴别", "Authentication"},
	"1.5.7":   {"访问控制", "Access Control"},
	"1.6.1":   {"访问控制", "Access Control"},
	"1.6.2":   {"访问控制", "Access Control"},
	"1.6.3":   {"访问控制", "Access Control"},
	"1.6.4":   {"访问控制", "Access Control"},
	"1.6.5":   {"访问控制", "Access Control"},
	"1.6.6":   {"身份鉴别", "Authentication"},
	"1.6.7":   {"访问控制", "Access Control"},
	"1.6.8":   {"访问控制", "Access Control"},
	"1.7.1":   {"访问控制", "Access Control"},
	"1.7.2":   {"访问控制", "Access Control"},
	"1.7.3":   {"访问控制", "Access Control"},
	"1.7.4":   {"访问控制", "Access Control"},
	"1.7.5":   {"访问控制", "Access Control"},
	"1.7.6":   {"访问控制", "Access Control"},
	"1.7.7":   {"访问控制", "Access Control"},
	"2.1.1":   {"访问控制", "Access Control"},
	"2.1.2":   {"身份鉴别", "Authentication"},
	"2.1.3":   {"访问控制", "Access Control"},
	"2.1.4":   {"身份鉴别", "Authentication"},
	"2.1.5":   {"访问控制", "Access Control"},
	"2.1.6":   {"资源控制", "Resource Control"},
	"2.1.7":   {"访问控制", "Access Control"},
	"2.1.8":   {"访问控制", "Access Control"},
	"2.1.9":   {"访问控制", "Access Control"},
	"2.1.10":  {"资源控制", "Resource Control"},
	"2.1.11":  {"身份鉴别", "Authentication"},
	"2.1.12":  {"身份鉴别", "Authentication"},
	"2.1.13":  {"身份鉴别", "Authentication"},
	"2.1.14":  {"身份鉴别", "Authentication"},
	"2.1.15":  {"身份鉴别", "Authentication"},
	"2.2.1":   {"访问控制", "Access Control"},
	"2.2.2":   {"访问控制", "Access Control"},
	"2.2.3":   {"访问控制", "Access Control"},
	"2.2.4":   {"访问控制", "Access Control"},
	"2.2.5":   {"访问控制", "Access Control"},
	"2.2.6":   {"访问控制", "Access Control"},
	"2.2.7":   {"访问控制", "Access Control"},
	"2.2.8":   {"访问控制", "Access Control"},
	"2.2.9":   {"访问控制", "Access Control"},
	"2.2.10":  {"访问控制", "Access Control"},
}

var ClassifiedDockerMap = map[string][]string{
	"0.1.1":  {"入侵防御", "Intrusion Detection"},
	"0.2.1":  {"资源控制", "Resource Control"},
	"1.1.1":  {"访问控制", "Access Control"},
	"1.1.2":  {"访问控制", "Access Control"},
	"1.2.1":  {"资源控制", "Resource Control"},
	"1.2.2":  {"身份鉴别", "Authentication"},
	"1.2.3":  {"安全审计", "Auditing"},
	"1.2.4":  {"安全审计", "Auditing"},
	"1.2.5":  {"安全审计", "Auditing"},
	"1.2.6":  {"安全审计", "Auditing"},
	"1.2.7":  {"安全审计", "Auditing"},
	"1.2.8":  {"安全审计", "Auditing"},
	"1.2.9":  {"安全审计", "Auditing"},
	"1.2.10": {"安全审计", "Auditing"},
	"1.2.11": {"安全审计", "Auditing"},
	"1.2.12": {"安全审计", "Auditing"},
	"2.1":    {"访问控制", "Access Control"},
	"2.2":    {"安全审计", "Auditing"},
	"2.3":    {"访问控制", "Access Control"},
	"2.4":    {"入侵防御", "Intrusion Detection"},
	"2.5":    {"入侵防御", "Intrusion Detection"},
	"2.6":    {"身份鉴别", "Authentication"},
	"2.7":    {"资源控制", "Resource Control"},
	"2.8":    {"访问控制", "Access Control"},
	"2.9":    {"资源控制", "Resource Control"},
	"2.10":   {"资源控制", "Resource Control"},
	"2.11":   {"身份鉴别", "Authentication"},
	"2.12":   {"安全审计", "Auditing"},
	"2.13":   {"访问控制", "Access Control"},
	"2.14":   {"访问控制", "Access Control"},
	"2.15":   {"访问控制", "Access Control"},
	"2.16":   {"访问控制", "Access Control"},
	"2.17":   {"访问控制", "Access Control"},
	"3.1":    {"访问控制", "Access Control"},
	"3.2":    {"访问控制", "Access Control"},
	"3.3":    {"访问控制", "Access Control"},
	"3.4":    {"访问控制", "Access Control"},
	"3.5":    {"访问控制", "Access Control"},
	"3.6":    {"访问控制", "Access Control"},
	"3.7":    {"访问控制", "Access Control"},
	"3.8":    {"访问控制", "Access Control"},
	"3.9":    {"访问控制", "Access Control"},
	"3.10":   {"访问控制", "Access Control"},
	"3.11":   {"访问控制", "Access Control"},
	"3.12":   {"访问控制", "Access Control"},
	"3.13":   {"访问控制", "Access Control"},
	"3.14":   {"访问控制", "Access Control"},
	"3.15":   {"访问控制", "Access Control"},
	"3.16":   {"访问控制", "Access Control"},
	"3.17":   {"访问控制", "Access Control"},
	"3.18":   {"访问控制", "Access Control"},
	"3.19":   {"访问控制", "Access Control"},
	"3.20":   {"访问控制", "Access Control"},
	"3.21":   {"访问控制", "Access Control"},
	"3.22":   {"访问控制", "Access Control"},
	"4.1":    {"身份鉴别", "Authentication"},
	"4.2":    {"恶意代码防护", "Malicious code"},
	"4.3":    {"恶意代码防护", "Malicious code"},
	"4.4":    {"入侵防御", "Intrusion Detection"},
	"4.5":    {"恶意代码防护", "Malicious code"},
	"4.6":    {"资源控制", "Resource Control"},
	"4.7":    {"访问控制", "Access Control"},
	"4.8":    {"访问控制", "Access Control"},
	"4.9":    {"访问控制", "Access Control"},
	"4.10":   {"业务监测", "Business Monitoring"},
	"4.11":   {"恶意代码防护", "Malicious code"},
	"5.1":    {"访问控制", "Access Control"},
	"5.2":    {"访问控制", "Access Control"},
	"5.3":    {"访问控制", "Access Control"},
	"5.4":    {"访问控制", "Access Control"},
	"5.5":    {"访问控制", "Access Control"},
	"5.6":    {"入侵防御", "Intrusion Detection"},
	"5.7":    {"访问控制", "Access Control"},
	"5.8":    {"访问控制", "Access Control"},
	"5.9":    {"访问控制", "Access Control"},
	"5.10":   {"资源控制", "Resource Control"},
	"5.11":   {"访问控制", "Access Control"},
	"5.12":   {"访问控制", "Access Control"},
	"5.13":   {"访问控制", "Access Control"},
	"5.14":   {"资源控制", "Resource Control"},
	"5.15":   {"访问控制", "Access Control"},
	"5.16":   {"访问控制", "Access Control"},
	"5.17":   {"访问控制", "Access Control"},
	"5.18":   {"资源控制", "Resource Control"},
	"5.19":   {"访问控制", "Access Control"},
	"5.20":   {"访问控制", "Access Control"},
	"5.21":   {"访问控制", "Access Control"},
	"5.22":   {"恶意代码防护", "Malicious code"},
	"5.23":   {"恶意代码防护", "Malicious code"},
	"5.24":   {"资源控制", "Resource Control"},
	"5.25":   {"访问控制", "Access Control"},
	"5.26":   {"入侵防御", "Intrusion Detection"},
	"5.27":   {"入侵防御", "Intrusion Detection"},
	"5.28":   {"资源控制", "Resource Control"},
	"5.29":   {"入侵防御", "Intrusion Detection"},
	"5.30":   {"访问控制", "Access Control"},
	"5.31":   {"访问控制", "Access Control"},
	"6.1":    {"业务监控", "Business Monitoring"},
	"6.2":    {"业务监控", "Business Monitoring"},
	"7.1":    {"访问控制", "Access Control"},
	"7.2":    {"访问控制", "Access Control"},
	"7.3":    {"访问控制", "Access Control"},
	"7.4":    {"身份鉴别", "Authentication"},
	"7.5":    {"业务监控", "Business Monitoring"},
	"7.6":    {"资源控制", "Resource Control"},
	"7.7":    {"业务监控", "Business Monitoring"},
	"7.8":    {"身份鉴别", "Authentication"},
	"7.9":    {"身份鉴别", "Authentication"},
	"7.10":   {"资源控制", "Resource Control"},
}
