package model

var UDBCPTranslateMap = map[string]string{
	"访问控制专项":   "Access Control",
	"访问控制":     "Access Control",
	"访问控制(AC)": "Access Control",

	"身份鉴别专项":     "Authentication",
	"身份鉴别":       "Authentication",
	"身份鉴别(Auth)": "Authentication",

	"入侵防御专项":    "Intrusion Detection",
	"入侵防御":      "Intrusion Detection",
	"入侵防御(IDS)": "Intrusion Detection",

	"安全审计专项":         "Auditing",
	"安全审计":           "Auditing",
	"安全审计(Auditing)": "Auditing",

	"资源控制专项":           "Resource Control",
	"资源控制":             "Resource Control",
	"资源控制(ResControl)": "Resource Control",

	"恶意代码防护":          "Malicious code",
	"恶意代码防护(Malcode)": "Malicious code",

	"业务监控":           "Business Monitoring",
	"业务监测":           "Business Monitoring",
	"业务监测(DataProc)": "Business Monitoring",
}

var SectionPTranslateMap = map[string]string{
	"Containerd守护程序配置文件":     "Containerd daemon configuration files",
	"Worker Node 配置文件":       "Worker Node Configuration Files",
	"Pod安全规则":                "Pod Security Policies",
	"网络策略与CNI":               "Network Policies and CNI",
	"Secrets管理":              "Secrets Management",
	"扩展访问控制":                 "Extensible Admission Control",
	"普通策略":                   "General Policies",
	"主节点配置文件":                "Master Node Configuration Files",
	"API 服务":                 "API Server",
	"控制管理":                   "Controller Manager",
	"Etcd 节点配置文件":            "Etcd Node Configuration",
	"认证与授权":                  "Authentication and Authorization",
	"主机配置":                   "Host Configuration",
	"Docker守护程序配置":           "Docker daemon configuration",
	"Docker守护程序配置文件":         "Docker daemon configuration files",
	"容器镜像和构建文件":              "Container Images and Build File",
	"容器运行时":                  "Container Runtime",
	"Docker安全运营":             "Docker Security Operations",
	"Docker Swarm配置":         "Docker Swarm Configuration",
	"文件系统配置":                 "Filesystem Configuration",
	"配置软件更新":                 "Configure Software Updates",
	"文件系统完整性检查":              "Filesystem Integrity Checking",
	"安全启动设置":                 "Secure Boot Settings",
	"Additional Process加固":   "Additional Process Hardening",
	"强制访问控制":                 "Mandatory Access Control",
	"命令行警告Banners":           "Command Line Warning Banners",
	"GNOME Display管理":        "GNOME Display Manager",
	"inetd服务":                "inetd Services",
	"特殊用途业务":                 "Special Purpose Services",
	"禁用未使用的网络协议和设备":          "Disable unused network protocols and devices",
	"网络参数 (Host Only)":       "Network Parameters (Host Only)",
	"网络参数 (仅主机)":             "Network Parameters (Host Only)",
	"网络参数 (Host and Router)": "Network Parameters (Host and Router)",
	"网络参数 (主机和路由器)":          "Network Parameters (Host and Router)",
	"不常见的网络协议":               "Uncommon Network Protocols",
	"防火墙配置":                  "Firewall Configuration",
	"配置系统计费 (auditd)":        "Configure System Accounting (auditd)",
	"配置日志记录":                 "Configure Logging",
	"配置基于时间的作业调度器":           "Configure time-based job schedulers",
	"配置sudo":                 "Configure sudo",
	"配置SSH Server":           "Configure SSH Server",
	"配置PAM":                  "Configure PAM",
	"用户帐号与环境":                "User Accounts and Environment",
	"系统文件权限":                 "System File Permissions",
	"用户和组设置":                 "User and Group Settings",
	"Docker企业配置":             "Docker Enterprise Configuration",
	"容器安全检查":                 "Containersecurity checks",
	"CRI-O守护程序配置":            "CRI-O daemon configuration",
	"CRI-O守护程序配置文件":          "CRI-O daemon configuration files",
}
