image:
  registry:  registry.t-appagile.com
  repository: tensorsecurity
  name: kibana-oss
  tag: 7.4.2
  pullSecret: harbor-admin-secret

resources:
  limits:
    cpu: "1"
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 200Mi

init: 
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
