apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "driftPrevention.fullname" . }}-config
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  presets.yaml: |
    env:
    - name: LD_PRELOAD
      value: "/tensorsec/dp.so"
    - name: TENSORSEC_EVENTCENTER_NEW_ADDR
      value: "{{ .Values.eventcenter.addr }}"
    - name: TENSORSEC_EVENTCENTER_NEW_PORT
      value: "{{ .Values.eventcenter.port }}"
    volumemounts:
    - name: "{{ .Values.volumes.clientName }}"
      mountpath: "{{ .Values.volumes.clientMountPath }}"
      readonly: true
    - name: {{ .Values.volumes.caName }}
      mountpath: "{{ .Values.volumes.caMountPath }}"
      readonly: true
    volumes:
      - name: "{{ .Values.volumes.clientName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.clientSecretName }}"
      - name: "{{ .Values.volumes.caName }}"
        volumesource:
          secret:
            defaultmode: 420
            secretname: "{{ .Values.volumes.caSecretName }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "driftPrevention.serviceAccount" . }}-cluster-role
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "patch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "driftPrevention.serviceAccount" . }}-service-account
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "driftPrevention.serviceAccount" . }}-cluster-role-binding
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "driftPrevention.serviceAccount" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "driftPrevention.serviceAccount" . }}-service-account
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "driftPrevention.fullname" . }}-service
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: {{ template "driftPrevention.fullname" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "driftPrevention.fullname" . }}
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "driftPrevention.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "driftPrevention.fullname" . }}
    spec:
      serviceAccountName: {{ template "driftPrevention.serviceAccount" . }}-service-account
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
      - name: {{ template "driftPrevention.serviceAccount" . }}-webhook
        image: {{ include "driftPrevention.image" . }}
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        # command: ["/bin/sh", "-c", "sleep 360000"]
        args:
        - --preset=/etc/config/presets.yaml
        - --cert=/etc/certs/tls.crt
        - --key=/etc/certs/tls.key
        - --port=8443
        volumeMounts:
        - name: certs
          mountPath: /etc/certs
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        resources:
{{ toYaml .Values.resources | trim | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "driftPrevention.fullname" . }}-config
      - name: certs
        secret:
          secretName: {{ template "driftPrevention.fullname" . }}-certs




