apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "driftPrevention.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
webhooks:
  - name: {{ template "driftPrevention.fullname" . }}-service.{{ .Release.Namespace }}.svc
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lKQUxlaThVL1V3UFBnTUEwR0NTcUdTSWIzRFFFQkN3VUFNQzh4TFRBckJnTlYKQkFNTUpFRmtiV2x6YzJsdmJpQkRiMjUwY205c2JHVnlJRmRsWW1odmIyc2dSR1Z0YnlCRFFUQWVGdzB5TVRBMgpNak13T1RNd016TmFGdzB6TVRBMk1qRXdPVE13TXpOYU1DOHhMVEFyQmdOVkJBTU1KRUZrYldsemMybHZiaUJECmIyNTBjbTlzYkdWeUlGZGxZbWh2YjJzZ1JHVnRieUJEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQU1xSi9QMlcxUVU3eDBYTmo4YmVqbWJUWFdGbFlBeFhnd3ZocEVnTjhKSmx5Q1ovLy9pWQoxeXFGNU9nYTZEU2hZZUVRd3dpQkpnWVlISGVBU25BN1hJTEdiSXE4RlJKcGVkKzJENDZIQ0tFb0tNeUVIaFM5CjYzb041Ym1OTGZLQmZoK3hxV0dpbkRKMnBnRnkrZ1k2MWx6cG1VU2h3QVNub1ZWSGc2TlE3MlRUMyt6L05YMnEKbWh0UkdRWDZCdGpKNDRPRmdFVmZHMG45RDllNndUSXdrQWVxSW0rVG1ab1BRc0hWUTd5c2xnbkVCeW96S2I5Vgp0QUxtQUdRQnR1N1FBMHA3UTE3elhBeDJnUVVxd0diMzFtcTRxN0wzODIzdHBRanBSM0pqMG94THZ2Q21RSkdZCnNMMW5uNktYTDB6Slo3bE9HUGtqbEowdWQwUThwWUJhNUlzQ0F3RUFBYU5RTUU0d0hRWURWUjBPQkJZRUZKekQKWkphNFQ2cS9odjNmVTJKRTkvZHlBK3o2TUI4R0ExVWRJd1FZTUJhQUZKekRaSmE0VDZxL2h2M2ZVMkpFOS9keQpBK3o2TUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR1NWQk5SY1JFVlEyYVZKClFLdk5JaVRUWDZPdmtiWExEejlmdW5rUm9nTUhYb291S3pkdFNYUnVZemZsK0RFWFE2UkZ4UzJhbm1GRmNVWUUKcE5OQkxZY0M4YWV2MnBLR0ZURmxqQ0RtZEhoUUwwUnVEOWVsckgrajlGenRDVE1VRm1YQVg4UklMTVltNkZNSwpTK3VURjB3MUJ0ci9XdnZsVzZJc2dxWTB5NXJaNFQ2MHRBVVg2LzhTUnFhQXV1akJsQ0M0b1hsZ0k3bUozQmFJCnM1TXFNQlRzc1gyQmh4dkEzWVVjZ2xRaHBiOEhDUkhrMlhTamVZeDFIS2JZaDJZd2d5b3crc3dBeG03eGVKL1cKN2FQVElpMVJxRUdVY3p0aHovMmdJYnlGdVByY1ZyS0p3b2F4bU1lakdPV2NnZDRXVTZudmVBRFJjQjRyUUNvdQppeGJNTVZVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== 
      service:
        name: "{{ template "driftPrevention.fullname" . }}-service"
        namespace: "{{ .Release.Namespace }}"
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: "name"
          operator: "NotIn"
          values:
            - "kube-system"
