apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "driftPrevention.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app: "{{ template "driftPrevention.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
webhooks:
  - name: {{ template "driftPrevention.fullname" . }}-service.{{ .Release.Namespace }}.svc
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lKQU13d0hIdEc1TVVMTUEwR0NTcUdTSWIzRFFFQkN3VUFNQzh4TFRBckJnTlYKQkFNTUpFRmtiV2x6YzJsdmJpQkRiMjUwY205c2JHVnlJRmRsWW1odmIyc2dSR1Z0YnlCRFFUQWVGdzB5TVRBMwpNRGN4TURNM01qZGFGdzB6TVRBM01EVXhNRE0zTWpkYU1DOHhMVEFyQmdOVkJBTU1KRUZrYldsemMybHZiaUJECmIyNTBjbTlzYkdWeUlGZGxZbWh2YjJzZ1JHVnRieUJEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVAKQURDQ0FRb0NnZ0VCQUs3a29qVWJVV3RZWkROZTJoT0pmQU5kQ25KTzhSL3laWHBKUWk1cUlJbi85YTZPU2J2cgp3ZXZCTkJpYTBMbnZ6d0tvQXZ2YmZOSVYrVzh5c2hmTnJOQzdkQVdrTExmN0E3WXBBMXJxSVlZeklDQmNDajFXCjhVd3dXNVBOdmhhWnVKWDdkWjZ5NjYzaTRxanpjSmJNYis4S20vMDNNbDBMSEFXYXFROEYyb2hJNjRtdTBmbk8KSEROTGhPL2IyeDRVK0ZaRWVUUzQzUUtjRmNINzVwbVZhdU11RTcxbE9yWE04d1Fqb1dDR3VMbnYvWTl0dmZkTwpHajY4Z1FiMm9XOFpoRHNYbVR3RldEWEI3MnpsbUNaYlE4YmxwZnZrTnpBUGhPV3dYTVNjbWZmV3M2TStLcG54CnFvaHJwWmkxMkhiV3dyQlZ3M3N3T2JCNVo0QUhwQW5hNVYwQ0F3RUFBYU5RTUU0d0hRWURWUjBPQkJZRUZBbk8KVmZKM2VUZExkTlk5QVVRSm1HVW5jL1RDTUI4R0ExVWRJd1FZTUJhQUZBbk9WZkozZVRkTGROWTlBVVFKbUdVbgpjL1RDTUF3R0ExVWRFd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSE9teVpiWWtubVNrajhkCk9NSGxRa3gwWWVKM1o1RVc0bGpJaTFOdUtwN1F3Ukdsdjg5SitEL096eTU4SWN3cTNoN3NnMnhJR09UOUpIclkKUUNmYlpaRUdzV3N4Vi9ENE9jK25zZloxdThtZzhHMy9Jdkw4YTRtUU5tWmFqSVhTWjJORmFtbWpqN2g0bnZCQgozSWk1V0k3RGo3L09TTW1GL29pQXdDV04vb0J5L1lGb05XTWZIVGc3SFN4WU1kbms4OVM0U1RlODJ2ams0RTBhCmx3cFBTN2lyeERJbjRMZEZQMC9pNVduSlpOeWVWMXpQR3YrYUlzRUltSmZydzJKRFdjVXVMZWlFZThlQUtJRncKMG1tbXI0aXlBZ0NkbmZ5anBvdi9Bc2UrMm5tR1kybk13SzVmKzlnWE90a25pTmF2aU95QnBSSlpiUHlKcHYwMwo3eHVIT1AwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== 
      service:
        name: "{{ template "driftPrevention.fullname" . }}-service"
        namespace: "{{ .Release.Namespace }}"
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    failurePolicy: Ignore
    namespaceSelector:
      matchExpressions:
        - key: "name"
          operator: "NotIn"
          values:
            - "kube-system"
