apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp-profile-generator
  labels:
    app: seccomp-profile-generator
spec:
  selector:
    matchLabels:
      app: seccomp-profile-generator
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: seccomp-profile-generator
      labels:
        app: seccomp-profile-generator
    spec:
      restartPolicy: Always
      containers:
      - name: seccomp-profile-generator
        image: "localhost:32000/tensordig:latest"
        command:
          - /bin/bash
          - -c
          - "/go/src/app/configs/tensordig/seccomp.sh"
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
        env:
        - name: TENSORSEC_SECCOMP_GENERATOR_HOST
          value: tensorsec-seccomp-generator.tensorsec-test.svc.cluster.local
        - name: TENSORSEC_SECCOMP_GENERATOR_PORT
          value: "8881"
        - name: TENSORSEC_CONSOLE_HOST
          value: tensorsec-console.tensorsec-test.svc.cluster.local
        - name: TENSORSEC_CONSOLE_PORT
          value: "8889"
        - name: TESTING_AFTER
          value: "90"
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RANDOM_UUID
          value: {{RANDOM_UUID}}
        volumeMounts:
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: usr
          mountPath: /usr/src
          readOnly: true
        - name: time
          mountPath: /etc/localtime
          readOnly: true
        - name: sys
          mountPath: /sys
        - name: proc
          mountPath: /host/proc
          readOnly: true
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1.5"
          limits:
            memory: "2048Mi"
            cpu: "1.5"
      # imagePullSecrets:
      #   - name: harbor-admin-secret
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: time
        hostPath:
          path: /etc/localtime
      - name: modules
        hostPath:
          path: /lib/modules
      - name: usr
        hostPath:
          path: /usr/src
      - name: proc
        hostPath:
          path: /proc
