apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scanner.fullname" . }}-configmap
data:
  patterns.json: |-
{{ .Files.Get "patterns.json" | indent 4}}

  registry.yaml: |-
{{ toYaml .Values.config.registry | indent 4 }}
