apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scanner.fullname" . }}
  labels:
{{ include "scanner.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scanner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scanner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.service.port }}
            name: {{ include "scanner.name" . }}

        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: tmp
            mountPath: "/tmp/"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: tmp
        hostPath:
          path: /tmp/


