apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scanner.fullname" . }}
  labels:
{{ include "scanner.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scanner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scanner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    # {{- with .Values.imagePullSecrets }}
    #   imagePullSecrets:
    #     {{- toYaml . | nindent 8 }}
    # {{- end }}
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: "postgres-listener"
        image: {{ include "scanner.registryPath" . }}/alpine:latest
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 tensorsec-postgresql 5432 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.init.resources | trim | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "scanner.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/tensor-scanner"]
        args: [
          "--mongo-endpoint=tensorsec-mongodb-0.tensorsec-mongodb-headless:27017",
          "--mongo-database={{ .Values.mongo.mongoDatabase }}",
          "--mongo-username={{ .Values.mongo.mongoUsername }}",
          "--clair-remote-address=tensorsec-clair",
          # clair-address and clair-port refer to Scanner Service address. Clair service needs to have access to layers published by Scanner service.
          # Path to them is sent in Scan request to Clair.
          # TODO: maybe rename? I spent hours on this because I was confused.
          "--clair-address=tensorsec-scanner",
          "--clair-port={{ .Values.service.LayerPort }}",
          "--clair-postgresconnectionstring={{ .Values.clair.postgresURI }}",
          "--clair-secretpattern=/config/patterns.json",
          "--redclair-skipregistrytlsverify", # Insecure
          "--redis-endpoint=tensorsec-redis-ha-announce-0:26379,tensorsec-redis-ha-announce-1:26379,tensorsec-redis-ha-announce-2:26379",
          "--harbor-configPath=/config/registry.yaml",
          "--harbor-skiptlsverify", # Insecure
          "-v"]
        env:
          - name: TENSORSEC_MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongo.mongoSecretName }}
                key: mongodb-password
          - name: TENSORSEC_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redis.redisSecretName }}
                key: auth
          - name: TENSORSEC_HARBOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.harbor.harborSecretName }}
                key: password
        ports:
          - containerPort: {{ .Values.service.ApiContainerPort }}
            name: {{ include "scanner.name" . }}-api
          - containerPort: {{ .Values.service.LayerContainerPort }}
            name: {{ include "scanner.name" . }}-layer
        volumeMounts:
          - name: scannerfiles
            mountPath: "/config/patterns.json"
            subPath: patterns.json
          - name: registryfiles
            mountPath: "/config/registry.yaml"
            subPath: registry.yaml
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: tmp
            mountPath: "/tmp/"
          - mountPath: /eventcenter-config
            name: scanner-eventcenter-config
          - mountPath: /auth/ca
            name: ca-cert
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "tensorsec.tplvalues" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: tmp
        hostPath:
          path: /tmp/
      - name: scannerfiles
        configMap:
          name: {{ template "scanner.fullname" . }}-configmap
          items:
            - key: patterns.json
              path: patterns.json
      - name: registryfiles
        configMap:
          name: {{ template "scanner.fullname" . }}-configmap
          items:
            - key: registry.yaml
              path: registry.yaml
      - name: scanner-eventcenter-config
        secret:
          defaultMode: 420
          secretName: eventcenter-tls-client-cert-secret
      - name: ca-cert
        secret:
          defaultMode: 400
          secretName: eventcenter-tls-ca-secret
