apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: scanner
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: scanner
  template:
    metadata:
      labels: {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: scanner
    spec:
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.pullSecret }}
      {{- else if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: "postgres-listener"
        image: {{ include "scanner.init.image" . }}
        imagePullPolicy: "IfNotPresent"
        command: [
          "sh", "-c",
          "for i in $(seq 1 200); do nc -z -w3 {{ include "common.pgpool.defaultName" . }} 5432 && exit 0 || sleep 3; done; exit 1"
        ]
        resources:
{{ toYaml .Values.init.resources | trim | indent 10 }}
      containers:
      - name: scanner
        image: {{ include "scanner.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/scanner"]
        args:
        - --image-cache-server-ip={{ include "common.names.fullname" . }}
        - --image-cache-server-port={{ .Values.service.ImageCacheServerPort }}
        - --redis-endpoint={{ include "common.redis.sentinel.address" . }}
        - --http-listen-addr=:{{ .Values.service.ApiContainerPort }}
        - --db-connect-str={{ include "common.pgpool.DSN" . }}
        - --pvc-path=/root/alldb
        - --web-shell-server-addr=http://{{ printf "%s-webshell-server" (include "common.names.fullname" .) }}:80
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "common.redis-ha.defaultName" . }}
                key: auth
          - name: CICD-BUF-REGISTRY-URL
            value: "http://{{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}:{{ .Values.dockerregistry.service.httpPort }}"
          - name: CICD-BUF-REGISTRY-USER
            value: {{ .Values.dockerregistry.secrets.username | quote }}
          - name: CICD-BUF-REGISTRY-PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-dockerregistry-normal" (include "common.names.fullname" .) }}
                key: pass
          - name: REGISTRY_GC_PORT
            value: {{ .Values.dockerregistry.service.gcPort | quote }}
          - name: SAFENODE-BUF-REGISTRY-URL
            value: "http://{{ printf "%s-dockerregistry" (include "common.names.fullname" .) }}:{{ .Values.dockerregistry.service.httpPort }}"
          - name: SAFENODE-BUF-REGISTRY-USER
            value: "registry"
          - name: SAFENODE-BUF-REGISTRY-PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-dockerregistry-normal" (include "common.names.fullname" .) }}
                key: pass
          - name: SAFENODE-BUF-INTERNAL
            value: "60"
        ports:
          - containerPort: {{ .Values.service.ApiContainerPort }}
            name: scanner-api
          - containerPort: {{ .Values.service.ImageCacheServerPort }}
            name: scanner-cache
        volumeMounts:
          - name: scannerfiles
            mountPath: "/config/patterns.json"
            subPath: patterns.json
          - name: dockersock
            mountPath: "/var/run/docker.sock"
          - name: tmp
            mountPath: "/tmp/"
          - mountPath: /eventcenter-config
            name: scanner-eventcenter-config
          - mountPath: /auth/ca
            name: ca-cert
          - mountPath: /root/alldb
            name: vuln-db
        resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: tmp
        hostPath:
          path: /tmp/
      - name: scannerfiles
        configMap:
          name: {{ include "common.names.fullname" . }}
          items:
            - key: patterns.json
              path: patterns.json
      - name: scanner-eventcenter-config
        secret:
          defaultMode: 420
          secretName: eventcenter-tls-client-cert-secret
      - name: ca-cert
        secret:
          defaultMode: 400
          secretName: eventcenter-tls-ca-secret
      {{- if .Values.persistence.enabled }}
      - name: vuln-db
        persistentVolumeClaim:
          claimName: {{ printf "%s-vulndb" (include "common.names.fullname" .) }}
      {{- else }}
      - name: vuln-db
        emptyDir: {}
      {{- end }}
