apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.redisSecretName }}
  labels:
    helm.sh/chart: {{ include "scanner.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc | quote }}
