apiVersion: v1
kind: Service
metadata:
  name: {{ include "scanner.fullname" . }}
  labels:
    helm.sh/chart: {{ include "scanner.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ApiPort }}
      targetPort: {{ .Values.service.ApiContainerPort }}
      protocol: TCP
      name: {{ include "scanner.name" . }}-api
    - port: {{ .Values.service.LayerPort }}
      targetPort: {{ .Values.service.LayerContainerPort }}
      protocol: TCP
      name: {{ include "scanner.name" . }}-layer

  selector:
    app.kubernetes.io/name: {{ include "scanner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}