apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: scanner
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ApiPort }}
      targetPort: {{ .Values.service.ApiContainerPort }}
      protocol: TCP
      name: scanner-api
    - port: {{ .Values.service.CachePort }}
      targetPort: {{ .Values.service.ImageCacheServerPort }}
      protocol: TCP
      name: scanner-cache
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: scanner