// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MultiLanguageKV struct {
	KVHash               map[string]*KV `protobuf:"bytes,1,rep,name=KVHash,proto3" json:"KVHash,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MultiLanguageKV) Reset()         { *m = MultiLanguageKV{} }
func (m *MultiLanguageKV) String() string { return proto.CompactTextString(m) }
func (*MultiLanguageKV) ProtoMessage()    {}
func (*MultiLanguageKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *MultiLanguageKV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiLanguageKV.Unmarshal(m, b)
}
func (m *MultiLanguageKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiLanguageKV.Marshal(b, m, deterministic)
}
func (m *MultiLanguageKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiLanguageKV.Merge(m, src)
}
func (m *MultiLanguageKV) XXX_Size() int {
	return xxx_messageInfo_MultiLanguageKV.Size(m)
}
func (m *MultiLanguageKV) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiLanguageKV.DiscardUnknown(m)
}

var xxx_messageInfo_MultiLanguageKV proto.InternalMessageInfo

func (m *MultiLanguageKV) GetKVHash() map[string]*KV {
	if m != nil {
		return m.KVHash
	}
	return nil
}

type MultiLanguageValue struct {
	ValueHash            map[string]string `protobuf:"bytes,1,rep,name=ValueHash,proto3" json:"ValueHash,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MultiLanguageValue) Reset()         { *m = MultiLanguageValue{} }
func (m *MultiLanguageValue) String() string { return proto.CompactTextString(m) }
func (*MultiLanguageValue) ProtoMessage()    {}
func (*MultiLanguageValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *MultiLanguageValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiLanguageValue.Unmarshal(m, b)
}
func (m *MultiLanguageValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiLanguageValue.Marshal(b, m, deterministic)
}
func (m *MultiLanguageValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiLanguageValue.Merge(m, src)
}
func (m *MultiLanguageValue) XXX_Size() int {
	return xxx_messageInfo_MultiLanguageValue.Size(m)
}
func (m *MultiLanguageValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiLanguageValue.DiscardUnknown(m)
}

var xxx_messageInfo_MultiLanguageValue proto.InternalMessageInfo

func (m *MultiLanguageValue) GetValueHash() map[string]string {
	if m != nil {
		return m.ValueHash
	}
	return nil
}

type Context struct {
	PodUID               string             `protobuf:"bytes,1,opt,name=PodUID,proto3" json:"PodUID,omitempty"`
	PodName              string             `protobuf:"bytes,2,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Namespace            string             `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Cluster              string             `protobuf:"bytes,4,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	ServiceID            string             `protobuf:"bytes,5,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	CustomKV             []*MultiLanguageKV `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetPodUID() string {
	if m != nil {
		return m.PodUID
	}
	return ""
}

func (m *Context) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *Context) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Context) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Context) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func (m *Context) GetCustomKV() []*MultiLanguageKV {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type DetectionRule struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Module               string                         `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category             string                         `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Description          string                         `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Severity             uint32                         `protobuf:"varint,5,opt,name=Severity,proto3" json:"Severity,omitempty"`
	MultiLanguage        map[string]*MultiLanguageValue `protobuf:"bytes,6,rep,name=MultiLanguage,proto3" json:"MultiLanguage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomKV             []*MultiLanguageKV             `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *DetectionRule) Reset()         { *m = DetectionRule{} }
func (m *DetectionRule) String() string { return proto.CompactTextString(m) }
func (*DetectionRule) ProtoMessage()    {}
func (*DetectionRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *DetectionRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectionRule.Unmarshal(m, b)
}
func (m *DetectionRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectionRule.Marshal(b, m, deterministic)
}
func (m *DetectionRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectionRule.Merge(m, src)
}
func (m *DetectionRule) XXX_Size() int {
	return xxx_messageInfo_DetectionRule.Size(m)
}
func (m *DetectionRule) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectionRule.DiscardUnknown(m)
}

var xxx_messageInfo_DetectionRule proto.InternalMessageInfo

func (m *DetectionRule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DetectionRule) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *DetectionRule) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DetectionRule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DetectionRule) GetSeverity() uint32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *DetectionRule) GetMultiLanguage() map[string]*MultiLanguageValue {
	if m != nil {
		return m.MultiLanguage
	}
	return nil
}

func (m *DetectionRule) GetCustomKV() []*MultiLanguageKV {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type RuleKey struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Module               string   `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleKey) Reset()         { *m = RuleKey{} }
func (m *RuleKey) String() string { return proto.CompactTextString(m) }
func (*RuleKey) ProtoMessage()    {}
func (*RuleKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *RuleKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleKey.Unmarshal(m, b)
}
func (m *RuleKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleKey.Marshal(b, m, deterministic)
}
func (m *RuleKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleKey.Merge(m, src)
}
func (m *RuleKey) XXX_Size() int {
	return xxx_messageInfo_RuleKey.Size(m)
}
func (m *RuleKey) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleKey.DiscardUnknown(m)
}

var xxx_messageInfo_RuleKey proto.InternalMessageInfo

func (m *RuleKey) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleKey) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *RuleKey) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type SendNotificationReq struct {
	RuleKey              *RuleKey `protobuf:"bytes,1,opt,name=RuleKey,proto3" json:"RuleKey,omitempty"`
	NotifyContext        *Context `protobuf:"bytes,2,opt,name=NotifyContext,proto3" json:"NotifyContext,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UUID                 uint64   `protobuf:"varint,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendNotificationReq) Reset()         { *m = SendNotificationReq{} }
func (m *SendNotificationReq) String() string { return proto.CompactTextString(m) }
func (*SendNotificationReq) ProtoMessage()    {}
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *SendNotificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendNotificationReq.Unmarshal(m, b)
}
func (m *SendNotificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendNotificationReq.Marshal(b, m, deterministic)
}
func (m *SendNotificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendNotificationReq.Merge(m, src)
}
func (m *SendNotificationReq) XXX_Size() int {
	return xxx_messageInfo_SendNotificationReq.Size(m)
}
func (m *SendNotificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendNotificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendNotificationReq proto.InternalMessageInfo

func (m *SendNotificationReq) GetRuleKey() *RuleKey {
	if m != nil {
		return m.RuleKey
	}
	return nil
}

func (m *SendNotificationReq) GetNotifyContext() *Context {
	if m != nil {
		return m.NotifyContext
	}
	return nil
}

func (m *SendNotificationReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SendNotificationReq) GetUUID() uint64 {
	if m != nil {
		return m.UUID
	}
	return 0
}

type AddDetectionRuleReq struct {
	Rule                 *DetectionRule `protobuf:"bytes,1,opt,name=Rule,proto3" json:"Rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AddDetectionRuleReq) Reset()         { *m = AddDetectionRuleReq{} }
func (m *AddDetectionRuleReq) String() string { return proto.CompactTextString(m) }
func (*AddDetectionRuleReq) ProtoMessage()    {}
func (*AddDetectionRuleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *AddDetectionRuleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDetectionRuleReq.Unmarshal(m, b)
}
func (m *AddDetectionRuleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDetectionRuleReq.Marshal(b, m, deterministic)
}
func (m *AddDetectionRuleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDetectionRuleReq.Merge(m, src)
}
func (m *AddDetectionRuleReq) XXX_Size() int {
	return xxx_messageInfo_AddDetectionRuleReq.Size(m)
}
func (m *AddDetectionRuleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDetectionRuleReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddDetectionRuleReq proto.InternalMessageInfo

func (m *AddDetectionRuleReq) GetRule() *DetectionRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type ResetCategoryRulesReq struct {
	Module               string           `protobuf:"bytes,1,opt,name=Module,proto3" json:"Module,omitempty"`
	Category             string           `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	Rules                []*DetectionRule `protobuf:"bytes,3,rep,name=Rules,proto3" json:"Rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResetCategoryRulesReq) Reset()         { *m = ResetCategoryRulesReq{} }
func (m *ResetCategoryRulesReq) String() string { return proto.CompactTextString(m) }
func (*ResetCategoryRulesReq) ProtoMessage()    {}
func (*ResetCategoryRulesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *ResetCategoryRulesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetCategoryRulesReq.Unmarshal(m, b)
}
func (m *ResetCategoryRulesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetCategoryRulesReq.Marshal(b, m, deterministic)
}
func (m *ResetCategoryRulesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetCategoryRulesReq.Merge(m, src)
}
func (m *ResetCategoryRulesReq) XXX_Size() int {
	return xxx_messageInfo_ResetCategoryRulesReq.Size(m)
}
func (m *ResetCategoryRulesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetCategoryRulesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetCategoryRulesReq proto.InternalMessageInfo

func (m *ResetCategoryRulesReq) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ResetCategoryRulesReq) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ResetCategoryRulesReq) GetRules() []*DetectionRule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*KV)(nil), "pb.KV")
	proto.RegisterType((*MultiLanguageKV)(nil), "pb.MultiLanguageKV")
	proto.RegisterMapType((map[string]*KV)(nil), "pb.MultiLanguageKV.KVHashEntry")
	proto.RegisterType((*MultiLanguageValue)(nil), "pb.MultiLanguageValue")
	proto.RegisterMapType((map[string]string)(nil), "pb.MultiLanguageValue.ValueHashEntry")
	proto.RegisterType((*Context)(nil), "pb.Context")
	proto.RegisterType((*DetectionRule)(nil), "pb.DetectionRule")
	proto.RegisterMapType((map[string]*MultiLanguageValue)(nil), "pb.DetectionRule.MultiLanguageEntry")
	proto.RegisterType((*RuleKey)(nil), "pb.RuleKey")
	proto.RegisterType((*SendNotificationReq)(nil), "pb.SendNotificationReq")
	proto.RegisterType((*AddDetectionRuleReq)(nil), "pb.AddDetectionRuleReq")
	proto.RegisterType((*ResetCategoryRulesReq)(nil), "pb.ResetCategoryRulesReq")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x96, 0x9d, 0x8f, 0x36, 0x13, 0xe5, 0x7d, 0xfb, 0x6e, 0xfb, 0x16, 0x63, 0x5a, 0xb5, 0xb2,
	0x5a, 0x51, 0x55, 0x95, 0x23, 0xc2, 0x01, 0x54, 0x7a, 0x29, 0x4e, 0x25, 0x4a, 0x68, 0x55, 0x5c,
	0x1a, 0x21, 0x6e, 0x4e, 0xbc, 0x0d, 0x56, 0x1d, 0xaf, 0xb1, 0xd7, 0x11, 0xbe, 0x72, 0xe7, 0xc4,
	0x81, 0x33, 0x7f, 0x85, 0xbf, 0xc0, 0x5f, 0xe0, 0xc8, 0x89, 0x5f, 0x80, 0xf6, 0x23, 0x4e, 0xec,
	0xb8, 0x87, 0x4a, 0x9c, 0xbc, 0x33, 0x3b, 0x33, 0xcf, 0xf3, 0xcc, 0x8c, 0x17, 0x9a, 0x78, 0x82,
	0x03, 0x6a, 0x86, 0x11, 0xa1, 0x04, 0xa9, 0xe1, 0x40, 0x7f, 0x30, 0x22, 0x64, 0xe4, 0xe3, 0x36,
	0xf7, 0x0c, 0x92, 0xeb, 0x36, 0x1e, 0x87, 0x34, 0x15, 0x01, 0xfa, 0x86, 0xbc, 0x74, 0x42, 0xaf,
	0xed, 0x04, 0x01, 0xa1, 0x0e, 0xf5, 0x48, 0x10, 0x8b, 0x5b, 0xe3, 0x00, 0xd4, 0x5e, 0x1f, 0xad,
	0x40, 0xa5, 0x87, 0x53, 0x4d, 0xd9, 0x56, 0xf6, 0x1a, 0x36, 0x3b, 0xa2, 0x35, 0xa8, 0xf5, 0x1d,
	0x3f, 0xc1, 0x9a, 0xca, 0x7d, 0xc2, 0x30, 0x3e, 0x2b, 0xf0, 0xef, 0x59, 0xe2, 0x53, 0xef, 0x95,
	0x13, 0x8c, 0x12, 0x67, 0x84, 0x7b, 0x7d, 0xf4, 0x04, 0xea, 0xbd, 0xfe, 0x0b, 0x27, 0x7e, 0xaf,
	0x29, 0xdb, 0x95, 0xbd, 0x66, 0x67, 0xcb, 0x0c, 0x07, 0x66, 0x21, 0xc8, 0x14, 0x11, 0x27, 0x01,
	0x8d, 0x52, 0x5b, 0x86, 0xeb, 0xc7, 0xd0, 0x9c, 0x73, 0x33, 0x0e, 0x37, 0x33, 0x0e, 0x37, 0x38,
	0x45, 0x1b, 0x50, 0x9b, 0x64, 0x1c, 0x9a, 0x9d, 0x3a, 0x2b, 0xdc, 0xeb, 0xdb, 0xc2, 0x79, 0xa8,
	0x3e, 0x55, 0x8c, 0xaf, 0x0a, 0xa0, 0x1c, 0x14, 0xa7, 0x89, 0x2c, 0x68, 0xf0, 0xc3, 0x1c, 0xab,
	0xdd, 0x05, 0x56, 0x3c, 0xc2, 0xcc, 0xe2, 0x04, 0xb7, 0x59, 0x9e, 0x7e, 0x04, 0xff, 0xe4, 0x2f,
	0x4b, 0x18, 0xae, 0xcd, 0x33, 0x6c, 0xcc, 0x33, 0xfb, 0xae, 0xc0, 0x92, 0x45, 0x02, 0x8a, 0x3f,
	0x52, 0xb4, 0x0e, 0xf5, 0x0b, 0xe2, 0x5e, 0x9d, 0x76, 0x65, 0xaa, 0xb4, 0x90, 0x06, 0x4b, 0x17,
	0xc4, 0x3d, 0x77, 0xc6, 0xd3, 0xfc, 0xa9, 0x89, 0x36, 0xa0, 0xc1, 0xbe, 0x71, 0xe8, 0x0c, 0xb1,
	0x56, 0xe1, 0x77, 0x33, 0x07, 0xcb, 0xb3, 0xfc, 0x24, 0xa6, 0x38, 0xd2, 0xaa, 0x22, 0x4f, 0x9a,
	0x2c, 0xef, 0x12, 0x47, 0x13, 0x6f, 0x88, 0x4f, 0xbb, 0x5a, 0x4d, 0xe4, 0x65, 0x0e, 0xd4, 0x86,
	0x65, 0x2b, 0x89, 0x29, 0x19, 0xf7, 0xfa, 0x9a, 0xcb, 0xbb, 0xb2, 0x5a, 0x32, 0x2b, 0x3b, 0x0b,
	0x32, 0x7e, 0xa9, 0xd0, 0xea, 0x62, 0x8a, 0x87, 0x6c, 0x63, 0xec, 0xc4, 0xc7, 0x08, 0x41, 0x95,
	0xf3, 0x15, 0x42, 0xf8, 0x99, 0xc9, 0x3b, 0x23, 0x6e, 0xe2, 0x4f, 0x55, 0x48, 0x0b, 0xe9, 0xb0,
	0x6c, 0x39, 0x14, 0x8f, 0x48, 0x94, 0x4a, 0x0d, 0x99, 0x8d, 0xb6, 0xa1, 0xd9, 0xc5, 0xf1, 0x30,
	0xf2, 0x42, 0x56, 0x5a, 0xca, 0x98, 0x77, 0xb1, 0xec, 0x4b, 0x3c, 0xc1, 0x91, 0x47, 0x53, 0xae,
	0xa4, 0x65, 0x67, 0x36, 0x7a, 0x09, 0xad, 0x1c, 0x69, 0xad, 0xce, 0xd5, 0xec, 0x30, 0x35, 0x39,
	0xbe, 0x79, 0x6d, 0x62, 0xc4, 0xf9, 0xd4, 0x3b, 0x37, 0x45, 0x7f, 0x5b, 0x58, 0xb9, 0xdb, 0x76,
	0xe3, 0x20, 0xbf, 0xbd, 0xeb, 0xe5, 0x0b, 0x38, 0xbf, 0x33, 0xaf, 0x61, 0x89, 0x91, 0x66, 0xbf,
	0xdf, 0x5f, 0xea, 0xb3, 0xf1, 0x4d, 0x81, 0xd5, 0x4b, 0x1c, 0xb8, 0xe7, 0x84, 0x7a, 0xd7, 0xde,
	0x90, 0xff, 0xfa, 0x36, 0xfe, 0x80, 0x76, 0x33, 0x28, 0x0e, 0xd1, 0xec, 0x34, 0x19, 0x3d, 0xe9,
	0xb2, 0x33, 0x1a, 0x8f, 0xa0, 0xc5, 0x33, 0x53, 0xb9, 0xca, 0x52, 0x0b, 0x0f, 0x96, 0x2e, 0x3b,
	0x1f, 0xc1, 0x56, 0xf0, 0x8d, 0x37, 0xc6, 0x31, 0x75, 0xc6, 0x21, 0xa7, 0x53, 0xb1, 0x67, 0x0e,
	0xa6, 0xeb, 0x8a, 0xfd, 0x08, 0x6c, 0xe0, 0x55, 0x9b, 0x9f, 0x8d, 0x23, 0x58, 0x3d, 0x76, 0xdd,
	0xdc, 0xdc, 0x04, 0xc5, 0x2a, 0x3b, 0x4a, 0x7e, 0xff, 0x2d, 0xcc, 0xd6, 0xe6, 0xd7, 0x06, 0x85,
	0xff, 0x6d, 0x1c, 0x63, 0x3a, 0x95, 0xcc, 0x9c, 0x31, 0xcb, 0x9f, 0xb5, 0x4b, 0xb9, 0xb5, 0x5d,
	0x6a, 0x61, 0x2d, 0x1f, 0x42, 0x8d, 0xe7, 0x6b, 0x15, 0xbe, 0x09, 0x25, 0xa0, 0xe2, 0xbe, 0xf3,
	0x5b, 0x85, 0xcd, 0x13, 0xf6, 0x0a, 0xc7, 0x16, 0x0e, 0x28, 0x8e, 0x2c, 0xe2, 0xfb, 0x22, 0x4a,
	0xfe, 0x6e, 0x68, 0x0c, 0x2b, 0xc5, 0xc6, 0xa3, 0x7b, 0xac, 0x5e, 0xc9, 0x38, 0xf4, 0x75, 0x53,
	0x3c, 0xd2, 0xe6, 0xf4, 0x05, 0x37, 0x4f, 0xd8, 0x0b, 0x6e, 0xec, 0x7d, 0xfa, 0xf1, 0xf3, 0x8b,
	0x6a, 0x18, 0x9b, 0x6d, 0xfe, 0xe4, 0x0f, 0x39, 0x56, 0x3b, 0x2e, 0x54, 0x38, 0x54, 0xf6, 0x19,
	0x5c, 0xb1, 0x89, 0x02, 0xae, 0xa4, 0xb5, 0x77, 0x84, 0x73, 0x0a, 0x15, 0x18, 0x5c, 0x0c, 0x68,
	0xb1, 0xeb, 0xe8, 0x3e, 0x5f, 0xa2, 0xb2, 0x69, 0xdc, 0x0a, 0xb9, 0xcf, 0x21, 0x77, 0x8c, 0xad,
	0x1c, 0x64, 0xb4, 0x50, 0xe3, 0x50, 0xd9, 0x7f, 0x5e, 0x7f, 0x57, 0x35, 0x9f, 0x85, 0x83, 0x41,
	0x9d, 0xd7, 0x78, 0xfc, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xfc, 0x7a, 0x8a, 0x08, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventsCenterCollectionServiceClient is the client API for EventsCenterCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsCenterCollectionServiceClient interface {
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如规则必须存在, 必须提供service信息或者提供podName/podUid用于服务端定位服务 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	AddDetectionRule(ctx context.Context, in *AddDetectionRuleReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	ResetCategoryRules(ctx context.Context, in *ResetCategoryRulesReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eventsCenterCollectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventsCenterCollectionServiceClient(cc *grpc.ClientConn) EventsCenterCollectionServiceClient {
	return &eventsCenterCollectionServiceClient{cc}
}

func (c *eventsCenterCollectionServiceClient) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterCollectionService/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterCollectionServiceClient) AddDetectionRule(ctx context.Context, in *AddDetectionRuleReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterCollectionService/AddDetectionRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterCollectionServiceClient) ResetCategoryRules(ctx context.Context, in *ResetCategoryRulesReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterCollectionService/ResetCategoryRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsCenterCollectionServiceServer is the server API for EventsCenterCollectionService service.
type EventsCenterCollectionServiceServer interface {
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如规则必须存在, 必须提供service信息或者提供podName/podUid用于服务端定位服务 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	SendNotification(context.Context, *SendNotificationReq) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	AddDetectionRule(context.Context, *AddDetectionRuleReq) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 customKV合法性校验(kv对必须提供英文版本) 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	ResetCategoryRules(context.Context, *ResetCategoryRulesReq) (*emptypb.Empty, error)
}

// UnimplementedEventsCenterCollectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventsCenterCollectionServiceServer struct {
}

func (*UnimplementedEventsCenterCollectionServiceServer) SendNotification(ctx context.Context, req *SendNotificationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (*UnimplementedEventsCenterCollectionServiceServer) AddDetectionRule(ctx context.Context, req *AddDetectionRuleReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDetectionRule not implemented")
}
func (*UnimplementedEventsCenterCollectionServiceServer) ResetCategoryRules(ctx context.Context, req *ResetCategoryRulesReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetCategoryRules not implemented")
}

func RegisterEventsCenterCollectionServiceServer(s *grpc.Server, srv EventsCenterCollectionServiceServer) {
	s.RegisterService(&_EventsCenterCollectionService_serviceDesc, srv)
}

func _EventsCenterCollectionService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterCollectionServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterCollectionService/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterCollectionServiceServer).SendNotification(ctx, req.(*SendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterCollectionService_AddDetectionRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDetectionRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterCollectionServiceServer).AddDetectionRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterCollectionService/AddDetectionRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterCollectionServiceServer).AddDetectionRule(ctx, req.(*AddDetectionRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterCollectionService_ResetCategoryRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCategoryRulesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterCollectionServiceServer).ResetCategoryRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterCollectionService/ResetCategoryRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterCollectionServiceServer).ResetCategoryRules(ctx, req.(*ResetCategoryRulesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventsCenterCollectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventsCenterCollectionService",
	HandlerType: (*EventsCenterCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _EventsCenterCollectionService_SendNotification_Handler,
		},
		{
			MethodName: "AddDetectionRule",
			Handler:    _EventsCenterCollectionService_AddDetectionRule_Handler,
		},
		{
			MethodName: "ResetCategoryRules",
			Handler:    _EventsCenterCollectionService_ResetCategoryRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
