// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.biz.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortBy int32

const (
	SortBy_DefaultBy SortBy = 0
	SortBy_Timestamp SortBy = 1
	SortBy_Severity  SortBy = 2
)

var SortBy_name = map[int32]string{
	0: "DefaultBy",
	1: "Timestamp",
	2: "Severity",
}

var SortBy_value = map[string]int32{
	"DefaultBy": 0,
	"Timestamp": 1,
	"Severity":  2,
}

func (x SortBy) String() string {
	return proto.EnumName(SortBy_name, int32(x))
}

func (SortBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{0}
}

type SortOrder int32

const (
	SortOrder_DefaultOrder SortOrder = 0
	SortOrder_Desc         SortOrder = 1
	SortOrder_Asc          SortOrder = 2
)

var SortOrder_name = map[int32]string{
	0: "DefaultOrder",
	1: "Desc",
	2: "Asc",
}

var SortOrder_value = map[string]int32{
	"DefaultOrder": 0,
	"Desc":         1,
	"Asc":          2,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{1}
}

type EventKind int32

const (
	EventKind_Any                        EventKind = 0
	EventKind_ReverseShellAttack         EventKind = 1
	EventKind_ComplianceCheck            EventKind = 2
	EventKind_VulnerabilityExploitAttack EventKind = 3
	EventKind_DriftPrevention            EventKind = 4
	EventKind_SeccompProfile             EventKind = 5
	EventKind_Attck                      EventKind = 6
)

var EventKind_name = map[int32]string{
	0: "Any",
	1: "ReverseShellAttack",
	2: "ComplianceCheck",
	3: "VulnerabilityExploitAttack",
	4: "DriftPrevention",
	5: "SeccompProfile",
	6: "Attck",
}

var EventKind_value = map[string]int32{
	"Any":                        0,
	"ReverseShellAttack":         1,
	"ComplianceCheck":            2,
	"VulnerabilityExploitAttack": 3,
	"DriftPrevention":            4,
	"SeccompProfile":             5,
	"Attck":                      6,
}

func (x EventKind) String() string {
	return proto.EnumName(EventKind_name, int32(x))
}

func (EventKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{2}
}

type CheckEventUpdateReq struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEventUpdateReq) Reset()         { *m = CheckEventUpdateReq{} }
func (m *CheckEventUpdateReq) String() string { return proto.CompactTextString(m) }
func (*CheckEventUpdateReq) ProtoMessage()    {}
func (*CheckEventUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{0}
}

func (m *CheckEventUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEventUpdateReq.Unmarshal(m, b)
}
func (m *CheckEventUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEventUpdateReq.Marshal(b, m, deterministic)
}
func (m *CheckEventUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEventUpdateReq.Merge(m, src)
}
func (m *CheckEventUpdateReq) XXX_Size() int {
	return xxx_messageInfo_CheckEventUpdateReq.Size(m)
}
func (m *CheckEventUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEventUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEventUpdateReq proto.InternalMessageInfo

func (m *CheckEventUpdateReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CheckEventUpdateRsp struct {
	HasUpdates           bool     `protobuf:"varint,1,opt,name=HasUpdates,proto3" json:"HasUpdates,omitempty"`
	NewestTimestamp      int64    `protobuf:"varint,2,opt,name=NewestTimestamp,proto3" json:"NewestTimestamp,omitempty"`
	UpdateNumStr         string   `protobuf:"bytes,3,opt,name=UpdateNumStr,proto3" json:"UpdateNumStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEventUpdateRsp) Reset()         { *m = CheckEventUpdateRsp{} }
func (m *CheckEventUpdateRsp) String() string { return proto.CompactTextString(m) }
func (*CheckEventUpdateRsp) ProtoMessage()    {}
func (*CheckEventUpdateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{1}
}

func (m *CheckEventUpdateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEventUpdateRsp.Unmarshal(m, b)
}
func (m *CheckEventUpdateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEventUpdateRsp.Marshal(b, m, deterministic)
}
func (m *CheckEventUpdateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEventUpdateRsp.Merge(m, src)
}
func (m *CheckEventUpdateRsp) XXX_Size() int {
	return xxx_messageInfo_CheckEventUpdateRsp.Size(m)
}
func (m *CheckEventUpdateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEventUpdateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEventUpdateRsp proto.InternalMessageInfo

func (m *CheckEventUpdateRsp) GetHasUpdates() bool {
	if m != nil {
		return m.HasUpdates
	}
	return false
}

func (m *CheckEventUpdateRsp) GetNewestTimestamp() int64 {
	if m != nil {
		return m.NewestTimestamp
	}
	return 0
}

func (m *CheckEventUpdateRsp) GetUpdateNumStr() string {
	if m != nil {
		return m.UpdateNumStr
	}
	return ""
}

type GetEventsReq struct {
	Offset               int32     `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit                int32     `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy               SortBy    `protobuf:"varint,3,opt,name=SortBy,proto3,enum=pb.SortBy" json:"SortBy,omitempty"`
	SortOrder            SortOrder `protobuf:"varint,4,opt,name=SortOrder,proto3,enum=pb.SortOrder" json:"SortOrder,omitempty"`
	Kind                 EventKind `protobuf:"varint,5,opt,name=Kind,proto3,enum=pb.EventKind" json:"Kind,omitempty"`
	Lang                 string    `protobuf:"bytes,6,opt,name=Lang,proto3" json:"Lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetEventsReq) Reset()         { *m = GetEventsReq{} }
func (m *GetEventsReq) String() string { return proto.CompactTextString(m) }
func (*GetEventsReq) ProtoMessage()    {}
func (*GetEventsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{2}
}

func (m *GetEventsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsReq.Unmarshal(m, b)
}
func (m *GetEventsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsReq.Marshal(b, m, deterministic)
}
func (m *GetEventsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsReq.Merge(m, src)
}
func (m *GetEventsReq) XXX_Size() int {
	return xxx_messageInfo_GetEventsReq.Size(m)
}
func (m *GetEventsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsReq proto.InternalMessageInfo

func (m *GetEventsReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetEventsReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetEventsReq) GetSortBy() SortBy {
	if m != nil {
		return m.SortBy
	}
	return SortBy_DefaultBy
}

func (m *GetEventsReq) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_DefaultOrder
}

func (m *GetEventsReq) GetKind() EventKind {
	if m != nil {
		return m.Kind
	}
	return EventKind_Any
}

func (m *GetEventsReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type History struct {
	UUID                 uint64            `protobuf:"varint,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PodUID               string            `protobuf:"bytes,2,opt,name=PodUID,proto3" json:"PodUID,omitempty"`
	PodName              string            `protobuf:"bytes,3,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Timestamp            int64             `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	CustomKV             map[string]string `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{3}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetUUID() uint64 {
	if m != nil {
		return m.UUID
	}
	return 0
}

func (m *History) GetPodUID() string {
	if m != nil {
		return m.PodUID
	}
	return ""
}

func (m *History) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *History) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *History) GetCustomKV() map[string]string {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type Rule struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Module               string            `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category             string            `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Description          string            `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Severity             uint32            `protobuf:"varint,6,opt,name=Severity,proto3" json:"Severity,omitempty"`
	DisplayAdapter       map[string]string `protobuf:"bytes,7,rep,name=DisplayAdapter,proto3" json:"DisplayAdapter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomKV             map[string]string `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{4}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Rule) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Rule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Rule) GetSeverity() uint32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *Rule) GetDisplayAdapter() map[string]string {
	if m != nil {
		return m.DisplayAdapter
	}
	return nil
}

func (m *Rule) GetCustomKV() map[string]string {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type Event struct {
	ID                   int32      `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cluster              string     `protobuf:"bytes,2,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Namespace            string     `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	NodeType             string     `protobuf:"bytes,4,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeKey              string     `protobuf:"bytes,5,opt,name=NodeKey,proto3" json:"NodeKey,omitempty"`
	Rule                 *Rule      `protobuf:"bytes,6,opt,name=Rule,proto3" json:"Rule,omitempty"`
	History              []*History `protobuf:"bytes,7,rep,name=History,proto3" json:"History,omitempty"`
	Timestamp            int64      `protobuf:"varint,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{5}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Event) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Event) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Event) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *Event) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *Event) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *Event) GetHistory() []*History {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetEventsRsp struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRsp) Reset()         { *m = GetEventsRsp{} }
func (m *GetEventsRsp) String() string { return proto.CompactTextString(m) }
func (*GetEventsRsp) ProtoMessage()    {}
func (*GetEventsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{6}
}

func (m *GetEventsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRsp.Unmarshal(m, b)
}
func (m *GetEventsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRsp.Marshal(b, m, deterministic)
}
func (m *GetEventsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRsp.Merge(m, src)
}
func (m *GetEventsRsp) XXX_Size() int {
	return xxx_messageInfo_GetEventsRsp.Size(m)
}
func (m *GetEventsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRsp proto.InternalMessageInfo

func (m *GetEventsRsp) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.SortBy", SortBy_name, SortBy_value)
	proto.RegisterEnum("pb.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterEnum("pb.EventKind", EventKind_name, EventKind_value)
	proto.RegisterType((*CheckEventUpdateReq)(nil), "pb.CheckEventUpdateReq")
	proto.RegisterType((*CheckEventUpdateRsp)(nil), "pb.CheckEventUpdateRsp")
	proto.RegisterType((*GetEventsReq)(nil), "pb.GetEventsReq")
	proto.RegisterType((*History)(nil), "pb.History")
	proto.RegisterMapType((map[string]string)(nil), "pb.History.CustomKVEntry")
	proto.RegisterType((*Rule)(nil), "pb.Rule")
	proto.RegisterMapType((map[string]string)(nil), "pb.Rule.CustomKVEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.Rule.DisplayAdapterEntry")
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*GetEventsRsp)(nil), "pb.GetEventsRsp")
}

func init() { proto.RegisterFile("event.biz.proto", fileDescriptor_c82ed24bf2a8c602) }

var fileDescriptor_c82ed24bf2a8c602 = []byte{
	// 829 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xde, 0x19, 0x8f, 0x1d, 0x4f, 0xe5, 0x6f, 0x54, 0x41, 0x61, 0xb0, 0xa2, 0x55, 0xd6, 0x12,
	0x52, 0x14, 0x24, 0x03, 0x5e, 0x90, 0x10, 0x7b, 0x72, 0xec, 0x88, 0x45, 0x59, 0xb2, 0x51, 0x7b,
	0xb3, 0x07, 0x6e, 0xe3, 0x99, 0xf2, 0x6e, 0x2b, 0xe3, 0x99, 0xa6, 0xbb, 0x1d, 0x98, 0x5c, 0x91,
	0xb8, 0x72, 0xe2, 0x8d, 0x78, 0x11, 0x6e, 0x3c, 0x06, 0xea, 0x9e, 0x1f, 0xff, 0x10, 0x0e, 0x68,
	0x6f, 0xfd, 0x55, 0xf5, 0x57, 0x53, 0xf5, 0x55, 0x75, 0x0d, 0x1c, 0xd2, 0x3d, 0x65, 0x7a, 0x30,
	0xe3, 0x0f, 0x03, 0x21, 0x73, 0x9d, 0xa3, 0x2b, 0x66, 0xfd, 0xe7, 0x70, 0x34, 0x7e, 0x4f, 0xf1,
	0xdd, 0xa5, 0xf1, 0xdd, 0x8a, 0x24, 0xd2, 0xc4, 0xe8, 0x27, 0x3c, 0x01, 0xff, 0x0d, 0x5f, 0x90,
	0xd2, 0xd1, 0x42, 0x84, 0xce, 0xa9, 0x73, 0xd6, 0x62, 0x2b, 0x43, 0xff, 0x57, 0xe7, 0x11, 0x96,
	0x12, 0xf8, 0x14, 0xe0, 0x65, 0xa4, 0x4a, 0xac, 0x2c, 0xad, 0xcb, 0xd6, 0x2c, 0x78, 0x06, 0x87,
	0xd7, 0xf4, 0x33, 0x29, 0xbd, 0x8a, 0xed, 0xda, 0xd8, 0xdb, 0x66, 0xec, 0xc3, 0x5e, 0x49, 0xba,
	0x5e, 0x2e, 0xa6, 0x5a, 0x86, 0xad, 0x53, 0xe7, 0xcc, 0x67, 0x1b, 0xb6, 0xfe, 0x9f, 0x0e, 0xec,
	0x7d, 0x47, 0xda, 0xe6, 0xa0, 0x4c, 0xd2, 0xc7, 0xd0, 0x79, 0x3d, 0x9f, 0x2b, 0xd2, 0xf6, 0xd3,
	0x6d, 0x56, 0x21, 0xfc, 0x08, 0xda, 0xaf, 0xf8, 0x82, 0x6b, 0xfb, 0xb1, 0x36, 0x2b, 0x01, 0xf6,
	0xa1, 0x33, 0xcd, 0xa5, 0xbe, 0x28, 0x6c, 0xf0, 0x83, 0x21, 0x0c, 0xc4, 0x6c, 0x50, 0x5a, 0x58,
	0xe5, 0xc1, 0xcf, 0xc0, 0x37, 0xa7, 0xd7, 0x32, 0x21, 0x19, 0x7a, 0xf6, 0xda, 0x7e, 0x7d, 0xcd,
	0x1a, 0xd9, 0xca, 0x8f, 0xcf, 0xc0, 0xbb, 0xe2, 0x59, 0x12, 0xb6, 0x57, 0xf7, 0x6c, 0x6e, 0xc6,
	0xc8, 0xac, 0x0b, 0x11, 0xbc, 0x57, 0x51, 0xf6, 0x2e, 0xec, 0xd8, 0x72, 0xec, 0xb9, 0xff, 0x97,
	0x03, 0x3b, 0x2f, 0xb9, 0xd2, 0xb9, 0x2c, 0x8c, 0xff, 0xf6, 0xf6, 0xfb, 0x89, 0xcd, 0xdf, 0x63,
	0xf6, 0x6c, 0xaa, 0xba, 0xc9, 0x13, 0x63, 0x75, 0x2d, 0xab, 0x42, 0x18, 0xc2, 0xce, 0x4d, 0x9e,
	0x5c, 0x47, 0x0b, 0xaa, 0xd4, 0xa9, 0xe1, 0x66, 0xf3, 0xbc, 0xad, 0xe6, 0xe1, 0xd7, 0xd0, 0x1d,
	0x2f, 0x95, 0xce, 0x17, 0x57, 0x6f, 0xc3, 0xe4, 0xb4, 0x75, 0xb6, 0x3b, 0xfc, 0xc4, 0xa4, 0x5a,
	0xa5, 0x30, 0xa8, 0x7d, 0x97, 0x99, 0x96, 0x05, 0x6b, 0xae, 0xf6, 0x5e, 0xc0, 0xfe, 0x86, 0x0b,
	0x03, 0x68, 0xdd, 0x51, 0x61, 0x53, 0xf5, 0x99, 0x39, 0x1a, 0x9d, 0xef, 0xa3, 0x74, 0x49, 0x55,
	0xa2, 0x25, 0xf8, 0xd6, 0xfd, 0xc6, 0xe9, 0xff, 0xd6, 0x02, 0x8f, 0x2d, 0x53, 0x32, 0x05, 0xda,
	0x8c, 0x4b, 0x96, 0x3d, 0x9b, 0x02, 0x7f, 0xc8, 0x93, 0x65, 0x5a, 0xf3, 0x2a, 0x84, 0x3d, 0xe8,
	0x8e, 0x23, 0x4d, 0xef, 0x72, 0x59, 0x54, 0x15, 0x36, 0x18, 0x4f, 0x61, 0x77, 0x42, 0x2a, 0x96,
	0x5c, 0x68, 0x9e, 0x67, 0xb6, 0x48, 0x9f, 0xad, 0x9b, 0x0c, 0x7b, 0x4a, 0xf7, 0x24, 0xb9, 0x2e,
	0xac, 0xdc, 0xfb, 0xac, 0xc1, 0x38, 0x81, 0x83, 0x09, 0x57, 0x22, 0x8d, 0x8a, 0x51, 0x12, 0x09,
	0x4d, 0x32, 0xdc, 0xb1, 0x42, 0x9c, 0x18, 0x21, 0x4c, 0x9e, 0x83, 0x4d, 0x77, 0xa9, 0xc5, 0x16,
	0x07, 0x87, 0xff, 0x12, 0xf2, 0xb8, 0xe1, 0xff, 0x97, 0x8a, 0x23, 0x38, 0x7a, 0x24, 0xf4, 0xff,
	0xd1, 0xf2, 0xc3, 0x1a, 0xf1, 0xb7, 0x03, 0x6d, 0x3b, 0x94, 0x78, 0x00, 0x6e, 0x35, 0x68, 0x6d,
	0xe6, 0x96, 0xe3, 0x34, 0x4e, 0x97, 0xca, 0x88, 0x51, 0xb2, 0x6a, 0x68, 0xc6, 0xc9, 0xf4, 0x49,
	0x89, 0x28, 0xae, 0x47, 0x6d, 0x65, 0x30, 0x3a, 0x5f, 0xe7, 0x09, 0xbd, 0x29, 0x04, 0x55, 0x6d,
	0x68, 0xb0, 0x89, 0x69, 0xce, 0x57, 0x54, 0xd8, 0x47, 0xe1, 0xb3, 0x1a, 0xe2, 0x49, 0x39, 0x0f,
	0xb6, 0x33, 0xbb, 0xc3, 0x6e, 0xad, 0x1b, 0x2b, 0xa7, 0xe4, 0xd3, 0xe6, 0x45, 0x54, 0x8d, 0xd9,
	0x5d, 0x9b, 0x50, 0xd6, 0xbc, 0x96, 0x8d, 0x39, 0xef, 0x6e, 0x2f, 0xa9, 0x2f, 0xd7, 0xb7, 0x83,
	0x12, 0xf8, 0x0c, 0x3a, 0x25, 0x08, 0x1d, 0x1b, 0xd3, 0x6f, 0x1e, 0x28, 0xab, 0x1c, 0xe7, 0x5f,
	0xd5, 0x2b, 0x01, 0xf7, 0xc1, 0x9f, 0xd0, 0x3c, 0x5a, 0xa6, 0xfa, 0xa2, 0x08, 0x9e, 0x18, 0xd8,
	0x04, 0x0e, 0x1c, 0xdc, 0x5b, 0xcd, 0x56, 0xe0, 0x9e, 0x7f, 0xb1, 0xb6, 0x24, 0x30, 0x80, 0xbd,
	0x8a, 0x68, 0x71, 0xf0, 0x04, 0xbb, 0xe0, 0x99, 0xb9, 0x0c, 0x1c, 0xdc, 0x81, 0xd6, 0x48, 0xc5,
	0x81, 0x7b, 0xfe, 0x87, 0x03, 0x7e, 0xb3, 0x1a, 0xac, 0x39, 0x33, 0x5f, 0x39, 0x06, 0x64, 0x26,
	0xac, 0xa2, 0xe9, 0x7b, 0x4a, 0xd3, 0x91, 0xd6, 0x51, 0x7c, 0x17, 0x38, 0x78, 0x04, 0x87, 0xe3,
	0x7c, 0x21, 0x52, 0x1e, 0x65, 0x31, 0xd9, 0xbd, 0x1b, 0xb8, 0xf8, 0x14, 0x7a, 0x6f, 0x97, 0x69,
	0x46, 0x32, 0x9a, 0xf1, 0x94, 0xeb, 0xe2, 0xf2, 0x17, 0x91, 0xe6, 0x5c, 0x57, 0xa4, 0x96, 0x21,
	0x4d, 0x24, 0x9f, 0xeb, 0x1b, 0x69, 0xd7, 0x3e, 0xcf, 0xb3, 0xc0, 0x43, 0x84, 0x83, 0x29, 0xc5,
	0x71, 0xbe, 0x10, 0x37, 0x32, 0x9f, 0xf3, 0x94, 0x82, 0x36, 0xfa, 0xd0, 0x1e, 0x69, 0x1d, 0xdf,
	0x05, 0x9d, 0xe1, 0xef, 0x0e, 0x1c, 0x97, 0x52, 0x8c, 0x29, 0xd3, 0x24, 0x2f, 0xf8, 0xc3, 0x94,
	0xe4, 0x3d, 0x8f, 0x09, 0x27, 0x10, 0x6c, 0x6f, 0x7c, 0xfc, 0xd8, 0x28, 0xf8, 0xc8, 0xdf, 0xa3,
	0xf7, 0xb8, 0x43, 0x09, 0xfc, 0x1c, 0xfc, 0xa6, 0x27, 0x18, 0x98, 0x5b, 0xeb, 0x0b, 0xbc, 0xb7,
	0x65, 0x51, 0xe2, 0xa2, 0xf3, 0xa3, 0x37, 0x78, 0x21, 0x66, 0xb3, 0x8e, 0xfd, 0x63, 0x3d, 0xff,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x38, 0x5e, 0xf8, 0xc4, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventsCenterBizServiceClient is the client API for EventsCenterBizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsCenterBizServiceClient interface {
	CheckEventUpdate(ctx context.Context, in *CheckEventUpdateReq, opts ...grpc.CallOption) (*CheckEventUpdateRsp, error)
	GetEvents(ctx context.Context, in *GetEventsReq, opts ...grpc.CallOption) (*GetEventsRsp, error)
}

type eventsCenterBizServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventsCenterBizServiceClient(cc *grpc.ClientConn) EventsCenterBizServiceClient {
	return &eventsCenterBizServiceClient{cc}
}

func (c *eventsCenterBizServiceClient) CheckEventUpdate(ctx context.Context, in *CheckEventUpdateReq, opts ...grpc.CallOption) (*CheckEventUpdateRsp, error) {
	out := new(CheckEventUpdateRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/CheckEventUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetEvents(ctx context.Context, in *GetEventsReq, opts ...grpc.CallOption) (*GetEventsRsp, error) {
	out := new(GetEventsRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsCenterBizServiceServer is the server API for EventsCenterBizService service.
type EventsCenterBizServiceServer interface {
	CheckEventUpdate(context.Context, *CheckEventUpdateReq) (*CheckEventUpdateRsp, error)
	GetEvents(context.Context, *GetEventsReq) (*GetEventsRsp, error)
}

// UnimplementedEventsCenterBizServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventsCenterBizServiceServer struct {
}

func (*UnimplementedEventsCenterBizServiceServer) CheckEventUpdate(ctx context.Context, req *CheckEventUpdateReq) (*CheckEventUpdateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEventUpdate not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetEvents(ctx context.Context, req *GetEventsReq) (*GetEventsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterEventsCenterBizServiceServer(s *grpc.Server, srv EventsCenterBizServiceServer) {
	s.RegisterService(&_EventsCenterBizService_serviceDesc, srv)
}

func _EventsCenterBizService_CheckEventUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEventUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).CheckEventUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/CheckEventUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).CheckEventUpdate(ctx, req.(*CheckEventUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetEvents(ctx, req.(*GetEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventsCenterBizService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventsCenterBizService",
	HandlerType: (*EventsCenterBizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckEventUpdate",
			Handler:    _EventsCenterBizService_CheckEventUpdate_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _EventsCenterBizService_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.biz.proto",
}
