// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.14.0
// source: event.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type MultiLanguageKV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KVHash map[string]*KV `protobuf:"bytes,1,rep,name=KVHash,proto3" json:"KVHash,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MultiLanguageKV) Reset() {
	*x = MultiLanguageKV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiLanguageKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiLanguageKV) ProtoMessage() {}

func (x *MultiLanguageKV) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiLanguageKV.ProtoReflect.Descriptor instead.
func (*MultiLanguageKV) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *MultiLanguageKV) GetKVHash() map[string]*KV {
	if x != nil {
		return x.KVHash
	}
	return nil
}

type MultiLanguageValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueHash map[string]string `protobuf:"bytes,1,rep,name=ValueHash,proto3" json:"ValueHash,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MultiLanguageValue) Reset() {
	*x = MultiLanguageValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiLanguageValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiLanguageValue) ProtoMessage() {}

func (x *MultiLanguageValue) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiLanguageValue.ProtoReflect.Descriptor instead.
func (*MultiLanguageValue) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *MultiLanguageValue) GetValueHash() map[string]string {
	if x != nil {
		return x.ValueHash
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodUID    string             `protobuf:"bytes,1,opt,name=PodUID,proto3" json:"PodUID,omitempty"`
	PodName   string             `protobuf:"bytes,2,opt,name=PodName,proto3" json:"PodName,omitempty"` // podName和podUID 优先使用podUID 没有podUID在考虑podName  cluster + podUID 或者 cluster + namespace + podName 唯一标识一个pod
	Namespace string             `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Cluster   string             `protobuf:"bytes,4,opt,name=Cluster,proto3" json:"Cluster,omitempty"`     // 必传
	ServiceID string             `protobuf:"bytes,5,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"` // 和namespace一起作为可选项 用于标识service信息
	CustomKV  []*MultiLanguageKV `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty"` // 自定义kv 包含多语言信息
}

func (x *Context) Reset() {
	*x = Context{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *Context) GetPodUID() string {
	if x != nil {
		return x.PodUID
	}
	return ""
}

func (x *Context) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Context) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Context) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Context) GetServiceID() string {
	if x != nil {
		return x.ServiceID
	}
	return ""
}

func (x *Context) GetCustomKV() []*MultiLanguageKV {
	if x != nil {
		return x.CustomKV
	}
	return nil
}

type DetectionRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                         `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // unique string
	Module        string                         `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category      string                         `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`                                                                                                   // Category + Module + Name uniquely identifies one Rule.
	Description   string                         `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`                                                                                             // optional
	Severity      uint32                         `protobuf:"varint,5,opt,name=Severity,proto3" json:"Severity,omitempty"`                                                                                                  // 0~10
	MultiLanguage map[string]*MultiLanguageValue `protobuf:"bytes,6,rep,name=MultiLanguage,proto3" json:"MultiLanguage,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // multi-language
	CustomKV      []*MultiLanguageKV             `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty"`                                                                                                 // 自定义kv 包含多语言信息
}

func (x *DetectionRule) Reset() {
	*x = DetectionRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionRule) ProtoMessage() {}

func (x *DetectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionRule.ProtoReflect.Descriptor instead.
func (*DetectionRule) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *DetectionRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetectionRule) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *DetectionRule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DetectionRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DetectionRule) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *DetectionRule) GetMultiLanguage() map[string]*MultiLanguageValue {
	if x != nil {
		return x.MultiLanguage
	}
	return nil
}

func (x *DetectionRule) GetCustomKV() []*MultiLanguageKV {
	if x != nil {
		return x.CustomKV
	}
	return nil
}

type RuleKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // unique string
	Module   string `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category string `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"` // Category + Module + Name uniquely identifies one Rule.
}

func (x *RuleKey) Reset() {
	*x = RuleKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleKey) ProtoMessage() {}

func (x *RuleKey) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleKey.ProtoReflect.Descriptor instead.
func (*RuleKey) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *RuleKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleKey) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RuleKey) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type SendNotificationReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleKey       *RuleKey `protobuf:"bytes,1,opt,name=RuleKey,proto3" json:"RuleKey,omitempty"`
	NotifyContext *Context `protobuf:"bytes,2,opt,name=NotifyContext,proto3" json:"NotifyContext,omitempty"`
	Timestamp     int64    `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UUID          uint64   `protobuf:"varint,4,opt,name=UUID,proto3" json:"UUID,omitempty"` // uniquely identifies one event
}

func (x *SendNotificationReq) Reset() {
	*x = SendNotificationReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationReq) ProtoMessage() {}

func (x *SendNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationReq.ProtoReflect.Descriptor instead.
func (*SendNotificationReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *SendNotificationReq) GetRuleKey() *RuleKey {
	if x != nil {
		return x.RuleKey
	}
	return nil
}

func (x *SendNotificationReq) GetNotifyContext() *Context {
	if x != nil {
		return x.NotifyContext
	}
	return nil
}

func (x *SendNotificationReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendNotificationReq) GetUUID() uint64 {
	if x != nil {
		return x.UUID
	}
	return 0
}

type AddDetectionRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule *DetectionRule `protobuf:"bytes,1,opt,name=Rule,proto3" json:"Rule,omitempty"`
}

func (x *AddDetectionRuleReq) Reset() {
	*x = AddDetectionRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDetectionRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDetectionRuleReq) ProtoMessage() {}

func (x *AddDetectionRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDetectionRuleReq.ProtoReflect.Descriptor instead.
func (*AddDetectionRuleReq) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *AddDetectionRuleReq) GetRule() *DetectionRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_event_proto protoreflect.FileDescriptor

var file_event_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x02,
	0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x0f, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x4b, 0x56, 0x12, 0x37,
	0x0a, 0x06, 0x4b, 0x56, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x4b, 0x56, 0x2e, 0x4b, 0x56, 0x48, 0x61, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x4b, 0x56, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x41, 0x0a, 0x0b, 0x4b, 0x56, 0x48, 0x61, 0x73,
	0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x97, 0x01, 0x0a, 0x12, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x43, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x61, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x3c, 0x0a, 0x0e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xc2, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x64, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x50, 0x6f, 0x64, 0x55, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x6f, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x2f, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x4b, 0x56, 0x18, 0x64, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x4b, 0x56, 0x52,
	0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4b, 0x56, 0x22, 0xec, 0x02, 0x0a, 0x0d, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74,
	0x79, 0x12, 0x4a, 0x0a, 0x0d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x2e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a,
	0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4b, 0x56, 0x18, 0x64, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x4b, 0x56, 0x52, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4b, 0x56, 0x1a, 0x58,
	0x0a, 0x12, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x51, 0x0a, 0x07, 0x52, 0x75, 0x6c, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0xa1, 0x01, 0x0a, 0x13,
	0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x07, 0x52, 0x75, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x07, 0x52, 0x75, 0x6c, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x0d, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x0d,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x3c, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x32, 0xfd, 0x01,
	0x0a, 0x1d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6d, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1d, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x6e, 0x64, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x01, 0x2a, 0x12, 0x6d,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75,
	0x6c, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x1d, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x64, 0x64, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6c, 0x65, 0x3a, 0x01, 0x2a, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData = file_event_proto_rawDesc
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_event_proto_rawDescData)
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_event_proto_goTypes = []interface{}{
	(*KV)(nil),                  // 0: pb.KV
	(*MultiLanguageKV)(nil),     // 1: pb.MultiLanguageKV
	(*MultiLanguageValue)(nil),  // 2: pb.MultiLanguageValue
	(*Context)(nil),             // 3: pb.Context
	(*DetectionRule)(nil),       // 4: pb.DetectionRule
	(*RuleKey)(nil),             // 5: pb.RuleKey
	(*SendNotificationReq)(nil), // 6: pb.SendNotificationReq
	(*AddDetectionRuleReq)(nil), // 7: pb.AddDetectionRuleReq
	nil,                         // 8: pb.MultiLanguageKV.KVHashEntry
	nil,                         // 9: pb.MultiLanguageValue.ValueHashEntry
	nil,                         // 10: pb.DetectionRule.MultiLanguageEntry
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_event_proto_depIdxs = []int32{
	8,  // 0: pb.MultiLanguageKV.KVHash:type_name -> pb.MultiLanguageKV.KVHashEntry
	9,  // 1: pb.MultiLanguageValue.ValueHash:type_name -> pb.MultiLanguageValue.ValueHashEntry
	1,  // 2: pb.Context.CustomKV:type_name -> pb.MultiLanguageKV
	10, // 3: pb.DetectionRule.MultiLanguage:type_name -> pb.DetectionRule.MultiLanguageEntry
	1,  // 4: pb.DetectionRule.CustomKV:type_name -> pb.MultiLanguageKV
	5,  // 5: pb.SendNotificationReq.RuleKey:type_name -> pb.RuleKey
	3,  // 6: pb.SendNotificationReq.NotifyContext:type_name -> pb.Context
	4,  // 7: pb.AddDetectionRuleReq.Rule:type_name -> pb.DetectionRule
	0,  // 8: pb.MultiLanguageKV.KVHashEntry.value:type_name -> pb.KV
	2,  // 9: pb.DetectionRule.MultiLanguageEntry.value:type_name -> pb.MultiLanguageValue
	6,  // 10: pb.EventsCenterCollectionService.SendNotification:input_type -> pb.SendNotificationReq
	7,  // 11: pb.EventsCenterCollectionService.AddDetectionRule:input_type -> pb.AddDetectionRuleReq
	11, // 12: pb.EventsCenterCollectionService.SendNotification:output_type -> google.protobuf.Empty
	11, // 13: pb.EventsCenterCollectionService.AddDetectionRule:output_type -> google.protobuf.Empty
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiLanguageKV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiLanguageValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Context); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectionRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendNotificationReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDetectionRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_rawDesc = nil
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventsCenterCollectionServiceClient is the client API for EventsCenterCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsCenterCollectionServiceClient interface {
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如规则必须存在, 参数长度不能超出限制 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	AddDetectionRule(ctx context.Context, in *AddDetectionRuleReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eventsCenterCollectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsCenterCollectionServiceClient(cc grpc.ClientConnInterface) EventsCenterCollectionServiceClient {
	return &eventsCenterCollectionServiceClient{cc}
}

func (c *eventsCenterCollectionServiceClient) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterCollectionService/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterCollectionServiceClient) AddDetectionRule(ctx context.Context, in *AddDetectionRuleReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterCollectionService/AddDetectionRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsCenterCollectionServiceServer is the server API for EventsCenterCollectionService service.
type EventsCenterCollectionServiceServer interface {
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如规则必须存在, 参数长度不能超出限制 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	SendNotification(context.Context, *SendNotificationReq) (*emptypb.Empty, error)
	// grpc错误码定义:
	// 1. 参数错误  完整性:必须带哪些参数 合法性: 例如severity范围是0-10, 参数长度不能超出限制 错误码:400 不可重试错误
	// 2. 服务器内部错误 错误码:500 可重试错误
	AddDetectionRule(context.Context, *AddDetectionRuleReq) (*emptypb.Empty, error)
}

// UnimplementedEventsCenterCollectionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventsCenterCollectionServiceServer struct {
}

func (*UnimplementedEventsCenterCollectionServiceServer) SendNotification(context.Context, *SendNotificationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (*UnimplementedEventsCenterCollectionServiceServer) AddDetectionRule(context.Context, *AddDetectionRuleReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDetectionRule not implemented")
}

func RegisterEventsCenterCollectionServiceServer(s *grpc.Server, srv EventsCenterCollectionServiceServer) {
	s.RegisterService(&_EventsCenterCollectionService_serviceDesc, srv)
}

func _EventsCenterCollectionService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterCollectionServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterCollectionService/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterCollectionServiceServer).SendNotification(ctx, req.(*SendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterCollectionService_AddDetectionRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDetectionRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterCollectionServiceServer).AddDetectionRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterCollectionService/AddDetectionRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterCollectionServiceServer).AddDetectionRule(ctx, req.(*AddDetectionRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventsCenterCollectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventsCenterCollectionService",
	HandlerType: (*EventsCenterCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotification",
			Handler:    _EventsCenterCollectionService_SendNotification_Handler,
		},
		{
			MethodName: "AddDetectionRule",
			Handler:    _EventsCenterCollectionService_AddDetectionRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
