// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.biz.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SortBy int32

const (
	SortBy_DefaultBy SortBy = 0
	SortBy_Timestamp SortBy = 1
	SortBy_Severity  SortBy = 2
)

var SortBy_name = map[int32]string{
	0: "DefaultBy",
	1: "Timestamp",
	2: "Severity",
}

var SortBy_value = map[string]int32{
	"DefaultBy": 0,
	"Timestamp": 1,
	"Severity":  2,
}

func (x SortBy) String() string {
	return proto.EnumName(SortBy_name, int32(x))
}

func (SortBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{0}
}

type SortOrder int32

const (
	SortOrder_DefaultOrder SortOrder = 0
	SortOrder_Desc         SortOrder = 1
	SortOrder_Asc          SortOrder = 2
)

var SortOrder_name = map[int32]string{
	0: "DefaultOrder",
	1: "Desc",
	2: "Asc",
}

var SortOrder_value = map[string]int32{
	"DefaultOrder": 0,
	"Desc":         1,
	"Asc":          2,
}

func (x SortOrder) String() string {
	return proto.EnumName(SortOrder_name, int32(x))
}

func (SortOrder) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{1}
}

type CheckEventUpdateReq struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEventUpdateReq) Reset()         { *m = CheckEventUpdateReq{} }
func (m *CheckEventUpdateReq) String() string { return proto.CompactTextString(m) }
func (*CheckEventUpdateReq) ProtoMessage()    {}
func (*CheckEventUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{0}
}

func (m *CheckEventUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEventUpdateReq.Unmarshal(m, b)
}
func (m *CheckEventUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEventUpdateReq.Marshal(b, m, deterministic)
}
func (m *CheckEventUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEventUpdateReq.Merge(m, src)
}
func (m *CheckEventUpdateReq) XXX_Size() int {
	return xxx_messageInfo_CheckEventUpdateReq.Size(m)
}
func (m *CheckEventUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEventUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEventUpdateReq proto.InternalMessageInfo

func (m *CheckEventUpdateReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CheckEventUpdateRsp struct {
	HasUpdates           bool     `protobuf:"varint,1,opt,name=HasUpdates,proto3" json:"HasUpdates,omitempty"`
	NewestTimestamp      int64    `protobuf:"varint,2,opt,name=NewestTimestamp,proto3" json:"NewestTimestamp,omitempty"`
	UpdateNumStr         string   `protobuf:"bytes,3,opt,name=UpdateNumStr,proto3" json:"UpdateNumStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckEventUpdateRsp) Reset()         { *m = CheckEventUpdateRsp{} }
func (m *CheckEventUpdateRsp) String() string { return proto.CompactTextString(m) }
func (*CheckEventUpdateRsp) ProtoMessage()    {}
func (*CheckEventUpdateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{1}
}

func (m *CheckEventUpdateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckEventUpdateRsp.Unmarshal(m, b)
}
func (m *CheckEventUpdateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckEventUpdateRsp.Marshal(b, m, deterministic)
}
func (m *CheckEventUpdateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckEventUpdateRsp.Merge(m, src)
}
func (m *CheckEventUpdateRsp) XXX_Size() int {
	return xxx_messageInfo_CheckEventUpdateRsp.Size(m)
}
func (m *CheckEventUpdateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckEventUpdateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckEventUpdateRsp proto.InternalMessageInfo

func (m *CheckEventUpdateRsp) GetHasUpdates() bool {
	if m != nil {
		return m.HasUpdates
	}
	return false
}

func (m *CheckEventUpdateRsp) GetNewestTimestamp() int64 {
	if m != nil {
		return m.NewestTimestamp
	}
	return 0
}

func (m *CheckEventUpdateRsp) GetUpdateNumStr() string {
	if m != nil {
		return m.UpdateNumStr
	}
	return ""
}

type GetAssociationEventsReq struct {
	Offset               int32     `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit                int32     `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy               SortBy    `protobuf:"varint,3,opt,name=SortBy,proto3,enum=pb.SortBy" json:"SortBy,omitempty"`
	SortOrder            SortOrder `protobuf:"varint,4,opt,name=SortOrder,proto3,enum=pb.SortOrder" json:"SortOrder,omitempty"`
	RuleFilter           string    `protobuf:"bytes,5,opt,name=RuleFilter,proto3" json:"RuleFilter,omitempty"`
	AssociationFilter    string    `protobuf:"bytes,6,opt,name=AssociationFilter,proto3" json:"AssociationFilter,omitempty"`
	Lang                 string    `protobuf:"bytes,7,opt,name=Lang,proto3" json:"Lang,omitempty"`
	ID                   int32     `protobuf:"varint,8,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAssociationEventsReq) Reset()         { *m = GetAssociationEventsReq{} }
func (m *GetAssociationEventsReq) String() string { return proto.CompactTextString(m) }
func (*GetAssociationEventsReq) ProtoMessage()    {}
func (*GetAssociationEventsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{2}
}

func (m *GetAssociationEventsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssociationEventsReq.Unmarshal(m, b)
}
func (m *GetAssociationEventsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssociationEventsReq.Marshal(b, m, deterministic)
}
func (m *GetAssociationEventsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssociationEventsReq.Merge(m, src)
}
func (m *GetAssociationEventsReq) XXX_Size() int {
	return xxx_messageInfo_GetAssociationEventsReq.Size(m)
}
func (m *GetAssociationEventsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssociationEventsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssociationEventsReq proto.InternalMessageInfo

func (m *GetAssociationEventsReq) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetAssociationEventsReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetAssociationEventsReq) GetSortBy() SortBy {
	if m != nil {
		return m.SortBy
	}
	return SortBy_DefaultBy
}

func (m *GetAssociationEventsReq) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_DefaultOrder
}

func (m *GetAssociationEventsReq) GetRuleFilter() string {
	if m != nil {
		return m.RuleFilter
	}
	return ""
}

func (m *GetAssociationEventsReq) GetAssociationFilter() string {
	if m != nil {
		return m.AssociationFilter
	}
	return ""
}

func (m *GetAssociationEventsReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *GetAssociationEventsReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type History struct {
	SignalID             string            `protobuf:"bytes,1,opt,name=SignalID,proto3" json:"SignalID,omitempty"`
	UUID                 uint64            `protobuf:"varint,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PodUID               string            `protobuf:"bytes,3,opt,name=PodUID,proto3" json:"PodUID,omitempty"`
	PodName              string            `protobuf:"bytes,4,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Timestamp            int64             `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	CustomKV             map[string]string `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{3}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetSignalID() string {
	if m != nil {
		return m.SignalID
	}
	return ""
}

func (m *History) GetUUID() uint64 {
	if m != nil {
		return m.UUID
	}
	return 0
}

func (m *History) GetPodUID() string {
	if m != nil {
		return m.PodUID
	}
	return ""
}

func (m *History) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *History) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *History) GetCustomKV() map[string]string {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type Rule struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Module               string            `protobuf:"bytes,2,opt,name=Module,proto3" json:"Module,omitempty"`
	Category             string            `protobuf:"bytes,3,opt,name=Category,proto3" json:"Category,omitempty"`
	Description          string            `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Severity             uint32            `protobuf:"varint,6,opt,name=Severity,proto3" json:"Severity,omitempty"`
	DisplayAdapter       map[string]string `protobuf:"bytes,7,rep,name=DisplayAdapter,proto3" json:"DisplayAdapter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomKV             map[string]string `protobuf:"bytes,100,rep,name=CustomKV,proto3" json:"CustomKV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Rule) Reset()         { *m = Rule{} }
func (m *Rule) String() string { return proto.CompactTextString(m) }
func (*Rule) ProtoMessage()    {}
func (*Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{4}
}

func (m *Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rule.Unmarshal(m, b)
}
func (m *Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rule.Marshal(b, m, deterministic)
}
func (m *Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rule.Merge(m, src)
}
func (m *Rule) XXX_Size() int {
	return xxx_messageInfo_Rule.Size(m)
}
func (m *Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_Rule proto.InternalMessageInfo

func (m *Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rule) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *Rule) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Rule) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Rule) GetSeverity() uint32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *Rule) GetDisplayAdapter() map[string]string {
	if m != nil {
		return m.DisplayAdapter
	}
	return nil
}

func (m *Rule) GetCustomKV() map[string]string {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

type TimeWindowEventDetail struct {
	Cluster              string     `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Namespace            string     `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	NodeType             string     `protobuf:"bytes,3,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeKey              string     `protobuf:"bytes,4,opt,name=NodeKey,proto3" json:"NodeKey,omitempty"`
	History              []*History `protobuf:"bytes,6,rep,name=History,proto3" json:"History,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TimeWindowEventDetail) Reset()         { *m = TimeWindowEventDetail{} }
func (m *TimeWindowEventDetail) String() string { return proto.CompactTextString(m) }
func (*TimeWindowEventDetail) ProtoMessage()    {}
func (*TimeWindowEventDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{5}
}

func (m *TimeWindowEventDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeWindowEventDetail.Unmarshal(m, b)
}
func (m *TimeWindowEventDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeWindowEventDetail.Marshal(b, m, deterministic)
}
func (m *TimeWindowEventDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeWindowEventDetail.Merge(m, src)
}
func (m *TimeWindowEventDetail) XXX_Size() int {
	return xxx_messageInfo_TimeWindowEventDetail.Size(m)
}
func (m *TimeWindowEventDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeWindowEventDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TimeWindowEventDetail proto.InternalMessageInfo

func (m *TimeWindowEventDetail) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *TimeWindowEventDetail) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *TimeWindowEventDetail) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *TimeWindowEventDetail) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *TimeWindowEventDetail) GetHistory() []*History {
	if m != nil {
		return m.History
	}
	return nil
}

type EventDetail struct {
	// Types that are valid to be assigned to Content:
	//	*EventDetail_TimeWindow
	Content              isEventDetail_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EventDetail) Reset()         { *m = EventDetail{} }
func (m *EventDetail) String() string { return proto.CompactTextString(m) }
func (*EventDetail) ProtoMessage()    {}
func (*EventDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{6}
}

func (m *EventDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventDetail.Unmarshal(m, b)
}
func (m *EventDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventDetail.Marshal(b, m, deterministic)
}
func (m *EventDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDetail.Merge(m, src)
}
func (m *EventDetail) XXX_Size() int {
	return xxx_messageInfo_EventDetail.Size(m)
}
func (m *EventDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDetail.DiscardUnknown(m)
}

var xxx_messageInfo_EventDetail proto.InternalMessageInfo

type isEventDetail_Content interface {
	isEventDetail_Content()
}

type EventDetail_TimeWindow struct {
	TimeWindow *TimeWindowEventDetail `protobuf:"bytes,1,opt,name=timeWindow,proto3,oneof"`
}

func (*EventDetail_TimeWindow) isEventDetail_Content() {}

func (m *EventDetail) GetContent() isEventDetail_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *EventDetail) GetTimeWindow() *TimeWindowEventDetail {
	if x, ok := m.GetContent().(*EventDetail_TimeWindow); ok {
		return x.TimeWindow
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*EventDetail) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*EventDetail_TimeWindow)(nil),
	}
}

type AssociationEvent struct {
	ID                   int32        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AssociationType      string       `protobuf:"bytes,2,opt,name=AssociationType,proto3" json:"AssociationType,omitempty"`
	Severity             uint32       `protobuf:"varint,3,opt,name=Severity,proto3" json:"Severity,omitempty"`
	Timestamp            int64        `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Detail               *EventDetail `protobuf:"bytes,5,opt,name=Detail,proto3" json:"Detail,omitempty"`
	Rule                 *Rule        `protobuf:"bytes,6,opt,name=Rule,proto3" json:"Rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AssociationEvent) Reset()         { *m = AssociationEvent{} }
func (m *AssociationEvent) String() string { return proto.CompactTextString(m) }
func (*AssociationEvent) ProtoMessage()    {}
func (*AssociationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{7}
}

func (m *AssociationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssociationEvent.Unmarshal(m, b)
}
func (m *AssociationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssociationEvent.Marshal(b, m, deterministic)
}
func (m *AssociationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssociationEvent.Merge(m, src)
}
func (m *AssociationEvent) XXX_Size() int {
	return xxx_messageInfo_AssociationEvent.Size(m)
}
func (m *AssociationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AssociationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AssociationEvent proto.InternalMessageInfo

func (m *AssociationEvent) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AssociationEvent) GetAssociationType() string {
	if m != nil {
		return m.AssociationType
	}
	return ""
}

func (m *AssociationEvent) GetSeverity() uint32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *AssociationEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AssociationEvent) GetDetail() *EventDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *AssociationEvent) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

type GetAssociationEventsRsp struct {
	Events               []*AssociationEvent `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAssociationEventsRsp) Reset()         { *m = GetAssociationEventsRsp{} }
func (m *GetAssociationEventsRsp) String() string { return proto.CompactTextString(m) }
func (*GetAssociationEventsRsp) ProtoMessage()    {}
func (*GetAssociationEventsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{8}
}

func (m *GetAssociationEventsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssociationEventsRsp.Unmarshal(m, b)
}
func (m *GetAssociationEventsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssociationEventsRsp.Marshal(b, m, deterministic)
}
func (m *GetAssociationEventsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssociationEventsRsp.Merge(m, src)
}
func (m *GetAssociationEventsRsp) XXX_Size() int {
	return xxx_messageInfo_GetAssociationEventsRsp.Size(m)
}
func (m *GetAssociationEventsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssociationEventsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssociationEventsRsp proto.InternalMessageInfo

func (m *GetAssociationEventsRsp) GetEvents() []*AssociationEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type GetSignalsReq struct {
	Filter               map[string]string `protobuf:"bytes,1,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OffsetSignalID       string            `protobuf:"bytes,2,opt,name=OffsetSignalID,proto3" json:"OffsetSignalID,omitempty"`
	SortOrder            SortOrder         `protobuf:"varint,3,opt,name=SortOrder,proto3,enum=pb.SortOrder" json:"SortOrder,omitempty"`
	Limit                uint32            `protobuf:"varint,4,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Lang                 string            `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	TimeFilter           *TimeFilter       `protobuf:"bytes,6,opt,name=TimeFilter,proto3" json:"TimeFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSignalsReq) Reset()         { *m = GetSignalsReq{} }
func (m *GetSignalsReq) String() string { return proto.CompactTextString(m) }
func (*GetSignalsReq) ProtoMessage()    {}
func (*GetSignalsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{9}
}

func (m *GetSignalsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSignalsReq.Unmarshal(m, b)
}
func (m *GetSignalsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSignalsReq.Marshal(b, m, deterministic)
}
func (m *GetSignalsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSignalsReq.Merge(m, src)
}
func (m *GetSignalsReq) XXX_Size() int {
	return xxx_messageInfo_GetSignalsReq.Size(m)
}
func (m *GetSignalsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSignalsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSignalsReq proto.InternalMessageInfo

func (m *GetSignalsReq) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GetSignalsReq) GetOffsetSignalID() string {
	if m != nil {
		return m.OffsetSignalID
	}
	return ""
}

func (m *GetSignalsReq) GetSortOrder() SortOrder {
	if m != nil {
		return m.SortOrder
	}
	return SortOrder_DefaultOrder
}

func (m *GetSignalsReq) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetSignalsReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *GetSignalsReq) GetTimeFilter() *TimeFilter {
	if m != nil {
		return m.TimeFilter
	}
	return nil
}

type TimeFilter struct {
	StartTimestamp       int64    `protobuf:"varint,1,opt,name=StartTimestamp,proto3" json:"StartTimestamp,omitempty"`
	EndTimestamp         int64    `protobuf:"varint,2,opt,name=EndTimestamp,proto3" json:"EndTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeFilter) Reset()         { *m = TimeFilter{} }
func (m *TimeFilter) String() string { return proto.CompactTextString(m) }
func (*TimeFilter) ProtoMessage()    {}
func (*TimeFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{10}
}

func (m *TimeFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeFilter.Unmarshal(m, b)
}
func (m *TimeFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeFilter.Marshal(b, m, deterministic)
}
func (m *TimeFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeFilter.Merge(m, src)
}
func (m *TimeFilter) XXX_Size() int {
	return xxx_messageInfo_TimeFilter.Size(m)
}
func (m *TimeFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TimeFilter proto.InternalMessageInfo

func (m *TimeFilter) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *TimeFilter) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

type GetSignalsRsp struct {
	Signals              []*Signal `protobuf:"bytes,1,rep,name=Signals,proto3" json:"Signals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSignalsRsp) Reset()         { *m = GetSignalsRsp{} }
func (m *GetSignalsRsp) String() string { return proto.CompactTextString(m) }
func (*GetSignalsRsp) ProtoMessage()    {}
func (*GetSignalsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{11}
}

func (m *GetSignalsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSignalsRsp.Unmarshal(m, b)
}
func (m *GetSignalsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSignalsRsp.Marshal(b, m, deterministic)
}
func (m *GetSignalsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSignalsRsp.Merge(m, src)
}
func (m *GetSignalsRsp) XXX_Size() int {
	return xxx_messageInfo_GetSignalsRsp.Size(m)
}
func (m *GetSignalsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSignalsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSignalsRsp proto.InternalMessageInfo

func (m *GetSignalsRsp) GetSignals() []*Signal {
	if m != nil {
		return m.Signals
	}
	return nil
}

type Signal struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UUID                 uint64            `protobuf:"varint,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Cluster              string            `protobuf:"bytes,3,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Namespace            string            `protobuf:"bytes,4,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	NodeType             string            `protobuf:"bytes,5,opt,name=NodeType,proto3" json:"NodeType,omitempty"`
	NodeKey              string            `protobuf:"bytes,6,opt,name=NodeKey,proto3" json:"NodeKey,omitempty"`
	Rule                 *Rule             `protobuf:"bytes,7,opt,name=Rule,proto3" json:"Rule,omitempty"`
	Severity             uint32            `protobuf:"varint,8,opt,name=Severity,proto3" json:"Severity,omitempty"`
	PodUID               string            `protobuf:"bytes,9,opt,name=PodUID,proto3" json:"PodUID,omitempty"`
	PodName              string            `protobuf:"bytes,10,opt,name=PodName,proto3" json:"PodName,omitempty"`
	CustomKV             map[string]string `protobuf:"bytes,11,rep,name=CustomKV,proto3" json:"CustomKV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            int64             `protobuf:"varint,12,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{12}
}

func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (m *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(m, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Signal) GetUUID() uint64 {
	if m != nil {
		return m.UUID
	}
	return 0
}

func (m *Signal) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *Signal) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Signal) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *Signal) GetNodeKey() string {
	if m != nil {
		return m.NodeKey
	}
	return ""
}

func (m *Signal) GetRule() *Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *Signal) GetSeverity() uint32 {
	if m != nil {
		return m.Severity
	}
	return 0
}

func (m *Signal) GetPodUID() string {
	if m != nil {
		return m.PodUID
	}
	return ""
}

func (m *Signal) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *Signal) GetCustomKV() map[string]string {
	if m != nil {
		return m.CustomKV
	}
	return nil
}

func (m *Signal) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetStatisticsReq struct {
	Days                 uint32   `protobuf:"varint,1,opt,name=Days,proto3" json:"Days,omitempty"`
	Hours                uint32   `protobuf:"varint,2,opt,name=Hours,proto3" json:"Hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatisticsReq) Reset()         { *m = GetStatisticsReq{} }
func (m *GetStatisticsReq) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsReq) ProtoMessage()    {}
func (*GetStatisticsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{13}
}

func (m *GetStatisticsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsReq.Unmarshal(m, b)
}
func (m *GetStatisticsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsReq.Marshal(b, m, deterministic)
}
func (m *GetStatisticsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsReq.Merge(m, src)
}
func (m *GetStatisticsReq) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsReq.Size(m)
}
func (m *GetStatisticsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsReq proto.InternalMessageInfo

func (m *GetStatisticsReq) GetDays() uint32 {
	if m != nil {
		return m.Days
	}
	return 0
}

func (m *GetStatisticsReq) GetHours() uint32 {
	if m != nil {
		return m.Hours
	}
	return 0
}

type GetStatisticsRsp struct {
	DayStatistics        []*StatisticItem `protobuf:"bytes,1,rep,name=DayStatistics,proto3" json:"DayStatistics,omitempty"`
	HourStatistics       []*StatisticItem `protobuf:"bytes,2,rep,name=HourStatistics,proto3" json:"HourStatistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetStatisticsRsp) Reset()         { *m = GetStatisticsRsp{} }
func (m *GetStatisticsRsp) String() string { return proto.CompactTextString(m) }
func (*GetStatisticsRsp) ProtoMessage()    {}
func (*GetStatisticsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{14}
}

func (m *GetStatisticsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatisticsRsp.Unmarshal(m, b)
}
func (m *GetStatisticsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatisticsRsp.Marshal(b, m, deterministic)
}
func (m *GetStatisticsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatisticsRsp.Merge(m, src)
}
func (m *GetStatisticsRsp) XXX_Size() int {
	return xxx_messageInfo_GetStatisticsRsp.Size(m)
}
func (m *GetStatisticsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatisticsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatisticsRsp proto.InternalMessageInfo

func (m *GetStatisticsRsp) GetDayStatistics() []*StatisticItem {
	if m != nil {
		return m.DayStatistics
	}
	return nil
}

func (m *GetStatisticsRsp) GetHourStatistics() []*StatisticItem {
	if m != nil {
		return m.HourStatistics
	}
	return nil
}

type StatisticItem struct {
	BeginTimestamp       int64    `protobuf:"varint,1,opt,name=BeginTimestamp,proto3" json:"BeginTimestamp,omitempty"`
	EndTimestamp         int64    `protobuf:"varint,2,opt,name=EndTimestamp,proto3" json:"EndTimestamp,omitempty"`
	Count                uint32   `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticItem) Reset()         { *m = StatisticItem{} }
func (m *StatisticItem) String() string { return proto.CompactTextString(m) }
func (*StatisticItem) ProtoMessage()    {}
func (*StatisticItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{15}
}

func (m *StatisticItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticItem.Unmarshal(m, b)
}
func (m *StatisticItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticItem.Marshal(b, m, deterministic)
}
func (m *StatisticItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticItem.Merge(m, src)
}
func (m *StatisticItem) XXX_Size() int {
	return xxx_messageInfo_StatisticItem.Size(m)
}
func (m *StatisticItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticItem.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticItem proto.InternalMessageInfo

func (m *StatisticItem) GetBeginTimestamp() int64 {
	if m != nil {
		return m.BeginTimestamp
	}
	return 0
}

func (m *StatisticItem) GetEndTimestamp() int64 {
	if m != nil {
		return m.EndTimestamp
	}
	return 0
}

func (m *StatisticItem) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetRuleCategoriesReq struct {
	Lang                 string   `protobuf:"bytes,1,opt,name=lang,proto3" json:"lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleCategoriesReq) Reset()         { *m = GetRuleCategoriesReq{} }
func (m *GetRuleCategoriesReq) String() string { return proto.CompactTextString(m) }
func (*GetRuleCategoriesReq) ProtoMessage()    {}
func (*GetRuleCategoriesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{16}
}

func (m *GetRuleCategoriesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleCategoriesReq.Unmarshal(m, b)
}
func (m *GetRuleCategoriesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleCategoriesReq.Marshal(b, m, deterministic)
}
func (m *GetRuleCategoriesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleCategoriesReq.Merge(m, src)
}
func (m *GetRuleCategoriesReq) XXX_Size() int {
	return xxx_messageInfo_GetRuleCategoriesReq.Size(m)
}
func (m *GetRuleCategoriesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleCategoriesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleCategoriesReq proto.InternalMessageInfo

func (m *GetRuleCategoriesReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type GetRuleCategoriesRsp struct {
	Modules              map[string]*RuleModuleInfo `protobuf:"bytes,1,rep,name=Modules,proto3" json:"Modules,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetRuleCategoriesRsp) Reset()         { *m = GetRuleCategoriesRsp{} }
func (m *GetRuleCategoriesRsp) String() string { return proto.CompactTextString(m) }
func (*GetRuleCategoriesRsp) ProtoMessage()    {}
func (*GetRuleCategoriesRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{17}
}

func (m *GetRuleCategoriesRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleCategoriesRsp.Unmarshal(m, b)
}
func (m *GetRuleCategoriesRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleCategoriesRsp.Marshal(b, m, deterministic)
}
func (m *GetRuleCategoriesRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleCategoriesRsp.Merge(m, src)
}
func (m *GetRuleCategoriesRsp) XXX_Size() int {
	return xxx_messageInfo_GetRuleCategoriesRsp.Size(m)
}
func (m *GetRuleCategoriesRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleCategoriesRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleCategoriesRsp proto.InternalMessageInfo

func (m *GetRuleCategoriesRsp) GetModules() map[string]*RuleModuleInfo {
	if m != nil {
		return m.Modules
	}
	return nil
}

type RuleModuleInfo struct {
	Name                 string                       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NameAdapter          string                       `protobuf:"bytes,2,opt,name=NameAdapter,proto3" json:"NameAdapter,omitempty"`
	Categories           map[string]*RuleCategoryInfo `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RuleModuleInfo) Reset()         { *m = RuleModuleInfo{} }
func (m *RuleModuleInfo) String() string { return proto.CompactTextString(m) }
func (*RuleModuleInfo) ProtoMessage()    {}
func (*RuleModuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{18}
}

func (m *RuleModuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleModuleInfo.Unmarshal(m, b)
}
func (m *RuleModuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleModuleInfo.Marshal(b, m, deterministic)
}
func (m *RuleModuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleModuleInfo.Merge(m, src)
}
func (m *RuleModuleInfo) XXX_Size() int {
	return xxx_messageInfo_RuleModuleInfo.Size(m)
}
func (m *RuleModuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleModuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RuleModuleInfo proto.InternalMessageInfo

func (m *RuleModuleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleModuleInfo) GetNameAdapter() string {
	if m != nil {
		return m.NameAdapter
	}
	return ""
}

func (m *RuleModuleInfo) GetCategories() map[string]*RuleCategoryInfo {
	if m != nil {
		return m.Categories
	}
	return nil
}

type RuleCategoryInfo struct {
	Name                 string                   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NameAdapter          string                   `protobuf:"bytes,2,opt,name=NameAdapter,proto3" json:"NameAdapter,omitempty"`
	Items                map[string]*RuleItemInfo `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RuleCategoryInfo) Reset()         { *m = RuleCategoryInfo{} }
func (m *RuleCategoryInfo) String() string { return proto.CompactTextString(m) }
func (*RuleCategoryInfo) ProtoMessage()    {}
func (*RuleCategoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{19}
}

func (m *RuleCategoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleCategoryInfo.Unmarshal(m, b)
}
func (m *RuleCategoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleCategoryInfo.Marshal(b, m, deterministic)
}
func (m *RuleCategoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleCategoryInfo.Merge(m, src)
}
func (m *RuleCategoryInfo) XXX_Size() int {
	return xxx_messageInfo_RuleCategoryInfo.Size(m)
}
func (m *RuleCategoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleCategoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RuleCategoryInfo proto.InternalMessageInfo

func (m *RuleCategoryInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleCategoryInfo) GetNameAdapter() string {
	if m != nil {
		return m.NameAdapter
	}
	return ""
}

func (m *RuleCategoryInfo) GetItems() map[string]*RuleItemInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type RuleItemInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NameAdapter          string   `protobuf:"bytes,2,opt,name=NameAdapter,proto3" json:"NameAdapter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleItemInfo) Reset()         { *m = RuleItemInfo{} }
func (m *RuleItemInfo) String() string { return proto.CompactTextString(m) }
func (*RuleItemInfo) ProtoMessage()    {}
func (*RuleItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{20}
}

func (m *RuleItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleItemInfo.Unmarshal(m, b)
}
func (m *RuleItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleItemInfo.Marshal(b, m, deterministic)
}
func (m *RuleItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleItemInfo.Merge(m, src)
}
func (m *RuleItemInfo) XXX_Size() int {
	return xxx_messageInfo_RuleItemInfo.Size(m)
}
func (m *RuleItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RuleItemInfo proto.InternalMessageInfo

func (m *RuleItemInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleItemInfo) GetNameAdapter() string {
	if m != nil {
		return m.NameAdapter
	}
	return ""
}

type GetATTCKPodProcessSignalTreeReq struct {
	Cluster              string   `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	PodName              string   `protobuf:"bytes,3,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lang                 string   `protobuf:"bytes,5,opt,name=Lang,proto3" json:"Lang,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetATTCKPodProcessSignalTreeReq) Reset()         { *m = GetATTCKPodProcessSignalTreeReq{} }
func (m *GetATTCKPodProcessSignalTreeReq) String() string { return proto.CompactTextString(m) }
func (*GetATTCKPodProcessSignalTreeReq) ProtoMessage()    {}
func (*GetATTCKPodProcessSignalTreeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{21}
}

func (m *GetATTCKPodProcessSignalTreeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeReq.Unmarshal(m, b)
}
func (m *GetATTCKPodProcessSignalTreeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeReq.Marshal(b, m, deterministic)
}
func (m *GetATTCKPodProcessSignalTreeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetATTCKPodProcessSignalTreeReq.Merge(m, src)
}
func (m *GetATTCKPodProcessSignalTreeReq) XXX_Size() int {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeReq.Size(m)
}
func (m *GetATTCKPodProcessSignalTreeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetATTCKPodProcessSignalTreeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetATTCKPodProcessSignalTreeReq proto.InternalMessageInfo

func (m *GetATTCKPodProcessSignalTreeReq) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *GetATTCKPodProcessSignalTreeReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetATTCKPodProcessSignalTreeReq) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *GetATTCKPodProcessSignalTreeReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetATTCKPodProcessSignalTreeReq) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type GetATTCKPodProcessSignalTreeRsp struct {
	Nodes                []*ProcessNode `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetATTCKPodProcessSignalTreeRsp) Reset()         { *m = GetATTCKPodProcessSignalTreeRsp{} }
func (m *GetATTCKPodProcessSignalTreeRsp) String() string { return proto.CompactTextString(m) }
func (*GetATTCKPodProcessSignalTreeRsp) ProtoMessage()    {}
func (*GetATTCKPodProcessSignalTreeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{22}
}

func (m *GetATTCKPodProcessSignalTreeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp.Unmarshal(m, b)
}
func (m *GetATTCKPodProcessSignalTreeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp.Marshal(b, m, deterministic)
}
func (m *GetATTCKPodProcessSignalTreeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp.Merge(m, src)
}
func (m *GetATTCKPodProcessSignalTreeRsp) XXX_Size() int {
	return xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp.Size(m)
}
func (m *GetATTCKPodProcessSignalTreeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetATTCKPodProcessSignalTreeRsp proto.InternalMessageInfo

func (m *GetATTCKPodProcessSignalTreeRsp) GetNodes() []*ProcessNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type ProcessNode struct {
	PID                  string         `protobuf:"bytes,1,opt,name=PID,proto3" json:"PID,omitempty"`
	PPID                 string         `protobuf:"bytes,2,opt,name=PPID,proto3" json:"PPID,omitempty"`
	ProcessName          string         `protobuf:"bytes,3,opt,name=ProcessName,proto3" json:"ProcessName,omitempty"`
	PProcessName         string         `protobuf:"bytes,4,opt,name=PProcessName,proto3" json:"PProcessName,omitempty"`
	Signals              []*Signal      `protobuf:"bytes,5,rep,name=Signals,proto3" json:"Signals,omitempty"`
	Children             []*ProcessNode `protobuf:"bytes,6,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ProcessNode) Reset()         { *m = ProcessNode{} }
func (m *ProcessNode) String() string { return proto.CompactTextString(m) }
func (*ProcessNode) ProtoMessage()    {}
func (*ProcessNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{23}
}

func (m *ProcessNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessNode.Unmarshal(m, b)
}
func (m *ProcessNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessNode.Marshal(b, m, deterministic)
}
func (m *ProcessNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessNode.Merge(m, src)
}
func (m *ProcessNode) XXX_Size() int {
	return xxx_messageInfo_ProcessNode.Size(m)
}
func (m *ProcessNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessNode.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessNode proto.InternalMessageInfo

func (m *ProcessNode) GetPID() string {
	if m != nil {
		return m.PID
	}
	return ""
}

func (m *ProcessNode) GetPPID() string {
	if m != nil {
		return m.PPID
	}
	return ""
}

func (m *ProcessNode) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *ProcessNode) GetPProcessName() string {
	if m != nil {
		return m.PProcessName
	}
	return ""
}

func (m *ProcessNode) GetSignals() []*Signal {
	if m != nil {
		return m.Signals
	}
	return nil
}

func (m *ProcessNode) GetChildren() []*ProcessNode {
	if m != nil {
		return m.Children
	}
	return nil
}

type GetNotifySettingsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifySettingsReq) Reset()         { *m = GetNotifySettingsReq{} }
func (m *GetNotifySettingsReq) String() string { return proto.CompactTextString(m) }
func (*GetNotifySettingsReq) ProtoMessage()    {}
func (*GetNotifySettingsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{24}
}

func (m *GetNotifySettingsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifySettingsReq.Unmarshal(m, b)
}
func (m *GetNotifySettingsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifySettingsReq.Marshal(b, m, deterministic)
}
func (m *GetNotifySettingsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifySettingsReq.Merge(m, src)
}
func (m *GetNotifySettingsReq) XXX_Size() int {
	return xxx_messageInfo_GetNotifySettingsReq.Size(m)
}
func (m *GetNotifySettingsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifySettingsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifySettingsReq proto.InternalMessageInfo

type GetNotifySettingsRsp struct {
	EmailNotification    bool     `protobuf:"varint,1,opt,name=EmailNotification,proto3" json:"EmailNotification,omitempty"`
	Emails               []string `protobuf:"bytes,2,rep,name=Emails,proto3" json:"Emails,omitempty"`
	ThresholdSeverity    uint32   `protobuf:"varint,3,opt,name=ThresholdSeverity,proto3" json:"ThresholdSeverity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNotifySettingsRsp) Reset()         { *m = GetNotifySettingsRsp{} }
func (m *GetNotifySettingsRsp) String() string { return proto.CompactTextString(m) }
func (*GetNotifySettingsRsp) ProtoMessage()    {}
func (*GetNotifySettingsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{25}
}

func (m *GetNotifySettingsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNotifySettingsRsp.Unmarshal(m, b)
}
func (m *GetNotifySettingsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNotifySettingsRsp.Marshal(b, m, deterministic)
}
func (m *GetNotifySettingsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNotifySettingsRsp.Merge(m, src)
}
func (m *GetNotifySettingsRsp) XXX_Size() int {
	return xxx_messageInfo_GetNotifySettingsRsp.Size(m)
}
func (m *GetNotifySettingsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNotifySettingsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetNotifySettingsRsp proto.InternalMessageInfo

func (m *GetNotifySettingsRsp) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *GetNotifySettingsRsp) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *GetNotifySettingsRsp) GetThresholdSeverity() uint32 {
	if m != nil {
		return m.ThresholdSeverity
	}
	return 0
}

type UpdateNotifySettingsReq struct {
	EmailNotification    bool     `protobuf:"varint,1,opt,name=EmailNotification,proto3" json:"EmailNotification,omitempty"`
	Emails               []string `protobuf:"bytes,2,rep,name=Emails,proto3" json:"Emails,omitempty"`
	ThresholdSeverity    uint32   `protobuf:"varint,3,opt,name=ThresholdSeverity,proto3" json:"ThresholdSeverity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNotifySettingsReq) Reset()         { *m = UpdateNotifySettingsReq{} }
func (m *UpdateNotifySettingsReq) String() string { return proto.CompactTextString(m) }
func (*UpdateNotifySettingsReq) ProtoMessage()    {}
func (*UpdateNotifySettingsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{26}
}

func (m *UpdateNotifySettingsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotifySettingsReq.Unmarshal(m, b)
}
func (m *UpdateNotifySettingsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotifySettingsReq.Marshal(b, m, deterministic)
}
func (m *UpdateNotifySettingsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotifySettingsReq.Merge(m, src)
}
func (m *UpdateNotifySettingsReq) XXX_Size() int {
	return xxx_messageInfo_UpdateNotifySettingsReq.Size(m)
}
func (m *UpdateNotifySettingsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotifySettingsReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotifySettingsReq proto.InternalMessageInfo

func (m *UpdateNotifySettingsReq) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *UpdateNotifySettingsReq) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *UpdateNotifySettingsReq) GetThresholdSeverity() uint32 {
	if m != nil {
		return m.ThresholdSeverity
	}
	return 0
}

type CheckNeedAlertReq struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Interval             int64    `protobuf:"varint,2,opt,name=Interval,proto3" json:"Interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckNeedAlertReq) Reset()         { *m = CheckNeedAlertReq{} }
func (m *CheckNeedAlertReq) String() string { return proto.CompactTextString(m) }
func (*CheckNeedAlertReq) ProtoMessage()    {}
func (*CheckNeedAlertReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{27}
}

func (m *CheckNeedAlertReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckNeedAlertReq.Unmarshal(m, b)
}
func (m *CheckNeedAlertReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckNeedAlertReq.Marshal(b, m, deterministic)
}
func (m *CheckNeedAlertReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckNeedAlertReq.Merge(m, src)
}
func (m *CheckNeedAlertReq) XXX_Size() int {
	return xxx_messageInfo_CheckNeedAlertReq.Size(m)
}
func (m *CheckNeedAlertReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckNeedAlertReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckNeedAlertReq proto.InternalMessageInfo

func (m *CheckNeedAlertReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CheckNeedAlertReq) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type CheckNeedAlertRsp struct {
	NeedAlert            bool     `protobuf:"varint,1,opt,name=NeedAlert,proto3" json:"NeedAlert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckNeedAlertRsp) Reset()         { *m = CheckNeedAlertRsp{} }
func (m *CheckNeedAlertRsp) String() string { return proto.CompactTextString(m) }
func (*CheckNeedAlertRsp) ProtoMessage()    {}
func (*CheckNeedAlertRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c82ed24bf2a8c602, []int{28}
}

func (m *CheckNeedAlertRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckNeedAlertRsp.Unmarshal(m, b)
}
func (m *CheckNeedAlertRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckNeedAlertRsp.Marshal(b, m, deterministic)
}
func (m *CheckNeedAlertRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckNeedAlertRsp.Merge(m, src)
}
func (m *CheckNeedAlertRsp) XXX_Size() int {
	return xxx_messageInfo_CheckNeedAlertRsp.Size(m)
}
func (m *CheckNeedAlertRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckNeedAlertRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckNeedAlertRsp proto.InternalMessageInfo

func (m *CheckNeedAlertRsp) GetNeedAlert() bool {
	if m != nil {
		return m.NeedAlert
	}
	return false
}

func init() {
	proto.RegisterEnum("pb.SortBy", SortBy_name, SortBy_value)
	proto.RegisterEnum("pb.SortOrder", SortOrder_name, SortOrder_value)
	proto.RegisterType((*CheckEventUpdateReq)(nil), "pb.CheckEventUpdateReq")
	proto.RegisterType((*CheckEventUpdateRsp)(nil), "pb.CheckEventUpdateRsp")
	proto.RegisterType((*GetAssociationEventsReq)(nil), "pb.GetAssociationEventsReq")
	proto.RegisterType((*History)(nil), "pb.History")
	proto.RegisterMapType((map[string]string)(nil), "pb.History.CustomKVEntry")
	proto.RegisterType((*Rule)(nil), "pb.Rule")
	proto.RegisterMapType((map[string]string)(nil), "pb.Rule.CustomKVEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.Rule.DisplayAdapterEntry")
	proto.RegisterType((*TimeWindowEventDetail)(nil), "pb.TimeWindowEventDetail")
	proto.RegisterType((*EventDetail)(nil), "pb.EventDetail")
	proto.RegisterType((*AssociationEvent)(nil), "pb.AssociationEvent")
	proto.RegisterType((*GetAssociationEventsRsp)(nil), "pb.GetAssociationEventsRsp")
	proto.RegisterType((*GetSignalsReq)(nil), "pb.GetSignalsReq")
	proto.RegisterMapType((map[string]string)(nil), "pb.GetSignalsReq.FilterEntry")
	proto.RegisterType((*TimeFilter)(nil), "pb.TimeFilter")
	proto.RegisterType((*GetSignalsRsp)(nil), "pb.GetSignalsRsp")
	proto.RegisterType((*Signal)(nil), "pb.Signal")
	proto.RegisterMapType((map[string]string)(nil), "pb.Signal.CustomKVEntry")
	proto.RegisterType((*GetStatisticsReq)(nil), "pb.GetStatisticsReq")
	proto.RegisterType((*GetStatisticsRsp)(nil), "pb.GetStatisticsRsp")
	proto.RegisterType((*StatisticItem)(nil), "pb.StatisticItem")
	proto.RegisterType((*GetRuleCategoriesReq)(nil), "pb.GetRuleCategoriesReq")
	proto.RegisterType((*GetRuleCategoriesRsp)(nil), "pb.GetRuleCategoriesRsp")
	proto.RegisterMapType((map[string]*RuleModuleInfo)(nil), "pb.GetRuleCategoriesRsp.ModulesEntry")
	proto.RegisterType((*RuleModuleInfo)(nil), "pb.RuleModuleInfo")
	proto.RegisterMapType((map[string]*RuleCategoryInfo)(nil), "pb.RuleModuleInfo.CategoriesEntry")
	proto.RegisterType((*RuleCategoryInfo)(nil), "pb.RuleCategoryInfo")
	proto.RegisterMapType((map[string]*RuleItemInfo)(nil), "pb.RuleCategoryInfo.ItemsEntry")
	proto.RegisterType((*RuleItemInfo)(nil), "pb.RuleItemInfo")
	proto.RegisterType((*GetATTCKPodProcessSignalTreeReq)(nil), "pb.GetATTCKPodProcessSignalTreeReq")
	proto.RegisterType((*GetATTCKPodProcessSignalTreeRsp)(nil), "pb.GetATTCKPodProcessSignalTreeRsp")
	proto.RegisterType((*ProcessNode)(nil), "pb.ProcessNode")
	proto.RegisterType((*GetNotifySettingsReq)(nil), "pb.GetNotifySettingsReq")
	proto.RegisterType((*GetNotifySettingsRsp)(nil), "pb.GetNotifySettingsRsp")
	proto.RegisterType((*UpdateNotifySettingsReq)(nil), "pb.UpdateNotifySettingsReq")
	proto.RegisterType((*CheckNeedAlertReq)(nil), "pb.CheckNeedAlertReq")
	proto.RegisterType((*CheckNeedAlertRsp)(nil), "pb.CheckNeedAlertRsp")
}

func init() { proto.RegisterFile("event.biz.proto", fileDescriptor_c82ed24bf2a8c602) }

var fileDescriptor_c82ed24bf2a8c602 = []byte{
	// 1721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x18, 0xdb, 0x6e, 0xdb, 0xc8,
	0x35, 0xd4, 0x5d, 0x47, 0x96, 0x2c, 0x4f, 0x1c, 0x47, 0x65, 0xdc, 0xc6, 0x60, 0x9b, 0xd4, 0x70,
	0x02, 0xa5, 0x55, 0x62, 0xb4, 0xa9, 0x8b, 0x16, 0xb6, 0xe4, 0xda, 0xae, 0x13, 0x47, 0xa0, 0xed,
	0xb6, 0xe8, 0x1b, 0x2d, 0x8d, 0x6d, 0x22, 0x94, 0xc8, 0x70, 0x46, 0x0e, 0x94, 0xd7, 0x02, 0x79,
	0x08, 0xd0, 0xe7, 0x7e, 0x41, 0xb1, 0xc0, 0x62, 0x1f, 0xf6, 0x3f, 0x76, 0xf7, 0x1b, 0xf6, 0x4b,
	0x16, 0x58, 0xcc, 0x8d, 0x1c, 0x52, 0x94, 0xbd, 0x49, 0x1e, 0xf6, 0x89, 0x73, 0x6e, 0x33, 0xe7,
	0x9c, 0x39, 0x37, 0x0e, 0x2c, 0xe2, 0x2b, 0x3c, 0xa6, 0xed, 0x33, 0xf7, 0x5d, 0x3b, 0x08, 0x7d,
	0xea, 0xa3, 0x5c, 0x70, 0x66, 0xde, 0xbb, 0xf0, 0xfd, 0x0b, 0x0f, 0x3f, 0xe1, 0x98, 0xb3, 0xc9,
	0xf9, 0x13, 0x3c, 0x0a, 0xe8, 0x54, 0x30, 0x58, 0x4f, 0xe1, 0x76, 0xf7, 0x12, 0x0f, 0x5e, 0xef,
	0x32, 0xc1, 0xd3, 0x60, 0xe8, 0x50, 0x6c, 0xe3, 0x37, 0x68, 0x15, 0xaa, 0x27, 0xee, 0x08, 0x13,
	0xea, 0x8c, 0x82, 0x96, 0xb1, 0x66, 0xac, 0xe7, 0xed, 0x18, 0x61, 0xfd, 0xc7, 0xc8, 0x90, 0x22,
	0x01, 0xfa, 0x15, 0xc0, 0xbe, 0x43, 0x04, 0x4c, 0xb8, 0x58, 0xc5, 0xd6, 0x30, 0x68, 0x1d, 0x16,
	0x8f, 0xf0, 0x5b, 0x4c, 0x68, 0xbc, 0x77, 0x8e, 0xef, 0x9d, 0x46, 0x23, 0x0b, 0x16, 0x84, 0xd0,
	0xd1, 0x64, 0x74, 0x4c, 0xc3, 0x56, 0x7e, 0xcd, 0x58, 0xaf, 0xda, 0x09, 0x9c, 0xf5, 0x21, 0x07,
	0x77, 0xf7, 0x30, 0xdd, 0x26, 0xc4, 0x1f, 0xb8, 0x0e, 0x75, 0xfd, 0x31, 0x57, 0x87, 0x30, 0xfd,
	0x57, 0xa0, 0xf4, 0xea, 0xfc, 0x9c, 0x60, 0xca, 0xb5, 0x28, 0xda, 0x12, 0x42, 0xcb, 0x50, 0x7c,
	0xe1, 0x8e, 0x5c, 0xca, 0xcf, 0x2d, 0xda, 0x02, 0x40, 0x16, 0x94, 0x8e, 0xfd, 0x90, 0xee, 0x4c,
	0xf9, 0x39, 0x8d, 0x0e, 0xb4, 0x83, 0xb3, 0xb6, 0xc0, 0xd8, 0x92, 0x82, 0x1e, 0x41, 0x95, 0xad,
	0x5e, 0x85, 0x43, 0x1c, 0xb6, 0x0a, 0x9c, 0xad, 0xae, 0xd8, 0x38, 0xd2, 0x8e, 0xe9, 0xcc, 0x11,
	0xf6, 0xc4, 0xc3, 0x7f, 0x73, 0x3d, 0x8a, 0xc3, 0x56, 0x91, 0x2b, 0xaf, 0x61, 0xd0, 0x63, 0x58,
	0xd2, 0xd4, 0x96, 0x6c, 0x25, 0xce, 0x36, 0x4b, 0x40, 0x08, 0x0a, 0x2f, 0x9c, 0xf1, 0x45, 0xab,
	0xcc, 0x19, 0xf8, 0x1a, 0x35, 0x20, 0x77, 0xd0, 0x6b, 0x55, 0xb8, 0x15, 0xb9, 0x83, 0x9e, 0xf5,
	0x83, 0x01, 0xe5, 0x7d, 0x97, 0x50, 0x3f, 0x9c, 0x22, 0x13, 0x2a, 0xc7, 0xee, 0xc5, 0xd8, 0xf1,
	0x0e, 0x7a, 0xdc, 0xfc, 0xaa, 0x1d, 0xc1, 0x6c, 0xaf, 0xd3, 0xd3, 0x83, 0x1e, 0xb7, 0xbf, 0x60,
	0xf3, 0x35, 0x73, 0x56, 0xdf, 0x1f, 0x32, 0xac, 0x70, 0xb3, 0x84, 0x50, 0x0b, 0xca, 0x7d, 0x7f,
	0x78, 0xe4, 0x8c, 0x30, 0x37, 0xb8, 0x6a, 0x2b, 0x30, 0x19, 0x1e, 0xc5, 0x54, 0x78, 0xa0, 0x4d,
	0xa8, 0x74, 0x27, 0x84, 0xfa, 0xa3, 0xc3, 0x7f, 0xb4, 0x86, 0x6b, 0xf9, 0xf5, 0x5a, 0xe7, 0x17,
	0xcc, 0x53, 0x52, 0xbd, 0xb6, 0xa2, 0xed, 0x8e, 0x69, 0x38, 0xb5, 0x23, 0x56, 0x73, 0x0b, 0xea,
	0x09, 0x12, 0x6a, 0x42, 0xfe, 0x35, 0x9e, 0x4a, 0x13, 0xd8, 0x92, 0x5d, 0xdf, 0x95, 0xe3, 0x4d,
	0x30, 0x57, 0xbf, 0x6a, 0x0b, 0xe0, 0x4f, 0xb9, 0x3f, 0x1a, 0xd6, 0xfb, 0x3c, 0x14, 0x98, 0x83,
	0x99, 0x81, 0x5c, 0x63, 0x21, 0xc5, 0xd7, 0xcc, 0xc0, 0x97, 0xfe, 0x70, 0xe2, 0x29, 0x39, 0x09,
	0x31, 0x47, 0x75, 0x1d, 0x8a, 0x2f, 0xfc, 0x70, 0x2a, 0x4d, 0x8f, 0x60, 0xb4, 0x06, 0xb5, 0x1e,
	0x26, 0x83, 0xd0, 0x0d, 0xd8, 0x4d, 0x48, 0x07, 0xe8, 0x28, 0xee, 0x66, 0x7c, 0x85, 0x43, 0x97,
	0x4e, 0xf9, 0xdd, 0xd5, 0xed, 0x08, 0x46, 0x3d, 0x68, 0xf4, 0x5c, 0x12, 0x78, 0xce, 0x74, 0x7b,
	0xe8, 0x04, 0xec, 0x76, 0xcb, 0xdc, 0x11, 0xab, 0xcc, 0x11, 0x4c, 0xcf, 0x76, 0x92, 0x2c, 0x7c,
	0x91, 0x92, 0x41, 0x9d, 0x19, 0x47, 0xae, 0x44, 0xf2, 0xf3, 0xbc, 0xb8, 0x0d, 0xb7, 0x33, 0xb6,
	0xfe, 0x18, 0x5f, 0x7e, 0xde, 0x45, 0x7c, 0x65, 0xc0, 0x1d, 0x16, 0x0a, 0xff, 0x74, 0xc7, 0x43,
	0xff, 0x2d, 0xcf, 0xc8, 0x1e, 0xa6, 0x8e, 0xeb, 0xb1, 0x70, 0xea, 0x7a, 0x13, 0xc2, 0x9c, 0x21,
	0x76, 0x52, 0x20, 0x0b, 0x27, 0x76, 0x4f, 0x24, 0x70, 0x06, 0x6a, 0xc7, 0x18, 0xc1, 0xfc, 0x7c,
	0xe4, 0x0f, 0xf1, 0xc9, 0x34, 0xc0, 0xea, 0x96, 0x14, 0xcc, 0xf6, 0x64, 0xeb, 0x43, 0x3c, 0x55,
	0x21, 0x2a, 0x41, 0xf4, 0x20, 0xca, 0x87, 0x56, 0x89, 0xbb, 0xae, 0xa6, 0xc5, 0xa0, 0xad, 0x68,
	0xd6, 0x29, 0xd4, 0x74, 0x1d, 0xb7, 0x00, 0x68, 0xa4, 0x3c, 0x57, 0x53, 0x06, 0x6f, 0xa6, 0x49,
	0xfb, 0xb7, 0x6c, 0x8d, 0x7d, 0xa7, 0x0a, 0xe5, 0xae, 0x3f, 0xa6, 0x78, 0x4c, 0xad, 0xef, 0x0c,
	0x68, 0xa6, 0x0b, 0x93, 0xcc, 0x59, 0x43, 0xe5, 0x2c, 0x2b, 0x87, 0x1a, 0x0f, 0xb7, 0x4f, 0x18,
	0x9f, 0x46, 0x27, 0x42, 0x2d, 0x9f, 0x0a, 0xb5, 0x44, 0x2e, 0x16, 0xd2, 0xb9, 0xf8, 0x5b, 0x28,
	0x09, 0x5d, 0x79, 0x9a, 0xd6, 0x3a, 0x8b, 0xcc, 0x18, 0xcd, 0x04, 0x5b, 0x92, 0xd1, 0xaa, 0xc8,
	0x1f, 0x1e, 0xc9, 0xb5, 0x4e, 0x45, 0xc5, 0x99, 0xcd, 0xb1, 0xd6, 0xde, 0x9c, 0x52, 0x4b, 0x02,
	0xf4, 0x18, 0x4a, 0x02, 0x68, 0x19, 0xdc, 0xcf, 0xcb, 0x4c, 0x34, 0xcd, 0x69, 0x4b, 0x1e, 0xeb,
	0xeb, 0x1c, 0xd4, 0xf7, 0x30, 0x15, 0xf5, 0x88, 0x97, 0xea, 0x4d, 0x28, 0xc9, 0x02, 0x28, 0xe4,
	0x7f, 0xc9, 0xe4, 0x13, 0x2c, 0x6d, 0x41, 0x17, 0x91, 0x2e, 0x99, 0xd1, 0x43, 0x68, 0x88, 0x9a,
	0x1e, 0x95, 0x3a, 0xe1, 0xbb, 0x14, 0x36, 0x59, 0xb7, 0xf3, 0x37, 0xd4, 0xed, 0xa8, 0x3d, 0x14,
	0xb8, 0x93, 0x65, 0x7b, 0x40, 0x50, 0xf0, 0x58, 0xfd, 0x15, 0x75, 0x9c, 0xaf, 0x51, 0x1b, 0x80,
	0x39, 0x59, 0x2b, 0xdd, 0xb5, 0x4e, 0x43, 0x05, 0x8a, 0xc0, 0xda, 0x1a, 0x87, 0xf9, 0x1c, 0x6a,
	0x9a, 0x15, 0x1f, 0x95, 0x51, 0xff, 0xd2, 0x8f, 0x62, 0x76, 0x1f, 0x53, 0x27, 0xa4, 0xe9, 0xf6,
	0x9c, 0xc2, 0xb2, 0x0e, 0xba, 0x3b, 0x1e, 0xa6, 0x1b, 0x6d, 0x02, 0x67, 0x6d, 0x26, 0xee, 0x82,
	0x04, 0xe8, 0x37, 0x50, 0x96, 0x90, 0xbc, 0x0c, 0xd1, 0x09, 0x39, 0xca, 0x56, 0x24, 0xeb, 0x7f,
	0x79, 0x28, 0x89, 0xb5, 0x16, 0xd2, 0x55, 0x1e, 0xd2, 0x59, 0xed, 0x45, 0xcb, 0xfb, 0xfc, 0x35,
	0x79, 0x5f, 0xb8, 0x2e, 0xef, 0x8b, 0xf3, 0xf3, 0xbe, 0x94, 0xcc, 0x7b, 0x15, 0xc7, 0xe5, 0xac,
	0x38, 0x4e, 0x24, 0x52, 0x25, 0x95, 0x48, 0x71, 0x1b, 0xac, 0xce, 0x6b, 0x83, 0x90, 0x6c, 0x83,
	0xcf, 0xb4, 0xfa, 0x5c, 0xe3, 0xfe, 0x6a, 0xc5, 0xfe, 0x9a, 0x57, 0xa1, 0x93, 0x09, 0xbb, 0x90,
	0x4a, 0xd8, 0xcf, 0x2b, 0xbe, 0x7f, 0x86, 0x26, 0xbb, 0x50, 0xea, 0x50, 0x97, 0x50, 0x77, 0xc0,
	0xf3, 0x0b, 0x41, 0xa1, 0xe7, 0x4c, 0xc5, 0x38, 0x56, 0xb7, 0xf9, 0x9a, 0xed, 0xb0, 0xef, 0x4f,
	0x42, 0xc2, 0x77, 0xa8, 0xdb, 0x02, 0xb0, 0xde, 0x1b, 0x69, 0x71, 0x12, 0xa0, 0x3f, 0x40, 0xbd,
	0xe7, 0x4c, 0x63, 0x9c, 0x0c, 0x8c, 0x25, 0x6e, 0xa8, 0xc2, 0x1e, 0x50, 0x3c, 0xb2, 0x93, 0x7c,
	0xe8, 0x39, 0x34, 0xd8, 0xb6, 0x9a, 0x64, 0x6e, 0x9e, 0x64, 0x8a, 0xd1, 0x7a, 0x03, 0xf5, 0x04,
	0x03, 0x0b, 0xfa, 0x1d, 0x7c, 0xe1, 0x8e, 0x67, 0x82, 0x3e, 0x89, 0xfd, 0x29, 0x41, 0xcf, 0x6c,
	0xef, 0xfa, 0x93, 0x31, 0x95, 0x85, 0x54, 0x00, 0xd6, 0x06, 0x2c, 0xef, 0x61, 0xca, 0x62, 0x44,
	0x4e, 0x00, 0x2e, 0x56, 0xde, 0xe3, 0xb9, 0x6f, 0xc4, 0xb9, 0x6f, 0x7d, 0x61, 0x64, 0x31, 0x93,
	0x00, 0xfd, 0x15, 0xca, 0x62, 0xb2, 0x50, 0x5e, 0x7a, 0x20, 0x6b, 0xd9, 0x0c, 0x6b, 0x5b, 0xf2,
	0x89, 0xd8, 0x50, 0x52, 0xe6, 0x11, 0x2c, 0xe8, 0x84, 0x8c, 0xbb, 0x5f, 0xd7, 0xef, 0xbe, 0xd6,
	0x41, 0x2a, 0xbe, 0x85, 0xd8, 0xc1, 0xf8, 0xdc, 0xd7, 0xe3, 0xe1, 0x7b, 0x03, 0x1a, 0x49, 0x6a,
	0xe6, 0x7c, 0xb4, 0x06, 0x35, 0xf6, 0x55, 0xa3, 0x8a, 0x08, 0x2b, 0x1d, 0x85, 0x76, 0x00, 0x06,
	0x91, 0xfe, 0xad, 0x3c, 0x37, 0xce, 0x9a, 0x3d, 0xbb, 0x1d, 0x1b, 0x29, 0x2c, 0xd3, 0xa4, 0xcc,
	0x63, 0x58, 0x4c, 0x91, 0x33, 0xec, 0xdb, 0x48, 0xda, 0xb7, 0xac, 0xce, 0x50, 0x73, 0x59, 0xda,
	0xc2, 0x6f, 0x0c, 0x68, 0xa6, 0xe9, 0x9f, 0x68, 0xe3, 0x26, 0x14, 0x5d, 0x8a, 0x47, 0xca, 0xbc,
	0xfb, 0x59, 0x47, 0xb7, 0x59, 0x38, 0x4a, 0xdb, 0x04, 0xb7, 0xf9, 0x77, 0x80, 0x18, 0x99, 0x61,
	0xd1, 0xc3, 0xa4, 0x45, 0x4d, 0xb5, 0x2d, 0x13, 0x4a, 0x5b, 0xd3, 0x83, 0x05, 0x9d, 0xf4, 0x69,
	0x86, 0x58, 0xff, 0x37, 0xe0, 0x3e, 0xeb, 0xd6, 0x27, 0x27, 0xdd, 0xc3, 0xbe, 0x3f, 0xec, 0x87,
	0xfe, 0x00, 0x13, 0x22, 0xaa, 0xd2, 0x49, 0x88, 0xf9, 0x0f, 0xde, 0xa7, 0x0e, 0x63, 0x5a, 0x31,
	0xcc, 0xcf, 0xfc, 0x13, 0xd0, 0xf4, 0x1c, 0x12, 0x21, 0xa2, 0x7f, 0x98, 0x62, 0xfc, 0x0f, 0x63,
	0xed, 0xdf, 0xa0, 0x26, 0x09, 0xd0, 0x03, 0x28, 0xb2, 0xc2, 0xae, 0xf2, 0x89, 0x4f, 0x2f, 0x92,
	0x91, 0xe1, 0x6d, 0x41, 0xb5, 0xbe, 0x35, 0xa0, 0xa6, 0xa1, 0xd9, 0x2d, 0xf4, 0xa3, 0xbe, 0xc4,
	0x96, 0xec, 0xfc, 0x7e, 0x3f, 0x1a, 0x12, 0xf8, 0x9a, 0x79, 0x52, 0x09, 0xc5, 0xf6, 0xe8, 0x28,
	0x56, 0x4f, 0xfa, 0x3a, 0x8b, 0xe8, 0x51, 0x09, 0x9c, 0xde, 0x33, 0x8b, 0x73, 0x7b, 0x26, 0x7a,
	0x04, 0x95, 0xee, 0xa5, 0xeb, 0x0d, 0x43, 0x3c, 0x96, 0xf3, 0xe8, 0x8c, 0x2d, 0x11, 0x83, 0xb5,
	0xc2, 0xeb, 0xcb, 0x91, 0x4f, 0xdd, 0xf3, 0xe9, 0x31, 0xa6, 0xd4, 0x1d, 0x5f, 0xb0, 0x62, 0x64,
	0x7d, 0x30, 0xb2, 0x08, 0x7c, 0x06, 0x5b, 0xda, 0x1d, 0x39, 0xae, 0xc7, 0x29, 0xee, 0x80, 0xcf,
	0x5d, 0xf2, 0xff, 0x7b, 0x96, 0xc0, 0x1a, 0x1d, 0x47, 0x8a, 0x8a, 0x5c, 0xb5, 0x25, 0xc4, 0x76,
	0x39, 0xb9, 0x0c, 0x31, 0xb9, 0xf4, 0xbd, 0x61, 0x6a, 0xdc, 0x9c, 0x25, 0x58, 0xff, 0x35, 0xe0,
	0xae, 0xfc, 0x1f, 0x4f, 0x2b, 0xfa, 0xb3, 0xe8, 0xf3, 0x12, 0x96, 0xf8, 0x9b, 0xc4, 0x11, 0xc6,
	0xc3, 0x6d, 0x0f, 0x87, 0xf4, 0xc6, 0x77, 0x0c, 0x36, 0x0d, 0x1c, 0x8c, 0x29, 0x0e, 0xaf, 0x1c,
	0x4f, 0xb6, 0x8a, 0x08, 0xb6, 0x7e, 0x3f, 0xb3, 0x1d, 0x09, 0x78, 0x6e, 0x28, 0x58, 0xda, 0x13,
	0x23, 0x36, 0x9e, 0xa9, 0x67, 0x04, 0x54, 0x87, 0x6a, 0x0f, 0x9f, 0x3b, 0x13, 0x8f, 0xee, 0x4c,
	0x9b, 0xb7, 0x18, 0x18, 0x1d, 0xda, 0x34, 0xd0, 0x42, 0x3c, 0x84, 0x34, 0x73, 0x1b, 0xbf, 0xd3,
	0x06, 0x54, 0xd4, 0x84, 0x05, 0x29, 0xc8, 0xe1, 0xe6, 0x2d, 0x54, 0x81, 0x02, 0xfb, 0xe9, 0x6c,
	0x1a, 0xa8, 0x0c, 0xf9, 0x6d, 0x32, 0x68, 0xe6, 0x3a, 0x5f, 0x16, 0x61, 0x45, 0x8c, 0xd3, 0x5d,
	0xcc, 0xd4, 0xdd, 0x71, 0xdf, 0x1d, 0xe3, 0xf0, 0xca, 0x1d, 0x60, 0xd4, 0x83, 0x66, 0xfa, 0x61,
	0x06, 0xdd, 0x65, 0x81, 0x96, 0xf1, 0xc8, 0x63, 0x66, 0x13, 0x48, 0x80, 0xfa, 0x3c, 0xcc, 0x66,
	0xa6, 0x7d, 0x74, 0x4f, 0xb6, 0xb3, 0xac, 0x27, 0x17, 0x73, 0x3e, 0x91, 0x04, 0xa8, 0x03, 0x10,
	0x4f, 0x9a, 0x68, 0x69, 0x66, 0xc4, 0x37, 0xd3, 0x28, 0x12, 0xa0, 0x2d, 0x31, 0x9d, 0xc6, 0x13,
	0xc5, 0xb2, 0xe2, 0xd1, 0xe7, 0x1b, 0x33, 0x03, 0x4b, 0x02, 0xb4, 0x07, 0x4b, 0x33, 0x7d, 0x17,
	0xb5, 0xb2, 0xdb, 0x31, 0x7e, 0x63, 0xb6, 0xe6, 0x35, 0x6a, 0x74, 0x09, 0xab, 0xd7, 0x15, 0x29,
	0xf4, 0x6b, 0x65, 0xf6, 0x35, 0xd5, 0xd6, 0xbc, 0x99, 0x29, 0x52, 0x39, 0x99, 0x4c, 0x91, 0xca,
	0x33, 0x39, 0x66, 0xce, 0xa1, 0x90, 0x00, 0x1d, 0xc2, 0x72, 0x56, 0x62, 0x8a, 0xeb, 0x9b, 0x93,
	0xb2, 0xe6, 0x4a, 0x5b, 0x3c, 0x13, 0xb6, 0xd5, 0x33, 0x61, 0x7b, 0x77, 0x14, 0xd0, 0x29, 0xfa,
	0x0b, 0x34, 0x92, 0x79, 0x80, 0xee, 0x44, 0x61, 0xa3, 0xa7, 0x9a, 0x99, 0x85, 0x26, 0xc1, 0x4e,
	0xe9, 0xdf, 0x85, 0xf6, 0x56, 0x70, 0x76, 0x56, 0xe2, 0xfb, 0x3e, 0xfd, 0x31, 0x00, 0x00, 0xff,
	0xff, 0xd7, 0xf1, 0x31, 0xfb, 0xa3, 0x14, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventsCenterBizServiceClient is the client API for EventsCenterBizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsCenterBizServiceClient interface {
	CheckEventUpdate(ctx context.Context, in *CheckEventUpdateReq, opts ...grpc.CallOption) (*CheckEventUpdateRsp, error)
	GetAssociationEvents(ctx context.Context, in *GetAssociationEventsReq, opts ...grpc.CallOption) (*GetAssociationEventsRsp, error)
	GetSignals(ctx context.Context, in *GetSignalsReq, opts ...grpc.CallOption) (*GetSignalsRsp, error)
	GetStatistics(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsRsp, error)
	GetRuleCategories(ctx context.Context, in *GetRuleCategoriesReq, opts ...grpc.CallOption) (*GetRuleCategoriesRsp, error)
	GetATTCKPodProcessSignalTree(ctx context.Context, in *GetATTCKPodProcessSignalTreeReq, opts ...grpc.CallOption) (*GetATTCKPodProcessSignalTreeRsp, error)
	GetNotifySettings(ctx context.Context, in *GetNotifySettingsReq, opts ...grpc.CallOption) (*GetNotifySettingsRsp, error)
	UpdateNotifySettings(ctx context.Context, in *UpdateNotifySettingsReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CheckNeedAlert(ctx context.Context, in *CheckNeedAlertReq, opts ...grpc.CallOption) (*CheckNeedAlertRsp, error)
}

type eventsCenterBizServiceClient struct {
	cc *grpc.ClientConn
}

func NewEventsCenterBizServiceClient(cc *grpc.ClientConn) EventsCenterBizServiceClient {
	return &eventsCenterBizServiceClient{cc}
}

func (c *eventsCenterBizServiceClient) CheckEventUpdate(ctx context.Context, in *CheckEventUpdateReq, opts ...grpc.CallOption) (*CheckEventUpdateRsp, error) {
	out := new(CheckEventUpdateRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/CheckEventUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetAssociationEvents(ctx context.Context, in *GetAssociationEventsReq, opts ...grpc.CallOption) (*GetAssociationEventsRsp, error) {
	out := new(GetAssociationEventsRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetAssociationEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetSignals(ctx context.Context, in *GetSignalsReq, opts ...grpc.CallOption) (*GetSignalsRsp, error) {
	out := new(GetSignalsRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetSignals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsReq, opts ...grpc.CallOption) (*GetStatisticsRsp, error) {
	out := new(GetStatisticsRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetRuleCategories(ctx context.Context, in *GetRuleCategoriesReq, opts ...grpc.CallOption) (*GetRuleCategoriesRsp, error) {
	out := new(GetRuleCategoriesRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetRuleCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetATTCKPodProcessSignalTree(ctx context.Context, in *GetATTCKPodProcessSignalTreeReq, opts ...grpc.CallOption) (*GetATTCKPodProcessSignalTreeRsp, error) {
	out := new(GetATTCKPodProcessSignalTreeRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetATTCKPodProcessSignalTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) GetNotifySettings(ctx context.Context, in *GetNotifySettingsReq, opts ...grpc.CallOption) (*GetNotifySettingsRsp, error) {
	out := new(GetNotifySettingsRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/GetNotifySettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) UpdateNotifySettings(ctx context.Context, in *UpdateNotifySettingsReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/UpdateNotifySettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsCenterBizServiceClient) CheckNeedAlert(ctx context.Context, in *CheckNeedAlertReq, opts ...grpc.CallOption) (*CheckNeedAlertRsp, error) {
	out := new(CheckNeedAlertRsp)
	err := c.cc.Invoke(ctx, "/pb.EventsCenterBizService/CheckNeedAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsCenterBizServiceServer is the server API for EventsCenterBizService service.
type EventsCenterBizServiceServer interface {
	CheckEventUpdate(context.Context, *CheckEventUpdateReq) (*CheckEventUpdateRsp, error)
	GetAssociationEvents(context.Context, *GetAssociationEventsReq) (*GetAssociationEventsRsp, error)
	GetSignals(context.Context, *GetSignalsReq) (*GetSignalsRsp, error)
	GetStatistics(context.Context, *GetStatisticsReq) (*GetStatisticsRsp, error)
	GetRuleCategories(context.Context, *GetRuleCategoriesReq) (*GetRuleCategoriesRsp, error)
	GetATTCKPodProcessSignalTree(context.Context, *GetATTCKPodProcessSignalTreeReq) (*GetATTCKPodProcessSignalTreeRsp, error)
	GetNotifySettings(context.Context, *GetNotifySettingsReq) (*GetNotifySettingsRsp, error)
	UpdateNotifySettings(context.Context, *UpdateNotifySettingsReq) (*emptypb.Empty, error)
	CheckNeedAlert(context.Context, *CheckNeedAlertReq) (*CheckNeedAlertRsp, error)
}

// UnimplementedEventsCenterBizServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEventsCenterBizServiceServer struct {
}

func (*UnimplementedEventsCenterBizServiceServer) CheckEventUpdate(ctx context.Context, req *CheckEventUpdateReq) (*CheckEventUpdateRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckEventUpdate not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetAssociationEvents(ctx context.Context, req *GetAssociationEventsReq) (*GetAssociationEventsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssociationEvents not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetSignals(ctx context.Context, req *GetSignalsReq) (*GetSignalsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignals not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetStatistics(ctx context.Context, req *GetStatisticsReq) (*GetStatisticsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetRuleCategories(ctx context.Context, req *GetRuleCategoriesReq) (*GetRuleCategoriesRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRuleCategories not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetATTCKPodProcessSignalTree(ctx context.Context, req *GetATTCKPodProcessSignalTreeReq) (*GetATTCKPodProcessSignalTreeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetATTCKPodProcessSignalTree not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) GetNotifySettings(ctx context.Context, req *GetNotifySettingsReq) (*GetNotifySettingsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifySettings not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) UpdateNotifySettings(ctx context.Context, req *UpdateNotifySettingsReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotifySettings not implemented")
}
func (*UnimplementedEventsCenterBizServiceServer) CheckNeedAlert(ctx context.Context, req *CheckNeedAlertReq) (*CheckNeedAlertRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNeedAlert not implemented")
}

func RegisterEventsCenterBizServiceServer(s *grpc.Server, srv EventsCenterBizServiceServer) {
	s.RegisterService(&_EventsCenterBizService_serviceDesc, srv)
}

func _EventsCenterBizService_CheckEventUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEventUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).CheckEventUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/CheckEventUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).CheckEventUpdate(ctx, req.(*CheckEventUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetAssociationEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssociationEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetAssociationEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetAssociationEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetAssociationEvents(ctx, req.(*GetAssociationEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetSignals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetSignals(ctx, req.(*GetSignalsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetStatistics(ctx, req.(*GetStatisticsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetRuleCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetRuleCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetRuleCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetRuleCategories(ctx, req.(*GetRuleCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetATTCKPodProcessSignalTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetATTCKPodProcessSignalTreeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetATTCKPodProcessSignalTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetATTCKPodProcessSignalTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetATTCKPodProcessSignalTree(ctx, req.(*GetATTCKPodProcessSignalTreeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_GetNotifySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotifySettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).GetNotifySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/GetNotifySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).GetNotifySettings(ctx, req.(*GetNotifySettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_UpdateNotifySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotifySettingsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).UpdateNotifySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/UpdateNotifySettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).UpdateNotifySettings(ctx, req.(*UpdateNotifySettingsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsCenterBizService_CheckNeedAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNeedAlertReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsCenterBizServiceServer).CheckNeedAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventsCenterBizService/CheckNeedAlert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsCenterBizServiceServer).CheckNeedAlert(ctx, req.(*CheckNeedAlertReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventsCenterBizService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventsCenterBizService",
	HandlerType: (*EventsCenterBizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckEventUpdate",
			Handler:    _EventsCenterBizService_CheckEventUpdate_Handler,
		},
		{
			MethodName: "GetAssociationEvents",
			Handler:    _EventsCenterBizService_GetAssociationEvents_Handler,
		},
		{
			MethodName: "GetSignals",
			Handler:    _EventsCenterBizService_GetSignals_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _EventsCenterBizService_GetStatistics_Handler,
		},
		{
			MethodName: "GetRuleCategories",
			Handler:    _EventsCenterBizService_GetRuleCategories_Handler,
		},
		{
			MethodName: "GetATTCKPodProcessSignalTree",
			Handler:    _EventsCenterBizService_GetATTCKPodProcessSignalTree_Handler,
		},
		{
			MethodName: "GetNotifySettings",
			Handler:    _EventsCenterBizService_GetNotifySettings_Handler,
		},
		{
			MethodName: "UpdateNotifySettings",
			Handler:    _EventsCenterBizService_UpdateNotifySettings_Handler,
		},
		{
			MethodName: "CheckNeedAlert",
			Handler:    _EventsCenterBizService_CheckNeedAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.biz.proto",
}
