---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-headless
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
  - name: monitor
    port: 8222
  {{- if not .Values.stan.nats.url }}
  - name: client
    port: 4222
  {{- end }}
