package api

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gitlab.com/piccolo_su/vegeta/cmd/scanner/component"
	_ "gitlab.com/piccolo_su/vegeta/cmd/scanner/docs" // docs is generated by Swag CLI
	"gitlab.com/piccolo_su/vegeta/pkg/logging"
)

var (
	log *logging.Logger
)

func init() {
	log = logging.GetLogger()
}

func SetupGinRouter(scannerSvc component.ScannerSrv, rejectSvc component.ImageRejectSrv, harborSvc component.HarborSvc, rejistrySrv component.RegistrySrvInterface) *gin.Engine {
	router := gin.Default()

	apiScannerSrv := NewScannerApiSrv(scannerSvc)
	apiRejectSrv := NewRejectApiSrv(rejectSvc)
	apiHaborSrv := NewHaborApiSrv(harborSvc, harborSvc.GetRedisClient())
	apiRegistrySrv := NewRegistrySrv(rejistrySrv, rejectSvc)

	router.Use(gin.Logger(), gin.Recovery())

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	v1 := router.Group("/api/v1/scan")
	{
		v1.GET("/reportsByImageList", apiScannerSrv.ListScannedByImageList)
		v1.GET("/reportsByImageOverview", apiScannerSrv.ListScannedByImageOverview)
		v1.GET("/reportsByImageDetails", apiScannerSrv.ScannedByImageDetails)

		v1.POST("/scanone", apiScannerSrv.StartScanOne)

		v1.POST("/harbor/scanAllNow", apiScannerSrv.ScanAllNow)
		v1.GET("/harbor/scanStatus", apiScannerSrv.GetScanStatus)
		v1.GET("/harbor/scanOneStatus", apiScannerSrv.GetScanOneStatus)
		v1.GET("/reportsByVulnOverview", apiScannerSrv.ListScannedByVulnOverview)
		v1.GET("/reportsBySimpleImageDetails", apiScannerSrv.GetSimpleImageDetail)
	}

	v2 := router.Group("/api/v1/images")
	{
		v2.GET("/:imgDigest/layers", apiScannerSrv.ListImgLayers)
		v2.POST("/bases", apiScannerSrv.CreateBaseImage)
		v2.DELETE("/bases/:imageID", apiScannerSrv.DeleteBaseImage)
		v2.GET("/bases", apiScannerSrv.ListBaseImage)
		v2.GET("/base/:imageID/apps", apiScannerSrv.ListBaseToAppImage)
		v2.GET("/app/:imageID/bases", apiScannerSrv.ListAppToBaseImage)
	}

	v3 := router.Group("/api/v1/layers")
	{
		v3.GET("/:layerDigest/info", apiScannerSrv.ImgLayerInfo)
	}

	v4 := router.Group("/api/v1/vulns")
	{
		v4.GET("/query/:name", apiScannerSrv.ListImageInfoFromVuln)
		v4.GET("/detail/:name", apiScannerSrv.ScannedByVulnDetails)
		v4.GET("/statistic", apiScannerSrv.ListScannedByVulnOverview)
		v4.GET("/all", apiScannerSrv.ListScannedByVulnList)
	}
	v5 := router.Group("/api/v1/imagereject")
	{

		v5.GET("/overview", apiRejectSrv.Overview)
		v5.GET("/images", apiRejectSrv.ListRejectRecord)
		v5.POST("/whitelist", apiRejectSrv.CreateWhitelist)
		v5.GET("/whitelist", apiRejectSrv.ListWhitelist)
		v5.DELETE("/whitelist/:id", apiRejectSrv.DeleteWhitelist)

		v5.GET("/policy/single", apiRejectSrv.ListPolicy)
		v5.POST("/policy/single", apiRejectSrv.CreatePolicy)
		v5.PUT("/policy/global", apiRejectSrv.UpdateGlobalPolicy)
		v5.GET("/policy/global", apiRejectSrv.GetGlobalPolicy)
		v5.PUT("/policy/single/:id", apiRejectSrv.UpdatePolicy)
		v5.DELETE("/policy/single/:id", apiRejectSrv.DeletePolicy)

		v5.POST("/online_moniter", apiScannerSrv.TickOnlineScan)
		v5.POST("/scanone/cicd", apiScannerSrv.ScanOneForDetectImage)
		v5.POST("/result/cicd", apiScannerSrv.ScanOneForCICDRequest)

		v5.GET("/reasons", apiRejectSrv.RejectReasons)
	}
	// 和仓库相关
	v6 := router.Group("/api/v1/register")
	{
		// v6.GET("/projects/:projectName", apiScannerSrv.CheckProjectAndCreateIfNotExist)
		v6.GET("/registries", apiRegistrySrv.SearchRegistry)
		v6.GET("/registry/:id", apiRegistrySrv.GetRegistry)
		v6.PUT("/registry/:id", apiRegistrySrv.UpdateRegistry)
		v6.POST("/registry", apiRegistrySrv.CreateRegistry)
		v6.DELETE("/registry/:id", apiRegistrySrv.DeleteRegistry)
		v6.GET("/reg-type", apiRegistrySrv.GetRegistryType)
	}
	// 对接harbor扫描器
	v7 := router.Group("/harbor/api/v1")
	{
		v7.GET("/metadata", apiHaborSrv.getHarborPluginManifest)
		v7.POST("/scan", apiHaborSrv.postHarborPluginScan)
		v7.GET("/scan/:id/report", apiHaborSrv.getHarborPluginReport)
	}

	return router
}
