package api

import (
	"github.com/gin-gonic/gin"

	"gitlab.com/piccolo_su/vegeta/cmd/scanner/component"
	"gitlab.com/piccolo_su/vegeta/cmd/scanner/component/ci"
	dbManage "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/db-manage"
	deploySrv "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/deployment"
	"gitlab.com/piccolo_su/vegeta/cmd/scanner/component/imagemeta"
	imagesecScanSrv "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/imagescan/service"
	imagesecSrv "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/imagesec"
	regService "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/registry/service"
	scanwebshell "gitlab.com/piccolo_su/vegeta/cmd/scanner/component/scanner-webshell"
	_ "gitlab.com/piccolo_su/vegeta/cmd/scanner/docs" // docs is generated by Swag CLI
	"gitlab.com/piccolo_su/vegeta/cmd/scanner/global"
	scanReportService "gitlab.com/piccolo_su/vegeta/cmd/scanner/scan-report/service"
	imagesecModel "gitlab.com/piccolo_su/vegeta/pkg/model/imagesec"
	"gitlab.com/piccolo_su/vegeta/pkg/util"
)

func SetupGinRouter(
	imageSvc imagemeta.ImageService,
	rejectSvc component.ImageRejectSrv,
	registrySrv regService.RegistryService,
	scanResultSrv imagesecScanSrv.ScanResultService,
	ciDalSrv ci.CiComponent,
	scannerInfo imagesecSrv.ScanInstanceService,
	webshellSrv scanwebshell.WebshellController,
	exportSrv scanReportService.ExportTaskInterface,
	dbManageSrv dbManage.DBManageSrv,
	policySrv imagesecSrv.SecurityPolicyService,
	scanTaskSrv imagesecScanSrv.ScanTaskService,
	sensitiveRuleService imagesecSrv.SensitiveRuleService,
	scanImageConfigService imagesecSrv.ScanImageConfigService,
	nodeSrv imagesecSrv.NodeReportService,
	dbUpdateSrv imagesecScanSrv.DBManagerService,
	deployService deploySrv.DeployService,
) *gin.Engine {

	router := gin.Default()
	router.MaxMultipartMemory = 2 << 20

	router.Use(gin.Logger(), gin.Recovery(), AddLanguage)

	router.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "healthy",
		})
	})

	router = WebAPI(
		router,
		imageSvc,
		rejectSvc,
		registrySrv,
		scanResultSrv,
		ciDalSrv,
		scannerInfo,
		webshellSrv,
		exportSrv,
		dbManageSrv,
		policySrv,
		scanTaskSrv,
		sensitiveRuleService,
		scanImageConfigService,
		nodeSrv,
		dbUpdateSrv,
		deployService,
	)
	// 这一期先不管 openAPI
	router = OpenAPI(router, rejectSvc, ciDalSrv, imageSvc, exportSrv)
	// router = OpenAPI(router, scannerSvc, rejectSvc, registrySrv, scanConfigSrv,
	// 	scanResultSrv, ciDalSrv, imageSvc, syncImageSrv, exportSrv)

	return router
}

func WebAPI(router *gin.Engine,
	imageService imagemeta.ImageService,
	rejectSvc component.ImageRejectSrv,
	registrySrv regService.RegistryService,
	scanResultSrv imagesecScanSrv.ScanResultService,
	ciDalSrv ci.CiComponent,
	scannerInfo imagesecSrv.ScanInstanceService,
	webshellSrv scanwebshell.WebshellController,
	exportSrv scanReportService.ExportTaskInterface,
	dbManageSrv dbManage.DBManageSrv,
	policySrv imagesecSrv.SecurityPolicyService,
	scanTaskSrv imagesecScanSrv.ScanTaskService,
	sensitiveRuleService imagesecSrv.SensitiveRuleService,
	scanImageConfigService imagesecSrv.ScanImageConfigService,
	nodeSrv imagesecSrv.NodeReportService,
	dBManagerSrv imagesecScanSrv.DBManagerService,
	deployService deploySrv.DeployService,
) *gin.Engine {
	// libImageSrv := NewScannerAPISrv(imageService)
	apiRejectSrv := NewRejectAPISrv(rejectSvc)
	// apiHarborSrv := NewHarborAPISrv(harborSvc, harborSvc.GetRedisClient())
	apiRegistrySrv := NewRegistrySrv(registrySrv, rejectSvc, scannerInfo)
	apiVulnSrv := NewVulnAPISrv(scanResultSrv)
	scanResultApi := NewScanResultAPI(imageService, scanResultSrv)

	imageBaseApi := NewImageInfoAPI(imageService)
	scanTaskAPI := NewScanTaskAPI(scanTaskSrv)
	nodeApiSrv := NewNodeReportAPISrv(nodeSrv)

	deployAPI := NewDeploySrv(deployService)
	configAPISrv := NewConfigAPISrv(sensitiveRuleService, scanImageConfigService, scanResultSrv)
	v5 := router.Group("/api/v1/imagereject")
	{
		v5.POST("/online_moniter", deployAPI.CheckDeploy)

		v5.GET("/reasons", apiRejectSrv.RejectReasons)

		trustedImageGroup := v5.Group("/trustedImages")
		{
			trustedImageGroup.GET("/rsa", apiRejectSrv.RSAList)
			trustedImageGroup.GET("/rsa/:id", apiRejectSrv.RSADetail)
			trustedImageGroup.POST("/rsa", apiRejectSrv.RSAGenerate)
			trustedImageGroup.PUT("/rsa/:id", apiRejectSrv.RSAUpdate)
			trustedImageGroup.DELETE("/rsa/:id", apiRejectSrv.RSADelete)
			trustedImageGroup.POST("/sign", apiRejectSrv.SignImageTrusted)
		}
	}

	// 对接harbor扫描器
	// v7 := router.Group("/harbor/api/v1")
	// {
	// 	v7.GET("/metadata", apiHarborSrv.getHarborPluginManifest)
	// 	v7.POST("/scan", apiHarborSrv.postHarborPluginScan)
	// 	v7.GET("/scan/:id/report", apiHarborSrv.getHarborPluginReport)
	// }

	// ci
	ciSrv := NewCiSrv(ciDalSrv, exportSrv)
	v14 := router.Group("/api/v1/ci")
	{
		v14.POST("/policy", ciSrv.CreateCiPolicy)
		v14.GET("/policy", ciSrv.CiPolicyDetail)
		v14.DELETE("/policy", ciSrv.DeleteCiPolicy)
		v14.GET("/policy/:name", ciSrv.GetCiPolicy)
		v14.PUT("/policy", ciSrv.UpdatePolicy)
		v14.GET("/policies", ciSrv.GetCiPolicyList)
		v14.POST("/whitelists", ciSrv.CreateWhitelist)
		v14.GET("/whitelist", ciSrv.GetWhitelist)
		v14.PUT("/whitelists", ciSrv.UpdateWhitelist)
		v14.GET("/image/whitelist", ciSrv.MatchWhitelist)
		v14.DELETE("/whitelist", ciSrv.DeleteWhitelist)
		v14.GET("/statistic/image", ciSrv.GetImageOverView)
		v14.GET("/statistic/top5", ciSrv.GetImageTop5)
		v14.GET("/images", ciSrv.GetImageList)
		v14.GET("/image", ciSrv.GetImageDetail)
		v14.POST("/vulnerability", ciSrv.MatchVulnerability)
		v14.POST("/result", ciSrv.SaveResult)
		v14.GET("/sensitives", ciSrv.GetSensitives)
		v14.GET("/vulns", ciSrv.GetRecordVulns)
		v14.GET("/vuln/detail", ciSrv.GetVulnDetail)
		v14.GET("/pkgs", ciSrv.GetRecordPkgs)
		v14.POST("/webhook", ciSrv.CreateWebhook)
		v14.PUT("/webhook", ciSrv.UpDateWebhook)
		v14.GET("/webhook", ciSrv.GetWebhook)
		v14.GET("/webhook/record", ciSrv.GetWebhookRecords)

		v14.GET("/tidb/version", ciSrv.TiDbVersion)
		v14.Static("/tidb/assets", global.ScannerOpts.PvcPath)
	}

	v16 := router.Group("/api/v1/webshells")
	{
		v16.GET("/imageWebshell/webshell", webshellSrv.ListWebshell)
		v16.GET("/imageWebshell/detail", webshellSrv.GetWebshellDetail)
		v16.GET("/imageWebshell/download", webshellSrv.Download)
		v16.POST("/imageWebshell/file", webshellSrv.GetFile)
	}
	updateDBApiSrv := NewDBManagerAPISrv(dBManagerSrv)
	v20 := router.Group("/api/v1/db")
	{
		v20.PUT("/update", dbManageSrv.UploadVulnOffline)
		v20.PUT("/update/malicious", dbManageSrv.UploadMaliciousOffline)
		v20.GET("/version", dbManageSrv.GetVersion)
		v20.GET("/history", dbManageSrv.GetHistory)
		v20.POST("/updateDB", updateDBApiSrv.UpdateDb)
	}

	// 和仓库相关
	v6 := router.Group("/api/v1/register")
	{
		v6.GET("/registries", apiRegistrySrv.SearchRegistry) // 暂时不删除，资产那边在用
		v6.GET("/registry", apiRegistrySrv.GetRegistry)
		v6.PUT("/registry/:id", apiRegistrySrv.UpdateRegistry)
		v6.POST("/registry", apiRegistrySrv.CreateRegistry)
		v6.DELETE("/registry/:id", apiRegistrySrv.DeleteRegistry)
		v6.GET("/reg-type", apiRegistrySrv.GetRegistryType)
		v6.GET("/regions", apiRegistrySrv.GetRegions)
	}

	// 和同步镜像相关
	v12 := router.Group("/api/v1/syncImage")
	{
		v12.POST("/startSync", apiRegistrySrv.CreateSyncTask)
		v12.GET("/syncProgress", apiRegistrySrv.GetSyncProgress)
		v12.GET("/syncStatus", apiRegistrySrv.GetSyncStatus)

		v12.GET("/registries", apiRegistrySrv.SearchRegistry)
		v12.GET("/registry", apiRegistrySrv.GetRegistry)
		v12.PUT("/registry", apiRegistrySrv.UpdateRegistry)
		v12.POST("/registry", apiRegistrySrv.CreateRegistry)
		v12.DELETE("/registry", apiRegistrySrv.DeleteRegistry)
		v12.GET("/regType", apiRegistrySrv.GetRegistryType)
		v12.GET("/regions", apiRegistrySrv.GetRegions)
	}

	// 内部调用
	v13 := router.Group("/api/v1/internal")
	{
		v13.POST("/overview/image", imageBaseApi.RiskImageOverview)     // down
		v13.POST("/overview/registry", apiRegistrySrv.RegistryOverview) // down
	}

	scannerInstanceInfoSrv := NewScannerInstanceInfoSrv(scannerInfo)
	v15 := router.Group("/api/v1/scannerInfo")
	{
		v15.GET("/list", scannerInstanceInfoSrv.GetScannerInstanceInfo)
	}

	v2 := router.Group("/api/v1/images")
	{
		v2.GET("/sampleList", imageBaseApi.SearchImages)
		v2.GET("/verifyExistence", imageBaseApi.VerifyExistence)
		v2.GET("/existenceCount", imageBaseApi.ExistenceCount)

		v2.POST("/list", imageBaseApi.SearchImageWithScan)
		v2.GET("/overview", imageBaseApi.ImageOverview)
		v2.GET("/resource", imageBaseApi.SearchResources)         // 镜像详情中关联容器
		v2.GET("/related/image", imageBaseApi.SearchRelatedImage) // 关联镜像

		v2.POST("/baseImage", imageBaseApi.CreateBaseImage)
		v2.DELETE("/baseImage", imageBaseApi.DeleteBaseImage)
		v2.GET("/registryProject", imageBaseApi.GetRegistryProject)

		v2.GET("/detail/base", scanResultApi.ImageBaseDetail)
		v2.GET("/detail/issueStatistic", scanResultApi.ImageIssueStatistic)
		v2.GET("/detail/issueOverview", scanResultApi.SecurityIssueOverview)
		v2.GET("/detail/env", scanResultApi.SearchEnv)
		v2.GET("/detail/virus", scanResultApi.SearchVirus)
		v2.GET("/detail/sensitiveFile", scanResultApi.SearchSensitive)
		v2.GET("/detail/software", scanResultApi.SearchSoftware)
		v2.GET("/detail/vulns/vuln", scanResultApi.GetImageVulns)
		v2.GET("/detail/vulns/pkg", scanResultApi.GetImageVulnPkg)
		v2.GET("/detail/vulns/language", scanResultApi.GetImageVulnLanguage)
		v2.GET("/detail/vulns/gobinary", scanResultApi.GetImageVulnGoBinary)
		v2.GET("/detail/vulns/frame", scanResultApi.GetImageVulnFrame)
		v2.GET("/detail/webshell", scanResultApi.GetImageWebshell)
		v2.GET("/detail/baseImage", imageBaseApi.GetBaseImages)
		v2.GET("/detail/appImage", imageBaseApi.GetAppImages)
		v2.GET("/detail/license", imageBaseApi.GetLicense)
		v2.POST("/detail/riskInfo", scanResultApi.GetImageRiskInfo)
		v2.GET("/detail/layers", scanResultApi.GetImageLayer)
		v2.GET("/vulns/vuln/detail", scanResultApi.GetVulnDetail)
		v2.GET("/vulns/vuln/list", apiVulnSrv.SearchVuln)

		v2.GET("/webshell/detail", scanResultApi.GetWebshellDetail)
		v2.GET("/sensitive/detail", scanResultApi.GetSensitiveDetail)
		v2.GET("/malware/detail", scanResultApi.GetMalwareDetail)
		v2.GET("/webshell/content", scanResultApi.GetWebshellContent)
		v2.GET("/webshell/file", scanResultApi.GetWebshellFile)
		v2.GET("/sensitive/file", scanResultApi.GetSensitiveFile)
		v2.GET("/malware/file", scanResultApi.GetMalwareFile)
		v2.GET("/license/file", scanResultApi.GetLicenseFile)
	}

	v4 := router.Group("/api/v1/vulns")
	{
		v4.GET("/list", apiVulnSrv.SearchVuln)                   //  漏洞发现列表：在线
		v4.GET("/statistic", apiVulnSrv.Statistic)               // down
		v4.GET("/topNImage", imageBaseApi.TopRiskImage)          // down
		v4.GET("/software", scanResultApi.SearchRelatedSoftware) // 和镜像详情中返回的数据不一样
		v4.GET("/query", imageBaseApi.GetImageByVuln)            // down
	}

	// 安全策略及镜像检测
	detectApi := NewDetectAPI(policySrv)
	v17 := router.Group("/api/v1/security")
	{
		v17.POST("/detect/policy", detectApi.CreatePolicy)
		v17.PUT("/detect/policy", detectApi.UpdatePolicy)
		v17.DELETE("/detect/policy", detectApi.DeletePolicy)
		v17.GET("/detect/policy/list", detectApi.SearchPolicy)
		v17.GET("/detect/policy/detail", detectApi.GetPolicyDetail)
		v17.GET("/detect/policy/snapshot", detectApi.GetPolicySnapshot)
	}

	// 扫描
	v18 := router.Group("/api/v1/scanTask")
	{
		v18.PUT("/image/scan/task/status", scanTaskAPI.UpdateScanTaskStatus)
		v18.PUT("/image/scan/subtask/reschedule", scanTaskAPI.RescheduleScanSubtask)
		v18.POST("/image/scan/task", scanTaskAPI.CreateImageScanTask)
		v18.GET("/image/scan/subtask/list", scanTaskAPI.SearchScanSubtask)
		v18.GET("/image/scan/task/list", scanTaskAPI.SearchScanTask)
	}

	v11 := router.Group("/api/v1/managementCenter")
	{
		v11.GET("/docs", configAPISrv.GetOpenapiDoc)
	}
	// 扫描配置
	v19 := router.Group("/api/v1/config")
	{
		v19.POST("/scan/sensitive/rule", configAPISrv.CreateSensitiveRule)
		v19.PUT("/scan/sensitive/rule", configAPISrv.UpdateSensitiveRule)
		v19.GET("/scan/sensitive/rule/list", configAPISrv.SearchSensitiveRule)
		v19.DELETE("/scan/sensitive/rule", configAPISrv.DeleteSensitiveRule)
		v19.GET("/scan/license/list", configAPISrv.SearchLicense)
		v19.GET("/scan/license/detail", configAPISrv.GetLicense)
		v19.GET("/view/const", configAPISrv.GetConstView)
		v19.GET("/scan/image", configAPISrv.GetScanImageConfig)
		v19.PUT("/scan/image", configAPISrv.UpdateScanImageConfig)
	}
	v21 := router.Group("/api/v1/node")
	{
		v21.GET("/nodeInfo/list", nodeApiSrv.SearchNode)
	}

	// 阻断
	v22 := router.Group("/api/v1/deploy")
	{
		v22.GET("/whiteImage", deployAPI.SearchDeployWhiteImage)
		v22.POST("/whiteImage", deployAPI.CreateDeployWhiteImage)
		v22.PUT("/whiteImage", deployAPI.UpdateDeployWhiteImage)
		v22.DELETE("/whiteImage", deployAPI.DeleteDeployWhiteImage)

		v22.POST("/record", deployAPI.SearchDeployRecord)
		v22.GET("/overview", deployAPI.DeployOverview)
		v22.GET("/blockTrend", deployAPI.DeployOverviewBlockTrend)
		v22.GET("/reasonTop5", deployAPI.DeployReasonTop5)
	}

	return router
}

func OpenAPI(router *gin.Engine,
	// scannerSvc component.ScannerSrv,
	rejectSvc component.ImageRejectSrv,
	// registrySrv component.RegistrySrvInterface,
	// scanConfigSrv component.ScanConfigSrvInterface,
	// vulnSrv component.VulnServiceInterface,
	ciDalSrv ci.CiComponent,
	imageSrv imagemeta.ImageService,
	// syncImageSrv component.SyncImageInterface,
	exportSrv scanReportService.ExportTaskInterface,
) *gin.Engine {

	// apiScannerSrv := openapi.NewScannerOpenAPISrv(scannerSvc, registrySrv, scanConfigSrv, imageSrv)
	apiRejectSrv := NewRejectAPISrv(rejectSvc)
	// scanConfigAPISrv := openapi.NewScanConfigOpenAPISrv(scanConfigSrv)
	// apiVulnSrc := openapi.NewVulnServer(vulnSrv, scannerSvc)

	openAPIRouter := router.Group("/openapi")
	// openApiRouter.Use(RateLimitMiddleware(redisClient, 20))
	// apiSyncImageSrv := NewSyncImageAPISrv(syncImageSrv, registrySrv)
	v1 := openAPIRouter.Group("/v1")
	{
		// image := v1.Group("/images")
		// {
		// 	image.GET("/list", apiScannerSrv.ListImages) // Deprecated:
		// 	image.POST("/list", apiScannerSrv.SearchImages)
		// 	image.GET("/registryProject", apiScannerSrv.GetRegistryProject)
		// 	image.POST("/scan/scantask/v2", apiScannerSrv.CreateScanTask) // Deprecated:
		// 	image.POST("/scan/scantask", apiScannerSrv.CreateScanImageTask)
		// 	image.GET("/detail", apiScannerSrv.GetImageDetails)
		// 	image.GET("/layers", apiScannerSrv.ListImgLayersByImageName)
		// }
		//
		// statistic := v1.Group("/statistic")
		// {
		// 	statistic.GET("/images", apiScannerSrv.ImageStatistic)
		// 	statistic.GET("/vulns", apiVulnSrc.Statistic)
		// }
		//
		// scanConfig := v1.Group("/scanConfig")
		// {
		// 	strategies := scanConfig.Group("/strategies")
		// 	{
		// 		strategies.POST("", scanConfigAPISrv.CreateStrategy2)
		// 		strategies.GET("", scanConfigAPISrv.ListStrategy2)
		// 		strategies.PUT("/:strategyName", scanConfigAPISrv.UpdateStrategyByName)
		// 		strategies.DELETE("/:strategyName", scanConfigAPISrv.DeleteStrategyByName)
		// 		strategies.GET("/:strategyName", scanConfigAPISrv.GetStrategyByName)
		// 	}
		// }
		//
		// vuln := v1.Group("/vulns")
		// {
		// 	vuln.GET("/list", apiVulnSrc.List)
		// 	vuln.GET("/detail", apiVulnSrc.Detail)
		// 	vuln.GET("/topNImage", apiVulnSrc.GetVulnTopNImage)
		// }

		// ci
		ciSrv := NewCiSrv(ciDalSrv, exportSrv)
		cig := v1.Group("/ci")
		{
			cig.GET("/policies", ciSrv.GetCiPolicies)
			cig.GET("/policy/:name", ciSrv.GetCiPolicy)
			cig.GET("/tidb/version", ciSrv.TiDbVersion)
			cig.Static("/tidb/assets", global.ScannerOpts.PvcPath)
			cig.POST("/result", ciSrv.SaveResult)
			cig.POST("/sign", apiRejectSrv.SignImageTrusted)
		}
		// // 和仓库相关
		// register := v1.Group("/register")
		// {
		// 	register.GET("/registries", apiScannerSrv.SearchRegistry)
		// 	register.PUT("/registry", apiScannerSrv.UpdateRegistry)
		// 	register.DELETE("/registry", apiScannerSrv.DeleteRegistry)
		// 	register.POST("/registry", apiScannerSrv.CreateRegistry)
		// }
		//
		// // 和同步镜像相关
		// v12 := v1.Group("/syncImage")
		// {
		// 	v12.POST("/startSync", apiSyncImageSrv.StartSyncByRegName)
		// }
	}

	return router
}

func AddLanguage(ctx *gin.Context) {
	ctx.Set(imagesecModel.AcceptLanguage, util.GetLanguage(ctx))
}
