---
apiVersion: batch/v1
kind: Job
metadata:
  name: platform-report
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: platform-report
    spec:
      containers:
        - name: platform-report
          image: localhost:32000/platform-report:latest
          command: ["/platform-report"]
          imagePullPolicy: Always
          volumeMounts:
            - name: audit
              mountPath: /audit
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "1000Mi"
              cpu: "0.5"
      restartPolicy: Never
      imagePullSecrets:
        - name: harbor-admin-secret
      volumes:
        - name: audit
          persistentVolumeClaim:
            claimName: audit-pvc

  backoffLimit: 0
