// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: net_policy_control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NetPolicyControl_PodUp_FullMethodName            = "/netpolicy.v1.NetPolicyControl/PodUp"
	NetPolicyControl_PodDown_FullMethodName          = "/netpolicy.v1.NetPolicyControl/PodDown"
	NetPolicyControl_AddPolicyRule_FullMethodName    = "/netpolicy.v1.NetPolicyControl/AddPolicyRule"
	NetPolicyControl_DeletePolicyRule_FullMethodName = "/netpolicy.v1.NetPolicyControl/DeletePolicyRule"
	NetPolicyControl_DumpHeapProfile_FullMethodName  = "/netpolicy.v1.NetPolicyControl/DumpHeapProfile"
	NetPolicyControl_DumpConfig_FullMethodName       = "/netpolicy.v1.NetPolicyControl/DumpConfig"
	NetPolicyControl_DumpConnections_FullMethodName  = "/netpolicy.v1.NetPolicyControl/DumpConnections"
	NetPolicyControl_ResetConfig_FullMethodName      = "/netpolicy.v1.NetPolicyControl/ResetConfig"
	NetPolicyControl_UpdateNodeConfig_FullMethodName = "/netpolicy.v1.NetPolicyControl/UpdateNodeConfig"
	NetPolicyControl_SetLogLevel_FullMethodName      = "/netpolicy.v1.NetPolicyControl/SetLogLevel"
)

// NetPolicyControlClient is the client API for NetPolicyControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetPolicyControlClient interface {
	PodUp(ctx context.Context, in *PodUpRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	PodDown(ctx context.Context, in *PodDownRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	AddPolicyRule(ctx context.Context, in *AddPolicyRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeletePolicyRule(ctx context.Context, in *DeletePolicyRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DumpHeapProfile(ctx context.Context, in *DumpHeapProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DumpConfig(ctx context.Context, in *DumpConfigRequest, opts ...grpc.CallOption) (*DumpConfigResponse, error)
	DumpConnections(ctx context.Context, in *DumpConnectionsRequest, opts ...grpc.CallOption) (*DumpConnectionsResponse, error)
	ResetConfig(ctx context.Context, in *ResetConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type netPolicyControlClient struct {
	cc grpc.ClientConnInterface
}

func NewNetPolicyControlClient(cc grpc.ClientConnInterface) NetPolicyControlClient {
	return &netPolicyControlClient{cc}
}

func (c *netPolicyControlClient) PodUp(ctx context.Context, in *PodUpRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_PodUp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) PodDown(ctx context.Context, in *PodDownRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_PodDown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) AddPolicyRule(ctx context.Context, in *AddPolicyRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_AddPolicyRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) DeletePolicyRule(ctx context.Context, in *DeletePolicyRuleRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_DeletePolicyRule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) DumpHeapProfile(ctx context.Context, in *DumpHeapProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_DumpHeapProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) DumpConfig(ctx context.Context, in *DumpConfigRequest, opts ...grpc.CallOption) (*DumpConfigResponse, error) {
	out := new(DumpConfigResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_DumpConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) DumpConnections(ctx context.Context, in *DumpConnectionsRequest, opts ...grpc.CallOption) (*DumpConnectionsResponse, error) {
	out := new(DumpConnectionsResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_DumpConnections_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) ResetConfig(ctx context.Context, in *ResetConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_ResetConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) UpdateNodeConfig(ctx context.Context, in *UpdateNodeConfigRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_UpdateNodeConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *netPolicyControlClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, NetPolicyControl_SetLogLevel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetPolicyControlServer is the server API for NetPolicyControl service.
// All implementations should embed UnimplementedNetPolicyControlServer
// for forward compatibility
type NetPolicyControlServer interface {
	PodUp(context.Context, *PodUpRequest) (*StatusResponse, error)
	PodDown(context.Context, *PodDownRequest) (*StatusResponse, error)
	AddPolicyRule(context.Context, *AddPolicyRuleRequest) (*StatusResponse, error)
	DeletePolicyRule(context.Context, *DeletePolicyRuleRequest) (*StatusResponse, error)
	DumpHeapProfile(context.Context, *DumpHeapProfileRequest) (*StatusResponse, error)
	DumpConfig(context.Context, *DumpConfigRequest) (*DumpConfigResponse, error)
	DumpConnections(context.Context, *DumpConnectionsRequest) (*DumpConnectionsResponse, error)
	ResetConfig(context.Context, *ResetConfigRequest) (*StatusResponse, error)
	UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*StatusResponse, error)
	SetLogLevel(context.Context, *SetLogLevelRequest) (*StatusResponse, error)
}

// UnimplementedNetPolicyControlServer should be embedded to have forward compatible implementations.
type UnimplementedNetPolicyControlServer struct {
}

func (UnimplementedNetPolicyControlServer) PodUp(context.Context, *PodUpRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PodUp not implemented")
}
func (UnimplementedNetPolicyControlServer) PodDown(context.Context, *PodDownRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PodDown not implemented")
}
func (UnimplementedNetPolicyControlServer) AddPolicyRule(context.Context, *AddPolicyRuleRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPolicyRule not implemented")
}
func (UnimplementedNetPolicyControlServer) DeletePolicyRule(context.Context, *DeletePolicyRuleRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicyRule not implemented")
}
func (UnimplementedNetPolicyControlServer) DumpHeapProfile(context.Context, *DumpHeapProfileRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpHeapProfile not implemented")
}
func (UnimplementedNetPolicyControlServer) DumpConfig(context.Context, *DumpConfigRequest) (*DumpConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpConfig not implemented")
}
func (UnimplementedNetPolicyControlServer) DumpConnections(context.Context, *DumpConnectionsRequest) (*DumpConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpConnections not implemented")
}
func (UnimplementedNetPolicyControlServer) ResetConfig(context.Context, *ResetConfigRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetConfig not implemented")
}
func (UnimplementedNetPolicyControlServer) UpdateNodeConfig(context.Context, *UpdateNodeConfigRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeConfig not implemented")
}
func (UnimplementedNetPolicyControlServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLogLevel not implemented")
}

// UnsafeNetPolicyControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetPolicyControlServer will
// result in compilation errors.
type UnsafeNetPolicyControlServer interface {
	mustEmbedUnimplementedNetPolicyControlServer()
}

func RegisterNetPolicyControlServer(s grpc.ServiceRegistrar, srv NetPolicyControlServer) {
	s.RegisterService(&NetPolicyControl_ServiceDesc, srv)
}

func _NetPolicyControl_PodUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).PodUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_PodUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).PodUp(ctx, req.(*PodUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_PodDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).PodDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_PodDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).PodDown(ctx, req.(*PodDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_AddPolicyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPolicyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).AddPolicyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_AddPolicyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).AddPolicyRule(ctx, req.(*AddPolicyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_DeletePolicyRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).DeletePolicyRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_DeletePolicyRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).DeletePolicyRule(ctx, req.(*DeletePolicyRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_DumpHeapProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpHeapProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).DumpHeapProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_DumpHeapProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).DumpHeapProfile(ctx, req.(*DumpHeapProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_DumpConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).DumpConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_DumpConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).DumpConfig(ctx, req.(*DumpConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_DumpConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).DumpConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_DumpConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).DumpConnections(ctx, req.(*DumpConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_ResetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).ResetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_ResetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).ResetConfig(ctx, req.(*ResetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_UpdateNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).UpdateNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_UpdateNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).UpdateNodeConfig(ctx, req.(*UpdateNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetPolicyControl_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetPolicyControlServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetPolicyControl_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetPolicyControlServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetPolicyControl_ServiceDesc is the grpc.ServiceDesc for NetPolicyControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetPolicyControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netpolicy.v1.NetPolicyControl",
	HandlerType: (*NetPolicyControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PodUp",
			Handler:    _NetPolicyControl_PodUp_Handler,
		},
		{
			MethodName: "PodDown",
			Handler:    _NetPolicyControl_PodDown_Handler,
		},
		{
			MethodName: "AddPolicyRule",
			Handler:    _NetPolicyControl_AddPolicyRule_Handler,
		},
		{
			MethodName: "DeletePolicyRule",
			Handler:    _NetPolicyControl_DeletePolicyRule_Handler,
		},
		{
			MethodName: "DumpHeapProfile",
			Handler:    _NetPolicyControl_DumpHeapProfile_Handler,
		},
		{
			MethodName: "DumpConfig",
			Handler:    _NetPolicyControl_DumpConfig_Handler,
		},
		{
			MethodName: "DumpConnections",
			Handler:    _NetPolicyControl_DumpConnections_Handler,
		},
		{
			MethodName: "ResetConfig",
			Handler:    _NetPolicyControl_ResetConfig_Handler,
		},
		{
			MethodName: "UpdateNodeConfig",
			Handler:    _NetPolicyControl_UpdateNodeConfig_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _NetPolicyControl_SetLogLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "net_policy_control.proto",
}
