// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.1
// source: net_policy_events.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NetPolicyEvents_SubscribeEvents_FullMethodName = "/netpolicy.v1.NetPolicyEvents/SubscribeEvents"
)

// NetPolicyEventsClient is the client API for NetPolicyEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetPolicyEventsClient interface {
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (NetPolicyEvents_SubscribeEventsClient, error)
}

type netPolicyEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewNetPolicyEventsClient(cc grpc.ClientConnInterface) NetPolicyEventsClient {
	return &netPolicyEventsClient{cc}
}

func (c *netPolicyEventsClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (NetPolicyEvents_SubscribeEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &NetPolicyEvents_ServiceDesc.Streams[0], NetPolicyEvents_SubscribeEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &netPolicyEventsSubscribeEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NetPolicyEvents_SubscribeEventsClient interface {
	Recv() (*PolicyEvent, error)
	grpc.ClientStream
}

type netPolicyEventsSubscribeEventsClient struct {
	grpc.ClientStream
}

func (x *netPolicyEventsSubscribeEventsClient) Recv() (*PolicyEvent, error) {
	m := new(PolicyEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NetPolicyEventsServer is the server API for NetPolicyEvents service.
// All implementations should embed UnimplementedNetPolicyEventsServer
// for forward compatibility
type NetPolicyEventsServer interface {
	SubscribeEvents(*SubscribeEventsRequest, NetPolicyEvents_SubscribeEventsServer) error
}

// UnimplementedNetPolicyEventsServer should be embedded to have forward compatible implementations.
type UnimplementedNetPolicyEventsServer struct {
}

func (UnimplementedNetPolicyEventsServer) SubscribeEvents(*SubscribeEventsRequest, NetPolicyEvents_SubscribeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}

// UnsafeNetPolicyEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetPolicyEventsServer will
// result in compilation errors.
type UnsafeNetPolicyEventsServer interface {
	mustEmbedUnimplementedNetPolicyEventsServer()
}

func RegisterNetPolicyEventsServer(s grpc.ServiceRegistrar, srv NetPolicyEventsServer) {
	s.RegisterService(&NetPolicyEvents_ServiceDesc, srv)
}

func _NetPolicyEvents_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NetPolicyEventsServer).SubscribeEvents(m, &netPolicyEventsSubscribeEventsServer{stream})
}

type NetPolicyEvents_SubscribeEventsServer interface {
	Send(*PolicyEvent) error
	grpc.ServerStream
}

type netPolicyEventsSubscribeEventsServer struct {
	grpc.ServerStream
}

func (x *netPolicyEventsSubscribeEventsServer) Send(m *PolicyEvent) error {
	return x.ServerStream.SendMsg(m)
}

// NetPolicyEvents_ServiceDesc is the grpc.ServiceDesc for NetPolicyEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetPolicyEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netpolicy.v1.NetPolicyEvents",
	HandlerType: (*NetPolicyEventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _NetPolicyEvents_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "net_policy_events.proto",
}
