// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v7.35.1
// source: net_policy_common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// mirrors FlowDir, net-policy.h:95-96
type FlowDirection int32

const (
	FlowDirection_FLOW_DIRECTION_UNSPECIFIED FlowDirection = 0
	FlowDirection_FLOW_DIRECTION_INGRESS     FlowDirection = 1
	FlowDirection_FLOW_DIRECTION_EGRESS      FlowDirection = 2
)

// Enum value maps for FlowDirection.
var (
	FlowDirection_name = map[int32]string{
		0: "FLOW_DIRECTION_UNSPECIFIED",
		1: "FLOW_DIRECTION_INGRESS",
		2: "FLOW_DIRECTION_EGRESS",
	}
	FlowDirection_value = map[string]int32{
		"FLOW_DIRECTION_UNSPECIFIED": 0,
		"FLOW_DIRECTION_INGRESS":     1,
		"FLOW_DIRECTION_EGRESS":      2,
	}
)

func (x FlowDirection) Enum() *FlowDirection {
	p := new(FlowDirection)
	*p = x
	return p
}

func (x FlowDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_net_policy_common_proto_enumTypes[0].Descriptor()
}

func (FlowDirection) Type() protoreflect.EnumType {
	return &file_net_policy_common_proto_enumTypes[0]
}

func (x FlowDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowDirection.Descriptor instead.
func (FlowDirection) EnumDescriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{0}
}

// mirrors NetPolicyRule (Deny/Allow/Mark), net-policy.cpp:1373-1379 ("Allow"/"Log" -> allow, "Alert" -> mark)
type PolicyAction int32

const (
	PolicyAction_POLICY_ACTION_UNSPECIFIED PolicyAction = 0
	PolicyAction_POLICY_ACTION_DENY        PolicyAction = 1
	PolicyAction_POLICY_ACTION_ALLOW       PolicyAction = 2
	PolicyAction_POLICY_ACTION_ALERT       PolicyAction = 3
)

// Enum value maps for PolicyAction.
var (
	PolicyAction_name = map[int32]string{
		0: "POLICY_ACTION_UNSPECIFIED",
		1: "POLICY_ACTION_DENY",
		2: "POLICY_ACTION_ALLOW",
		3: "POLICY_ACTION_ALERT",
	}
	PolicyAction_value = map[string]int32{
		"POLICY_ACTION_UNSPECIFIED": 0,
		"POLICY_ACTION_DENY":        1,
		"POLICY_ACTION_ALLOW":       2,
		"POLICY_ACTION_ALERT":       3,
	}
)

func (x PolicyAction) Enum() *PolicyAction {
	p := new(PolicyAction)
	*p = x
	return p
}

func (x PolicyAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyAction) Descriptor() protoreflect.EnumDescriptor {
	return file_net_policy_common_proto_enumTypes[1].Descriptor()
}

func (PolicyAction) Type() protoreflect.EnumType {
	return &file_net_policy_common_proto_enumTypes[1]
}

func (x PolicyAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyAction.Descriptor instead.
func (PolicyAction) EnumDescriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{1}
}

type L4Protocol int32

const (
	L4Protocol_L4_PROTOCOL_UNSPECIFIED L4Protocol = 0
	L4Protocol_L4_PROTOCOL_TCP         L4Protocol = 1
	L4Protocol_L4_PROTOCOL_UDP         L4Protocol = 2
	L4Protocol_L4_PROTOCOL_ICMP        L4Protocol = 3
)

// Enum value maps for L4Protocol.
var (
	L4Protocol_name = map[int32]string{
		0: "L4_PROTOCOL_UNSPECIFIED",
		1: "L4_PROTOCOL_TCP",
		2: "L4_PROTOCOL_UDP",
		3: "L4_PROTOCOL_ICMP",
	}
	L4Protocol_value = map[string]int32{
		"L4_PROTOCOL_UNSPECIFIED": 0,
		"L4_PROTOCOL_TCP":         1,
		"L4_PROTOCOL_UDP":         2,
		"L4_PROTOCOL_ICMP":        3,
	}
)

func (x L4Protocol) Enum() *L4Protocol {
	p := new(L4Protocol)
	*p = x
	return p
}

func (x L4Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L4Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_net_policy_common_proto_enumTypes[2].Descriptor()
}

func (L4Protocol) Type() protoreflect.EnumType {
	return &file_net_policy_common_proto_enumTypes[2]
}

func (x L4Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L4Protocol.Descriptor instead.
func (L4Protocol) EnumDescriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{2}
}

// mirrors RULE_PORT / RulePort, net-policy.h:194-200; end_port == 0 means "same as port"
type PortRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port    uint32 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	EndPort uint32 `protobuf:"varint,2,opt,name=end_port,json=endPort,proto3" json:"end_port,omitempty"`
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_policy_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_net_policy_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{0}
}

func (x *PortRange) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PortRange) GetEndPort() uint32 {
	if x != nil {
		return x.EndPort
	}
	return 0
}

// mirrors HTTP_RULE_INFO's host/method/path fields, net-policy.h:209-216
type HttpMatchRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host   string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HttpMatchRule) Reset() {
	*x = HttpMatchRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_policy_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpMatchRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpMatchRule) ProtoMessage() {}

func (x *HttpMatchRule) ProtoReflect() protoreflect.Message {
	mi := &file_net_policy_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpMatchRule.ProtoReflect.Descriptor instead.
func (*HttpMatchRule) Descriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{1}
}

func (x *HttpMatchRule) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HttpMatchRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpMatchRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// mirrors one element of rules[].from_addresses[]/to_addresses[], net-policy.cpp:1519-1544, 1578-1602.
type AddressEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip    string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	PodId uint64 `protobuf:"varint,2,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
}

func (x *AddressEndpoint) Reset() {
	*x = AddressEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_net_policy_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressEndpoint) ProtoMessage() {}

func (x *AddressEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_net_policy_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressEndpoint.ProtoReflect.Descriptor instead.
func (*AddressEndpoint) Descriptor() ([]byte, []int) {
	return file_net_policy_common_proto_rawDescGZIP(), []int{2}
}

func (x *AddressEndpoint) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddressEndpoint) GetPodId() uint64 {
	if x != nil {
		return x.PodId
	}
	return 0
}

var File_net_policy_common_proto protoreflect.FileDescriptor

var file_net_policy_common_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6e, 0x65, 0x74, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6e, 0x65, 0x74, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x3a, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x50,
	0x6f, 0x72, 0x74, 0x22, 0x4f, 0x0a, 0x0d, 0x48, 0x74, 0x74, 0x70, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x38, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x2a, 0x66,
	0x0a, 0x0d, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x1a, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x1a, 0x0a, 0x16, 0x46, 0x4c, 0x4f, 0x57, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x49, 0x4e, 0x47, 0x52, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x46,
	0x4c, 0x4f, 0x57, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x47,
	0x52, 0x45, 0x53, 0x53, 0x10, 0x02, 0x2a, 0x77, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x19, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x01, 0x12, 0x17, 0x0a,
	0x13, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41,
	0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x4f, 0x4c, 0x49, 0x43, 0x59,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x10, 0x03, 0x2a,
	0x69, 0x0a, 0x0a, 0x4c, 0x34, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x1b, 0x0a,
	0x17, 0x4c, 0x34, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4c, 0x34,
	0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x54, 0x43, 0x50, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x4c, 0x34, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f, 0x4c, 0x5f, 0x55,
	0x44, 0x50, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x34, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f,
	0x43, 0x4f, 0x4c, 0x5f, 0x49, 0x43, 0x4d, 0x50, 0x10, 0x03, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_net_policy_common_proto_rawDescOnce sync.Once
	file_net_policy_common_proto_rawDescData = file_net_policy_common_proto_rawDesc
)

func file_net_policy_common_proto_rawDescGZIP() []byte {
	file_net_policy_common_proto_rawDescOnce.Do(func() {
		file_net_policy_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_net_policy_common_proto_rawDescData)
	})
	return file_net_policy_common_proto_rawDescData
}

var file_net_policy_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_net_policy_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_net_policy_common_proto_goTypes = []interface{}{
	(FlowDirection)(0),      // 0: netpolicy.v1.FlowDirection
	(PolicyAction)(0),       // 1: netpolicy.v1.PolicyAction
	(L4Protocol)(0),         // 2: netpolicy.v1.L4Protocol
	(*PortRange)(nil),       // 3: netpolicy.v1.PortRange
	(*HttpMatchRule)(nil),   // 4: netpolicy.v1.HttpMatchRule
	(*AddressEndpoint)(nil), // 5: netpolicy.v1.AddressEndpoint
}
var file_net_policy_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_net_policy_common_proto_init() }
func file_net_policy_common_proto_init() {
	if File_net_policy_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_net_policy_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_policy_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpMatchRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_net_policy_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_net_policy_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_net_policy_common_proto_goTypes,
		DependencyIndexes: file_net_policy_common_proto_depIdxs,
		EnumInfos:         file_net_policy_common_proto_enumTypes,
		MessageInfos:      file_net_policy_common_proto_msgTypes,
	}.Build()
	File_net_policy_common_proto = out.File
	file_net_policy_common_proto_rawDesc = nil
	file_net_policy_common_proto_goTypes = nil
	file_net_policy_common_proto_depIdxs = nil
}
