#scanner config
scanner:
  -
    registry:
      type: registry-v2
      options:
        url: http://docker-registry:5000
        username: testuser
        password: testpassword
        skiptlsverify: true
        paginationkey:
        usetype: 2
#    -
#      registry:
#        type: harbor-v2.0
#        options:
#          url: http://192.168.199.107:30000
#          username: admin
#          password: Harbor12345
#          skiptlsverify: true
#          paginationkey:
  -
    registry:
      type: harbor-v2.0
      options:
        url: https://registry.t-appagile.com
        username: admin
        password: Hrbr12@Tensor.*#)
        skiptlsverify: true
        paginationkey:
        usetype: 1
