
syntax = "proto3";
package consumer;
message EventInfoT {
	bytes procName = 1;
	uint64 ts = 2;
	uint32 pid = 3;
	uint32 tid = 4;
	uint32 gid = 5;
	uint32 uid = 6;
	uint32 euid = 7;
	uint32 egid = 8;
	uint32 major = 9;
	uint32 minor = 10;
	uint32 nsid = 11;
	repeated uint32 fileType = 12;
	repeated uint32 sports = 13;
	repeated uint32 dports = 14;
	repeated uint32 saddrs = 15;
	repeated uint32 daddrs = 16;
	repeated uint64 inodes = 17;
	uint32 ptid = 18;
	uint32 ptgid = 19;
	bytes eventName = 20;
	uint32 netns = 21;
	repeated uint32 protos = 22;
	int64 ret = 23;
}

message Msg {
	bool isSyscall = 1;
	EventInfoT eventInfo = 2;
	uint64	TimeTloc = 3; 
	uint64	MigratePagesPid = 4; 
	uint64	MigratePagesMaxnode = 5; 
	uint64	MigratePagesOldNodes = 6; 
	uint64	MigratePagesNewNodes = 7; 
	string	LsetxattrPathname = 8; 
	string	LsetxattrName = 9; 
	uint64	LsetxattrValue = 10; 
	uint64	LsetxattrSize = 11; 
	uint64	LsetxattrFlags = 12; 
	uint64	ClockGetresWhichClock = 13; 
	uint64	ClockGetresTp = 14; 
	uint64	SetTidAddressTidptr = 15; 
	uint64	Pipe2Fildes = 16; 
	uint64	Pipe2Readfd = 17; 
	uint64	Pipe2Writefd = 18; 
	uint64	Pipe2Flags = 19; 
	string	SethostnameName = 20; 
	uint64	SethostnameLen = 21; 
	uint64	Dup3Oldfd = 22; 
	uint64	Dup3Newfd = 23; 
	uint64	Dup3Flags = 24; 
	uint64	UmaskMask = 25; 
	uint64	ExitGroupErrorCode = 26; 
	uint64	SetRobustListHead = 27; 
	uint64	SetRobustListLen = 28; 
	uint64	IoplLevel = 29; 
	string	LgetxattrPathname = 30; 
	string	LgetxattrName = 31; 
	uint64	LgetxattrValue = 32; 
	uint64	LgetxattrSize = 33; 
	uint64	KillPid = 34; 
	uint64	KillSig = 35; 
	uint64	Pread64Fd = 36; 
	string	Pread64Buf = 37; 
	uint64	Pread64Count = 38; 
	uint64	Pread64Pos = 39; 
	uint64	NewfstatatDfd = 40; 
	string	NewfstatatFilename = 41; 
	uint64	NewfstatatStatbuf = 42; 
	uint64	NewfstatatFlag = 43; 
	string	NewlstatFilename = 44; 
	uint64	NewlstatStatbuf = 45; 
	uint64	WriteFd = 46; 
	string	WriteBuf = 47; 
	uint64	WriteCount = 48; 
	uint64	SetregidRgid = 49; 
	uint64	SetregidEgid = 50; 
	uint64	UstatDev = 51; 
	uint64	UstatUbuf = 52; 
	uint64	GetrlimitResource = 53; 
	uint64	GetrlimitRlim = 54; 
	uint64	TkillPid = 55; 
	uint64	TkillSig = 56; 
	uint64	Dup2Oldfd = 57; 
	uint64	Dup2Newfd = 58; 
	uint64	ClockAdjtimeWhichClock = 59; 
	uint64	ClockAdjtimeUtx = 60; 
	uint64	RtSigqueueinfoPid = 61; 
	uint64	RtSigqueueinfoSig = 62; 
	uint64	RtSigqueueinfoUinfo = 63; 
	string	UtimeFilename = 64; 
	uint64	UtimeTimes = 65; 
	string	SetxattrPathname = 66; 
	string	SetxattrName = 67; 
	uint64	SetxattrValue = 68; 
	uint64	SetxattrSize = 69; 
	uint64	SetxattrFlags = 70; 
	uint64	MembarrierCmd = 71; 
	uint64	MembarrierFlags = 72; 
	uint64	MlockStart = 73; 
	uint64	MlockLen = 74; 
	uint64	TeeFdin = 75; 
	uint64	TeeFdout = 76; 
	uint64	TeeLen = 77; 
	uint64	TeeFlags = 78; 
	uint64	SetpgidPid = 79; 
	uint64	SetpgidPgid = 80; 
	string	UtimesFilename = 81; 
	uint64	UtimesUtimes = 82; 
	string	LremovexattrPathname = 83; 
	string	LremovexattrName = 84; 
	string	LinkOldname = 85; 
	string	LinkNewname = 86; 
	uint64	ReadvFd = 87; 
	uint64	ReadvVec = 88; 
	uint64	ReadvVlen = 89; 
	uint64	FutexUaddr = 90; 
	uint64	FutexOp = 91; 
	uint64	FutexVal = 92; 
	uint64	FutexUtime = 93; 
	uint64	FutexUaddr2 = 94; 
	uint64	FutexVal3 = 95; 
	string	GetxattrPathname = 96; 
	string	GetxattrName = 97; 
	uint64	GetxattrValue = 98; 
	uint64	GetxattrSize = 99; 
	uint64	SchedGetPriorityMaxPolicy = 100; 
	uint64	Preadv2Fd = 101; 
	uint64	Preadv2Vec = 102; 
	uint64	Preadv2Vlen = 103; 
	uint64	Preadv2PosL = 104; 
	uint64	Preadv2PosH = 105; 
	uint64	Preadv2Flags = 106; 
	uint64	ReadlinkatDfd = 107; 
	string	ReadlinkatPathname = 108; 
	string	ReadlinkatBuf = 109; 
	uint64	ReadlinkatBufsiz = 110; 
	uint64	PrctlOption = 111; 
	uint64	PrctlArg2 = 112; 
	uint64	PrctlArg3 = 113; 
	uint64	PrctlArg4 = 114; 
	uint64	PrctlArg5 = 115; 
	uint64	RenameatOlddfd = 116; 
	string	RenameatOldname = 117; 
	uint64	RenameatNewdfd = 118; 
	string	RenameatNewname = 119; 
	uint64	Renameat2Olddfd = 120; 
	string	Renameat2Oldname = 121; 
	uint64	Renameat2Newdfd = 122; 
	string	Renameat2Newname = 123; 
	uint64	Renameat2Flags = 124; 
	uint64	SendmmsgFd = 125; 
	uint64	SendmmsgMmsg = 126; 
	uint64	SendmmsgVlen = 127; 
	uint64	SendmmsgFlags = 128; 
	uint64	ModifyLdtFunc = 129; 
	uint64	ModifyLdtPtr = 130; 
	uint64	ModifyLdtBytecount = 131; 
	uint64	CloseFd = 132; 
	uint64	IoprioGetWhich = 133; 
	uint64	IoprioGetWho = 134; 
	uint64	SetreuidRuid = 135; 
	uint64	SetreuidEuid = 136; 
	uint64	Sendfile64OutFd = 137; 
	uint64	Sendfile64InFd = 138; 
	uint64	Sendfile64Offset = 139; 
	uint64	Sendfile64Count = 140; 
	string	StatfsPathname = 141; 
	uint64	StatfsBuf = 142; 
	uint64	GetpriorityWhich = 143; 
	uint64	GetpriorityWho = 144; 
	string	TruncatePath = 145; 
	uint64	TruncateLength = 146; 
	uint64	GetcpuCpup = 147; 
	uint64	GetcpuNodep = 148; 
	uint64	GetcpuUnused = 149; 
	uint64	ShmatShmid = 150; 
	string	ShmatShmaddr = 151; 
	uint64	ShmatShmflg = 152; 
	string	SwaponSpecialfile = 153; 
	uint64	SwaponSwapFlags = 154; 
	uint64	WaitidWhich = 155; 
	uint64	WaitidUpid = 156; 
	uint64	WaitidInfop = 157; 
	uint64	WaitidOptions = 158; 
	uint64	WaitidRu = 159; 
	uint64	SyncFileRangeFd = 160; 
	uint64	SyncFileRangeOffset = 161; 
	uint64	SyncFileRangeNbytes = 162; 
	uint64	SyncFileRangeFlags = 163; 
	uint64	SchedRrGetIntervalPid = 164; 
	uint64	SchedRrGetIntervalInterval = 165; 
	uint64	SchedGetschedulerPid = 166; 
	uint64	SignalfdUfd = 167; 
	uint64	SignalfdUserMask = 168; 
	uint64	SignalfdSizemask = 169; 
	uint64	Accept4Fd = 170; 
	uint64	Accept4UpeerSockaddr = 171; 
	uint64	Accept4UpeerAddrlen = 172; 
	uint64	Accept4Flags = 173; 
	uint64	IoDestroyCtx = 174; 
	uint64	ShutdownFd = 175; 
	uint64	ShutdownHow = 176; 
	uint64	ExecveatFd = 177; 
	string	ExecveatFilename = 178; 
	string	ExecveatArgv1 = 179; 
	string	ExecveatArgv2 = 180; 
	string	ExecveatArgv3 = 181; 
	uint64	ExecveatEnvp = 182; 
	uint64	ExecveatFlags = 183; 
	uint64	ReadaheadFd = 184; 
	uint64	ReadaheadOffset = 185; 
	uint64	ReadaheadCount = 186; 
	uint64	MsgrcvMsqid = 187; 
	uint64	MsgrcvMsgp = 188; 
	uint64	MsgrcvMsgsz = 189; 
	uint64	MsgrcvMsgtyp = 190; 
	uint64	MsgrcvMsgflg = 191; 
	string	RemovexattrPathname = 192; 
	string	RemovexattrName = 193; 
	uint64	ShmctlShmid = 194; 
	uint64	ShmctlCmd = 195; 
	uint64	ShmctlBuf = 196; 
	uint64	SendmsgFd = 197; 
	uint64	SendmsgMsg = 198; 
	uint64	SendmsgFlags = 199; 
	uint64	SetrlimitResource = 200; 
	uint64	SetrlimitRlim = 201; 
	uint64	MunmapAddr = 202; 
	uint64	MunmapLen = 203; 
	uint64	ExitErrorCode = 204; 
	uint64	IoGeteventsCtxId = 205; 
	uint64	IoGeteventsMinNr = 206; 
	uint64	IoGeteventsNr = 207; 
	uint64	IoGeteventsEvents = 208; 
	uint64	IoGeteventsTimeout = 209; 
	string	SymlinkOldname = 210; 
	string	SymlinkNewname = 211; 
	uint64	RtSigpendingUset = 212; 
	uint64	RtSigpendingSigsetsize = 213; 
	uint64	FanotifyInitFlags = 214; 
	uint64	FanotifyInitEventFFlags = 215; 
	uint64	GetpeernameFd = 216; 
	uint64	GetpeernameUsockaddr = 217; 
	uint64	GetpeernameUsockaddrLen = 218; 
	uint64	FsetxattrFd = 219; 
	string	FsetxattrName = 220; 
	uint64	FsetxattrValue = 221; 
	uint64	FsetxattrSize = 222; 
	uint64	FsetxattrFlags = 223; 
	string	AcctName = 224; 
	uint64	TimesTbuf = 225; 
	uint64	MsggetKey = 226; 
	uint64	MsggetMsgflg = 227; 
	uint64	InotifyAddWatchFd = 228; 
	string	InotifyAddWatchPathname = 229; 
	uint64	InotifyAddWatchMask = 230; 
	uint64	TimerfdGettimeUfd = 231; 
	uint64	TimerfdGettimeOtmr = 232; 
	uint64	RtTgsigqueueinfoTgid = 233; 
	uint64	RtTgsigqueueinfoPid = 234; 
	uint64	RtTgsigqueueinfoSig = 235; 
	uint64	RtTgsigqueueinfoUinfo = 236; 
	uint64	TimerDeleteTimerId = 237; 
	uint64	PkeyAllocFlags = 238; 
	uint64	PkeyAllocInitVal = 239; 
	uint64	SetfsgidGid = 240; 
	uint64	TgkillTgid = 241; 
	uint64	TgkillPid = 242; 
	uint64	TgkillSig = 243; 
	uint64	SetgidGid = 244; 
	uint64	AdjtimexTxcP = 245; 
	uint64	FgetxattrFd = 246; 
	string	FgetxattrName = 247; 
	uint64	FgetxattrValue = 248; 
	uint64	FgetxattrSize = 249; 
	uint64	PkeyMprotectStart = 250; 
	uint64	PkeyMprotectLen = 251; 
	uint64	PkeyMprotectProt = 252; 
	uint64	PkeyMprotectPkey = 253; 
	uint64	SchedSetschedulerPid = 254; 
	uint64	SchedSetschedulerPolicy = 255; 
	uint64	SchedSetschedulerParam = 256; 
	uint64	MqNotifyMqdes = 257; 
	uint64	MqNotifyUNotification = 258; 
	uint64	EpollPwaitEpfd = 259; 
	uint64	EpollPwaitEvents = 260; 
	uint64	EpollPwaitMaxevents = 261; 
	uint64	EpollPwaitTimeout = 262; 
	uint64	EpollPwaitSigmask = 263; 
	uint64	EpollPwaitSigsetsize = 264; 
	uint64	SyncfsFd = 265; 
	string	GetrandomBuf = 266; 
	uint64	GetrandomCount = 267; 
	uint64	GetrandomFlags = 268; 
	string	CreatPathname = 269; 
	uint64	CreatMode = 270; 
	uint64	PpollUfds = 271; 
	uint64	PpollNfds = 272; 
	uint64	PpollTsp = 273; 
	uint64	PpollSigmask = 274; 
	uint64	PpollSigsetsize = 275; 
	uint64	FutimesatDfd = 276; 
	string	FutimesatFilename = 277; 
	uint64	FutimesatUtimes = 278; 
	uint64	KexecLoadEntry = 279; 
	uint64	KexecLoadNrSegments = 280; 
	uint64	KexecLoadSegments = 281; 
	uint64	KexecLoadFlags = 282; 
	uint64	FanotifyMarkFanotifyFd = 283; 
	uint64	FanotifyMarkFlags = 284; 
	uint64	FanotifyMarkMask = 285; 
	uint64	FanotifyMarkDfd = 286; 
	string	FanotifyMarkPathname = 287; 
	string	ChrootFilename = 288; 
	uint64	SelectN = 289; 
	uint64	SelectInp = 290; 
	uint64	SelectOutp = 291; 
	uint64	SelectExp = 292; 
	uint64	SelectTvp = 293; 
	uint64	GetrusageWho = 294; 
	uint64	GetrusageRu = 295; 
	uint64	PwritevFd = 296; 
	uint64	PwritevVec = 297; 
	uint64	PwritevVlen = 298; 
	uint64	PwritevPosL = 299; 
	uint64	PwritevPosH = 300; 
	uint64	GetsockoptFd = 301; 
	uint64	GetsockoptLevel = 302; 
	uint64	GetsockoptOptname = 303; 
	string	GetsockoptOptval = 304; 
	uint64	GetsockoptOptlen = 305; 
	string	RenameOldname = 306; 
	string	RenameNewname = 307; 
	uint64	FstatfsFd = 308; 
	uint64	FstatfsBuf = 309; 
	uint64	SysfsOption = 310; 
	uint64	SysfsArg1 = 311; 
	uint64	SysfsArg2 = 312; 
	uint64	MincoreStart = 313; 
	uint64	MincoreLen = 314; 
	uint64	MincoreVec = 315; 
	uint64	CopyFileRangeFdIn = 316; 
	uint64	CopyFileRangeOffIn = 317; 
	uint64	CopyFileRangeFdOut = 318; 
	uint64	CopyFileRangeOffOut = 319; 
	uint64	CopyFileRangeLen = 320; 
	uint64	CopyFileRangeFlags = 321; 
	uint64	SpliceFdIn = 322; 
	uint64	SpliceOffIn = 323; 
	uint64	SpliceFdOut = 324; 
	uint64	SpliceOffOut = 325; 
	uint64	SpliceLen = 326; 
	uint64	SpliceFlags = 327; 
	string	NewstatFilename = 328; 
	uint64	NewstatStatbuf = 329; 
	uint64	ProcessVmWritevPid = 330; 
	uint64	ProcessVmWritevLvec = 331; 
	uint64	ProcessVmWritevLiovcnt = 332; 
	uint64	ProcessVmWritevRvec = 333; 
	uint64	ProcessVmWritevRiovcnt = 334; 
	uint64	ProcessVmWritevFlags = 335; 
	uint64	TimerGettimeTimerId = 336; 
	uint64	TimerGettimeSetting = 337; 
	string	PivotRootNewRoot = 338; 
	string	PivotRootPutOld = 339; 
	uint64	NameToHandleAtDfd = 340; 
	string	NameToHandleAtName = 341; 
	uint64	NameToHandleAtHandle = 342; 
	uint64	NameToHandleAtMntId = 343; 
	uint64	NameToHandleAtFlag = 344; 
	uint64	BindFd = 345; 
	uint64	BindUmyaddr = 346; 
	uint64	BindAddrlen = 347; 
	string	ReadlinkPath = 348; 
	string	ReadlinkBuf = 349; 
	uint64	ReadlinkBufsiz = 350; 
	uint64	SetuidUid = 351; 
	uint64	MremapAddr = 352; 
	uint64	MremapOldLen = 353; 
	uint64	MremapNewLen = 354; 
	uint64	MremapFlags = 355; 
	uint64	MremapNewAddr = 356; 
	uint64	KeyctlOption = 357; 
	uint64	KeyctlArg2 = 358; 
	uint64	KeyctlArg3 = 359; 
	uint64	KeyctlArg4 = 360; 
	uint64	KeyctlArg5 = 361; 
	uint64	Pselect6N = 362; 
	uint64	Pselect6Inp = 363; 
	uint64	Pselect6Outp = 364; 
	uint64	Pselect6Exp = 365; 
	uint64	Pselect6Tsp = 366; 
	uint64	Pselect6Sig = 367; 
	string	DeleteModuleNameUser = 368; 
	uint64	DeleteModuleFlags = 369; 
	uint64	UtimensatDfd = 370; 
	string	UtimensatFilename = 371; 
	uint64	UtimensatUtimes = 372; 
	uint64	UtimensatFlags = 373; 
	uint64	GetMempolicyPolicy = 374; 
	uint64	GetMempolicyNmask = 375; 
	uint64	GetMempolicyMaxnode = 376; 
	uint64	GetMempolicyAddr = 377; 
	uint64	GetMempolicyFlags = 378; 
	uint64	DupFildes = 379; 
	uint64	EventfdCount = 380; 
	uint64	RecvfromFd = 381; 
	uint64	RecvfromUbuf = 382; 
	uint64	RecvfromSize = 383; 
	uint64	RecvfromFlags = 384; 
	uint64	RecvfromAddr = 385; 
	uint64	RecvfromAddrLen = 386; 
	uint64	StatxDfd = 387; 
	string	StatxFilename = 388; 
	uint64	StatxFlags = 389; 
	uint64	StatxMask = 390; 
	uint64	StatxBuffer = 391; 
	uint64	RtSigactionSig = 392; 
	uint64	RtSigactionAct = 393; 
	uint64	RtSigactionOact = 394; 
	uint64	RtSigactionSigsetsize = 395; 
	uint64	GetdentsFd = 396; 
	uint64	GetdentsDirent = 397; 
	uint64	GetdentsCount = 398; 
	uint64	EpollCreate1Flags = 399; 
	uint64	Wait4Upid = 400; 
	uint64	Wait4StatAddr = 401; 
	uint64	Wait4Options = 402; 
	uint64	Wait4Ru = 403; 
	uint64	MlockallFlags = 404; 
	uint64	SchedGetattrPid = 405; 
	uint64	SchedGetattrUattr = 406; 
	uint64	SchedGetattrSize = 407; 
	uint64	SchedGetattrFlags = 408; 
	uint64	SetpriorityWhich = 409; 
	uint64	SetpriorityWho = 410; 
	uint64	SetpriorityNiceval = 411; 
	uint64	SocketFamily = 412; 
	uint64	SocketType = 413; 
	uint64	SocketProtocol = 414; 
	uint64	SemtimedopSemid = 415; 
	uint64	SemtimedopTsops = 416; 
	uint64	SemtimedopNsops = 417; 
	uint64	SemtimedopTimeout = 418; 
	uint64	SetfsuidUid = 419; 
	uint64	EpollCreateSize = 420; 
	uint64	SemopSemid = 421; 
	uint64	SemopTsops = 422; 
	uint64	SemopNsops = 423; 
	string	OpenFilename = 424; 
	uint64	OpenFlags = 425; 
	uint64	OpenMode = 426; 
	uint64	OpenatDfd = 427; 
	string	OpenatFilename = 428; 
	uint64	OpenatFlags = 429; 
	uint64	OpenatMode = 430; 
	uint64	FremovexattrFd = 431; 
	string	FremovexattrName = 432; 
	uint64	FaccessatDfd = 433; 
	string	FaccessatFilename = 434; 
	uint64	FaccessatMode = 435; 
	uint64	FtruncateFd = 436; 
	uint64	FtruncateLength = 437; 
	uint64	SchedGetPriorityMinPolicy = 438; 
	uint64	MovePagesPid = 439; 
	uint64	MovePagesNrPages = 440; 
	uint64	MovePagesPages = 441; 
	uint64	MovePagesNodes = 442; 
	uint64	MovePagesStatus = 443; 
	uint64	MovePagesFlags = 444; 
	uint64	LseekFd = 445; 
	uint64	LseekOffset = 446; 
	uint64	LseekWhence = 447; 
	uint64	PollUfds = 448; 
	uint64	PollNfds = 449; 
	uint64	PollTimeoutMsecs = 450; 
	uint64	FdatasyncFd = 451; 
	uint64	FsyncFd = 452; 
	uint64	SetsockoptFd = 453; 
	uint64	SetsockoptLevel = 454; 
	uint64	SetsockoptOptname = 455; 
	string	SetsockoptOptval = 456; 
	uint64	SetsockoptOptlen = 457; 
	uint64	TimerGetoverrunTimerId = 458; 
	uint64	CapsetHeader = 459; 
	uint64	CapsetData = 460; 
	uint64	SemgetKey = 461; 
	uint64	SemgetNsems = 462; 
	uint64	SemgetSemflg = 463; 
	uint64	Prlimit64Pid = 464; 
	uint64	Prlimit64Resource = 465; 
	uint64	Prlimit64NewRlim = 466; 
	uint64	Prlimit64OldRlim = 467; 
	string	MqUnlinkUName = 468; 
	uint64	ClockSettimeWhichClock = 469; 
	uint64	ClockSettimeTp = 470; 
	uint64	RtSigtimedwaitUthese = 471; 
	uint64	RtSigtimedwaitUinfo = 472; 
	uint64	RtSigtimedwaitUts = 473; 
	uint64	RtSigtimedwaitSigsetsize = 474; 
	uint64	SigaltstackUss = 475; 
	uint64	SigaltstackUoss = 476; 
	uint64	ShmgetKey = 477; 
	uint64	ShmgetSize = 478; 
	uint64	ShmgetShmflg = 479; 
	uint64	WritevFd = 480; 
	uint64	WritevVec = 481; 
	uint64	WritevVlen = 482; 
	uint64	MprotectStart = 483; 
	uint64	MprotectLen = 484; 
	uint64	MprotectProt = 485; 
	uint64	SetitimerWhich = 486; 
	uint64	SetitimerValue = 487; 
	uint64	SetitimerOvalue = 488; 
	uint64	RemapFilePagesStart = 489; 
	uint64	RemapFilePagesSize = 490; 
	uint64	RemapFilePagesProt = 491; 
	uint64	RemapFilePagesPgoff = 492; 
	uint64	RemapFilePagesFlags = 493; 
	uint64	GetresgidRgidp = 494; 
	uint64	GetresgidEgidp = 495; 
	uint64	GetresgidSgidp = 496; 
	uint64	SeccompOp = 497; 
	uint64	SeccompFlags = 498; 
	string	SeccompUargs = 499; 
	uint64	GettimeofdayTv = 500; 
	uint64	GettimeofdayTz = 501; 
	uint64	GetsocknameFd = 502; 
	uint64	GetsocknameUsockaddr = 503; 
	uint64	GetsocknameUsockaddrLen = 504; 
	string	SymlinkatOldname = 505; 
	uint64	SymlinkatNewdfd = 506; 
	string	SymlinkatNewname = 507; 
	uint64	TimerCreateWhichClock = 508; 
	uint64	TimerCreateTimerEventSpec = 509; 
	uint64	TimerCreateCreatedTimerId = 510; 
	string	ListxattrPathname = 511; 
	string	ListxattrList = 512; 
	uint64	ListxattrSize = 513; 
	uint64	KexecFileLoadKernelFd = 514; 
	uint64	KexecFileLoadInitrdFd = 515; 
	uint64	KexecFileLoadCmdlineLen = 516; 
	string	KexecFileLoadCmdlinePtr = 517; 
	uint64	KexecFileLoadFlags = 518; 
	uint64	MsgsndMsqid = 519; 
	uint64	MsgsndMsgp = 520; 
	uint64	MsgsndMsgsz = 521; 
	uint64	MsgsndMsgflg = 522; 
	uint64	UnlinkatDfd = 523; 
	string	UnlinkatPathname = 524; 
	uint64	UnlinkatFlag = 525; 
	string	ExecveFilename = 526; 
	string	ExecveArgv1 = 527; 
	string	ExecveArgv2 = 528; 
	string	ExecveArgv3 = 529; 
	uint64	ExecveEnvp = 530; 
	uint64	CloneCloneFlags = 531; 
	uint64	CloneNewsp = 532; 
	uint64	CloneParentTidptr = 533; 
	uint64	CloneChildTidptr = 534; 
	uint64	CloneTls = 535; 
	uint64	RseqRseq = 536; 
	uint64	RseqRseqLen = 537; 
	uint64	RseqFlags = 538; 
	uint64	RseqSig = 539; 
	uint64	FinitModuleFd = 540; 
	string	FinitModuleUargs = 541; 
	uint64	FinitModuleFlags = 542; 
	uint64	PkeyFreePkey = 543; 
	uint64	BrkBrk = 544; 
	uint64	SetresuidRuid = 545; 
	uint64	SetresuidEuid = 546; 
	uint64	SetresuidSuid = 547; 
	uint64	RtSigsuspendUnewset = 548; 
	uint64	RtSigsuspendSigsetsize = 549; 
	string	LchownFilename = 550; 
	uint64	LchownUser = 551; 
	uint64	LchownGroup = 552; 
	uint64	FallocateFd = 553; 
	uint64	FallocateMode = 554; 
	uint64	FallocateOffset = 555; 
	uint64	FallocateLen = 556; 
	uint64	IoprioSetWhich = 557; 
	uint64	IoprioSetWho = 558; 
	uint64	IoprioSetIoprio = 559; 
	uint64	MknodatDfd = 560; 
	string	MknodatFilename = 561; 
	uint64	MknodatMode = 562; 
	uint64	MknodatDev = 563; 
	uint64	PipeFildes = 564; 
	uint64	PipeReadfd = 565; 
	uint64	PipeWritefd = 566; 
	uint64	RebootMagic1 = 567; 
	uint64	RebootMagic2 = 568; 
	uint64	RebootCmd = 569; 
	uint64	RebootArg = 570; 
	uint64	Eventfd2Count = 571; 
	uint64	Eventfd2Flags = 572; 
	string	UnlinkPathname = 573; 
	uint64	RecvmmsgFd = 574; 
	uint64	RecvmmsgMmsg = 575; 
	uint64	RecvmmsgVlen = 576; 
	uint64	RecvmmsgFlags = 577; 
	uint64	RecvmmsgTimeout = 578; 
	uint64	MsyncStart = 579; 
	uint64	MsyncLen = 580; 
	uint64	MsyncFlags = 581; 
	string	AccessFilename = 582; 
	uint64	AccessMode = 583; 
	uint64	Signalfd4Ufd = 584; 
	uint64	Signalfd4UserMask = 585; 
	uint64	Signalfd4Sizemask = 586; 
	uint64	Signalfd4Flags = 587; 
	uint64	MbindStart = 588; 
	uint64	MbindLen = 589; 
	uint64	MbindMode = 590; 
	uint64	MbindNmask = 591; 
	uint64	MbindMaxnode = 592; 
	uint64	MbindFlags = 593; 
	string	MknodFilename = 594; 
	uint64	MknodMode = 595; 
	uint64	MknodDev = 596; 
	uint64	MunlockStart = 597; 
	uint64	MunlockLen = 598; 
	uint64	GetpgidPid = 599; 
	uint64	GetresuidRuidp = 600; 
	uint64	GetresuidEuidp = 601; 
	uint64	GetresuidSuidp = 602; 
	uint64	FchownatDfd = 603; 
	string	FchownatFilename = 604; 
	uint64	FchownatUser = 605; 
	uint64	FchownatGroup = 606; 
	uint64	FchownatFlag = 607; 
	uint64	PerfEventOpenAttrUptr = 608; 
	uint64	PerfEventOpenPid = 609; 
	uint64	PerfEventOpenCpu = 610; 
	uint64	PerfEventOpenGroupFd = 611; 
	uint64	PerfEventOpenFlags = 612; 
	uint64	NewunameName = 613; 
	uint64	TimerfdCreateClockid = 614; 
	uint64	TimerfdCreateFlags = 615; 
	string	ShmdtShmaddr = 616; 
	string	RmdirPathname = 617; 
	uint64	OpenByHandleAtMountdirfd = 618; 
	uint64	OpenByHandleAtHandle = 619; 
	uint64	OpenByHandleAtFlags = 620; 
	uint64	SocketpairFamily = 621; 
	uint64	SocketpairType = 622; 
	uint64	SocketpairProtocol = 623; 
	uint64	SocketpairUsockvec = 624; 
	uint64	SetresgidRgid = 625; 
	uint64	SetresgidEgid = 626; 
	uint64	SetresgidSgid = 627; 
	uint64	GetitimerWhich = 628; 
	uint64	GetitimerValue = 629; 
	uint64	MqGetsetattrMqdes = 630; 
	uint64	MqGetsetattrUMqstat = 631; 
	uint64	MqGetsetattrUOmqstat = 632; 
	string	ChdirFilename = 633; 
	uint64	FchdirFd = 634; 
	uint64	MmapAddr = 635; 
	uint64	MmapLen = 636; 
	uint64	MmapProt = 637; 
	uint64	MmapFlags = 638; 
	uint64	MmapFd = 639; 
	uint64	MmapOff = 640; 
	uint64	LookupDcookieCookie64 = 641; 
	string	LookupDcookieBuf = 642; 
	uint64	LookupDcookieLen = 643; 
	uint64	SyslogType = 644; 
	string	SyslogBuf = 645; 
	uint64	SyslogLen = 646; 
	uint64	AcceptFd = 647; 
	uint64	AcceptUpeerSockaddr = 648; 
	uint64	AcceptUpeerAddrlen = 649; 
	uint64	SetMempolicyMode = 650; 
	uint64	SetMempolicyNmask = 651; 
	uint64	SetMempolicyMaxnode = 652; 
	uint64	MkdiratDfd = 653; 
	string	MkdiratPathname = 654; 
	uint64	MkdiratMode = 655; 
	uint64	FchmodatDfd = 656; 
	string	FchmodatFilename = 657; 
	uint64	FchmodatMode = 658; 
	string	MkdirPathname = 659; 
	uint64	MkdirMode = 660; 
	string	MountDevName = 661; 
	string	MountDirName = 662; 
	string	MountType = 663; 
	uint64	MountFlags = 664; 
	uint64	MountData = 665; 
	uint64	SchedSetaffinityPid = 666; 
	uint64	SchedSetaffinityLen = 667; 
	uint64	SchedSetaffinityUserMaskPtr = 668; 
	uint64	MqTimedreceiveMqdes = 669; 
	string	MqTimedreceiveUMsgPtr = 670; 
	uint64	MqTimedreceiveMsgLen = 671; 
	uint64	MqTimedreceiveUMsgPrio = 672; 
	uint64	MqTimedreceiveUAbsTimeout = 673; 
	uint64	GetsidPid = 674; 
	uint64	UnshareUnshareFlags = 675; 
	uint64	CapgetHeader = 676; 
	uint64	CapgetDataptr = 677; 
	uint64	LinkatOlddfd = 678; 
	string	LinkatOldname = 679; 
	uint64	LinkatNewdfd = 680; 
	string	LinkatNewname = 681; 
	uint64	LinkatFlags = 682; 
	uint64	AlarmSeconds = 683; 
	uint64	IoSetupNrEvents = 684; 
	uint64	IoSetupCtxp = 685; 
	uint64	MqTimedsendMqdes = 686; 
	string	MqTimedsendUMsgPtr = 687; 
	uint64	MqTimedsendMsgLen = 688; 
	uint64	MqTimedsendMsgPrio = 689; 
	uint64	MqTimedsendUAbsTimeout = 690; 
	string	GetcwdBuf = 691; 
	uint64	GetcwdSize = 692; 
	uint64	EpollWaitEpfd = 693; 
	uint64	EpollWaitEvents = 694; 
	uint64	EpollWaitMaxevents = 695; 
	uint64	EpollWaitTimeout = 696; 
	uint64	IopermFrom = 697; 
	uint64	IopermNum = 698; 
	uint64	IopermTurnOn = 699; 
	uint64	FlockFd = 700; 
	uint64	FlockCmd = 701; 
	uint64	EpollCtlEpfd = 702; 
	uint64	EpollCtlOp = 703; 
	uint64	EpollCtlFd = 704; 
	uint64	EpollCtlEvent = 705; 
	uint64	ClockGettimeWhichClock = 706; 
	uint64	ClockGettimeTp = 707; 
	uint64	SemctlSemid = 708; 
	uint64	SemctlSemnum = 709; 
	uint64	SemctlCmd = 710; 
	uint64	SemctlArg = 711; 
	uint64	RtSigprocmaskHow = 712; 
	uint64	RtSigprocmaskNset = 713; 
	uint64	RtSigprocmaskOset = 714; 
	uint64	RtSigprocmaskSigsetsize = 715; 
	uint64	PersonalityPersonality = 716; 
	string	LlistxattrPathname = 717; 
	string	LlistxattrList = 718; 
	uint64	LlistxattrSize = 719; 
	uint64	PtraceRequest = 720; 
	uint64	PtracePid = 721; 
	uint64	PtraceAddr = 722; 
	uint64	PtraceData = 723; 
	string	SetdomainnameName = 724; 
	uint64	SetdomainnameLen = 725; 
	uint64	ProcessVmReadvPid = 726; 
	uint64	ProcessVmReadvLvec = 727; 
	uint64	ProcessVmReadvLiovcnt = 728; 
	uint64	ProcessVmReadvRvec = 729; 
	uint64	ProcessVmReadvRiovcnt = 730; 
	uint64	ProcessVmReadvFlags = 731; 
	uint64	ArchPrctlOption = 732; 
	uint64	ArchPrctlArg2 = 733; 
	uint64	RecvmsgFd = 734; 
	uint64	RecvmsgMsg = 735; 
	uint64	RecvmsgFlags = 736; 
	uint64	NanosleepRqtp = 737; 
	uint64	NanosleepRmtp = 738; 
	uint64	FcntlFd = 739; 
	uint64	FcntlCmd = 740; 
	uint64	FcntlArg = 741; 
	uint64	IoCancelCtxId = 742; 
	uint64	IoCancelIocb = 743; 
	uint64	IoCancelResult = 744; 
	uint64	Getdents64Fd = 745; 
	uint64	Getdents64Dirent = 746; 
	uint64	Getdents64Count = 747; 
	uint64	InotifyRmWatchFd = 748; 
	uint64	InotifyRmWatchWd = 749; 
	uint64	FlistxattrFd = 750; 
	string	FlistxattrList = 751; 
	uint64	FlistxattrSize = 752; 
	uint64	ReadFd = 753; 
	string	ReadBuf = 754; 
	uint64	ReadCount = 755; 
	uint64	ClockNanosleepWhichClock = 756; 
	uint64	ClockNanosleepFlags = 757; 
	uint64	ClockNanosleepRqtp = 758; 
	uint64	ClockNanosleepRmtp = 759; 
	uint64	SysctlArgs = 760; 
	string	ChownFilename = 761; 
	uint64	ChownUser = 762; 
	uint64	ChownGroup = 763; 
	uint64	SetgroupsGidsetsize = 764; 
	uint64	SetgroupsGrouplist = 765; 
	uint64	NewfstatFd = 766; 
	uint64	NewfstatStatbuf = 767; 
	uint64	MadviseStart = 768; 
	uint64	MadviseLenIn = 769; 
	uint64	MadviseBehavior = 770; 
	uint64	FchownFd = 771; 
	uint64	FchownUser = 772; 
	uint64	FchownGroup = 773; 
	uint64	InotifyInit1Flags = 774; 
	string	AddKeyType = 775; 
	string	AddKeyDescription = 776; 
	uint64	AddKeyPayload = 777; 
	uint64	AddKeyPlen = 778; 
	uint64	AddKeyRingid = 779; 
	string	MemfdCreateUname = 780; 
	uint64	MemfdCreateFlags = 781; 
	string	MqOpenUName = 782; 
	uint64	MqOpenOflag = 783; 
	uint64	MqOpenMode = 784; 
	uint64	MqOpenUAttr = 785; 
	uint64	InitModuleUmod = 786; 
	uint64	InitModuleLen = 787; 
	string	InitModuleUargs = 788; 
	uint64	SchedSetattrPid = 789; 
	uint64	SchedSetattrUattr = 790; 
	uint64	SchedSetattrFlags = 791; 
	uint64	IoctlFd = 792; 
	uint64	IoctlCmd = 793; 
	uint64	IoctlArg = 794; 
	string	RequestKeyType = 795; 
	string	RequestKeyDescription = 796; 
	string	RequestKeyCalloutInfo = 797; 
	uint64	RequestKeyDestringid = 798; 
	string	UmountName = 799; 
	uint64	UmountFlags = 800; 
	uint64	PreadvFd = 801; 
	uint64	PreadvVec = 802; 
	uint64	PreadvVlen = 803; 
	uint64	PreadvPosL = 804; 
	uint64	PreadvPosH = 805; 
	uint64	VmspliceFd = 806; 
	uint64	VmspliceUiov = 807; 
	uint64	VmspliceNrSegs = 808; 
	uint64	VmspliceFlags = 809; 
	uint64	SysinfoInfo = 810; 
	uint64	TimerSettimeTimerId = 811; 
	uint64	TimerSettimeFlags = 812; 
	uint64	TimerSettimeNewSetting = 813; 
	uint64	TimerSettimeOldSetting = 814; 
	uint64	QuotactlCmd = 815; 
	string	QuotactlSpecial = 816; 
	uint64	QuotactlId = 817; 
	uint64	QuotactlAddr = 818; 
	uint64	GetgroupsGidsetsize = 819; 
	uint64	GetgroupsGrouplist = 820; 
	uint64	FchmodFd = 821; 
	uint64	FchmodMode = 822; 
	uint64	Fadvise64Fd = 823; 
	uint64	Fadvise64Offset = 824; 
	uint64	Fadvise64Len = 825; 
	uint64	Fadvise64Advice = 826; 
	uint64	IoSubmitCtxId = 827; 
	uint64	IoSubmitNr = 828; 
	uint64	IoSubmitIocbpp = 829; 
	string	ChmodFilename = 830; 
	uint64	ChmodMode = 831; 
	uint64	Pwrite64Fd = 832; 
	string	Pwrite64Buf = 833; 
	uint64	Pwrite64Count = 834; 
	uint64	Pwrite64Pos = 835; 
	uint64	SettimeofdayTv = 836; 
	uint64	SettimeofdayTz = 837; 
	uint64	SchedGetparamPid = 838; 
	uint64	SchedGetparamParam = 839; 
	uint64	SchedGetaffinityPid = 840; 
	uint64	SchedGetaffinityLen = 841; 
	uint64	SchedGetaffinityUserMaskPtr = 842; 
	uint64	MsgctlMsqid = 843; 
	uint64	MsgctlCmd = 844; 
	uint64	MsgctlBuf = 845; 
	uint64	TimerfdSettimeUfd = 846; 
	uint64	TimerfdSettimeFlags = 847; 
	uint64	TimerfdSettimeUtmr = 848; 
	uint64	TimerfdSettimeOtmr = 849; 
	uint64	ConnectFd = 850; 
	uint64	ConnectUservaddr = 851; 
	uint64	ConnectAddrlen = 852; 
	uint64	SendtoFd = 853; 
	uint64	SendtoBuff = 854; 
	uint64	SendtoLen = 855; 
	uint64	SendtoFlags = 856; 
	uint64	SendtoAddr = 857; 
	uint64	SendtoAddrLen = 858; 
	uint64	BpfCmd = 859; 
	uint64	BpfUattr = 860; 
	uint64	BpfSize = 861; 
	uint64	KcmpPid1 = 862; 
	uint64	KcmpPid2 = 863; 
	uint64	KcmpType = 864; 
	uint64	KcmpIdx1 = 865; 
	uint64	KcmpIdx2 = 866; 
	uint64	Mlock2Start = 867; 
	uint64	Mlock2Len = 868; 
	uint64	Mlock2Flags = 869; 
	uint64	Pwritev2Fd = 870; 
	uint64	Pwritev2Vec = 871; 
	uint64	Pwritev2Vlen = 872; 
	uint64	Pwritev2PosL = 873; 
	uint64	Pwritev2PosH = 874; 
	uint64	Pwritev2Flags = 875; 
	uint64	SchedSetparamPid = 876; 
	uint64	SchedSetparamParam = 877; 
	string	SwapoffSpecialfile = 878; 
	uint64	UserfaultfdFlags = 879; 
	uint64	IoPgeteventsCtxId = 880; 
	uint64	IoPgeteventsMinNr = 881; 
	uint64	IoPgeteventsNr = 882; 
	uint64	IoPgeteventsEvents = 883; 
	uint64	IoPgeteventsTimeout = 884; 
	uint64	IoPgeteventsUsig = 885; 
	uint64	ListenFd = 886; 
	uint64	ListenBacklog = 887; 
	uint64	GetRobustListPid = 888; 
	uint64	GetRobustListHeadPtr = 889; 
	uint64	GetRobustListLenPtr = 890; 
	uint64	SetnsFd = 891; 
	uint64	SetnsNstype = 892; 
}